### ISSUE TITLE
Mutate state of another module

### ISSUE THREAD

**Issue by nicolas-t** [vuejs/vuex#100]
Hi :)

let's say I have two modules: 
1. users
2. posts

I have an action to retrieve a `post` (GET: api/posts/:id), i am returned the `post` and the author (a `user`) :  
``` javascript
"data": {
	"post": {
		# a post object
	}
	"author": {
		# a user object
	}
}
```
As you would expect i want to update both my `post` module state and `user` module state.  
Maybe with something like [normalizr](https://github.com/gaearon/normalizr)

But in my mutations I can only access my current module state (coffee): 
``` coffeescript
myMutation = (state) ->
    # here state is in fact currentModuleState
```

My question: Is it a bad practice to mutate another module state? If not, how can i achieve it ?

Thanks :peach:

**Comment by yyx990803** [comment]
That's by design - however, multiple modules can listen to the same mutation.

**Comment by blake-newman** [comment]
This is how vuex works by design.  Modules hold mutations on the state of that module. However modules can listen to the same mutation type to affect change.

**Comment by blooddrunk** [comment]
@yyx990803 Sorry to bother but I'm a little confused about multiple modules listening to the same mutation. Say I have a music list, a video list and a favorite list which contents may come from any of them. All these modules listen to `TOGGLE_FAVORITE` mutation. Now when committing a `TOGGLE_FAVORITE` mutation from the music store, do I have to deal with this mutation in video store even if it's unnecessary? Or maybe I'm doing the wrong way?
