### ISSUE TITLE
Documentation: Missing reference for needed Promise polyfill

### ISSUE THREAD

**Issue by AnnikaNissen** [vuejs/vuex#1002]
### What problem does this feature solve?
After starting using vuex (by the way: it's great!) I got a little bit checked when opening the IE 11 and getting  "[vuex] vuex requires a Promise polyfill in this browser."

I did read the installation guide in the documentation carefully, but it is not mentioned at all, that vuex depends on / requires a Promis ployfill, if it should work in IE. It would be great to include that in the documentation, along with tip, which polyfill to use and how to include it.

### What does the proposed API look like?
-

**Comment by GufNZ** [comment]
This is also required if doing unit tests under Karma/PhantomJS, but I'm new at this so am not sure how to specify one there...
