### ISSUE TITLE
Typescript compilation fails with version 2.5.0 without allowSyntheticDefaultImports (and with)

### ISSUE THREAD

**Issue by lanthaler** [vuejs/vuex#1003]
### Version
2.5.0

### Reproduction link
Can provide one later if necessary, but I think the problem is clear enough with the information below.

### Steps to reproduce
Upgrade app to use vue 2.5.2 and vuex 2.5.0 and get rid of allowSyntheticDefaultImports as recommended (it doesn't work with either due to other issues).

### What is expected?
Compiles

### What is actually happening?
Doesn't compile. Error 'Module '"../vuex/types/index"' has no default export.' at: '2,8' source: 'ts'

This is because https://github.com/vuejs/vuex/blob/v2.5.0/types/index.d.ts has no default export. It was already fixed in https://github.com/vuejs/vuex/commit/65dbfec40d5fe7aac05aab333c7b70768997ca7f#diff-88bec6beae84369c0376b56b3bb88fe1 but has only been released as version 3

**Comment by ktsn** [comment]
As described in released note, you need use Vuex >= v3.0.0 with Vue >= v2.5.

https://github.com/vuejs/vuex/releases/tag/v3.0.0

**Comment by lanthaler** [comment]
Thanks a lot @ktsn. This solved the issue. I only looked at Vue's release notes and didn't expect a new major version for vuex and other packages. Might be worth defining these `peerDependencies` going forward.
