### ISSUE TITLE
Remove remove object key

### ISSUE THREAD

**Issue by Garito** [vuejs/vuex#1013]
Hi
How can I remove an object key in a reactive way?
Example:
```javascript
state: {
  users: {
    'user1': {name: 'user1', email: 'email@xx.com'}
  }
}
```
I want to remove users['user1']

Thanks

**Comment by webdesignberlin** [comment]
i use
```
mutations: {
    remove(state, data) {
      if (state.users) {
        delete state.users.user1;
      }
    }
}
```

**Comment by zatziky** [comment]
@webdesignberlin Michael, do you have any idea why so many people disliked your solution? I've tested in a unit test and it looks fine. Not sure about the reactivity though...

**Comment by kiaking** [comment]
It's reactivity issue. You can't use `delete` for state properties due to [same reason stated here](https://vuejs.org/v2/guide/reactivity.html#For-Objects). However, you could use `Vue.delete`.
