### ISSUE TITLE
Suggestion to have store object as "this" in getters

### ISSUE THREAD

**Issue by yariksav** [vuejs/vuex#1020]
### What problem does this feature solve?
Store getters don't have this parameter and link to store instance

### What does the proposed API look like?
Is it possible to add instance "store" as parameter to call function "rawGetter"? Or change to rawGetter.call(store, {...}) to have "this" parameter in getters functions?
https://github.com/vuejs/vuex/blob/a8326b1bd77158e7e5903eed4cc98b52599e3dbd/src/store.js#L436-L442

**Comment by posva** [comment]
It's generally a bad idea to use the store from a getter because it's meant to be a pure function, so everything you need is already passed as a parameter. Why do you want to have access to the store inside of a getter

**Comment by yariksav** [comment]
I understand, but maybe you give advice to me. I need to have access to i18n instance to generate getters with strings in current locales. For example how to have access to $t(message) in getters?

**Comment by ktsn** [comment]
You can use i18n module in Vuex store and refer its state/getters.
