### ISSUE TITLE
getters are `undefined` in `data()`, but `this.$store.state` is not

### ISSUE THREAD

**Issue by SidKwok** [vuejs/vuex#1022]
### Version
3.0.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/72284/](https://jsfiddle.net/50wL7mdz/72284/)

### Steps to reproduce
The jsfiddle link should illustrate this issue well

### What is expected?
test1, test2, test3 should be the same value

### What is actually happening?
test2 is undefined, which is set by getters in data()

### Other Comments
Vuex1 seem to have no such issue.

**Comment by ktsn** [comment]
Because `computed` is not initialized at the moment. You need to use `$store` in data hook.
