### ISSUE TITLE
Vuex mutations not being processed

### ISSUE THREAD

**Issue by minedun6** [vuejs/vuex#1024]
What is the problem ?
================

The problem seems to be a bit odd as i add an object to an array, it doesn't update getters.
I joined a video to detail the problem a bit more.

[Problem](https://youtu.be/w-CPQ-JGVLc)

I have no idea why it works sometimes, and sometimes it doesn't work.
And when I commit it using Vue Devtools it works and the rest of the flow works perfectly.
But for the first it doesn't and it is confusing me so much.
the getter responsible for getting the custom presentations doesn't get updated at first.

**Comment by LinusBorg** [comment]
You should try getting helkp on fourm.vuejs.org or chat.vuejs.org before opening an issue.
