### ISSUE TITLE
Alternate method to tracking state changes via actions.

### ISSUE THREAD

**Issue by jaesung2061** [vuejs/vuex#1029]
### What problem does this feature solve?
I find myself taking a lot of time working with async tasks because I have to use actions. I have to write a lot of boilerplate. So instead of forcing refactoring async calls to actions, why not allow them to start tracking from the components?

### What does the proposed API look like?
From the component:

```
methods() {
    callApi() {
        // take snapshot before api call beings
        const trackerId = this.$store.track('actionName');

        asyncCall().then((response) => {
            this.$store.commit('makeMutation', response.data);

            // take snapshot at completion
            this.$store.complete(trackerId);
        })
    }
}
````

Edit: I'm not entire sure how the internals work, but it looks like it should work like this?

```
methods() {
    callApi() {
        const context = this.$store.track('actionName');

        asyncCall().then((response) => {
            context.commit('makeMutation', response.data);
        })
    }
}
```

I hope I'm not completely missing the point of actions, but here is another possible method.

```
methods() {
    callApi() {
        this.$store.track('actionName', (context) => {
            asyncCall().then((response) => {
                context.commit('makeMutation', response.data);
            })
        });
    }
}
```

**Comment by ktsn** [comment]
What does this API do? I'm not sure why not just use `this.$store.commit`.

**Comment by jaesung2061** [comment]
I thought you shouldn't use this directly for async calls?

**Comment by jaesung2061** [comment]
Nevermind, I'm an idiot. I misunderstood the docs.
