### ISSUE TITLE
state function is triggered twice

### ISSUE THREAD

**Issue by smonkey72** [vuejs/vuex#1030]
### Version
3.0.0 and earlier

### Reproduction link
[https://codepen.io/anon/pen/RjNgoM](https://codepen.io/anon/pen/RjNgoM)

### Steps to reproduce
1. open codepen
2. open / read console

### What is expected?
state() is triggered once

### What is actually happening?
state() is triggered twice

---
Codepen is forked from https://codepen.io/royportas/pen/ENEELJ

**Comment by LinusBorg** [comment]
Hi, thanks for reporting.

It seems this can indeed be optimized, thanks!
