### ISSUE TITLE
[TypeScript] Can not access props in mapState

### ISSUE THREAD

**Issue by galenyuan** [vuejs/vuex#1032]
### Version
3.0.0

### Reproduction link
[https://github.com/galenyuan/todomvc-vue-typescript/blob/master/src/pages/Home.vue#L63](https://github.com/galenyuan/todomvc-vue-typescript/blob/master/src/pages/Home.vue#L63)

### Steps to reproduce
```
npm i
npm run dev
```

### What is expected?
no errors

### What is actually happening?
```
(63,22): error TS2339: Property 'type' does not exist on type 'VueConstructor<Vue>'.
```

**Comment by HerringtonDarkholme** [comment]
We probably cannot support accessing `this` in `mapState` or so.

Vue uses `ThisType` to check `this` in methods. However, `ThisType` will only work in object literal contexually typed, or object literal which is a direct child of another `ThisType`d object literal.

Simply put, you cannot infer `this` in `mapState`. You have to define it as an object literal, not in a function call.

**Comment by galenyuan** [comment]
what about note it in doc if can not support accessing this in mapState?

**Comment by SidKwok** [comment]
Any progress on this issue?

**Comment by ktsn** [comment]
#1044

**Comment by ryutamaki** [comment]
I said in #1044 but let me say again here.
Could you merge and release this feature or please let us know when that wold be merged?
