### ISSUE TITLE
Vuex getter-properties failed to be reactive when using vue-router

### ISSUE THREAD

**Issue by superSamChow** [vuejs/vuex#104]
When I use router and vuex together, I find properties in getters can't be reactive.

I am quite sure that the `store` has been injected into the App Component(root Component in router). And I did use `Vue.use(Vuex)` in my codes.

Here's the codes:

`actionA` in `action.js`

    export const actionA = ({ dispatch }) => {
        dispatch ('A');
    }

`moduleA.js`: 

    export const state  =  {
        a: false
    };
    export const mutations = {
        A(state){
            state.a = ! state.a;
        }
    }

`store.js` : 

     // import moduleA ... 
     vue.use(Vuex);
     export default new Vuex.Store({
          modules: {
             moduleA
          }
     })

`vuex` in `mya.vue`:  

    vuex: {
        actions: {
            actionA // this action changes one of the state by calling dispatch
        }
    }

I would troggle `actionA` by a method which listens button click event then... 

`getters` in `myb.vue`

    vuex: {
        getters: {
            A:  ( {moduleA} ) =  moduleA.a  // this can be called inside the component, while returning the correct value(Boolean Type),
        }
    }

`template` in `myb.vue`

    <template>
        <a v-link="#" v-if="A"> something... </a>
    </template>

This `<a>`could be rendered right at first. However, when I called `actionA` to change state, the problem came up.  the `<a>` in `myb.vue` seems to failed to be reactive as `v-if` didn't work.

And the component in `mya.vue` together with the component in `myb.vue` are in the same route.

Why.

**Comment by yyx990803** [comment]
reproduction please.

**Comment by superSamChow** [comment]
@yyx990803 ,Thanks for answering. But do I need to reproduce all my code? I mean my codes are just so simple that I have already depicted above.

**Comment by yyx990803** [comment]
Yes, because otherwise I still have to do it.

**Comment by superSamChow** [comment]
Sorry, but I think it's the time to close this issue. 
Because I find this problem exist when I code **without `router`**.

So why can't my getters be reactive? 😭😭

**Comment by blake-newman** [comment]
If you find that you want to reopen the issue please do with a small reproduction link and we can help you out.  

However the best place for support for things like this is the [vue forums](http://forum.vuejs.org) or on the [gitter.im channel]

**Comment by superSamChow** [comment]
Okay, THANK YOU. @blake-newman
