### ISSUE TITLE
Add documentation entry for watch store unsubscription on component

### ISSUE THREAD

**Issue by PonyLux** [vuejs/vuex#1050]
### What problem does this feature solve?
Actually there are no information regarding the necessity to "unsubscribe" store watch on component destroy.

It would be good to set a warning on the API documentation (https://vuex.vuejs.org/en/api.html) to let users know that without explicit unsubscription, the watch will be keep even after component destroy.

This issue has been reported here https://github.com/vuejs/vuex/issues/599 and closed as a won't fix.

This problem cause *memory leak* and in most of the case *errors* extremely hard to debug.

## For a minimalist resolution
A *warning quote* in https://vuex.vuejs.org/en/api.html .

## Nice to have
A new entry in menu to explain how to use `watch` (and then the tips for the *unsubscription*).
It could be great to give a better knowledge of this feature.

**Comment by karanisverma** [comment]
@LinusBorg I would like to pick this up

**Comment by kiaking** [comment]
It could be nice to have this added in the doc I think. It has been awhile but do you want to work on with this @karanisverma?

**Comment by karanisverma** [comment]
Hey @kiaking, sorry I would not be able to pick this up.

**Comment by kiaking** [comment]
@karanisverma OK! Thanks for checking 👍

**Comment by anschwa** [comment]
I would also like to see this get added to the docs. I opened a PR here: https://github.com/vuejs/vuex/pull/1838
