### ISSUE TITLE
FIlters with Store.getters

### ISSUE THREAD

**Issue by vankhuong** [vuejs/vuex#1054]
### What problem does this feature solve?
I like feature filters in Vue, but now i can't apply getters to filters in Vuex, this is more convenient for Vuex

### What does the proposed API look like?
```javascipt
export default {
   filters: {
      capitalize: function (value) {
         return this.$store.getters.capitalize(value)
      }
   }
}
```

**Comment by LinusBorg** [comment]
Hi.

I don't understand your proposal. How/where would these filters be used?

**Comment by vankhuong** [comment]
Hi @LinusBorg, 

These filters may be used in a component of Vue

**Comment by LinusBorg** [comment]
Oh yoiu just want to store the filters that you use in your template in vuex?

Well, I don't think that makes a lot of sense. Vuex is concerned with state management not the state's visualization. The latter is the component's job. So I think filters don't belong in the store.

**Comment by vankhuong** [comment]
This is a nice way you want filter with a query in store instead of using methods in template, methods are good for calling some actions and mutations in store

**Comment by vankhuong** [comment]
### What problem does this feature solve?
Now Vuex can't be used in filters of Vue, you only can use in methods
```javascript
Vue.component('locale-price', {
    props: ['price'],
    template: '<div class="price">{{ getPriceByLocale (price) }}</div>',
    methods: getPriceByLocale (price) {
        return this.$store.getters.getPriceByLocale(price)
    }
});
```
### What does the proposed API look like?
I proposed Vuex can be used in filters of Vue component the same like this
```javascript
Vue.component('locale-price', {
    props: ['price'],
    template: '<div class="price">{{ price | priceByLocale }}</div>',
    filters: {
        priceByLocale (value) {
           return this.$store.getters.getPriceByLocale(value)
        }
    }
});
```

**Comment by LeWestopher** [comment]
@vankhuong I think the functionality you're looking for is the `computed` property on the component object.  Your request is functionality of the Vue API ,not the Vuex API.  You would use `computed` in basically the same way that you would use your `filters` property:

```
// Default store object
const defaultStore = {
  animals: [
    { id: 1, name: 'Horse', color: 'Brown' },
    { id: 2, name: 'Dog', color: 'White' },
    { id: 3, name: 'Cow', color: 'Brown' }
  ],
}

// Store
const store = new Vuex.Store({
  state: defaultState,
  getters: {
    filterAnimalsByColor: state => color => state.animals.filter(animal => animal.color === color),
  },
});

// Template
const tmpl = `
<ul>
  <li v-for="animal in brownAnimals">{{ animal.name }}</li>
</ul>
`;

// Component
Vue.component('animals-filter-component', {
  computed: {
    brownAnimals() {
      return this.$store.getters.filterAnimalsByColor('brown');
    }
  }
});
```

**Comment by vankhuong** [comment]
Hi @LeWestopher,

Thanks for your hint, i think having a bit different when you use `filters` property, that's you can apply query filter by expressions in a template, this is more convenient

**Comment by LeWestopher** [comment]
@vankhuong Oh!  I see what your issue is now.

Filters are pure functions.  They do not have a `this` reference to the component that they are declared on, they are just included locally as available in the template.  However, the functionality that you are looking for already exists, you just import the store object rather than using the `$store` property attached to the component.  Like so:

```js
// import your Vuex store object
import { store } from './store';

Vue.component('locale-price', {
    props: ['price'],
    template: '<div class="price">{{ price | priceByLocale }}</div>',
    filters: {
        priceByLocale (value) {
           // replace `this.$store` with `store`
           return store.getters.getPriceByLocale(value)
        }
    }
});
```

**Comment by ktsn** [comment]
^ as @LeWestopher described, you can just import your store.

Also we already can do this by using `methods` instead of `filters`. We would not add a only stylistic feature to keep size and API surface small.
