### ISSUE TITLE
TypeScript declaration for subscribeAction missing

### ISSUE THREAD

**Issue by jvanoostrum** [vuejs/vuex#1066]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vuex/blob/dev/types/index.d.ts](https://github.com/vuejs/vuex/blob/dev/types/index.d.ts)

### Steps to reproduce
Try to subscribe to an action within the store with the new introduced method in version 3.0.1 subscribeAction.

### What is expected?
No error

### What is actually happening?
[ts] Property 'subscribeAction' does not exist on type 'Store<{}>'.

---
Please add typescript declaration just like line 19 of https://github.com/vuejs/vuex/blob/dev/types/index.d.ts
subscribeAction<P extends MutationPayload>(fn: (mutation: P, state: S) => any): () => void;

and instead of MutationPayload maybe ActionPayload.
and instead of mutation maybe action

**Comment by byrnedo** [comment]
Any chance of getting cutting a 3.0.2 release to get this change @ktsn ?
