### ISSUE TITLE
Dispatch mutation from middleware onInit

### ISSUE THREAD

**Issue by perkola** [vuejs/vuex#107]
How do I dispatch a mutation from within the `onInit` function inside a middleware attached to the store?

I have a module, `auth`, which contain a mutation `AUTHENTICATE` which I would like to trigger `onInit` if there is a user cookie in storage. See full code below.

```
// store.js
const localStorageMiddleware = {
    onInit (state) {
        // if user cookie in storage, dispatch mutation
    }
}

export default new Vuex.Store({
    modules: {
        auth
    },
    middlewares: [localStorageMiddleware]
})
```
```
// auth.js
import {
    AUTHENTICATE
} from '../mutation-types'

const state = {
    authenticated: false
}

const mutations = {
    [AUTHENTICATE] (state) {
        state.authenticated = true
    }
}

export default {
    state,
    mutations
}
```
According to the docs, mutating the state directly is regarded as bad practise.

**Comment by skyronic** [comment]
I believe `onInit` takes a second parameter which is the store. Maybe something like this will work:

```
onInit (state, { dispatch })) {
    dispatch (AUTHENTICATE);
}
```

I am not at my work env to try this out but I saw the code on github and it looks like the store is being passed to `onInit`

**Comment by yyx990803** [comment]
Yes, store is passed as the last argument in both `onInit` and `onMutation`. (I somehow forgot to add it to the docs, PR welcome)

**Comment by perkola** [comment]
A pull request has been created. See #108.

**Comment by blake-newman** [comment]
Closing as pull request has been merged.
