### ISSUE TITLE
LocalStorage.getItem() not works in vuex's getters

### ISSUE THREAD

**Issue by bedlate** [vuejs/vuex#1070]
### Version
2.5.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
    user(state) {
        return localStorage.getItem("something")
    }

### What is expected?
the value of something

### What is actually happening?
null

**Comment by ktsn** [comment]
This seems not related with Vuex...
In addition, you should not do that in getters since getters must not include any side effects.
