### ISSUE TITLE
Throw not exist mutation and action

### ISSUE THREAD

**Issue by akleandrov** [vuejs/vuex#1073]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vuex/blob/f26d39d99313879e8353d49ec730f937f27acc32/dist/vuex.js#L401](https://github.com/vuejs/vuex/blob/f26d39d99313879e8353d49ec730f937f27acc32/dist/vuex.js#L401)

### Steps to reproduce
Call not exist mutation. If i use vuex.esm.js all ok.

### What is expected?
process.env.NODE_ENV !== 'production'

### What is actually happening?
 "development" !== 'production'

---
So it certainly should not be.
And why only in development?

**Comment by ktsn** [comment]
Because it's development build for browser. You should use `vuex.common.js` or `vuex.esm.js` for module bundler.
