### ISSUE TITLE
Array computed property

### ISSUE THREAD

**Issue by kobimilan995** [vuejs/vuex#1075]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/kobimilan995/50wL7mdz/80973/](https://jsfiddle.net/kobimilan995/50wL7mdz/80973/)

### Steps to reproduce
Hello. I m using vue/vuex with laravel, and i m having problems with array computed property. The example is similar to attached jsfiddle. The computed property in the component doesn't seem do watch over a state.statuses when i push elements on to it. Even if i log the statuses, in vuex, i can see statuses being added, but not in the component.

### What is expected?
Expected to see statuses appearing dynamically.

### What is actually happening?
Nothing is happening. I dont see any statuses.

**Comment by posva** [comment]
as said in #1076 please do not open multiple issues for the same thing
