### ISSUE TITLE
Proposal: Component-like methods

### ISSUE THREAD

**Issue by etki** [vuejs/vuex#1087]
### What problem does this feature solve?
Currently, Vuex allows to have set of custom getters which act as computed properties for components, but doesn't have anything like component methods. While this may seem to contradict with some of Vuex principles (methods usually imply some kind of action, which in turn is implied to be in mutations/actions), it doesn't necessarily do so: just like getters, there is need for some helper computational functionality that takes some arguments. Imagine that i have application that may have several modes turned on and i need to check if some specific mode is set. If i would have something like `.hasMode(mode)` method, it would be a breeze.

### What does the proposed API look like?
```js
{
  methods: {
     hasMode (state, payload, rootState) {
        return state.modes.indexOf(payload) > -1
     }
  }
}
```

**Comment by posva** [comment]
You can actually return a function in a getter: https://vuex.vuejs.org/en/getters.html

**Comment by ktsn** [comment]
As @posva said, you can return a function in a getter for that purpose.
