### ISSUE TITLE
Should vuex mapState print error message

### ISSUE THREAD

**Issue by balazser** [vuejs/vuex#1093]
### What problem does this feature solve?
I got the following error: Uncaught TypeError: Cannot convert undefined or null to object
then realized I invoked the  `...mapState(NSP_CONCEPT) `without a second parameter. 
It took some time while I figured out, would have been great, if there is a condition to don't fail or print out a message.

### What does the proposed API look like?
print a message, or put a condition into the function

**Comment by EdyHartono** [comment]
#1297

**Comment by ktsn** [comment]
fixed via #1297
