### ISSUE TITLE
Action subscribers do not wait for associated actions to resolve

### ISSUE THREAD

**Issue by wa3l** [vuejs/vuex#1098]
### What problem does this feature solve?
I noticed that my store action subscribers were being called before the actions finish. Digging into the code, [it looks like](https://github.com/vuejs/vuex/blob/dev/src/store.js#L131-L135) not only do action subscribers not wait on the actions to resolve, but they execute _before_ the action. Mutation subscribers, on the other hand, [seem to work](https://github.com/vuejs/vuex/blob/dev/src/store.js#L97-L102) as expected (call mutation first, call subscriber second). Since actions are often asynchronous (and vuex always wraps them with promises), I think it makes more sense to wait on the action and then call subscribers.

I wasn't sure if this was intentional or not, hence the feature request.

### What does the proposed API look like?
I think something like the following would be more in line with what developers expect:

```js
const result = entry.length > 1
      ? Promise.all(entry.map(handler => handler(payload)))
      : entry[0](payload);
result.then(() => this._actionSubscribers.forEach(sub => sub(action, this.state)));
return result;
```

I could open a pull request if that looks reasonable (will add tests, etc.)

**Comment by wa3l** [comment]
@LinusBorg interesting, thanks for providing that context. I'm trying to implement undo/redo, which a bit different than logging in that mutations represent a state change, but actions represent the actual "history steps" in state that the user cares about undoing. Without a way to notify some centralized subscriber when an action resolves, there is no built-in way of tracking those "logical" history changes. 

I can probably wrap all (or a subset) of my actions with a function that does the waiting/reporting for me. I saw the term "action enhancer" thrown around a couple of times, but the vuexfire docs weren't very clear. The problem with this solution is, after refactoring my existing store, if anyone in the future forgets or doesn't know to wrap their actions with this action wrapper, then they are suddenly excluded from the history tracking.

I understand that `subscribeAction` was not meant for this purpose, but would it make sense to create an `asyncActionSubscribe()` that does what I'm describing?

**Comment by ktsn** [comment]
I think extending `subscribeAction` to let the store notify after finished action would work.

For example:
```js
store.subscribeAction({
  before () { /* called before dispatching action */ },

  after () { /* called after the returned Promise is resolved */ }
})
```

**Comment by wa3l** [comment]
@ktsn that would be awesome. I'll take a crack at it.

**Comment by johnmerced** [comment]
Looking forward for this! Any idea when will this be released?

**Comment by wa3l** [comment]
@johnmerced the pr is [here](https://github.com/vuejs/vuex/pull/1115), waiting on Evan's review.

**Comment by johnmerced** [comment]
@wa3l Awesome! We are looking forward for this! 👍

**Comment by jbgraug** [comment]
Any updates or deadline for this feature?

**Comment by winniehell** [comment]
@ktsn https://github.com/vuejs/vuex/pull/1115 is merged and released, so this issue can probably be closed.
