### ISSUE TITLE
Type checking is broken in Vue components when using mapping helpers

### ISSUE THREAD

**Issue by Demivan** [vuejs/vuex#1119]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vuex/pull/1105](https://github.com/vuejs/vuex/pull/1105)

### Steps to reproduce
1. Create new Vue component.
2. In jsconfig.json (tsconfig.json) enable strict mode and js checking
3. Add `mapState` or `mapActions` to the component

### What is expected?
Type checking should work.
Intellisense should suggest actions mapped using `mapActions` and suggest data mapped using `mapState`
![image](https://user-images.githubusercontent.com/2339406/34556103-b34dda70-f13d-11e7-83b7-20692df3667c.png)

### What is actually happening?
Type checking stops working.
Intellisense is not suggesting mapped actions and state.
![image](https://user-images.githubusercontent.com/2339406/34556113-bd7b2da4-f13d-11e7-8722-1b33c8a41ebd.png)

---
This is due to `mapState` and `mapActions` returning `Dictionary<any>`
I created pull request that fixes this for me: https://github.com/vuejs/vuex/pull/1105

**Comment by bmdalex** [comment]
It's been a while, any news on this @Demivan @ktsn
