### ISSUE TITLE
logger source call

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vuex#112]
Hi, the logger middleware is very useful but many times a same mutation is called from different actions, and those actions from different components and is not easy to find out who is calling what. Is there any way to add the code from where the action was called for such mutation? Thanks.

**Comment by skyronic** [comment]
From what I understand, the actions don't really know which component is calling the mutation, and nor do the dispatchers/stores. I could be wrong, but the store/mutations can be called from other functions/middlewares or even something like a websocket callback.

But I do see the usefulness of having something like this. One quick workaround is to have a middleware of your own which shows a stacktrace. Maybe someone else can figure out a more elegant and proper solution.

**Comment by miljan-aleksic** [comment]
Thanks @skyronic. I assume a well structured code should not make this kind of double calls, but during the learning curve of many devs a stacktrace or similar would be helpful, reason I would like to request this feature as part of the core.

**Comment by blake-newman** [comment]
I agree would be nice a trace of where it came from.

However the implementation of this will be difficult... As getting the stack trace is not standard across all browsers. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack

This can be achieved with putting `debugger`s in your code when attempting to debug code.
