### ISSUE TITLE
Property in App.vue affect property in vuex store

### ISSUE THREAD

**Issue by Rolanddoda** [vuejs/vuex#1127]
### Version
3.0.1

### Reproduction link
https://jsfiddle.net/hej8Lax9/

### Steps to reproduce
We suppose we have the below property in vuex store:

data: [
  { name: 'john', lname: 'doe' },
  { name: 'george', lname: 'doe' }
]

In App.vue i have a property like below:

data: this.$store.getters.fetchData //this will return the data prop of state

Then in App.vue i run the below code :

this.data.splice(0,1) //to remove the first element of data property in App.vue

### What is expected?
It is expected to remove the first element from data property in App.vue

### What is actually happening?
But,that is not affect only the property in App.vue,it is affect also the prop in vuex store.

Note that i have experience to change the state of vuex only within mutation

---
Is that actually the default behavior or it is a bug?

**Comment by ktsn** [comment]
It's expected javascript behavior since splice mutates the caller array. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice
