### ISSUE TITLE
Strict mode especially slow on Firefox / Linux

### ISSUE THREAD

**Issue by charlesfleche** [vuejs/vuex#1139]
### Version
3.0.1

### Reproduction link
[https://app.previz.co](https://app.previz.co)

### Steps to reproduce
Run Firefox / Linux

### What is expected?
Same order of magnitude of performance degradation on Firefox / Linux than on other OS combination

### What is actually happening?
Vuex strict on Firefox / Linux is much slower than any other browser / OS combination.

---
Our Vuex stores objects that are facades that drive a direct acyclic graph that itself drives a WebGL scene (THREE.js). When a property of a Vuex object is modified (a parameter is changed, or input event on the canvas triggers a camera move), our render graph is set dirty and we schedule a refresh with requestAnimationFrame. Usually refreshing our DAG takes just a few milliseconds.
With Vuex in strict mode, performances (3D framerate) is not affected too much most of the time in any OS / browser combination, apart for Firefox (57.0.4 64-bit) on Linux (Ubuntu 17.10). I don't get those kind of performance degradation on Firefox / macOS or Firefox / Windows.
Why would Vuex strict would have such a performance impact on Firefox / Linux ?

**Comment by LinusBorg** [comment]
That's hard to pinpoint from a description alone

What strict mode does is basically create a deep watcher on the whole state tree. That *is* hard on performance when you have a big store and many operations, it's a tradeoff during development to prevent state changes outside of mutations.

It's probably possbile that the particular code that the deep watcher generates is not optimized well by the browser on that browser/OS combination. The code is not different so there's little if anything we can do about it. We would have to analyse the heap of your app etc. in the same environment that you use - not something we would want to do if it's likely a browser thing.

**Comment by charlesfleche** [comment]
Do you experience / can measure bigger performance hits on FF / Linux generally, or would it be something that is specific to our code ?

**Comment by LinusBorg** [comment]
Personally I can't say anything about that since I haven't really used vuex with a big state in that setup. I don't work on Linux and mostly use chrome for my dev.

**Comment by fnlctrl** [comment]
Since `strict` mode is only meant for development and not production, we won't be investing time trying to find out it may have poor performance on some browser/os combination. If you're interested, you can use [Firefox's Performance Tool](https://developer.mozilla.org/en-US/docs/Tools/Performance) to do some profiling and probably file an issue to Firefox 😄
