### ISSUE TITLE
中英语言doc内容不一致

### ISSUE THREAD

**Issue by yanni4night** [vuejs/vuex#114]
看[这个](https://github.com/vuejs/vuex/commit/db2815909f5341ac767b5334c552e2b892e70c76#diff-1c237e8002fb91ce03a02a02e068a6deR36) CI，这样的示例显然是错误的，store 无法访问到 `actions` 属性。不知道为什么有这样的翻译行为，有误导作用。

**Comment by yyx990803** [comment]
中文翻译标注了 outdated，没看见？

**Comment by yanni4night** [comment]
我是从外链进的其中一页，并没有在入口处看到。如果没有参考价值就可以下掉吧，避免别人也不小心走了弯路。
