### ISSUE TITLE
Error triggering media via store state change in Safari

### ISSUE THREAD

**Issue by breadadams** [vuejs/vuex#1140]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/536yj99n7n](https://codesandbox.io/s/536yj99n7n)

### Steps to reproduce
When trying to play media (audio in this case, but from what [I've read](https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/) it appears to apply to video too), triggering playback of media via an update to the store's state throws an error:

![Safari error](https://s13.postimg.org/hu94qv6hz/image.png)

Clicking the _I DO work in Safari_ button in the codesandbox example, you'll see the audio does play. And after having clicked this, the _TOGGLE AUDIO_ button works too.

### What is expected?
Audio should be played clicking the _TOGGLE AUDIO_ button the first time.

### What is actually happening?
Seeing an error when trying to play media after a state change

**Comment by ktsn** [comment]
Well, this is not a bug of Vuex. As the article you had referred stated, you must play the audio in the context of a user click event.
For support questions, you may want to ask it in [our forum](https://forum.vuejs.org/) or [chat room](https://chat.vuejs.org/).

**Comment by breadadams** [comment]
Yeah I get what you're saying @ktsn, but as you can see in the example I provided, there is a user action involved in playing the media.

It's just that the way Safari is interpreting that "play" is as if it wasn't coming from a user action.

**Comment by ktsn** [comment]
`TOGGLE AUDIO` is indeed a user action, however it only commits the `toggleAudio` action and changes `audioPlaying`. The actual `this.audio.play()` is in the `BackgroundAudio` watcher which is no longer in the click context.

**Comment by breadadams** [comment]
Yes, understood. I guess my _issue_ is more of a question of how to accomplish such a thing with Vuex - ie. how to get around this annoyance in Safari. I'll open a thread in the forums.
