### ISSUE TITLE
The wording of Store.watch in API reference is confusable

### ISSUE THREAD

**Issue by diit** [vuejs/vuex#1141]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/92559/](https://jsfiddle.net/50wL7mdz/92559/)

### Steps to reproduce
Attempt to use store.watch with a getter (store.getters.GETTER_HERE) as explained in docs, and shown in reproduction.

### What is expected?
Handler to be called when variable updated.

### What is actually happening?
Uncaught Error: [vuex] store.watch only accepts a function.

**Comment by diit** [comment]
To see error in reproduction uncomment L18-L21

**Comment by ktsn** [comment]
It actually should be a function but not a real getter. I guess it is written as so because the users have function form getters in Vuex 1.x. We need update the wording to avoid confusion.
