### ISSUE TITLE
"Do not mutate store state outside mutation handler" error but I am using a mutation

### ISSUE THREAD

**Issue by davewood** [vuejs/vuex#1151]
<h3 id="version">Version</h3>
<p>3.0.1</p>
<h3 id="reproduction-link">Reproduction link</h3>
<p><a href="https://github.com/davewood/vuejs-demo/tree/vuex_mutation_error">https://github.com/davewood/vuejs-demo/tree/vuex_mutation_error</a></p>
<h3 id="steps-to-reproduce">Steps to reproduce</h3>
<pre><code>git clone -b vuex_mutation_error git@github.com:davewood/vuejs-demo.git
cd vuejs-demo
npm install
npm run dev
trigger error in console by changing the language in top right corner
</code></pre><h3 id="what-is-expected-">What is expected?</h3>
<p>the state is changed and a notification is shown as expected but i dont get an error in the console</p>
<h3 id="details-">details:</h3>
<ul>
<li>store has an array of notifications</li>
<li>notifications are added using a mutation in <a href="https://github.com/davewood/vuejs-demo/blob/vuex_mutation_error/src/store.js#L16">src/store.js</a></li>
<li>global Vue handler to trigger notification is installed in <a href="https://github.com/davewood/vuejs-demo/blob/vuex_mutation_error/src/notify.js#L15">src/notify.js</a></li>
</ul>
<h3 id="what-is-actually-happening-">What is actually happening?</h3>
<p>the code works but there is an error in the console </p>
<hr>
<pre><code>[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers."

(found in &lt;Root&gt;)  9:579:7
    warn webpack-internal:///9:579:7
    logError webpack-internal:///9:1714:5
    globalHandleError webpack-internal:///9:1709:3
    handleError webpack-internal:///9:1698:3
    run webpack-internal:///9:3209:11
    update webpack-internal:///9:3181:5
    notify webpack-internal:///9:685:5
    mutator webpack-internal:///9:843:5
    add_notification/&lt; webpack-internal:///116:21:9
Error: [vuex] Do not mutate vuex store state outside mutation handlers.
Stack trace:
assert@webpack-internal:///50:104:27
enableStrictMode/&lt;@webpack-internal:///50:753:7
run@webpack-internal:///9:3207:11
update@webpack-internal:///9:3181:5
notify@webpack-internal:///9:685:5
mutator@webpack-internal:///9:843:5
add_notification/&lt;@webpack-internal:///116:21:9
  9:1718:5
    logError webpack-internal:///9:1718:5
    globalHandleError webpack-internal:///9:1709:3
    handleError webpack-internal:///9:1698:3
    run webpack-internal:///9:3209:11
    update webpack-internal:///9:3181:5
    notify webpack-internal:///9:685:5
    mutator webpack-internal:///9:843:5
    add_notification/&lt; webpack-internal:///116:21:9
</code></pre>

**Comment by ktsn** [comment]
@davewood You should not execute async processing like `setTimeout` in mutations. The error happens because the `setTimeout` callback is treated as out of the mutation since its async.

**Comment by davewood** [comment]
hi ktns thank you for the quick answer on my issue even though it was autoclosed (#1150 )

and here is the fix for anyone interested.

https://github.com/davewood/vuejs-demo/commit/668f3d185c89333599330bf18892caf466aeb9ab
