### ISSUE TITLE
Getters on injected dynamic module get lost

### ISSUE THREAD

**Issue by hungphongbk** [vuejs/vuex#1158]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/104859/](https://jsfiddle.net/50wL7mdz/104859/)

### Steps to reproduce
Getters from injected dynamic module on reproduction code must returned "bar ahihi", but actually I got undefined (the getter didn't exist)

### What is expected?
Getters from injected dynamic module on reproduction code must returned "bar ahihi"

### What is actually happening?
Got undefined

**Comment by ktsn** [comment]
You have a typo on `namespaced` option. After fixed it, it's working. https://jsfiddle.net/50wL7mdz/105181/
