### ISSUE TITLE
Mutations not commited

### ISSUE THREAD

**Issue by zokipirlo** [vuejs/vuex#1159]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/r0p9pnr49p](https://codesandbox.io/s/r0p9pnr49p)

### Steps to reproduce
If you open Vue devtools and click commit on last mutation, data will appear.

### What is expected?
Numbers from 1-7 below Data title.

### What is actually happening?
Only title is visible.

---
There is some commented code inside store (`state: items, getter: getItemsForLayoutId`) because that is a code from my real project. This `abc` is just for demonstration that it doesn't work even in a more simple solution.

In HelloWorld component is a `cards`computed property, which loads data from store. If it's not there, then it will dispatch an action to retrieve a data (api call is replaced with dummy data).

I guess I'm doing something wrong, but don't know why.

**Comment by ktsn** [comment]
You shouldn't make side effect in computed properties. In your example, `store.dispatch` is a side effect, then Vue cannot trace the dependency was changed.
You should use life cycle hooks to make request. https://codesandbox.io/s/v3zpn6w4n7

**Comment by zokipirlo** [comment]
Thank you!
