### ISSUE TITLE
Mutation handler don't commit -v

### ISSUE THREAD

**Issue by kwame101** [vuejs/vuex#1161]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/l4k5ko85qm](https://codesandbox.io/s/l4k5ko85qm)

### Steps to reproduce
If you open Vue devtools and click commit on last mutation it returns null in console

### What is expected?
should console log 'CoolStuff' just for testing purpose

### What is actually happening?
The logo and a few text only shows (welcome test)

---
I'm using mapGetter function to get the name but mutation doesnt commit

**Comment by LinusBorg** [comment]
Your reproduction code has a mutation that is never comitted anywhere. of course `name` is still null.

> If you open Vue devtools and click commit on last mutation it returns null in console

There's no option to do that as your example never committed any mutation. Please check your example, it's apparently incomplete.

**Comment by kwame101** [comment]
> There's no option to do that as your example never committed any mutation.
Yes you are right, I forgot to commit it silly me 🤯 btw my problem has been resolved
