### ISSUE TITLE
If module state is an array his submodules are not reactive

### ISSUE THREAD

**Issue by hrasekj** [vuejs/vuex#1167]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/nvkupd14/16/](https://jsfiddle.net/nvkupd14/16/)

### Steps to reproduce
Create an module which have his state as Array. Then create submodule for it.

### What is expected?
Im expecting that computed properties in modules will react to changes on submodule.

### What is actually happening?
Vue does not map his getters & setters to submodule. So submodules state is changing, but computed properties not.

---
It should warn user or something.

**Comment by ktsn** [comment]
state must be an object or a function returning an object. This is because Vue does not make the properties on array reactive.
https://vuex.vuejs.org/en/api.html
