### ISSUE TITLE
Error: [vuex] Do not mutate vuex store state outside mutation handlers.

### ISSUE THREAD

**Issue by rawbin-** [vuejs/vuex#1174]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/m391k2vm8p](https://codesandbox.io/s/m391k2vm8p)

### Steps to reproduce
change the grid lines

### What is expected?
show errors

### What is actually happening?
no errors
<img width="1651" alt="qq20180308-073512 2x" src="https://user-images.githubusercontent.com/8169783/37125015-a0c59d5e-22a5-11e8-99c1-53e85970c4a1.png">

---
any good idea to do with the editable grids with vue and vuex?

**Comment by dodanex** [comment]
@rawbin - I see you have closed this issue. I am having the same problem. How did you fixed it?
