### ISSUE TITLE
Is this safety way?

### ISSUE THREAD

**Issue by bichikim** [vuejs/vuex#1178]
### What problem does this feature solve?
Using a custom property in vuex

### What does the proposed API look like?
    store.subscribeAction((action, state) => {
      if(!state[sSymbol]){
        state[sSymbol] = myToolForSomething
      }
    })

in vuex plugin

It looks likes working well

for example
```
const actions = {
  a({state}, payload) {
    state[sSymbol](gogogo)
  },
} //working
```

What do you guys think?
Is it ok to use in production?

**Comment by LinusBorg** [comment]
Abusing a feature request issue for asking a question is not permitted.

Please use forum.vuejs.org or chat.vuejs.org for questions.

**Comment by bichikim** [comment]
Thanks @LinusBorg I will.
