### ISSUE TITLE
Found text cut off in API Documentation

### ISSUE THREAD

**Issue by Toltar** [vuejs/vuex#1179]
Wanted to report that in the [api documentation](https://vuex.vuejs.org/en/api.html), there is cut off where it shows the arguments of the capture and dispatch methods. See image below.

![documentationcutsoff](https://user-images.githubusercontent.com/6003536/37168025-310ca088-22c9-11e8-9347-4956d4916da5.PNG)

**Comment by fnlctrl** [comment]
Reopening as this is indeed an issue.

**Comment by Toltar** [comment]
Thanks @fnlctrl , I was unsure of how to report this type of issue on here.

**Comment by Jinjiang** [comment]
Guys how about this solution #1189 ? I have split the long api code into 2 pieces and placed them one-by-one together for workaround.
Thanks.

**Comment by Jinjiang** [comment]
![2018-03-14 9 20 14](https://user-images.githubusercontent.com/206848/37405007-74ec14e6-27ce-11e8-83c7-76a79784eec3.png)

**Comment by Toltar** [comment]
@Jinjiang For a permanent solution, could we provide subsections for each method in the documentation of **Usage** and **Description** for this? Such as:

### Vuex Store Instance Methods
#### `commit()`
- Usage
    - **`commit(type: string, payload?: any, options?: Object)`**
    - **`commit(mutation: Object, options?: Object)`**
- Description
    - Commit a mutation. `options` can have `root: true` that allows to commit root mutations in [namespaced modules.](https://vuex.vuejs.org/en/modules.html#namespacing) [Details](https://vuex.vuejs.org/en/mutations.html)

**Comment by Jinjiang** [comment]
@Toltar Yes it's good.
There already are many docs such as vuex vue-router vue-loader vue-test-utils etc with the same format. It will cost a lot if we decide to make the change. Until now there are just two cases not OK and could be fixed another way easily. Maybe it's not necessary enough at this time imo. 🤔
@posva @chrisvfritz how do you think about it? 🙂
Thanks.

**Comment by Toltar** [comment]
@Jinjiang If it is a lot of work, I am willing to help on changing the overall formatting in the English markdown files. 😄 That is, if everyone agrees to it.

**Comment by chrisvfritz** [comment]
I think keeping one bullet-point per item would be best, but I don't have a problem with splitting it into multiple lines. 🙂

**Comment by ktsn** [comment]
This seems to be resolved by migrating vuepress.
