### ISSUE TITLE
Add support for ES5 native getters in state

### ISSUE THREAD

**Issue by parzh** [vuejs/vuex#1180]
### What problem does this feature solve?
It allows on-demand invocations of getters.

See example: https://codepen.io/parzh/pen/KowYJQ?editors=1010

In the given example Vuex store is used to store collection of newly created accounts. Every account is designed so it has a list of related `transactions` and getter `balance`, that returns sum of all the transactions.  
Even in the case with a few accounts the amount of phantom invocations is off the limits.

***

Although on-demand invocations are currently possible (sort of) through usage of Vuex getters, nevertheless such solutions require iterations:
- convertion of every single account to Vuex-compatible object;
- some sort of identification, that iteratively finds the target account and returns its balance;
- dynamic creation of a corresponding Vuex store for every single account in a collection (huh?);

Neither of the solutions above seems reasonable:
- Vuex-compatible object is one with `getBalance()` method, but balance is rather dynamic property;
- iteration, obviously, - number of accounts may be arbitrarily large;
- it is planned that accounts can be easily created and almost as easily deleted;

### What does the proposed API look like?
*no additional API is expected*

**Comment by ktsn** [comment]
Well, you can already do that. https://jsfiddle.net/kmm1x84L/5/

Note that it's not recommended since the getter property cannot be serialized (so you cannot inspect it in the devtools). You should create a helper function which receives your object and returns derived value in that case.

**Comment by parzh** [comment]
Yeah, that's what the third option I was talking about:

> dynamic creation of a corresponding Vuex store for every single account in a collection

Imagine if there are a couple thousand accounts. Then there must be a couple thousand store modules - one for each account. That will definitely exceed the needs.

**Comment by ktsn** [comment]
What do you mean? I think you don’t have to create multiple modules for your use case. You can just store them in state on one module and use helper function or your predefined getter property if you want to derive a part of your account data

**Comment by parzh** [comment]
I mean, `balance` getters belong to account objects. Each `account` has its own `balance`. And there are list of accounts, stored directly in `store.state`:

```js
// won't work
state: {
    accounts: [
        {
            transactions: [ /* ... */ ],
            get balance() { /* ... */ },
        },
        {
            transactions: [ /* ... */ ],
            get balance() { /* ... */ },
        },
    ],
}
```

And in your jsfiddle getter has to belong to the store itself (if I understood correctly):

```js
state: {
    transactions: [ /* ... */ ],
    get balance() { /* ... */ },
}
```

But where should I put the rest of the accounts then?

**Comment by ktsn** [comment]
Wherever the getter property belongs to, it should work since all sub state will be reactive by Vue’s reactive system. I suspect your problem is from other point. 
We encourage you to use [our forum](https://forum.vuejs.org) or [chat room](https://chat.vuejs.org) to ask further support.

**Comment by parzh** [comment]
I'm not saying that it doesn't work!

I'm saying that getters are being evaluated too soon, before any direct interaction. That's the whole point. If I have some heavy task in getter (which I *do* have in real app), it will be executed to often and the whole app will constantly lag.
