### ISSUE TITLE
common state namespace

### ISSUE THREAD

**Issue by GMounir** [vuejs/vuex#1187]
### Version
3.0.0

I have state with common objects for example:

```
export default {
	resource: {
		all: [],
		selected: null
	},
        ....
}
```

i import the state to use in components  

```
import state from '@common/store/state'

export default {
	namespaced: true,
	state,
	getters,
	actions,
	mutations
}
```

after that i use namespace in every component everything working, but one thing i don't know if is right or not:

i'm working in namespace **test1**
if i did an action to resource for example fill **resource.all[...]**
the namespace **test2** also is filled.
i tried _.clone(), _.assign() not working or i did not used right.
Please someone help me...

### What is expected?
expected: fill only the state that i'm woking in

### What is actually happening?
happening: fill all states

**Comment by ktsn** [comment]
This is expected. If you don't want to mutate original object, you should make separated object by using a generator function.

```js
function createState() {
  return { /* state */ }
}

export default {
  // provide initial state
  state: createState()
}

// use it outside of vuex
const state = createState()
```
