### ISSUE TITLE
vuex中文文档更新

### ISSUE THREAD

**Issue by jqjiang** [vuejs/vuex#119]
vuex中文文档更新及时一些

**Comment by yyx990803** [comment]
你可以参与翻译发 PR，但请不要开这种无意义的 issue。

**Comment by yisibl** [comment]
https://vuefe.cn/vuex/

**Comment by jingsam** [comment]
@yyx990803 vuex 2.0 的中文文档其实早就提[PR](https://github.com/vuejs/vuex/pull/401) 了，似乎没什么人管

**Comment by yyx990803** [comment]
@jingsam 抱歉，那个 PR 的 title 比较长，我还以为是 windows 相关的所以我一直没仔细看...

里面有一个小 conflict，resolve 一下我就可以 merge。
