### ISSUE TITLE
Vuex KR documentation has an issue

### ISSUE THREAD

**Issue by khg0712** [vuejs/vuex#1203]
### What problem does this feature solve?
In state part of origin Vuex documentation, it use same word 'Object Spread Operator'. but it was translated into different words in the Korean translation '객체 전파 연산자' and ' 객체 확산 연산자'. This problem can be misunderstood by other users.

### What does the proposed API look like?
in KR Vuex documentation it has an error

**Comment by ktsn** [comment]
You can open a PR for that 🙂

**Comment by ktsn** [comment]
fixed via #1204
