### ISSUE TITLE
e2e test command went wrong

### ISSUE THREAD

**Issue by zexiplus** [vuejs/vuex#1213]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vuex/blob/dev/test/e2e/runner.js](https://github.com/vuejs/vuex/blob/dev/test/e2e/runner.js)

### Steps to reproduce
npm run test:e2e --test cart.js

### What is expected?
saw the e2e test result

### What is actually happening?
something went wrong and no test result

---
when I run npm run test:e2e --test cart.js, nothing happens and no result.
I think node won't read args with '--' like '--test' as process.argv .
One snippet in test/e2e/runner.js is 
```js
var i = args.indexOf('--test')
if (i > -1) {
  args[i   1] = 'test/e2e/specs/'   args[i   1]
}
```
emm, the process.argv seems contains no '--test'

**Comment by ktsn** [comment]
Please try `npm run test:e2e -- --test cart.js`

https://docs.npmjs.com/cli/run-script

> As of npm@2.0.0, you can use custom arguments when executing scripts. The special option -- is used by getopt to delimit the end of the options. npm will pass all the arguments after the -- directly to your script:
> 
> npm run test -- --grep="pattern"

**Comment by zexiplus** [comment]
thanks for your answer
