### ISSUE TITLE
Proposal: make registerModule() accessible in action context

### ISSUE THREAD

**Issue by drdaemos** [vuejs/vuex#1224]
### What problem does this feature solve?
Currently, the only way to dynamically create a module is the `$store.registerModule` method. I consider this a leaking abstraction because the components should not control store internals. It would be helpful to have such method as a part of action context object (also, a namespaced version would be very good to have) because more often than not such dynamic activity is strongly tied to API querying (otherwise, why would one not register modules in before?).

My end user experience which led to this proposal is trying to build a page, which would show multiple collections of items filtered by various conditions (an app marketplace, to be exact). These collections are acquired from the backend via GraphQL and are tied to a 3rd party API which cannot be accessed directly from the frontend.

Right now I'm doing this via `beforeMount` hook of the root presentation component:
```
// Presentation component
      this.$store.dispatch('selections/fetchLanding', this.$store.registerModule.bind(this.$store))
}

// Store module
actions: {
  fetchLanding ({commit, state}, registerModule) {
    queryCollections.bind(self)(state.filter)
      .then((result) => {
        for (let key in result.collections) {
          if (typeof state.collections[key] === 'undefined') {
            registerModule(['collections', key], (new CollectionModule(self.client)).createModule())
          }
        }
        commit('SET_COLLECTIONS', result.collections)
      })
  }
},
```

But passing the bound registerModule method in payload looks ugly.

### What does the proposed API look like?
I've cleaned up the example to keep it precise to the task:

```
// Store module
namespaced: true,
actions: {
  fetchSomething ({commit, state, registerModule}) {
    querySomeAPI()
      .then((result) => {
        registerModule(namespacedKey, new ModuleInstance())
      })
  }
}
```

**Comment by ktsn** [comment]
Hi @drdaemos, thanks for proposing this!
I would see you want to separate your module registration logic with the view. So why don't you just import `store` instance in separated files?

```js
import store from './store'

function fetchAndRegister(param) {
  querySomeAPI(param)
    .then(result => {
      store.registerModule(key, new ModuleInstance(result))
    })
}
```

I'm not sure including `registerModule` in context since it seems to be less related with the modules themselves. Is there any use case that you need to register a new module in the modules?

**Comment by drdaemos** [comment]
Hi @ktsn, thanks for answering.

The reason not import `store` instance is that this requires exporting instance as a module, which would complicate injecting some dependencies like an API wrapper (also, it goes against the idea of providing modules as classes, not instances). Right now the store instance is being provided by a module with generating function:

```
export default function (authorizationClient, apiClient) {
  return new Vuex.Store({
    state: initialState,
    mutations: mutations,
    actions: (new Actions(authorizationClient, apiClient)).createActions(),
    getters: (new Getters()).createGetters(),

    modules: {
      exampleModule1: (new ExampleModule(apiClient)).createModule(),
      exampleModule2: (new ExampleModule2(apiClient)).createModule(),
    }
  })
}
```

As I've previously stated, we're registering modules dynamically after we get information from the API. We could have just a state property and do `Vue.set(state, 'dynamicProp', updatedValue`, but nested submodules are so much better.

Personally, I don't see much difference between the simple state object and the vuex module as an encapsulated state object with local getters\actions\mutations (it is even available in the local state) - these are just tools to structure the global app state with different abstraction level.

Sorry if I might seem unclear, I'm open to any questions.

**Comment by bichikim** [comment]
I made [this](https://www.npmjs.com/package/vuex-keg) just take a look :) 
It might help you~

**Comment by pi0** [comment]
@drdaemos I think you can use `this` in the context of vuex action functions which references to the store instance. So this may work:

```js
// Store module
namespaced: true,
actions: {
  fetchSomething ({commit, state}) {
    querySomeAPI()
      .then((result) => {
        this.registerModule(namespacedKey, new ModuleInstance())
      })
  }
}
```

**Comment by LinusBorg** [comment]
Note that for this to work, the action itself can't be an arrow function (which is otherwise pretty common to do, so an easy pitfall)

**Comment by drdaemos** [comment]
@pi0, oh wow, I never thought to check `this`. You've just opened my eyes О_о
In the light of this conclusion, there is no reason to change anything, my problem is solved. 

Thanks everyone for your help!
