### ISSUE TITLE
[docs] I want to write a Portuguese version

### ISSUE THREAD

**Issue by isaacguerreir** [vuejs/vuex#1230]
### What problem does this feature solve?
I'm from Brazil and using Vuex in my work. I want to translate the documentation to Portuguese. I have to do something before start the translation?

### What does the proposed API look like?
I will only create a paste in docs with the Portuguese version of the documentation, like other languages do.

**Comment by eeerrrttty** [comment]
nice friend! Im from Brasil too! Love vuex

**Comment by ktsn** [comment]
Thanks! I just merged an initial pt-br translation. https://github.com/vuejs/vuex/tree/dev/docs/pt-br
If you find something to improve, please make a PR for that 🙂
