### ISSUE TITLE
A small fix in typings for StoreOptions

### ISSUE THREAD

**Issue by MrVichr** [vuejs/vuex#1231]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/l2wzjwp4vm](https://codesandbox.io/s/l2wzjwp4vm)

### Steps to reproduce
Sorry I'm not going to spend several hours making a minimal demo project and uploading it to github just to have 8 letters added. The error and fix should be obvious.
```typescript
// src/datamodel/appstore.ts
class TAppStore {
  counter: number=0;
};

export var AppStore=new Vuex.Store<TAppStore>({ 
  state: function() {
    console.log('creating AppStore'); //gets called just fine
    return new TAppStore();
  }
}
```

### What is expected?
No errors reported on compilation.

### What is actually happening?
```
ERROR in j:\types\CML\front\src\datamodel\appstore.ts
[tsl] ERROR in j:\types\CML\front\src\datamodel\appstore.ts(44,2)
      TS2345: Argument of type '{ state: () => TAppStore; }' is not assignable to parameter of type 'StoreOptions<TAppStore>'.
  Types of property 'state' are incompatible.
    Type '() => TAppStore' is not assignable to type 'TAppStore | undefined'.
      Type '() => TAppStore' is not assignable to type 'TAppStore'.
        Property 'counter' is missing in type '() => TAppStore'.

  Build failed with errors.
```

---
It seems that vuex/types/index.d.ts, in interface StoreOptions, is missing the possibility of using a function instead of an object.
This is the recommended way to initialize state: https://vuex.vuejs.org/en/modules.html (chapter Module Reuse, at the very bottom).
An easy fix would be editing the vuex/types/index.d.ts StoreOptions:
```diff
export interface StoreOptions<S> {
- state?: S;
  state?: S|(()=>S);
  getters?: GetterTree<S, S>;
  actions?: ActionTree<S, S>;
  mutations?: MutationTree<S>;
  modules?: ModuleTree<S>;
  plugins?: Plugin<S>[];
  strict?: boolean;
}
```

**Comment by ktsn** [comment]
Thanks. There is a PR already #1132

**Comment by ktsn** [comment]
#1132 is already merged.
