### ISSUE TITLE
handle async action with promise call to REST API

### ISSUE THREAD

**Issue by rcholic** [vuejs/vuex#1234]
### What problem does this feature solve?
I posted the following question on Stackoverflow in the first place, but then I realized I should have probably asked you guys first: [https://stackoverflow.com/questions/49849725/vuex-handle-async-action-with-promise-call-to-rest-api](https://stackoverflow.com/questions/49849725/vuex-handle-async-action-with-promise-call-to-rest-api)

I use TypeScript with Vue/Vuex to create a toy app, in which I need to load a list of items from remote API upon rendering a component. In the actions below, I use the library `axios` to make http request, and I return it as a promise:

```ts
    const actions = {    
      getCurrentSession(context: Context) {
        return axios.get("http://localhost:3000/sessions/current")
          .then((res) => {
            commitSharedFiles(context, res.data.shared_files);
          })
          .catch((e: string) => {
            console.error(e);
          });
      }
    };
    
    // export action
    export const dispatchGetSharedFiles = dispatch(actions.getCurrentSession);

    // commit
    export const commitSharedFiles = commit(mutations.setSharedFileList);
    
    // mutations to the state tree
    const mutations = {
      setSharedFileList(state: State, sharedFiles: StoreState.DirFile[]) {
        state.sharedFileList = sharedFiles;
      }
    };
```
Because of the asynchronous nature of the actions, I have to resolve the promise before retrieving the fetched list of files from the store/state tree:
```ts
    // this is called in the mounted() life cycle method:
    Store.dispatchGetSharedFiles(this.$store).then(res => {
                this.sharedFiles = Store.readSharedFilesList(this.$store);
    });
```
This works, but I think it is very convoluted to resolve the promise and then get the data. Is there a better way to use async actions in Vuex? thanks

### What does the proposed API look like?
no idea

**Comment by ktsn** [comment]
Please use StackOverflow, [forum](https://forum.vuejs.org) or [chat room](https://chat.vuejs.org) for asking usage questions. The issue list of this repo is dedicated for bug reports and feature request.
