### ISSUE TITLE
Modify documentation(jp) to remove 'silent commit'

### ISSUE THREAD

**Issue by aloerina01** [vuejs/vuex#1236]
### What problem does this feature solve?
A user, especially Japanese user, use 'silent' option by mistake.

### What does the proposed API look like?
Remove or modify below.  
[サイレントコミット · Vuex](https://github.com/vuejs/vuex/blob/5c0050b8861f1995118c9b49a50da25bbd9354ce/docs/ja/mutations.md#%E3%82%B5%E3%82%A4%E3%83%AC%E3%83%B3%E3%83%88%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88)

Refs:
- [adds mutation filtering to Vuex tab](https://github.com/vuejs/vue-devtools/pull/172)
- [https://github.com/vuejs/vuex/blob/38b236803d592efda141384387bddaf4e0025e2c/src/store.js#L109-L110](https://github.com/vuejs/vuex/blob/38b236803d592efda141384387bddaf4e0025e2c/src/store.js#L109-L110)

**Comment by ktsn** [comment]
You can open a PR.

**Comment by ktsn** [comment]
fixed via #1239
