### ISSUE TITLE
Pass options in mapGetters for computed

### ISSUE THREAD

**Issue by willypuzzle** [vuejs/vuex#1237]
### What problem does this feature solve?
For example when I use mapGetters, I need the resulting computed ones have cache:false flag set. But it could be valid even for other flags.

### What does the proposed API look like?
```
computed: {
   ...mapGetters('module', {
               simpleGetter: {
                        options: {
                                 cache: false
                        },
                       handler: 'simpleGetter'
               }
      })
}
```

**Comment by ktsn** [comment]
Actually `cache` option of `computed` is soft deprecated. It is not written in the Vue.js documentation now. So you should not use it.
