### ISSUE TITLE
registerModule option to preserve state while initializing attributes added since previous initialization

### ISSUE THREAD

**Issue by acan13** [vuejs/vuex#1257]
### What problem does this feature solve?
Context: Currently if you use registerModule with {preserveState: false} it will reinitialize the entire module state and overwrite all the values. If you use {preserveState: true} it will not do anything to the current values.

Problem: What if you wish to preserve the values, but you have added attributes since the last time the module was initialized? If you use {preserveState: true} it will not add the new attribute (possible breaking things) while if you use {preserveState: false} it will overwrite all of the state already there. 

Feature request: Could there be a happy medium where vuex will only initialize attributes that aren't already present?

Use case: We are using vue persisted state to persist UI settings stored in vuex. Because we reuse these settings in a few different apps, we store the module definitions in a shared folder and then import them into our different apps using registerModule. If we use {preserveState: false} then the settings in place are overwritten while if we use {preserveState: true} the new settings we add don't get added to the store.

### What does the proposed API look like?
The current behavior makes sense to me, so I would propose leaving it and adding another option. I have no idea what to call it, but something like:
```javascript
Vue.registerModule('mymodule', myModule, {preserveState: true, updateAttributes: true});
```

I'm new to this, but I would be willing to look into how to implement it if people think it would be a good idea.

**Comment by jatarga** [comment]
I think you should check the state attributes and merge or update based on your business case. You may want to use [_.merge()](https://lodash.com/docs/4.17.10#merge) which recursively does the job for you.

**Comment by ktsn** [comment]
I agree with @jatarga. I think adding such feature in Vuex seems not appropriate since it is your app specific logic. Also you can easily update your state by using mutation after registering the module.
