### ISSUE TITLE
Can you add hooks before and after mutation actions ?

### ISSUE THREAD

**Issue by smithyj** [vuejs/vuex#1262]
### What problem does this feature solve?
come true global loading plugins

### What does the proposed API look like?
for example:
store.subscribeBeforeAction()
store.subscribeAfterAction()
store.subscribeBeforeMutation()
store.subscribeAfterMutation()

**Comment by LinusBorg** [comment]
> come true global loading plugins

I assume that this is because of a language barrier but I don't have antsy idea what you mean by that.

**Comment by smithyj** [comment]
Sorry, I hope vuex is supports global loading status

**Comment by smithyj** [comment]
see title , that is also problem

**Comment by smithyj** [comment]
@LinusBorg

**Comment by LinusBorg** [comment]
I think I get what you mean. I think something like that was already discussed, we'll see if we willl implement it. If we do, it won't be "tomorrow".

Until then you can write simply action enhancers on your own:

```javascript
function enhanceAcion(actionFn) {

  return function (context, payload)  {
    // initialize global loading status

    actionFn.call(this, context, payload).then(() => {
      // disable gloabl loading status.
    })
  }
}

// in a store module:

const actions = {
  myAction: enhanceAcion(({commit}, payload) => {
    //... your normal action. make sure to return a promise.
  })
}
```

IF you have questions about this, please use forum.vuejs.org or chat.vuejs.org, don't ask here - this issue is about your proposal, not my workaround.

**Comment by smithyj** [comment]
Great Idea Thanks

**Comment by smithyj** [comment]
全局loading包装

**Comment by seyfer** [comment]
@LinusBorg this hack doesn't work if helper `mapActions` is used. Then payload is undefined.

**Comment by LinusBorg** [comment]
Wouldn't see why as it's passed through transparently.

**Comment by danbars** [comment]
Wouldn't plugins allow to do exactly that? From the example [here](https://vuex.vuejs.org/guide/plugins.html):
```js
store.subscribe(mutation => {
   if (mutation.type === 'UPDATE_DATA') {
     socket.emit('update', mutation.payload)
   }
 })
```
