### ISSUE TITLE
add a `mapDataFromGetters` helper 

### ISSUE THREAD

**Issue by rv-akim** [vuejs/vuex#1265]
### What problem does this feature solve?
This would allow developers to hydrate component state in the `data` property  from the store, without having to do it in mounted.

The problem right now with `mapGetters` and `mapState` is that they are defined in computed after data gets evaluated.

I want to get away from:

```
data() {
  return {
    firstName: this.$store.getters.firstName,
    lastName: this.$store.getters.lastName,
  }
}
```

Setting these values in mounted and using computed values on mount seems to be a lot of boiler plate when I simply want to hydrate data using store values in `data` of a component.

### What does the proposed API look like?
The above example would translate roughly to this:
```
function mapGettersToData(gettersObj, context) {
  const mappedGetters = {};
  Object.keys(gettersObj).forEach((key, i) => {
     mappedGetters[key] = context.$store.getters[Object.values(gettersObj)[i]];
  });
  return mappedGetters;
}
```
```
data() {
  return {
    ...mapGettersToData({
      propName: 'path/to/getter',
    }, this),
  };
}
```

Or extend mapGetters/mapState to work in data property of a component

**Comment by GopherJ** [comment]
mapState can't work in data property ?

**Comment by rv-akim** [comment]
doesn't work for me.

**Comment by ktsn** [comment]
You can write such helper function without modifying Vuex. I encourage you to make it as an external library.
