### ISSUE TITLE
Adjust vuex types for using state values and modules in one store

### ISSUE THREAD

**Issue by ChristianStornowski** [vuejs/vuex#1267]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/14njpn10p3](https://codesandbox.io/s/14njpn10p3)

### Steps to reproduce
1. Create a project like https://codesandbox.io/s/14njpn10p3
2. npm run test:types

### What is expected?
no type errors.

### What is actually happening?
src/test.ts(46,41): error TS2345: Argument of type '{ state: { value: number; }; modules: { a: Module<AModule, RootState>; }; }' is not assignable to parameter of type 'StoreOptions<RootState>'.
  Types of property 'state' are incompatible.
    Type '{ value: number; }' is not assignable to type 'RootState | undefined'.
      Type '{ value: number; }' is not assignable to type 'RootState'.
        Property 'a' is missing in type '{ value: number; }'.

**Comment by pikax** [comment]
your `RootState` requires the `{ a: AModule; }`, that error should be expected.

The issue comes from the `Store` class doesn't merge the `modules.state` to the `root.state`.

**Comment by kiaking** [comment]
Yes, you should be adding all module states to the root state interface 👍
