### ISSUE TITLE
TypeError: Cannot read property '${anyKey}' of undefined

### ISSUE THREAD

**Issue by falstack** [vuejs/vuex#1272]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/m99jmqsa/2/](https://jsfiddle.net/m99jmqsa/2/)

### Steps to reproduce
```
1：open：https://jsfiddle.net/m99jmqsa/2/
2：open chrome console
3：look error
4：rewrite [html] "<!-- <div>{{myData2}}</div> --> " to "<div>{{myData2}}</div>"
5：run，look error
```

### What is expected?
noError, can render success

### What is actually happening?
render error

---
when i get a object，it may very deep，{ a: 1, b: { c: 2, d: { e: 3 } } }...

how can i set init state?

**Comment by ktsn** [comment]
You are accessing the empty property before dispatching action.
