### ISSUE TITLE
The TypeScript definition files incorrectly specifies the map* functions as named exports.

### ISSUE THREAD

**Issue by ciddan** [vuejs/vuex#1274]
### Version
3.0.1

### Reproduction link
[https://github.com/ciddan/vuex-ts-issue](https://github.com/ciddan/vuex-ts-issue)

### Steps to reproduce
Reproduction of an issue with the TypeScript type definitions in Vuex.

1. Clone the provided repository.
2. run npm install
3. run npm start
4. Open browser and go to http://localhost:8080.
5. Open dev tools and look at the console output.

### What is expected?
That the first log output: ```mapActions from: import { mapActions } undefined``` isn't undefined.

### What is actually happening?
mapActions is undefined.

---
Please read the README in the linked repository for full information on the issue.

We ran into this issue while working on TypeScript decorators that required the use of the various map functions.

**Comment by nulpatrol** [comment]
@ciddan I see that you specify module-option as "system" in your TS config.
And then you will try to use ES Module feature - named exports (not destructuring).
Try to change option to "es2015" and all will be OK. I checked.

@LinusBorg I think there is no any Vuex issues.

**Comment by ktsn** [comment]
fixed via #1408
