### ISSUE TITLE
Syntactic sugar for commiting mutations

### ISSUE THREAD

**Issue by vog** [vuejs/vuex#1281]
### What problem does this feature solve?
Committing mutations has a very strange syntax, which really stands out negatively, compared to the otherwise very elegant APIs found in the Vue/Vuex ecosystem:

    this.$store.commit('someMutation', args...)

The docs mention that this is to emphasize that a commit is not a direct call to the mutation. I don't think this line of reasoning holds in the Vue/Vuex world. In almost all other aspects of Vue/Vuex, the API looks straight forward (e.g. just getting and setting properties), but under the hood a lot of additional logic runs (dependency tracking, etc.). So there is really no need to make committing mutations more cumbersome than they need to be.

In addition to making the code harder to read, this leads to additional rules about argument passing.

Moreover, it is very hard to spot typos in the mutation name early on, as the mutation name is just a string - let alone checking that the call to `commit()` received the correct arguments according to the mutation function. These types of errors should be easy to spot at compile time, but with the current syntax, these are all pushed into runtime.

Finally, this cumbersome syntax might be (correctly) perceived as boilerplate, especially to beginners. Hence, replacing the commit syntax with a more straight forward syntax might improve the adoption of Vuex.

### What does the proposed API look like?
Instead of:

    this.$store.commit('someMutation', args...)

one should be allowed to write:

    this.$store.someMutation(args...)

Moreover, it would be great if looking at `this.$store` in the developer console all available mutation methods are shown. That is, the methods should be real properties of this.$store, collected once at program start.

Under the hood, of course, these methods might all call some central commit() function.

Alternative syntax: The above syntax might introduce some name collisions. For example, someone might name one of their mutations "state", for whatever reason, making "this.$store.state" ambiguous. For the sake of simplicity, these names should just be forbidden as mutation names. But if this is not an option for whatever reason, an intermediate object might do the trick as well. This would be less beautiful, but still better than what we have today:

    this.$store.commit.someMutation(args...)

or shorter:

    this.$store.c.someMutation(args...)

As an additional proposal, the old `this.$store.commit()` syntax should be marked deprecated.  And removed in future Vuex versions. This generic call is not needed. Any generic commit call might as well be formulated as `this.$store[mutationName](args...)`, which is still easy to understand and even shorter than `this.$store.commit(mutationName, args...)`.

**Comment by ikenfin** [comment]
I think commit changes outside of vuex store is'nt a good practice - you can use actions instead (and get syntax sugar there (es6) - `actionName({ commit }, data) { commit('something', data) }`)

Secondly - it's a common pattern to use `namespace/name` mutation names, so i don't think it's possible to use that names with dot notation.

By the way, i think we already have a good pattern of vuex use:

```javascript
// state.js
export {
  data: ''
}

// mutation-types.js
const MY_MUTATION = 'module_a/CHANGE_SOMETHING_IN_STATE'
export {
  MY_MUTATION
}

// mutations.js
import { MY_MUTATION } from './mutation-types'
export default {
  [MY_MUTATION] (state, data) { state.data = data }
}

// actions.js
import { MY_MUTATION } from './mutation-types'
export default {
  setData ({ commit }, data) {
    commit(MY_MUTATION, data)
  }
}
```

**Comment by ikenfin** [comment]
@vog sure, there you go - https://vuex.vuejs.org/guide/structure.html

**Comment by vog** [comment]
Thanks!
