### ISSUE TITLE
The `find` function didn't check the first item in a array

### ISSUE THREAD

**Issue by zach5078** [vuejs/vuex#1286]
https://github.com/vuejs/vuex/blob/b536fbd898ebbd452154d94aabb35c2747d8e2f3/src/util.js#L9

example:
console.log(find([3, 1, 1, 2], (v) => v > 2))    // undefined

correct version:
```
function find (list, f) {
  const { length } = list
  let index = 0
  let value
  while (index < length) {
    value = list[index++]
    if (f(value, index, list)) {
      return value
    }
  }
}
```

**Comment by jiraguha** [comment]
@ktsn why proposition made by @zach5078 to solve your initial code was not taken into account. I think it was a good idea. `list.filter(f)[0]` is slower especially when the element to find in the list has a low index. But I am sure that you agree!

**Comment by jiraguha** [comment]
And you probably do not use the `arr.find(callback(element[, index[, array]])[, thisArg])` because IE :-(
