### ISSUE TITLE
Tutorial is not working

### ISSUE THREAD

**Issue by watkazuki** [vuejs/vuex#1295]
### Version
3.0.1

### Reproduction link
[https://github.com/watkazuki/vuex-tutorial](https://github.com/watkazuki/vuex-tutorial)

### Steps to reproduce
Please download this repository. 

### What is expected?
Not stumble for learner of vuex like me.
https://github.com/vuejs/vuex/blob/master/docs/en/tutorial.md
I tried it and not working. I would appreciate it if this turorial could be updated, or add ' this way of coding is deprecated '.

### What is actually happening?
https://github.com/vuejs/vuex/blob/master/docs/en/tutorial.md
I saw it in Japanese Version, I saw and try it, and I can't solve it.Then, I  saw this website https://github.com/vuejs/vuex/releases/tag/v2.0.0-rc.1,
I got to know this way of coding is deprecated.

```
export default {
    vuex: { 
       actions: {}
    }
}
```

---

**Comment by ktsn** [comment]
It's outdated docs. Please see https://vuex.vuejs.org/
