### ISSUE TITLE
store.registerGetters and store.registerActions

### ISSUE THREAD

**Issue by trainiac** [vuejs/vuex#1299]
### What problem does this feature solve?
To be able to fully code split all application logic across application routes it would be helpful to have a way to dynamically register getters and actions.  Currently registerModule only supports registering namespaced modules with `store.registerModule`.  

For example lets say you have two namespaced modules that you dynamically load into your application: Sandwich and Human.  The two modules shouldn't know anything about each other.  There needs to be some highter level actions and getters that can tie the two together that you can also dynamically load.

### What does the proposed API look like?
```
store.registerActions({
  ...newActions
})

store.registerGetters({
  ...newGetters
})
```
These functions would still throw errors if the user tried to register duplicate actions or getters so it would be up the the user to make sure they are not passing in duplicates by checking existing data and making sure their actions and getters are namespaced appropriately.

**Comment by LinusBorg** [comment]
>  The two modules shouldn't know anything about each other.

Why? In a "large application", that seems to be an unnecessary limitation. I understand that plugins that add store modules have the callenge of not necessarily having contol over the namespace they are given, but that's a different problem.

Can you make the case, shortly, why these modules should not kow about each other? It sounds like they need to interact in some way, why can't/shound't they know about each other's namespace in the application you contol?

>  There needs to be some highter level actions and getters that can tie the two together that you can also dynamically load.

So assuming for a moment you made that case that they should not kow about each other, in other words: they don't know about. Wouldn't it be enough to have some pre-defined actions/mutations in the main state which you can use to save a "public interface"  in the main state for each module?

What would those actions that you define here typically do?

**Comment by trainiac** [comment]
Hi @LinusBorg. 

I use `store.registerModule` to be able to code split my vuex store across routes not for loading 3rd party modules.  It works great for that so why cant I also do that getters and setters.

Let's say that I am making two parts of a Party planning app.  The first part is for the organizer who is managing the party.  The second part is for the people rsvping.  The underyling modules in the store are for managing data for party details, participants, and the organizer.  Both apps would need the underlying mechanism for fetching that data, storing it locally and retrieving it in a consistent way.  Ideally both apps could reuse those modules.  However, there are a number of operations an organizer might do on the participants list such as adding, editing, or removing that some one rsvping would never do. Those operations involve code that would never be run on the RSVP page so why add the page weight?  In this trivial example it's not a big deal but in my app there are enough routes and business logic that putting all of that information in the store before it's needed wouldn't scale.

I'm achieve code splitting for this type of logic now by defining plain functions that my router and components can import and pass the whole store into. But seems like it would be trivial for Vuex to expose these two functions with main reason being code splitting.

**Comment by trainiac** [comment]
So in other words it's not that they shouldn't know about each other.  It's just that on some pages they need to know some things about each other and on other pages they need to know other things about each other.  Those "things" they "know" about each other is business logic, lines of code that are only applicable on those pages and if you have an app with a 30 different routes or so and you trying to meet the impossible PWA limitation of ~200K before gzipped you will never get there front loading your vuex store full of business logic that is specific to each page :)

**Comment by LinusBorg** [comment]
I understand the scenario, but I don'T see what `registerAction()` or `registerGetter()` would allow to that solves / improves this situation.

**Comment by trainiac** [comment]
It allows you to dynamically load in code that is specific to the page being viewed. Specifically getters and actions that are at the root level so they can dispatch to and get from a variety of children modules. 

I _could_ just register another namespaced module that encapsulates this page specific business logic but it just feels awkard because I'd constantly be reaching for rootState, rootGetters, or dispatching to root within the module in order to communicate with the other namespaced modules.

What I'm currently doing "works", registering another namespaced module would also "work" but they both feel like awkward ways of doing what I want.  I want to dynamically load actions and getters that dont have use rootState and rootGetters in order to get to the information that I need.

**Comment by trainiac** [comment]
This would be an example of what I mean tying together two different modules
```js
export default {
   actions: {
     addParticpantToParty ({ dispatch }, participantData) {
       return dispatch('participant/create',  participantData).then(participant => {
       return dispatch('party/addParticipant', { id: participant.id })
      })
    },
   }
}
  
```

If I register this actions as another namespaced module it would look a little uglier
```js
export default {
   actions: {
      addParticpantToParty ({ dispatch }, participantData) {
        return dispatch('participant/create',  participantData).then(participant => {
          return dispatch('party/addParticipant', { id: participant.id }, { root: true })
        }, { root: true })
     },
   }
}
  
```


Or what I'm doing now. It's a llittle better than having to declare root all the time but it's no fun having to always rembember to pass in the store every time.
```js
export default function addParticpantToParty (store, participantData) {
      return store.dispatch('participant/create',  participantData).then(participant => {
        return dispatch('party/addParticipant', { id: participant.id })
      })
}
  
```

**Comment by sagunkho** [comment]
could this be related? https://stackoverflow.com/questions/51491124/vuex-dynamic-modules-are-not-being-namespaced

**Comment by LinusBorg** [comment]
No, it isnt.

**Comment by trainiac** [comment]
@ktsn Thanks for the reply, somehow I missed it.  I tried dynamically registering them as root but there is a restriction https://github.com/vuejs/vuex/blob/dev/src/store.js#L159-L171.   You cant register modules as root.
