### ISSUE TITLE
Warn when adding a function to the state

### ISSUE THREAD

**Issue by essenmitsosse** [vuejs/vuex#1309]
### What problem does this feature solve?
Right now Vuex warns you (in dev mode) when changing the state from outside - which is good and important. But right now it can (accidentally) be circumvented with closures, by adding a function to the state.

```javascript
// Create a closure
const myFunctionFactory = () => {
	const myValues = {
		foo: 0,
	};

	return () => {
		myValues.foo  = 1;
		return myValues.foo;
	};
};

// Get the function inside the closure
const myFunction = myFunctionFactory();

// Add the function to the state
Vue.set( state, 'myFunction', myFunction );

// New each time the function is called, a different result is returned
state.myFunction(); // => 1;
state.myFunction(); // => 2;
state.myFunction(); // => 3;
state.myFunction(); // => 4;
```

This can introduce really subtle bugs and also makes time travel unusable. There also seems to be no way to prevent this, except for not allowing functions in state at all.

It would be great to hear other peoples opinions on the subject.

### What does the proposed API look like?
In my opinion adding functions to the state should be discouraged in docs.

In dev mode it would be great if an error could be thrown if a function is discovered in the state - at least if strict mode is enabled or something like that.

**Comment by ktsn** [comment]
IMO, providing warning in such case is not appropriate. Because users may do that to switch their app behavior by changing the function in the state and it's not a problem if the function is pure.

In any cases, observing all state property types is too complicated to implement than just realizing any state changes (current behavior). I don't think we can add such feature in Vuex.

**Comment by essenmitsosse** [comment]
I understand your reasoning here. Switching app behaviour trough functions in the state is also the situation that created the subtle bug for me. Even just referencing the function (for example by string name) doesn't help, because now the state is referencing something impure.

So I was wondering if there is a "save" way of doing that. How do I ensure, nothing in my state mutates without vuex noticing it?

Also if there (currently) is no way of guaranteeing this, the question remains: Is this something, that should be pointed out in the docs? 

Or is the abuse of closures to "mutate" the state even considered a use case?

**Comment by ktsn** [comment]
Important point here is mutating a variable in lexical scope is not a Vuex specific thing. So I don't think it should be stated in the Vuex docs. I think a function mutating some value in a lexical scope is a bit problematic but having a pure function in the state should not make any problems. And we cannot detect the function whether includes problematic logic or not.
