### ISSUE TITLE
variable of state changed for 3 times, but the getters use it only triggered for once when app init.

### ISSUE THREAD

**Issue by owey0312** [vuejs/vuex#1325]
### Version
2.5.0

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
1、start app;  we can see shoppedGoodsList getter triggered once.
2、see shopping cart page: empty now;
3、add 2 goods to cart, commit has changed state variable goodsInfo as we can see it from console;
       but at this time, we can not see  shoppedGoodsList getter triggered any more;
4、see shopping cart page: empty as before;

### What is expected?
getter triggered for 3 times

### What is actually happening?
getter triggered for 1 times at app startup.

---
/********store info as below******************/
const state = {
   goodsInfo: {}
};

const getters = {
    shoppedGoodsInfo(state){
        return state.goodsInfo;
    },
    shoppedGoodsList(state){
        let info = UTILS.object.map(state.goodsInfo, (k, v)=>{
            let rs = {
                id: k,
                name: v.info.prodName,
                price: v.info.price,
                media: v.info.thumbnailList[0],
                feature: v.info.feature,
                count: v.count,
                maxCount: v.info.limit
            };
            return rs;
        });
        console.log('triggered', info);
        return info;
    }
};

export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions
}

/******vue info as below************/
computed: {
        ...mapGetters('shoppingCart', ['shoppedGoodsList']),
    }

**Comment by LinusBorg** [comment]
Hi  

Thanks for filing this issue! Could you please provide a small reporduction on jsfiddle.net so we can debug this without trying to replicate this ourselves?`

That would be very helpful, thanks!

**Comment by owey0312** [comment]
i have find what's wrong, as i should remove attribute of object use globally function: 
**Vue.delete( target, key )**
I  print the answer here for helping whom got errors as same as me in develop.
