### ISSUE TITLE
Warn when mapGetters et. al. are used in the wrong property

### ISSUE THREAD

**Issue by tomers** [vuejs/vuex#1329]
### What problem does this feature solve?
I've spend couple of hours debugging an issue which caused by me mistakenly writing _mapGetters_ under _computed_ instead of under _methods_.
It would be so much helpful that the _Vuex_ code could notify the user if one of the following happens:

- _mapState_ is not under _computed_ property
- _mapGetters_ is not under _methods_ property
- _mapActions_ is not under _methods_ property
- _mapMutations_ is not under _methods_ property

### What does the proposed API look like?
n/a

**Comment by ktsn** [comment]
It's impossible to detect in Vuex side since the helper functions are just returning computed / methods object. It might be achievable with eslint custom rules, I guess.
