### ISSUE TITLE
High CPU usage in strict mode with a large state

### ISSUE THREAD

**Issue by BenoitZugmeyer** [vuejs/vuex#1338]
### Version
3.0.1

### Reproduction link
[https://jsbin.com/xetolobaba/edit?html,output](https://jsbin.com/xetolobaba/edit?html,output)

### Steps to reproduce
* Have a Vuex store with a large state (ex: thousands of reactive values)
* Activate strict mode
* Trigger any store mutation

### What is expected?
The mutation should complete in a few ms, like in non-strict mode.

### What is actually happening?
The mutation can take a very long time. It seems that vuex is iterating over the whole store at each `commit`.

---
Each store `commit` is really costly, even if they are all done at once (synchronously).

This is reproductible in any browser. For example, the example shows ~= 150ms in Chrome and ~= 250ms in Firefox.
This is reproductible in previous Vuex versions as well (2.3).

Related issues: https://github.com/vuejs/vuex/issues/1139 https://github.com/vuejs/vuex/issues/659

**Comment by LinusBorg** [comment]
"strict mode" adds a deep watcher on the whole state - that watcher is used to trigger the warning when you mutate any piece of vuex state outside of a mutation.

Unfortunately, a deep watcher on a very large state tree is very expensive, which is what you are experiencing.

There's not much to do except deactivating strict mode while you develop with large data sets, and only activate it when you want to test your work. Maybe you can decrease the amount of data in the store during development?

**Comment by BenoitZugmeyer** [comment]
I read a bit of Vue code, and I feel the approach taken here is far too overkill. There is already a concept of "custom setter", used by Vue to warn the developer about such unexpected usages.

With a bit of work, I guess it can be leveraged with an API looking like that:

```js
  store._vm = new Vue({
    data: {
      $$state: state
    },
    computed,
    customSetter () {
      if (process.env.NODE_ENV !== 'production') {
        assert(store._committing, `do not mutate vuex store state outside mutation handlers.`)
      }
    }
  })
```

The `customSetter` option would be sent to every `defineReactive` calls.

What do you think about it?

**Comment by LinusBorg** [comment]
Well, that won't woken for arrays, for example

**Comment by LinusBorg** [comment]
Interesting idea, not sure if it's feasable. However, that would be a proposal to make in the Vue core repository, as Vuex itself can't implement this.
