### ISSUE TITLE
State changing on getters method-style

### ISSUE THREAD

**Issue by GuilhemBarboux** [vuejs/vuex#1347]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/493598/](https://jsfiddle.net/50wL7mdz/493598/)

### Steps to reproduce
- Declare an array state item
- Create a getter method-style
- Use 'state.array.reverse()'
- Changing state for all application

export default {
  state: {
    sections,
    currentSectionIndex: -1
  },

  getters: {
    getAvailableSection: (state) => (id) => {
      const section = state.sections.find(s => s.id === id)
      if (section instanceof Section) return section
      else state.sections.reverse().find(s => s.isAvailable())
    },
}

### What is expected?
Doesn't changing store state

### What is actually happening?
Changing store state

**Comment by ktsn** [comment]
You should not use `reverse` since it will mutate the array.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse

You need to copy the array by using `slice`

```js
state.sections.slice().reverse()
```
