### ISSUE TITLE
vuex to broadcast event to manipulate vue.js component fields.

### ISSUE THREAD

**Issue by ThomasRalee** [vuejs/vuex#135]
Hi,
I am wondering if its possible to manipulate data in a vue component that are not registered in vuex store. A broadcast event with a event listener in the component would be awesome. 

For example: 
````
export const displayForm = (store, form) =>{
store.dispatch(types.UPDATE_SHOW, form,true)
//dispatch/broadcast event to set value of property in component to empty/''/null
}
````

Is this possible?

**Comment by bartlomieju** [comment]
Why would you want to do that, isn't it defying the purpose of Vuex?

**Comment by azamat-sharapov** [comment]
As @bartlomieju says, it defeats the purpose of Vuex. But if you are in the middle of integrating Vuex into big Vue app, there may be some things expensive to refactor. Here are couple of workarounds:

1. `$watch()` specific property in root app and broadcast event from there in `$watch` callback. 
2. Check out vuex middlewares (`onMutation`), where you can catch changes and possibly can `$dispatch/$broadcast`.
3. You could pass VM instance as an argument to action and call whatever function you like from inside action, but I find it dirty.
4. Don't limit yourself to Vue's event system (or don't "overuse" it). There are other event emitters like Node.js's `EventEmitter`, which is easy to integrate.

**Comment by blake-newman** [comment]
@azamat-sharapov Solutions are a good starting point.
