### ISSUE TITLE
Swapping array indexes does not trigger update

### ISSUE THREAD

**Issue by ghost** [vuejs/vuex#1350]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/p5zq2w8x7q](https://codesandbox.io/s/p5zq2w8x7q)

### Steps to reproduce
Example with steps.

### What is expected?
Computed property to be updated.

### What is actually happening?
not updating computed prop.

**Comment by atilkan** [comment]
I understand i have to use **splice**. Why though?

**Comment by ktsn** [comment]
Please read:

* https://vuex.vuejs.org/guide/mutations.html#mutations-follow-vue-s-reactivity-rules
* https://vuejs.org/v2/guide/list.html#Caveats

**Comment by atilkan** [comment]
@ktsn So the state changes but vue core doesn't know it.
