### ISSUE TITLE
The `subscribeAction` types  is not in types/index.d.ts in the latest v3.0.1

### ISSUE THREAD

**Issue by ijse** [vuejs/vuex#1354]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vuex/blob/v3.0.1/types/index.d.ts#L19](https://github.com/vuejs/vuex/blob/v3.0.1/types/index.d.ts#L19)

### Steps to reproduce
use `store.subscribeAction()` method

### What is expected?
no error

### What is actually happening?
TypeScript throws `Property 'subscribeAction' does not exist on type 'Store<any>'`

---
I checked the source code downloaded from NPM registry, there is no subscribeAction types declared in `types/index.d.ts` in fact.
https://github.com/vuejs/vuex/blob/v3.0.1/types/index.d.ts#L19

**Comment by ffMathy** [comment]
Can we make a release soon that includes this? It's kind of hard to use VueX from TypeScript in its current state.

**Comment by byrnedo** [comment]
It was fixed here but there just hasn't been a release since:
https://github.com/vuejs/vuex/issues/1066

**Comment by bodograumann** [comment]
There was a release, so this can be closed now afaics.
