### ISSUE TITLE
What is the best combination of ts and vuex?

### ISSUE THREAD

**Issue by BengBu-YueZhang** [vuejs/vuex#1355]
### What problem does this feature solve?
good typescript and vuex docking

### What does the proposed API look like?
The optimal solution recommended by the government

**Comment by ClickerMonkey** [comment]
I tackled it here - with no additional code, just better typing:

https://github.com/ClickerMonkey/vuex-typescript-interface

So now state, getters, commit, and dispatch all require valid strings and types or TS will throw an error. If you also have state/getters/actions/mutations defined on your interface and NOT in your store it will throw an error. The getter/mutation/action definitions passed in as options must have the proper types or it will also throw an error here as well!
