### ISSUE TITLE
TypeScript `watch` doesn't support getters parameter for getter

### ISSUE THREAD

**Issue by spiffytech** [vuejs/vuex#1357]
### Version
3.0.1

### Reproduction link
[https://codepen.io/anon/pen/LBexJp?editors=0010#0](https://codepen.io/anon/pen/LBexJp?editors=0010#0)

### Steps to reproduce
- Use TypeScript to define your store.
- Use `store.watch` with a getter that accepts getters as the second argument (as described in the Vuex docs)
- Observe typescript error "Argument of type '(_state: any, getters: any) => any' is not assignable to parameter of type '(state: { n: number; }) => any'."

### What is expected?
Vuex recognizes the getter as valid, still types `state`, and preferably types `getters`.

### What is actually happening?
TypeScript error "Argument of type '(_state: any, getters: any) => any' is not assignable to parameter of type '(state: { n: number; }) => any'."

**Comment by initial-wu** [comment]
I found the same case without TypeScript

**Comment by ktsn** [comment]
That's already fixed on dev branch. (via #1058)

**Comment by uiii** [comment]
Hello, why this is still not released even it was fixed a year ago?

**Comment by leoyli** [comment]
I also wonder this... a year of no releasing is very rare in a fast developing open-sourced project...

**Comment by alexeigs** [comment]
Yup, would also need the same but I guess Vuex is not properly updated anymore because many things will change with the next big release of Vue - whenever this will be...

**Comment by mccxiv** [comment]
For anyone reaching from search engines: it is released as of 3.5.1 (probably earlier)
