### ISSUE TITLE
replaceState only for namespaced module

### ISSUE THREAD

**Issue by Alex-Sokolov** [vuejs/vuex#1362]
### What problem does this feature solve?
For example, making undo/redo functionality in namespaced module, where used replaceState for time-travelling in stored data.

```
export default {
  namespaced: true,
  state: {
    nodes: []
  },
  mutations: {
    emptyState(state) {
      this.replaceState({ nodes: [] })
    },

    // ...
  },
  actions: {
    // ...
  }
}

```

Now calling replaceState from namespaced module will clear all Vuex state at all.

### What does the proposed API look like?
`this.replaceState(initialModuleState, { module: true })` or `this.replaceModuleState(initialModuleState)`

**Comment by ktsn** [comment]
You should just clear `nodes` in the mutation in that case.
I don't think `replaceState` should be used such a use case because it is meant to be used for time traveling debugging and hydration.

```js
mutations: {
  emptyState(state) {
    state.nodes = []
  },
}
```
