### ISSUE TITLE
Direct mutation of state not throwing error in strict mode

### ISSUE THREAD

**Issue by philBrown** [vuejs/vuex#1378]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/r1z0a4gp/7/](https://jsfiddle.net/r1z0a4gp/7/)

### Steps to reproduce
In the JSFiddle example, type into the text box.

The input's `v-model` is bound to a computed property with getter and setter. The getter maps directly to `$store.state.foo` and the setter dispatches the "setFoo" action.

The action directly modifies `context.state.foo` instead of committing a mutation.

### What is expected?
Strict mode is enabled so I would expect to see an error about directly mutating state outside of a mutation

### What is actually happening?
No errors are reported and state is modified

**Comment by ktsn** [comment]
Because you are using minified build which all assertions are eliminated. Use development build if you want such assertion.
