### ISSUE TITLE
store.watch not functioning in SSR mode

### ISSUE THREAD

**Issue by devinholloway** [vuejs/vuex#1381]
### Version
3.0.1

### Reproduction link
[https://github.com/devinholloway/vuex-watch-ssr](https://github.com/devinholloway/vuex-watch-ssr)

### Steps to reproduce
Clone the github account. Follow instructions in README

### What is expected?
store.watch to execute its callback when the state its watching chanes

### What is actually happening?
callback is not called on state update only in SSR

---
This is a project using Quasar for SSR. preFetch methods execute server side, much like the fetch methods in Nuxt. The purpose of this is to execute multiple server side functions where one depends on the results of the other.

**Comment by ktsn** [comment]
This is expected. On the server side, Vue's reactivity system is disabled.
https://ssr.vuejs.org/guide/universal.html#data-reactivity-on-the-server
