### ISSUE TITLE
mutate setHours by date.setHours() will not trigger view update 

### ISSUE THREAD

**Issue by lin-123** [vuejs/vuex#1384]
### Version
3.0.1

### Reproduction link
[https://codepen.io/lin-123/pen/RYoaOK?editors=1111](https://codepen.io/lin-123/pen/RYoaOK?editors=1111)

## code
- store.js
```javascript
import Vue from 'vue'
import Vuex from 'vuex'
import * as mutations from './mutations'
import * as actions from './actions'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    date: new Date()
  },
  mutations,
  actions,
  strict: process.env.NODE_ENV !== 'production'
})
```

- mutations.js
```javascript
export const SET_HOUR = (state, hours) => {
  state.date.setHours(hours)
}
```

- components
```html
<template>
<div class="map">
  <h2>{{dateFull}}</h2>
  <button @click="updateHours">update hours</button>
</div>
</template>
<script>
import L from 'leaflet'
import { mapState } from 'vuex'

export default {
  data: () => ({
    hours: 0
  }),
  computed: {
    ...mapState({
      date: state => state.date
    })
  },
  methods: {
    updateHours() {
      this.hours  = 1
      this.$store.commit('SET_HOURS', this.hours)
    }
  }
}
```

### What is expected?
date should be change on view when i mutate date

### What is actually happening?
view have no change when i mutate date by state.date.setHours(hours).

**Comment by ktsn** [comment]
It's what Vue.js reactive system works.
Vue.js cannot detect such mutation because it's not done via property setter. You should reassign date object or use serialized value (such as unix time) in this case.
