### ISSUE TITLE
Confused namespace for get module

### ISSUE THREAD

**Issue by leecade** [vuejs/vuex#1386]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
1. create files in store folder

`store/foo/index.js`

`store/foo/a.js`

2. get module by namespace

```js
computed: {
   ...mapState('foo/a', []), // correct
   ...mapState('foo', []), // correct
   //  ...mapState('foo/index', []), // not works here
}
```

### What is expected?
it make sense if `mapState('foo/index', [])` works as `mapState('foo', [])`

### What is actually happening?
`mapState('foo/index', [])` not work

**Comment by ktsn** [comment]
I don't think this is reasonable. Namespace is not a directory...
If we resolve a module named `index` implicitly, we cannot access its parent module (`foo` module on your example).
