### ISSUE TITLE
proposal - add examples work with vue-class-component

### ISSUE THREAD

**Issue by coderhaoxin** [vuejs/vuex#139]

**Comment by jdittrich** [comment]
Hi @coderhaoxin, could you provide some more information on why this might be useful for the users of vuex?

**Comment by coderhaoxin** [comment]
I use vue with [vue-class-component](https://github.com/vuejs/vue-class-component), it's awesome if there are some `simple demos` work with `vue-class-component`. That will be helpful for some guys just get a glance at vuex.

But there is no significant advantage, so, just a proposal.

**Comment by tonypee** [comment]
yah, im interested in this, like how can you use mapActions, or mapGetters, etc. when you are on a class, not in an object

**Comment by dmitrykurmanov** [comment]
The same issue in _vue-class-component_  repo : https://github.com/vuejs/vue-class-component/issues/56
