### ISSUE TITLE
Vuex module helpers

### ISSUE THREAD

**Issue by imatmati** [vuejs/vuex#1393]
### What problem does this feature solve?
Prevent wrong placement of mapping helpers in component.
I came across a trouble lately with coding calls to modules. I used the helpers but incorrectly. For example, I used an action helper in the computed part of my component. The issue was that it was called only once .

### What does the proposed API look like?
`mapActions(myComponent,["action1", "action2"])`

But to prevent any wrong insertion in the component, it would be convenient to register the component in the helpers instead of inserting the helpers in the component which is error prone.

**Comment by ktsn** [comment]
Thanks for filing the issue. However we won't add a new API for addressing such code styling preference. You can easily create the helper like that without modifying Vuex. The interface is also hard to statically typed on TypeScript.
