### ISSUE TITLE
Improve Computed Support

### ISSUE THREAD

**Issue by ClickerMonkey** [vuejs/vuex#1397]
### What problem does this feature solve?
Better support for computed properties with a set function.

### What does the proposed API look like?

```vue
import { mapComputed } from 'vuex'
new Vue({
  computed: {
    ...mapComputed({
       'mutationName': 'stateVariable',
       // example:
       'setLoading': 'loading'
    })
  }
})
```

This would generate a computed property that would return `stateVariable` and when the value is changed it would call the mutation `mutationName` with the new value.

This greatly simplifies directives like `v-model`.

Implementation:

```TypeScript
type VuexComputedMap = { [mutation: string]: string };

export function mapComputed(map: VuexComputedMap) {
  const mapped = Object.create(null);
  for (const mutation in map) {
    const variable = map[mutation]
    mapped[variable] = {
      get () {
         return this.$store.state[ variable ]
      },
      set (value) {
        this.$store.commit(mutation, value)
      }
    };
  }
  return mapped;
}
```

### Problems

The implementation would need to be changed to account for modules & namespaces.

**Comment by LinusBorg** [comment]
there's a cool library called vuex-map-fields that does this, including modules, namespaces, support for arrays.

**Comment by kiaking** [comment]
I think this is a nice feature as a plugin, though I think Vuex core should be consistent with how Vue works, and try not to do much of a magic like this one.
