### ISSUE TITLE
Mutations or Actions deprecated?

### ISSUE THREAD

**Issue by the-s0urce** [vuejs/vuex#1398]
### What problem does this feature solve?
Hello,
as first sorry for abusing the issue system, but did not find any other contact option. On one of the last two vue.js conferences (not sure wich of both it was), you said, that Mutations and Actions will be merged to one call. I was looking for some written news about this now for quite a time. Now we are setting up a new big project and we would really love to get a confirmation about this.
Thank you

**Comment by leopiccionia** [comment]
It's in the roadmap for [Vuex 4.x](https://github.com/vuejs/roadmap#vuex-4x), that's not in active development (as far as I know) and has no EDD so far.

Neither mutations nor actions will be deprecated in Vuex 3.x, as they can achieve different goals: mutations are strictly synchronous (and can be tracked by [vue-devtools](https://github.com/vuejs/vue-devtools)), while actions can be asynchronous.

**Comment by the-s0urce** [comment]
Thank you for your feedback.
Then we will assume for now, this will not happen.
