### ISSUE TITLE
Dynamic module generation - Nested modules doesn't have proper levels

### ISSUE THREAD

**Issue by AshwinTayson** [vuejs/vuex#1405]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/749394/](https://jsfiddle.net/50wL7mdz/749394/)

### Steps to reproduce
Run the program and check the console and the paragraph tag

### What is expected?
1. There should be two nested modules a and b in the console store[getters].<br>
1.a The two modules should be namespaced with a/aa and b/aa

2. The first &lt;p&gt; tag should be undefined since namespace a was not given
3. Second &lt;p&gt; tag should get "module a/aa"
4. Third &lt;p&gt; tag should get "module b/aa"

### What is actually happening?
1. There is only one getter.(nested namespacing did not work)<br>
1.a The getter is not namespaced by neither a nor b

2. The first &lt;p&gt; tag is giving value (not respecting namespace)
3. Second &lt;p&gt; tag is undefined since namespace is not registering properly
4. Third &lt;p&gt; tag is undefined since namespace is not registering properly

---
But if u check the state property of the store object in the console, you can see the modules registered with the correct namespace.

**Comment by ktsn** [comment]
Because you don't provide `namespaced: true` flag in your `a` and `b` module.
fixed example: https://jsfiddle.net/ktsn/50wL7mdz/759107/
