### ISSUE TITLE
is there a way to access module properties especially in getters with a passing function eg. this.$store.rootGetters.[module].mygetter(passing_val)

### ISSUE THREAD

**Issue by PedroJuan91** [vuejs/vuex#1413]
### What problem does this feature solve?
every time i want to filter my array in my modules state properties.
i will write it to my root getters. and its kinda confusing to me like accessing to the root just to make a filter.  
then its kinda messy accessing something from the modules going to root

### What does the proposed API look like?
````
//root getters
getters: {
 createMe(state, getters, rootState){
  return function(nameID) {
   return rootState.persons.names.find(function (thisName) {
    return thisName.id === nameID
   })
  }
 }
}
//computed 
loadname(id){
 return this.$store.getters.createMe(id)
}
```

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by LinusBorg** [comment]
I'm not sure I understand your problem or what you are proposing as a solution.
