### ISSUE TITLE
Wrong data for getters at least in actions because getters are mutables

### ISSUE THREAD

**Issue by nicodmf** [vuejs/vuex#1415]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/fqm3tj5y/3/](https://jsfiddle.net/fqm3tj5y/3/)

### Steps to reproduce
clic on "display values" text

### What is expected?
wrapper: values ===  getter: value

### What is actually happening?
wrapper: values !==  getter: value

---
I change the line 17
from 
       let begin = getters.begin
to 
       let begin = moment(getters.begin);

And this works. 

Anyway, it seems to me that a getter should'nt change and be a copy in every call. If not this should be good documented with an big warning : " Attention : a getter is mutable, copy it, if you want to play with the value given by it."

**Comment by LinusBorg** [comment]
Why are you using a private method (`_wrappedGetters`)?

Also, I don't really understand what the jsfiddle is trying to demonstrate. If you run a _wrappedGetter as a normal function, and inside of this function, create a fresh moment object, it will of course differ from the one that the *real* getter, from the object that was created when the real getter was actually run.

Please explain.

**Comment by nicodmf** [comment]
@LinusBorg The fiddle demonstrate that the getter change it's value after to use it.

The wrapped component is a direct call to getter method without the cache, it work as expected.

**Comment by LinusBorg** [comment]
> The getter is consquently mutable. A getter shouln't be mutable, shouldn't it.

Getters are just computed properties, and just like with computed properties, you *can* mutate an object (in this case: a `moment` instance) that a getter returns - it's just not something you should do.

If you want to make your getter's return values read-only, that's something you have t take care of yourself.

**Comment by nicodmf** [comment]
yes i understand but the documentation isn't clear about this fact. A getter is usually not mutable in almost all language.
