### ISSUE TITLE
Support for IndexedDB

### ISSUE THREAD

**Issue by syntacticsolutions** [vuejs/vuex#1416]
### What problem does this feature solve?
It should (in theory) make dealing with Big Data Web Visualizations easier and more performant.

I'm using echarts to render big data vizualizations at the company I work for. The problem is that when my data gets really big (1m records), It's takes way too long to do anything. The app pretty much becomes unresponsive and so now the only alternative I have is to do all of the aggregation on the backend and then return the response.

### What does the proposed API look like?
I would imagine that the vuex instance would send messages back and forth between the serviceworker and itself. The mutations could then be passed as arguments to the serviceworker. The serviceworker would perform the operation and return the aggregated data. If the user does not have third-party-cookies enabled. It would just fall back to the normal Vuex instance.

**Comment by kazupon** [comment]
I think it's should be supported with third party plugin of vuex...
you can create it.

**Comment by LinusBorg** [comment]
I'll second kazupon here. 

Messing with any kind of persistence layer is outside of the scope of vuex itself, but cdn be solved as a plugin or library
