### ISSUE TITLE
It is possible to sync vuex state across devices?

### ISSUE THREAD

**Issue by 7iomka** [vuejs/vuex#1424]
### What problem does this feature solve?
I want to make the same user, authorized on different devices, interact with the site, when the state changes, so that it synchronously changes on all devices.

Back-Ender asks to implement the mechanism via *web sockets*   how-to about **change the state from the server(!)**. 
He says that in *react-redux* he calls action with *type* and some *payload*. 
But vuex has **two entities**: *mutations* and *actions*, which adds complexity! Especially when store is namespaced by modules.

### What does the proposed API look like?
  I would be grateful for any help.

**Comment by ktsn** [comment]
Hi, please use [our forum](https://forum.vuejs.org/) or [chat room](https://chat.vuejs.org) to ask usage questions as the issue list is dedicated for bug reports and feature requests. Thanks!

**Comment by yiyasha15** [comment]
Any update on this?
