### ISSUE TITLE
Vuex modules with same method names to be mapped with different alias, via an array

### ISSUE THREAD

**Issue by vonKristoff** [vuejs/vuex#1427]
### What problem does this feature solve?
Currently when using nameSpaced modules, one can alias the method if the name is unique. My issue is that I often have the same method names in each module - ie: `actions: { update() { ... } }`.

If I were to map them, I either have to explicitly use the full namespace to describe the alias ie: `this['user/update']() && this['status/update]()`, otherwise one of them will be superseded at runtime.

By allowing the module alias feature to be declared within an array,  then multiple methods can be duly created that share the same method names yet be written explicitly unique as when needed within a component, because currently using the map helper only allows for one alias at a time.
Ultimately it will allow this: 
```
this.addTodo()
this.removeTodo()
this.addUser()
this.removeUser()
// from the following declaration
methods: {
    ...mapMutations('todos', [{ addTodo: 'add' }, { removeTodo: 'destroy' }],
    ...mapMutations('users', [{ addUser: 'add' }, { removeUser: 'destroy' }]
}
```

### What does the proposed API look like?
```
// currently only this works
methods: {
    ...mapActions('todos', { addTodo: 'increment' }) // map `this.addTodo()` to `this.$store.commit('increment')`
}
// proposed feature :
methods: {
    ...mapActions('todos', [{ addTodo: 'increment' }]) // wrap within array so that multiple module methods can be aliased cleanly
}
```

**Comment by ktsn** [comment]
Well, you can just write multiple mapping in the object. 

```js
    ...mapMutations('todos', { 
      addTodo: 'add',
      removeTodo: 'destroy'
    }),
```

I'm not sure about your proposal still. Is there anything I'm missing?

**Comment by vonKristoff** [comment]
I thought that didn't work... 
I have personally tried that and got errors, thus suggesting the array. 

If this is the case close the request. And my bad. But I will try as you suggest.

**Comment by ktsn** [comment]
I see. Then I'll close this issue as it should work.
If this does not work in your case, it may be a bug. So it would be helpful if you create a new issue with a reproduction. Thanks!
