### ISSUE TITLE
Italian translations

### ISSUE THREAD

**Issue by lorenaramonda** [vuejs/vuex#1429]
Hi guys, I would like to add the Italian translation.
What is the best workflow to do that? I simply create the it folder in docs and copy api/guide folder with md and translate in them?
Is there a way to see the final result as web pages or I just go through markdown files?

Thanks! 🙏

**Comment by lorenaramonda** [comment]
Double issue because of github down, I close.

**Comment by LF1314** [comment]
what happend ？
How did I get so many emails?

**Comment by lorenaramonda** [comment]
I'm really sorry didn't meant that but it was a github issue :( https://status.github.com/messages?fbclid=IwAR0gynlu8yHguuCo0uTmqW7RwUJzi5TZ2y-EdZ5eQ_oNMErA27s2P7cihHA
Once added the issue it goes on 404 error so I tried once again and again before realizing there was a down 👉 👈 so sorry.
I've already closed all the double issues
