### ISSUE TITLE
Best practices for realtime backend

### ISSUE THREAD

**Issue by niallobrien** [vuejs/vuex#143]
Hi all,
I'm using Feather.js on the backend, and initially created a component with all of the Feathers client stuff in the component like so: https://gist.github.com/niallobrien/7eb51d17c977c46babb8

I'm now trying to implement Vuex and am making slow progress. I've moved the data fetching code (on load for now) to 'actions.js` and am mutating the state according to how the docs instruct so my component is quite clean.

However, when a new item is created on the backend, the server emits an event to the client which you can listen for and update your UI accordingly. I previously did this in the component itself.

The problem is that I'm unsure how to utilise this within `actions.js` and it doesn't feel right to put it in my component itself, as then I'd have Feathers client code split between the component and `actions.js`.

Please see the attached example of my current implementation.

https://gist.github.com/niallobrien/4f7b39bdd27f7f47a4dfa355864656ef

I'm thinking that instead I should keep the Feather client stuff in the component, my actions would simply receive the data from the component as a param and dispatch the mutation passing along the data. What are your thoughts on this as I know the docs advocate doing REST API in `actions.js`.

Thanks in advance.

**Comment by fnlctrl** [comment]
Maybe you should post this to the [fourm](http://forum.vuejs.org/)

**Comment by niallobrien** [comment]
@fnlctrl Good thinking, will do. Thanks.
