### ISSUE TITLE
dealing with nested data

### ISSUE THREAD

**Issue by jdittrich** [vuejs/vuex#144]
The examples and documentation show how to deal with flat data. For more advanced applications, vuex users may need to deal with nested data though. An example for such a structure would be the [vue.js included "tree" demo](https://github.com/vuejs/vue/tree/dev/examples/tree).

How should vuex used with such nested data?

In redux, it seems to be most often recommanded to "flatten" the structure manually or using [normalizr](https://github.com/gaearon/normalizr), sometimes in conjunction with [reselect](https://github.com/reactjs/reselect) to ease retrieval.

**Comment by yyx990803** [comment]
It depends. The "flatten" from `normalizr` is typical for data coming from REST endpoints, e.g. posts that has authors and comments, etc. You can totally use `normalizr` with Vuex - in fact the [chat example](https://github.com/vuejs/vuex/blob/master/examples/chat/vuex/store.js) does use a "normalized" structure which is similar to the data structure produced by `normalizr`.

On the other hand, tree structure data is usually less commonly seen, and in some cases it may be easier to keep the original structure. Or, you can use the same flat structure and use ids to reference nested items, and use a Vuex getter in each tree item component to retrieve its children.

Vuex getters basically already does what `reselect` does for Redux, both from data retrieval and performance perspectives.

**Comment by jdittrich** [comment]
Would it make sense to refer to this in the docs? It may be helpful for others (In an FAQ section?)

**Comment by yyx990803** [comment]
Sure, feel free to open a PR
