### ISSUE TITLE
About unregisterModule 

### ISSUE THREAD

**Issue by lyz1991** [vuejs/vuex#1446]
my version of vuex is 3.0.1 and project is ssr
when I call unregisterModule the api in beforeRouteLeave like this:
<img width="316" alt="wechatimg14" src="https://user-images.githubusercontent.com/15042461/48430087-739da280-e7a9-11e8-8fee-1e3111ff816e.png">
It throw a error like this：
<img width="497" alt="wechatimg15" src="https://user-images.githubusercontent.com/15042461/48430384-2bcb4b00-e7aa-11e8-9da3-8ae7f8750f5d.png">
and I debug find that 
<img width="544" alt="wechatimg16" src="https://user-images.githubusercontent.com/15042461/48430528-7ea50280-e7aa-11e8-9a03-3180c2d4c42f.png">
there path is [], how can I deal with?
And if I not use this api  how can I check a module it is installed

**Comment by mlavina** [comment]
@lyz1991 did you ever figure out a solution for you problem. I am getting this error.
