### ISSUE TITLE
Update documentation for $watch with an example

### ISSUE THREAD

**Issue by toymachiner62** [vuejs/vuex#1450]
### What problem does this feature solve?
The documentation for $watch is pretty unclear how to use without an example https://vuex.vuejs.org/api/#watch

I figured out how to use it from this comment in the forums https://forum.vuejs.org/t/correct-way-to-use-store-watch-in-vuex/1800/6

### What does the proposed API look like?
The documentation will have an example similar to https://forum.vuejs.org/t/correct-way-to-use-store-watch-in-vuex/1800/6

**Comment by karanisverma** [comment]
I would like to pick this up!

**Comment by winniehell** [comment]
@karanisverma did you start working on it already?

**Comment by karanisverma** [comment]
@winniehell Sorry for replying so late, I have not pick this up.

**Comment by kiaking** [comment]
Closing due to duplication #1050
