### ISSUE TITLE
mapGetters 辅助函数，将一个 getter 属性另取一个名字

### ISSUE THREAD

**Issue by dinglittle** [vuejs/vuex#1452]
### Version
3.0.1

### Reproduction link
[https://vuex.vuejs.org/zh/guide/getters.html](https://vuex.vuejs.org/zh/guide/getters.html)

### Steps to reproduce
Vuex 官方 [链接所示](https://vuex.vuejs.org/zh/guide/getters.html)  mapGetters 辅助函数，将一个 getter 属性另取一个名字 ， 示例代码

### What is expected?

```
mapGetters({
  // 把 `this.doneCount` 映射为 `this.$store.getters.doneTodosCount`
  doneCount: 'doneTodosCount'
})
```

### What is actually happening?
修正

```
...mapGetters({
  // 把 `this.doneCount` 映射为 `this.$store.getters.doneTodosCount`
  doneCount: 'doneTodosCount'
})
```

**Comment by ktsn** [comment]
The example code does not need to have object spread operator since it just shows the example of its argument.
In fact, there are some cases we can use it without object spread operator:

```js
export default {
  computed: mapGetters({
    doneCount: 'doneTodosCount'
  })
}
```
