### ISSUE TITLE
Suggestion to Vuex best practice when using nested modules

### ISSUE THREAD

**Issue by JaeYeopHan** [vuejs/vuex#1459]
### What problem does this feature solve?
IMHO, there are several problems with Vuex.

1. Overuse string when using `mapState`, `mapGetters`, `mapActions`
2. Duplicated namespace in components

like this:
_my-component.vue_ (AS-IS version)

```js
export default {
  computed: {
    ...mapState("todos", {
      allItems: ({ items }) => items,
    }),
    ...mapGetters("todos", {
      doneItems: "doneItems",
      activeItems: "activeItems",
    }),
  }
}
```

In this code, `"doneItmes"` is written by string. It will cause bug easily.
And there are duplicated namespace called `"todos"`. It will inhibit maintainabillity.

### What does the proposed API look like?
The way to introduce it is not to suggest a new API, but to use the existing API properly.
We can use `createNamespacedHelpers` API with constants in store directory!

### Example

_@/store/todos/types.js_

```js
export const NAMESPACE = "todos";
```

_@/store/todos/index.js_

```js
import { createNamespacedHelpers } from"vuex";
import { NAMESPACE } from "./types";

// Key point !
const { mapState, mapGetters, mapActions } = createNamespacedHelpers(NAMESPACE);

export { mapState, mapGetters, mapActions };

export default { /* namespaced, state, getters, mutations, actions */ }
```

_@/store/todos/getters.js_

```js
// Key point !
export const DONE_ITEMS = "DONE_ITEMS";
export const ACTIVE_ITEMS = "ACTIVE_ITEMS";

export default {
  [DONE_ITEMS]: state => state.items.filter(todo => todo.isDone),
  [ACTIVE_ITEMS]: state => state.items.filter(todo => !todo.isDone)
};
```

If we do this, we can use customized binding helpers.

_my-component.vue_ (TO-BE version)

```js
import * as todos from '@/store/todos'; // Key point !
import * as getters from '@/store/todos/getters'; // Key point !
import * as actions from '@/store/todos/types'; // Key point !

export default {
  computed: {
    ...todos.mapState({
      allItems: ({ items }) => items,
    }),
    ...todos.mapGetters([
      getters.DONE_ITEMS,
      getters.ACTIVE_ITEMS,
    ])
  },
  methods: {
    ...todos.mapActions([
      actions.ADD_ITEM,
    ]),
  }
}
```

How about this? If you do not mind this, I would like to post it on the official Vuex document.
You can see the all example code in [this repository](https://github.com/JaeYeopHan/vuex-best-practice-lab)

Thanks!

**Comment by kiaking** [comment]
I think this is valid approach and I don't think it will cause any problem using it inside project teams. But it might be too opinionated to be in the docs. I mean users are free to do what ever they want with `mapXXX` helpers 👍
