### ISSUE TITLE
辅助函数连接多个store

### ISSUE THREAD

**Issue by hqzh** [vuejs/vuex#1473]
### What problem does this feature solve?
有时我的组件需要连多个store,比如公共的和我自己的

### What does the proposed API look like?
```
import { createNamespacedHelpers } from "vuex";

const {
    mapState,
    mapGetters,
    mapActions,
    mapMutations
         } = createNamespacedHelpers(["myStore","commonStore"]);
```

**Comment by bbbbx** [comment]
You can use module.
see [https://vuex.vuejs.org/zh/guide/modules.html](https://vuex.vuejs.org/zh/guide/modules.html).

**Comment by hqzh** [comment]
@bbbbx I know this, I want easily API

**Comment by kiaking** [comment]
Do we have any update on this issue...? Seems like things are solved by the module...?
