### ISSUE TITLE
[vuex] unknown getter: accessing nested property fails with mapGetters but works with this.$store

### ISSUE THREAD

**Issue by mbana** [vuejs/vuex#1475]
### Version
3.0.1

### Reproduction link
[https://github.com/banaio/vue_js_vuex_accessing_nested_property_bug](https://github.com/banaio/vue_js_vuex_accessing_nested_property_bug)

### Steps to reproduce
```sh
git clone git@github.com:banaio/vue_js_vuex_accessing_nested_property_bug.git
cd vue_js_vuex_accessing_nested_property_bug
yarn install
yarn serve
open http://localhost:8080/
```

### What is expected?
We should see the message `{ "level_3_field": "level_3_field_value" }` twice, however it
appears only once. Please see the screenshot.

### What is actually happening?
The message `{ "level_3_field": "level_3_field_value" }` appears only once. As per this screenshot:

![Image of broken](https://raw.githubusercontent.com/banaio/vue_js_vuex_accessing_nested_property_bug/master/broken.png)

---

When `state`, see [https://github.com/banaio/vue_js_vuex_accessing_nested_property_bug/blob/master/src/store.js#L7](https://github.com/banaio/vue_js_vuex_accessing_nested_property_bug/blob/master/src/store.js#L7), is defined as:

```js
  state: {
    level_1: {
      level_2: {
        level_3: {
          level_3_field: 'level_3_field_value',
        },
      },
    },
  },
  getters: {
    level_1: (state) => state.level_1,
  },
```

And used as, see [https://github.com/banaio/vue_js_vuex_accessing_nested_property_bug/blob/master/src/components/HelloWorld.vue#L95](https://github.com/banaio/vue_js_vuex_accessing_nested_property_bug/blob/master/src/components/HelloWorld.vue#L95),
the `level_3_broken` does not work, but the `level_3_working` seems to work:

```js
  computed: {
    ...mapGetters({
      level_3_broken: 'level_1.level_2.level_3',
    }),
    level_3_working() {
      return this.$store.getters['level_1']['level_2'].level_3;
    },
  },
```

**Comment by LinusBorg** [comment]
That's because your using mapGetters incorrectly. 

Within the object that you pass to mapGetters, you can't actually access the result of the getters - which you try to do here. 

The object only defined what getters to map  into your local computed properties.

**Comment by mbana** [comment]
@LinusBorg thank you for the reply.

Can you give an example of what you mean, please. Or better yet, can you show me a working example of what I am trying to achieve.

At the moment it is unclear to me why `level_3_working` works yet `level_3_broken` doesn't. I've debugged the code and I can see the cause of this issue, however I don't know enough about the code to make an informed decision as to whether this is a bug or intentional.
