### ISSUE TITLE
Store getters do not re-evaluate on dynamic module registration

### ISSUE THREAD

**Issue by SebastianS90** [vuejs/vuex#1480]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/ll6zjklq97](https://codesandbox.io/s/ll6zjklq97)

### Steps to reproduce
- Open the CodeSandbox
- Click "Register Module"

### What is expected?
All four values should switch to true

### What is actually happening?
Only the values based on watchers from the component switch to true

**Comment by mozzkay** [comment]
The `getters` will be exposed on the `store.getters` object.
So you should use `$store.getters.hasModule`.

**Comment by SebastianS90** [comment]
My bad, thanks for the hint!
