### ISSUE TITLE
解决 SSR 场景中 cookie 穿透 问题

### ISSUE THREAD

**Issue by VanquisherMe** [vuejs/vuex#1494]
### What problem does this feature solve?
SSR 场景中 cookie 穿透问题，在服务器入口，创建store的时候可以添加，自定函数，这样我就可以判断是服务端还是客户端来决定 异步请求的逻辑，并且在actions 第一个参数 context，添加上这个自定义函数的对象，就可以在store actions的时候拿到这个请求函数，如此可以完美解决 SSR 场景中 服务端无非带cookie 的问题

### What does the proposed API look like?
 new Vuex.Store({
    method:{
        request(){
           ...请求函数
        }
    }
  });

actions:{
    getuser({ method }){  method.request("url") }
}

this.$store.method.request("url")

**Comment by kiaking** [comment]
This is pretty old issue but do you have any updates on this? Sorry, I don't understand Chinese so I don't know what the issue is... 😓

**Comment by wanjiaang** [comment]
咋操作的啊 hxd
