### ISSUE TITLE
页面通过路由跳转时会闪现一下之前的数据，然后再显示该显示的数据

### ISSUE THREAD

**Issue by NeverlandForKi** [vuejs/vuex#150]
从页面A点击链接跳转到B1页，正常显示数据，然后返回A，再从A页点击另一个链接，跳转到B2，这时候B页面会先闪一下B1的数据，然后再显示B2的数据

原因应该是Action里面发的请求是异步的，跳转过去的时候请求还没处理完成，所以会出现这种情况，
我的处理方式是在A页面添加一个watch项，如果数据返回了，再router.go

但是总感觉这种处理方式不太好，感觉搞复杂了，想问一下有更好的处理方式吗？

**Comment by yyx990803** [comment]
用 `$loadingRouteData` 给页面一个 loading 的状态。
