### ISSUE TITLE
DOCUMENTATION REQUEST: how to publish vuex module on npm. how to publish sfc component library and vuex module on npm

### ISSUE THREAD

**Issue by SumNeuron** [vuejs/vuex#1502]
### What problem does this feature solve?
Vuex modules, in theory, are divorced of their vue components which access them. One could take the module, register it and (re)make components to utilize the vuex module as desired. However, in (perhaps poor) practice, vuex modules and vue components are often made concurrently; namely, the components serve as the api to the store and it is expected that inclusion of the vue components come _with_ the vuex module.

However turning a vuex module and library of sfcs into reusable chunks does not seem to be straight forward.

The expected behavior would be using the vue-cli to create a new project with a vuex store.
the store would be moved to its own directory:

```
src/
-- store/
---- modules/
------ moduleA/
-------- actions.js
-------- state.js
-------- mutations.js
-------- getters.js
-------- store.js 
...
```

All components under `src/components` (or nested directories) would be exposed so users could import each constitute component
All modules under `src/store/modules` would be exposed so users could just import the module if desired 

### What does the proposed API look like?
```
# install library
npm install vuex-vue-sfc-library

# inside app.vue or some other component
// import the vuex modules and components that access the modules 
import {moduleA, nestedComponentB, conglomerateComponentA} from 'vuex-vue-sfc-library

export default {
    components: {
        nestedComponentB, conglomerateComponentA
    },
    created() {
        this.$store.registerModule('moduleA', moduleA)
    }

}
```

**Comment by kiaking** [comment]
I think what you propose is possible. Though creating npm bundles is possible in many ways so I don't know if we can document this in a good way.

I mean you could juts simply bundle your chunks, and let user register it as a module just like you have in your example. I think that's as simple as it can get.
