### ISSUE TITLE
Bug: getters of a dynamic module will lose after unregistering other module

### ISSUE THREAD

**Issue by hezhuojie** [vuejs/vuex#1515]
### Version
3.1.0

### Reproduction link
[https://jsbin.com/bejenutewi/edit?js,console](https://jsbin.com/bejenutewi/edit?js,console)

### Steps to reproduce
just one the page [https://jsbin.com/bejenutewi/edit?js,console](https://jsbin.com/bejenutewi/edit?js,console)

### What is expected?
result of `store.getters['mod/getOne']` should always be 1

### What is actually happening?
getter `mod/getOne` is missing, return `undefined`

**Comment by ktsn** [comment]
Why do you register the getter separately (in your example `getOne` and `getTwo`)? `registerModule` does not expect such use case and I feel it should throw error instead of overwrite the existing one.
