### ISSUE TITLE
Feature Request: Private State

### ISSUE THREAD

**Issue by jcupps** [vuejs/vuex#1520]
### What problem does this feature solve?
I would like the ability to make certain state private to the store, i.e. accessible within store getters, actions, and mutations, but not directly accessible by consumers (e.g. components). This would prevent unintended reading or manipulation of state which should be done through getters or actions/mutations respectively. As far as I know, there is no good way to achieve this today in Vuex.

### What does the proposed API look like?
The API could look something like this:

A store:
```javascript
{
  state() {
    return {
      somethingPublic: ''
    };
  },

  privateState() {
    return {
      somethingPrivate: []
    };
  },

  getters: {
    filtered: (state, getters, privateState) => privateState.somethingPrivate.filter(...)
  }
}
```

In a component:
```javascript
// works:
this.$store.state.somethingPublic
this.$store.getters.filtered
// doesn't work:
this.$store.state.somethingPrivate
this.$store.privateState.somethingPrivate
```

Thanks.

**Comment by Jinjiang** [comment]
Don't think it's necessary. And it also increases the complexity of the lib which would probably also make users more confused. Maybe ES private field would help in the future but I am not sure about this.
Thanks.

**Comment by jcupps** [comment]
I agree that it would increase the complexity, but I haven't been able to come up with a good workaround. Are there any you could recommend?

**Comment by Jinjiang** [comment]
How about strict mode https://vuex.vuejs.org/guide/strict.html? Or put the data you would expose into a module. Or just by giving some conventions with all your colleagues. Btw this question could also be asked in forum and StackOverflow.

**Comment by jcupps** [comment]
Thanks for the suggestions; I had considered those, although unfortunately none would solve the problem. I asked the question here because I assumed that the assertion that it isn't necessary implied that good alternatives already exist. I don't think I would agree that private state in general isn't necessary, but I can understand not prioritizing it over other enhancements. I'll continue to look for a workaround. Thanks

**Comment by LinusBorg** [comment]
What's wrong with just using a closure?

**Comment by jcupps** [comment]
That's certainly a possibility, although the downsides would be 1) it would be inconsistent with the usage of `state`, 2) it would be more difficult to unit test, and 3) I'd be limited to a single instance of a module (not necessarily a desired use case but see point 2 about unit-testing), unless I used a factory function or something.

I could probably come up with a solution for 2 and 3, but it would involve non-standard composition or extra code to work around it (like what I ended up doing to inject dependencies into action methods, for instance), so I thought it would be much cleaner just to have a new `privateState` option. I can definitely understand this not being a common enough use case to warrant adding a new feature though.

**Comment by kiaking** [comment]
Closing the issue due to inactivity. I think this goes against where Vue prefer to stick with ordinary JavaScript paradigm. I think it would be better to just use underscore or something to indicate that it's a private thing.

**Comment by pjar** [comment]
Coming from backend world, where private methods are common pattern I'm a bit confused with no traction within that field. Just by marking something private you can explicitly and forever explain to other devs that this method should not be used directly as it is probably only a building block and very integral and necessary part for more complex business logic.  This then helps on reviewing others code - you simply check if someone tries to call a private method. 

I really hope Vuex could offer similar pattern one day.
