### ISSUE TITLE
Unused callback parameter in registerAction method causing trouble when testing mapActions

### ISSUE THREAD

**Issue by FlorentinBurgeat** [vuejs/vuex#1526]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vuex/blob/4c0d0ae0abcd48f1df2c0c263402a94a214168b2/src/store.js#L434](https://github.com/vuejs/vuex/blob/4c0d0ae0abcd48f1df2c0c263402a94a214168b2/src/store.js#L434)

### Steps to reproduce
1. Create a component with method using mapActions
2. Test call of the method
3. Notice that the store action is called with 3 parameters: the store, the payload, and a unused callback always set to undefined.

### What is expected?
The action must be called with only the 2 first parameters.

### What is actually happening?
The action is called with a third parameters (cb) set to undefined.

---
I think this is an error. I don't see where it can be used.
I did not do a JSFiddle but linked you directly to the line where the potentially unused callback is.

**Comment by LinusBorg** [comment]
What's the trouble that this is causing for you?

**Comment by FlorentinBurgeat** [comment]
When I test that the method is called with my two first parameters (aka the store and payload), it fails because it expects a third parameter which is always undefined (aka 'cb').

**Comment by kiaking** [comment]
I don't think this is a problem? I'm still not sure why having extra `undefined` arg at the end would cause the problem.

Could you create some reproduction for the real world use case?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to open another issue if there's anything 👍
