### ISSUE TITLE
ES6 Classes casted to plain object for previous states

### ISSUE THREAD

**Issue by piknik** [vuejs/vuex#153]
A minor issue, doesn't affect any production code of mine since it doesn't utilize undo's or time reversal. I get this warning/error when choosing a previous state in Vue devtools:
```
[Vue warn]: Error when evaluating expression "item.options.width.html()": TypeError: scope.item.options.width.html is not a function
```
I have classes for each nested object in this particular state. I keep the root object of the module as a plain javascript object. I suppose that internally, Vuex casts objects of classes into plain objects, thus the error about no function in the object.

I don't know how Vuex stores previous state which doesn't matter, but there should be some kind of mechanism to cast the object back into its original class so the functions would become available again.

**Comment by yyx990803** [comment]
You shouldn't be putting class object as state. State must be plain objects.

**Comment by Be-ngt-oH** [comment]
I had the same issue and it took me a while to figure it out. Would it be possible to add a warning to the docs e.g. to [docs/en/api.md](https://github.com/vuejs/vuex/blob/dev/docs/en/api.md)?
