### ISSUE TITLE
Using .map function on getters returns null

### ISSUE THREAD

**Issue by jippy89** [vuejs/vuex#1535]
### Version
3.1.0

### Reproduction link
[https://jsfiddle.net/irfandyjip89/ts3uwza8/](https://jsfiddle.net/irfandyjip89/ts3uwza8/)

### Steps to reproduce
It was exactly in the JSFiddle, I was trying to return manipulated data based on the state through getters.
But it seems that I've done it wrong. I've been trying to google but it seems that the word `map` keep referencing me to `mapGetters`, `mapState`, etc. So, since I can't find any I thought I post one here. Thank you.

### What is expected?
`getters.issue` returns the manipulated value

### What is actually happening?
`getters.issue` returns Array of `nulls`

**Comment by kiaking** [comment]
@jippy89 You need to `return` inside `map` function.

```js
getters: {
  issues: state => {
    return state.issues.map( (val, i , arr) => {
      return val.SomeExample = true // <- This part.
    })
  }
}
```

**Comment by jippy89** [comment]
**OMG! Sorry that was some silly mistake. Thank you.**

**Comment by kiaking** [comment]
Cheers 🍻
