### ISSUE TITLE
报错：[vuex] store not injected.

### ISSUE THREAD

**Issue by pencil2014** [vuejs/vuex#154]
这是main.js的代码：
![1](https://cloud.githubusercontent.com/assets/10042880/14734372/a2b83d76-089c-11e6-8b03-c4e7a7df2a70.png)
这是store的代码：
![2](https://cloud.githubusercontent.com/assets/10042880/14734381/b5d3a7d8-089c-11e6-9fbf-0e2a8983d1ec.png)
这是组件的代码：
![3](https://cloud.githubusercontent.com/assets/10042880/14734387/bce9d254-089c-11e6-8cad-6ae6178626af.png)
最后报错：
![4](https://cloud.githubusercontent.com/assets/10042880/14734389/c66d9a68-089c-11e6-8e35-5dc998d17566.png)
请问这是什么原因？

**Comment by yyx990803** [comment]
请用 [webpackbin](http://www.webpackbin.com/41MQpKQgZ) 给重现。

**Comment by xbill82** [comment]
Please could you guys discuss this issue in english? I think I'm having the same issue (but to me it only happens when using slots)
