### ISSUE TITLE
VUEX for flutter

### ISSUE THREAD

**Issue by syedsimanta03** [vuejs/vuex#1544]
### What problem does this feature solve?
Hi.I like vuex,but I'm currently using flutter to develop apps, and I don't have a state management library that I like to use.Will you develop a vuex for the flutter?

### What does the proposed API look like?
343dsgds32324

**Comment by LinusBorg** [comment]
No. We don't develop tools for native android development

**Comment by hjJunior** [comment]
I'm creating a new package ([vuex4flutter](https://github.com/hjJunior/vuex4flutter)), It would be great to have contributions :)

**Comment by TatsuUkraine** [comment]
@LinusBorg Flutter not just about native android, it's a cross-platform tool, which means it for Android, iOS, web, desktop etc. based on the single code base which is written with Dart

**Comment by araeuchle** [comment]
i would also love to see a vuex for flutter :) as i dont like redux :D
