### ISSUE TITLE
preserveState: true 时 嵌套 3层以上 module 会出现 state undefined 问题 ,导致 actions 多所有方法无法调用

### ISSUE THREAD

**Issue by GoodLuckIce** [vuejs/vuex#1549]
### Version
3.1.0

### Reproduction link
[http://没有](http://没有)

### Steps to reproduce
当registerModule 动态注册.   preserveState: true 时 嵌套 3层以上 module 会出现 state undefined 问题 ,导致 actions 多所有方法无法调用

### What is expected?
期望 第一次动态注册 保留新注册的state ,之后的注册 采用 preserveState: true 方案

### What is actually happening?
 state undefined 导致 actions 多所有方法无法调用

**Comment by ktsn** [comment]
Please provide reproduction when you report a bug, thanks 🙂
