### ISSUE TITLE
Is anyone currently working on Chinese docs update? If not I can do it.

### ISSUE THREAD

**Issue by mondaychen** [vuejs/vuex#155]

**Comment by yyx990803** [comment]
@ryerh has been working on it, I'm not sure if it's complete though. Feel free to take a pass and see if anything is still out of sync with the English version.

**Comment by mondaychen** [comment]
I took a look at https://github.com/vuejs/vuex/commits/master/docs/zh-cn and https://github.com/ryerh/vuex/commits/master/docs/zh-cn. It seems that everything he has done has been merged into master and some parts are still missing (e.g. tutorial.md).

**Comment by yyx990803** [comment]
@mondaychen feel free to submit PRs to complete the missing parts.

**Comment by mondaychen** [comment]
@yyx990803 I'm working on it.

Could you provide me with the source used to make [this picture](https://github.com/vuejs/vuex/blob/master/docs/en/tutorial/vuex_flow.png)? In the Português version it was not translated. But it has a lot of text so I believe it's the best if I can translate the picture as well.

**Comment by yyx990803** [comment]
Hmm, I didn't make that image, but maybe @skyronic can provide the source file?
