### ISSUE TITLE
MapGetters not working for modules with namespaced=true in vuex 

### ISSUE THREAD

**Issue by Xambey** [vuejs/vuex#1553]
### Version
3.1.1

### Reproduction link
[https://gitlab.com/Xambey/large](https://gitlab.com/Xambey/large)

### Steps to reproduce
1) Run the application.
2) Open console in web browser (or vue extensions)
3) Catch the error in the log (ChildA.vue: 14 )

"Property or method "score" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property"

found in

---> <ChildA> at src/components/ChildA.vue
       <Parent> at src/components/Parent.vue
         <App> at src/App.vue
           <Root>

### What is expected?
The getter 'score'  is created in my component. (this.$store.getters['scoreBoard/score'] -> this.score)

### What is actually happening?
Getter no mapped, vue google chrome extension show what state existed https://i.imgur.com/QKB7Wqm.png

---
```
computed: {
    ...mapGetters([
      'scoreBoard/score' // Not found when /scoreBoard/score is existed. 
    ])
  }
```
if you do this, then everything works (or namespaced = false): 
```
computed: {
    ...mapGetters({
      score: 'scoreBoard/score'
    })
  }
```

**Comment by liyangworld** [comment]
computed: {
    ...mapGetters([
      'scoreBoard/score' 
    ])
  }
the upper is equal to the lower:
computed: {
    ...mapGetters({
      'scoreBoard/score' : 'scoreBoard/score' 
    })
  }

**Comment by Xambey** [comment]
@liyangworld thanks. I realized. It turns out that there are some problems from using the namespace for submodules, they can be called only explicitly and they cannot be imported normally ... Is there any alternative way to import getters implicitly in the form of scoreBoard / score -> score?

**Comment by ktsn** [comment]
As @liyangworld said.
Vuex does not implicitly omit namespace for you. If you mean you want to save typing for many getters, pass namespace string to 1st argument.

```js
computed: {
  ...mapGetters('scoreBoard', ['score'])
}
```

**Comment by atilkan** [comment]
`createNamespacedHelpers()`

**Comment by stunnitysoft** [comment]
@Xambey there are two ways you can to it

1. first way do this
```
computed: {
   ...mapGetters('scoreBoard',['score'])
}
```
buy this upper method you have said that **scoreBoard** is the module then what following in the array are getters that you have in the module

2.  another way is this one
```
computed: {
 ...mapGetters({
        score: 'scoreBoard/score'
     }) 
}
```
I think there are understandable
