### ISSUE TITLE
Disable Direct State Mutation Outside of Mutation Handlers, at Least in Strict Mode

### ISSUE THREAD

**Issue by xianshenglu** [vuejs/vuex#1556]
### What problem does this feature solve?
As [doc](https://vuex.vuejs.org/guide/strict.html) said, 

> In strict mode, whenever Vuex state is mutated outside of mutation handlers, an error will be thrown. 

However, **state will still be mutated** though an error would be thrown. 

In my opinion, this behavior is weird and misleading. Normally,  operation would fail if an error showed. But in this case, it didn't. 

Also, if a developer doesn't see this error and only see the result which is actually worked, he might do this behavior all the time until one day he find the error.

 So, my propose is

>  Why Not Disable Direct State Mutation Outside of Mutation Handlers, at Least in Strict Mode?

There should be a way to absolutely disable direct state mutation outside of mutation handlers. 

### What does the proposed API look like?
```js
const store = new Vuex.Store({
  // ...
  strict: true
})
```
Direct state mutation outside of mutation handlers would be disabled when `strict` is true.

**Comment by ktsn** [comment]
This is unfortunately impossible in practice. We can detect if the state is changed out of mutation but cannot block mutation itself. To achieve it, we need to modify all nested properties in state not to mutate and revert it during mutation. That makes Vuex store much slower and too complicated.
