### ISSUE TITLE
[Firefox] Zero value in an object is displayed as undefined in terminal but works as expected logically and displays properly

### ISSUE THREAD

**Issue by chulman444** [vuejs/vuex#1557]
### Version
3.1.1

### Reproduction link
[https://jsfiddle.net/2tb9frcj/1/](https://jsfiddle.net/2tb9frcj/1/)

### Steps to reproduce
Run the reproduction, open the developer console panel, click on the "click", Look at the result and please click on the `Object > val`.

### What is expected?
0 is printed out when clicking on the output of:

```
console.log("Printed as undefined", store.state.tests[0])
```

### What is actually happening?
Printed as undefined but behaves like zero

---
I know that `mutations` are not asynchronous, so the `setTimeout` or `$nextTick` won't fix it; try clicking the button multiple times to add more entries but the old values still 'display' as undefined but behaves like zero.

Behaves like zero, so I'm fine with it. Printing out the value directly prints zero, so I'm fine with it. But this was HUGELY misleading in my case when it printed out `undefined`.

**Comment by LinusBorg** [comment]
Not 100% sure what to look for, but this is what I see:

![image](https://user-images.githubusercontent.com/1444526/58431914-4151f380-80b0-11e9-812a-70129e31e450.png)

No `undefined` to be seen. Chrome 74.0.3 on OSX.

Am I missing something?

**Comment by chulman444** [comment]
![Screenshot_20190528_015920](https://user-images.githubusercontent.com/11896831/58432420-39fd0b00-80ed-11e9-8fe0-929e19ce6720.jpg)

Oh ... Firefox 67.0 on Ubuntu. Including this would've been so much better.

Checked on the chrome, and it DOES print as expected just like your screenshot. Just changed to Firefox 1 or 2 days ago, and wasn't thinking about the "different browser issues".

So, it doesn't work as expected on Firefox. Help

**Comment by LinusBorg** [comment]
Can reproduce in FF, but there isn't anything we can do about it, really. This is an issue with FF.
