### ISSUE TITLE
Add handler "subscribeAction.error"

### ISSUE THREAD

**Issue by de-don** [vuejs/vuex#1558]
### What problem does this feature solve?
The "subscribeAction.after" is not run if an action throws an error.

### What does the proposed API look like?
I propose to add one more property for catching errors in actions:

```js
const waitPlugin = (store) => {
  store.subscribeAction({
    before: (action) => {
      console.log(action.type);
    },
    after: (action) => {
      console.log(action.type);
    },
    error: (action, error) => {
      console.log(action.type);
    }
  });
};
```

**Comment by ktsn** [comment]
It would make more sense if the handler name is just `error` for consistency.

**Comment by milesingrams** [comment]
This would be really, really, really awesome. Been using a timeout hack to resolve issues where I don't know if an action has errored out.

**Comment by de-don** [comment]
> It would make more sense if the handler name is just `error` for consistency.

Thanks, I updated my example.

**Comment by evgeniy-legkun** [comment]
This is really good idea. I use subscribeAction handler to manage API calls loaders (spinners) and this feature with errors will be really useful. Waiting for it ...

**Comment by milesingrams** [comment]
Any update on this? Using this for loading spinners as well and it is critical to know if the action has failed before the after hook is called.

**Comment by samuelhgf** [comment]
Hi, guys! Any solution for that? I'm having a problem with loading. The after method is not colling when happens a error. Some body found a solution for that?

**Comment by verhichi** [comment]
Does anyone know how to deal with this issue as of this moment?

**Comment by rodrigoj42** [comment]
I'm using https://github.com/VitorLuizC/vuex-handler

**Comment by samuelhgf** [comment]
@verhichi I'm catching any error with onError function from apollo-link-error. The setup is on ApolloClient.

**Comment by verhichi** [comment]
@samuelhgf 
Yeah, that's the approach I went with too.
The only difference being I'm using REST so axios instead of apollo.

**Comment by kiaking** [comment]
This issue is in progress at #1531.

**Comment by kiaking** [comment]
This has been added via https://github.com/vuejs/vuex/pull/1740 👍
