### ISSUE TITLE
the parent state's key is covered by the same key of the child module

### ISSUE THREAD

**Issue by savoygu** [vuejs/vuex#1560]
### Version
3.1.1

### Reproduction link
[https://jsfiddle.net/msz5nv6e/](https://jsfiddle.net/msz5nv6e/)

### Steps to reproduce
Just look at the content displayed on the page.

### What is expected?
Not covered

### What is actually happening?
Covered

---
```javascript
const store = new Vuex.Store({
  state: {
    a: 'From root state'
  },
  modules: {
    a: {  
      namespaced: true,
      state: {
        a: 'From a state'
      }
    }
  }
})
```

In the source installModule method，the module a will cover the root a state：

```javascript
if (!isRoot && !hot) {
    const parentState = getNestedState(rootState, path.slice(0, -1))
    const moduleName = path[path.length - 1]
    store._withCommit(() => {
      Vue.set(parentState, moduleName, module.state) // caused the bug 
    })
 }
```

**Comment by ktsn** [comment]
This is expected behavior. https://vuex.vuejs.org/guide/modules.html
You shouldn't declare a state key having the same name with child module name.
