### ISSUE TITLE
This file maybe has a mistake. 

### ISSUE THREAD

**Issue by lemongranule** [vuejs/vuex#1569]
examples/server.js
One more "de" in the first line

**Comment by Akryum** [comment]
> One more "de" in the first line

What do you mean?

**Comment by lemongranule** [comment]
Thank you for your reply. I reviewed it again.That maybe is my mistake. Thank you again. ------------------ 原始邮件 ------------------
发件人: "Guillaume Chau"<notifications@github.com>
发送时间: 2019年6月17日(星期一) 晚上6:48
收件人: "vuejs/vuex"<vuex@noreply.github.com>;
抄送: "lemongranule"<3104464626@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vuejs/vuex] This file maybe has a mistake.  (#1569)


 
One more "de" in the first line
  
What do you mean?
 
&mdash;
