### ISSUE TITLE
Actions mapped to namespaced modules pass unexpected explicit `undefined` payload to `store.dispatch`

### ISSUE THREAD

**Issue by markrian** [vuejs/vuex#1571]
### Version
3.1.1

### Reproduction link
[https://codepen.io/markrian/pen/vqeGZZ?editors=0010](https://codepen.io/markrian/pen/vqeGZZ?editors=0010)

### Steps to reproduce
1. Open https://codepen.io/markrian/pen/vqeGZZ?editors=0010
1. Open the browser's console
1. Observe the differing logged arguments passed to `store.dispatch` depending on whether it's a root-mapped action or a namespace-mapped action (`[ "foo" ]` and `[ "childModule/foo", undefined ]` respectively - note the extra `undefined` argument in the second case; the different action name is of course expected)

Note that this only really applies in a testing scenario, where the test spies on `store.dispatch` to ensure the component dispatches the expected actions.

### What is expected?
`store.dispatch` receives exactly the same arguments regardless of whether the actions are namespace-mapped or not.

### What is actually happening?
`store.dispatch` receives a payload argument of `undefined` for namespace-mapped actions.

---
I encountered this when refactoring a store into a namespaced module, and found that my expectations needed to change: that `store.dispatch` received an extra `undefined` argument.

I'm not sure if this should be considered a bug in Vuex, or in my testing approach of spying on `store.dispatch` :man_shrugging:

**Comment by gitlab-winnie** [comment]
This is happening because of https://github.com/vuejs/vuex/blob/v3.1.1/src/store.js#L360 (explicitly passing `payload` to dispatch even if `undefined`). A simple (but admittedly not elegant) fix would be

```diff
-  return store.dispatch(type, payload)
+  return payload ? store.dispatch(type, payload) : store.dispatch(type)
```

**Comment by hugoazevedosoares** [comment]
I can work on this issue. Seems preety simple to implement @gitlab-winnie solution.

**Comment by kiaking** [comment]
Closing due to it might already fixed. See comment https://github.com/vuejs/vuex/pull/1676#issuecomment-618341755. Please feel free to open another issue if this is something that we should solve.
