### ISSUE TITLE
Duplicate getter key: 'something/something' : When register/unregister Vuex module

### ISSUE THREAD

**Issue by Rolanddoda** [vuejs/vuex#1580]
### Version
3.1.1

### Reproduction link
[https://codesandbox.io/s/vuex-register-unregister-module-roli-roli-ct4kz](https://codesandbox.io/s/vuex-register-unregister-module-roli-roli-ct4kz)

### Steps to reproduce
1. When the page loads you are in the home component (`/` route)
2. Click the `Contact` button to navigate to the contact component (`/contact` route)
3. Observe the error in the console.

In the Home and Contact  components (or pages) I use `store.registerModule` and `store.unregisterModule` to dynamically register/unregister the same module.

### What is expected?
No error should be shown. If you go to the Home later About and later Contact page (and vise versa) everything works as expected.

### What is actually happening?
An error is showing in the console that I have duplicate getter keys.

**Comment by MartinManev** [comment]
This is a problem with how vue/vue-router handles the component lifecycle.
Visiting another page immediately creates and mounts the respective component, before disposing the component of the previous page. That is why the first error says that the module is already registered, but then you also get an error that the module namespace doesn't exist. You can easily verify this by printing to the console when each lifecycle hook is called.

This is also a problem when using HMR. The new component is created before the old component is disposed, so you get the same errors.

I haven't thought up of a good solution for this yet. Maybe someone else can provide an example of how they implement dynamic modules?

**Comment by Rolanddoda** [comment]
Thanks for the comment @MartinManev. So it seems that is a `vue-router` bug.

**Comment by Rolanddoda** [comment]
As a workaround you can use transition mode out-in.

```
<transition mode="out-in">
   <router-view></router-view>
</transition>
```

Vue router issue -> [#2847](https://github.com/vuejs/vue-router/issues/2847)
