### ISSUE TITLE
add reference (in docs) to static typing libraries available

### ISSUE THREAD

**Issue by fvigotti** [vuejs/vuex#1585]
### What problem does this feature solve?
static typing

### What does the proposed API look like?
After some days with vuex I'm already bored by the lack of refactoring capacity and the slowdown of programming speed when you have to call namespace/method names using strings,
I've already tried with static string references in both methods names and method calls but this is ugly and for big store become also a mess..

I've found some libraries which brings better typing support to vuex , the best solution obviously would be toadd everything directly in vuex but If you don't find it useful at least I think that a credit in documentation should be added so users we are approaching vuex (which have less knowledge than skilled users which also mantain the docs ) can have an idea of which library choose , and also those library could get more focused support from the community ,

I vote for this library to get a sort of "officialization" as typing library for vuex :
https://github.com/championswimmer/vuex-module-decorators

(the officialization is necessary for the reasons described above), I choose this library because seems to provide the better typed experience even if his documentation is a bit incomplete

**Comment by pikax** [comment]
I've used typescript with vuex successfully.

you can have a look on `createNamespacedHelpers`

https://vuex.vuejs.org/guide/modules.html
```javascript
import { createNamespacedHelpers } from 'vuex'

const { mapState, mapActions } = createNamespacedHelpers('some/nested/module')

export default {
  computed: {
    // look up in `some/nested/module`
    ...mapState({
      a: state => state.a,
      b: state => state.b
    })
  },
  methods: {
    // look up in `some/nested/module`
    ...mapActions([
      'foo',
      'bar'
    ])
  }
}
```


You can get the string validated using typescript.

**Comment by fvigotti** [comment]
I'm using full typescript from nuxt.config.ts to vue + vue classes ( not export default object but export a class which extends Vue object and in that ...mapState doesn't work )
also I'm not sure how deep the static-typing integration goes which that method.. do you have a very simple sample project where I can test your solution ?

**Comment by pikax** [comment]
Decorators are not official supported by VueJS (check https://github.com/vuejs/rfcs/pull/17), vuex should follow the same path https://github.com/vuejs/rfcs/pull/14 https://github.com/vuejs/rfcs/pull/15

**Comment by fvigotti** [comment]
Understood, that make senses I'll investigate more ..  thank you, 
Francesco
