### ISSUE TITLE
Improve modules data map import

### ISSUE THREAD

**Issue by cherenkor** [vuejs/vuex#1596]
### What problem does this feature solve?
Repeating code, Safe import, More convenient way to import data

### What does the proposed API look like?
Hi, I've been working with Vuex recently and got a task where I would need to get a property of the object from the state.

Like this: ```state.headers.username```

What do you think to implement this solution for importing this property from the state (it also could be done for actions, getters, mutations):

```
...mapState({ username: 'collection-data/headers.username' })
```

What do you think about it?

**Comment by fourpixels** [comment]
What would be the benefit over a simple `getter`?

**Comment by ktsn** [comment]
Duplicate of #459
