### ISSUE TITLE
not working on ubuntu 14.10

### ISSUE THREAD

**Issue by chagamkamalakar** [vuejs/vuex#16]
cd examples/shopping-cart && webpack-dev-server --inline --hot --config ../webpack.shared.config.js

I am trying to test it out. I am running this on ubuntu 14.10 . on running npm install  warning is "  vue-loader@7.2.0 requires a peer of babel-runtime@^5.8.0 but none was installed." 

on running : npm run cart 

i am getting the following error

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at net.js:1253:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)

any help please

**Comment by wkwiatek** [comment]
`EADDRINUSE` means that something is listening on port you are trying to run your server. Confirm please that `8080` is not occupied by other app.

**Comment by chagamkamalakar** [comment]
LOL it's working ... thanks @wkwiatek
