### ISSUE TITLE
Does not work properly with vue 1.0.7 and older

### ISSUE THREAD

**Issue by vedraan** [vuejs/vuex#161]
You should probably mention this somewhere in the docs, since I added vuex to my app which used vue@1.0.7 and got an error when I tried to use modules in my vuex store.

Vuex tries to call this function:
`Vue.parsers.path.setPath`
which does not exist in vue@1.0.7

The issue was fixed by updating to latest vue@1.0.21, but only after some half an hour trying to figure out what I did wrong and then proceeding to inspect Vuex source code.

Adding it to docs might save someone from wasting more time debugging.

**Comment by yyx990803** [comment]
This has been fixed in 0.6.3.
