### ISSUE TITLE
$router.push() with redirect in route's beforeEnter hook causes uncaught promise rejection

### ISSUE THREAD

**Issue by berniegp** [vuejs/vuex#1616]
### Version
3.1.1

### Reproduction link
[https://jsfiddle.net/asu3qnry/](https://jsfiddle.net/asu3qnry/)

### Steps to reproduce
To trigger the uncaught promise rejection, click on "/home" and then the button.

### What is expected?
No error in console

### What is actually happening?
Console reports `Uncaught (in promise) undefined`

---
Using a `router-link` instead of the initial `$router.push()` call removes the error.

**Comment by ktsn** [comment]
I think you are filing it in wrong repo. It's vue-router issue rather than vuex.

**Comment by berniegp** [comment]
You're absolutely right, sorry!
