### ISSUE TITLE
Jumping an input caret on the strict mode

### ISSUE THREAD

**Issue by ktsn** [vuejs/vuex#162]
I try to write a simple Vuex input field following [the documentation example](http://vuejs.github.io/vuex/en/forms.html).
But when I input some texts to the field, the caret jumps to tail of the input field.

The example code that reproduce this issue is following.
https://jsfiddle.net/ktsn/dcuf7q2u/

I think it is happened because Vuex assigns the state value to input element's value even if they are both same.
Is it Vuex's issue? (or Vue's issue?)

**Comment by piknik** [comment]
The example you gave works fine for me in firefox and chrome, and demonstrates exactly how this kind of input should be used with Vuex. What browser are you using?

**Comment by ktsn** [comment]
This happens on Chrome 50.0.2661.86 and Safari 9.1 on OSX 10.11.4 (not happens on Firefox 46.0).
![input](https://cloud.githubusercontent.com/assets/2194624/14887640/9ef76b22-0d91-11e6-9707-abc5d19d5435.gif)

One of use cases for this kind of input field is autocomplete.
Autocomplete input should watch every user input and dispatch an action with input value. The store filters some suggestions for the input field. If the user selects a suggestion, the state for this input field is mutated and the input should be also updated.

In any case, I think this behavior is a little wired when users want to update their input value.

**Comment by piknik** [comment]
Ah, didn't try that. Yea looks like a bug to me, happens on chrome but not firefox.

**Comment by kazupon** [comment]
I think that this is the behavior of bug.
/ping @vuejs/collaborators

**Comment by posva** [comment]
You can use a proxy: https://jsfiddle.net/j8odng79/

But I agree it should work out of the box

**Comment by zigomir** [comment]
I think I have a fix but it's on `vue`, not `vuex` in my opinion. Will link issue here.
