### ISSUE TITLE
The Set object accessor size

### ISSUE THREAD

**Issue by iliakut** [vuejs/vuex#1627]
### Version
3.1.1

### Reproduction link
[https://codepen.io/iliakut/pen/PooPPLm](https://codepen.io/iliakut/pen/PooPPLm)

### Steps to reproduce
let Vuex see changes in Set object accessor size

### What is expected?
getter return size of Set object

### What is actually happening?
getter can't return size of Set object

---
I have a getter in vuex that returns state.setObject.size, but getter does't return actual size;
example: getter: state => state.setObject.size
I use setObject.add() and setObject.delete() methods to change setObject. 
Are there any ways to read setObject.size? Exclude component computed cache: false.

**Comment by ktsn** [comment]
Set is not supported in current Vue.js reactivity.
https://github.com/vuejs/vuex/issues/961
https://github.com/vuejs/vue/issues/1319
https://github.com/vuejs/vue/issues/2410
