### ISSUE TITLE
Access vue root instance from within a module action

### ISSUE THREAD

**Issue by seminarian** [vuejs/vuex#1645]
### What problem does this feature solve?
The possibility to use root vue instance methods from within the actions of modules.

Within actions of vuex (not in modules) the vm can be accessed by this._vm .. See https://github.com/vuejs/vuex/issues/1399

I can't succeed doing this from a module action. this is just the exports defined in the module file..

### What does the proposed API look like?
I'm not sure.. There's more clever minds than me to solve this..

**Comment by ktsn** [comment]
Please answer the first section of the issue template with proper use case. “I want to do this” doesn’t describes the justification.

**Comment by seminarian** [comment]
Same justificiation as in the Issue i referred to. Using a $notification or $axios method that got installed on the instance.

**Comment by seminarian** [comment]
I've done it this ("dirty"?) way:
`export let vm = new Vue({
  el: '#app',
  router,
  store,
  template: '<App/>',
  components: { App }
})`

and in module file.. 
`import {vm} from '../../main'
`

**Comment by ktsn** [comment]
1. You don't need to (and should not) access them via Vue instance. Just access them directly by importing it.
2. If you are talking by SSR context, you should extend store instance (`this` in action) as [Nuxt does](https://axios.nuxtjs.org/).

**Comment by seminarian** [comment]
1. Okay.. If you say so
2. is wrong. If you do `this` in the action in a module, it's a reference to the module file, not the store instance..

**Comment by ktsn** [comment]
> If you do this in the action in a module, it's a reference to the module file, not the store instance..

You probably use arrow function in that case. Don't use it if you want to use `this` as it binds `this` value with the one under declared context.

**Comment by seminarian** [comment]
You are right! Thank you very much for clearing that out!

**Comment by shredmaster** [comment]
> You are right! Thank you very much for clearing that out!

you can access the root instance by doing this. 
```
const app = new Vue({
  router,
  store,
  render: h => h(App)
})
store.$app = app
app.$mount('#app')
```
