### ISSUE TITLE
Defualt sample vuex

### ISSUE THREAD

**Issue by jgilbertcastro** [vuejs/vuex#1646]
### What problem does this feature solve?
Vue-cli create some file and directory for vuejs but new vue developer don't now how to config a simple var. So I want to make a defualt sample for vuex on vue-cli options

### What does the proposed API look like?
I will to add a new step to ask "sample config vuex?" And this will edit index.js on store  to add a simple var to state and then edit HelloComponent to render that var

**Comment by ktsn** [comment]
What do you mean by "simple var"? Why are the existing examples not enough for you?
https://github.com/vuejs/vuex/tree/dev/examples

**Comment by jgilbertcastro** [comment]
a variable from data that i can save on state, example : "title" it could
be to change on and save on state:
[image: image.png]

[image: image.png]


*Jesús** Manuel Gilbert Castro*
Senior Software Developer.

**Comment by ktsn** [comment]
I'm afraid still not get you. An example code what you would want to describe would be helpful.

**Comment by jgilbertcastro** [comment]
I just want to be able  when I create an application on vue-cli and chooses
vuex it can have a basic configuration with at least one variable that can
change the value and save on state, because vue-cli just add store folder
and index.js inside




*Jesús** Manuel Gilbert Castro*
Senior Software Developer.

**Comment by ktsn** [comment]
Ok, you are talking about boilerplate code generated by Vue CLI. In that case you should open an issue on [Vue CLI repo](https://github.com/vuejs/vue-cli) rather than this repo as it is Vue CLI template.

**Comment by jgilbertcastro** [comment]
thanks!




*Jesús** Manuel Gilbert Castro*
Senior Software Developer.
