### ISSUE TITLE
PhantomJS is an unmaintained project

### ISSUE THREAD

**Issue by ossdev07** [vuejs/vuex#1647]
### What problem does this feature solve?
The PhantomJS browser used by the vue package is an unmaintained project and also doesn't have support for aarch64.

I am curious to know that will you be interested in removing the phantomjs from vuex.
In my view, it will be better if the package uses all up to date dependencies.

Please revert that what are your thoughts on the phantomjs removal and share your suggestion on how to proceed further with this.

### What does the proposed API look like?
We could consider using the ChromeHeadless browser as an alternative to phantomjs as it is a maintained alternative to it.

**Comment by ktsn** [comment]
Definitely we should do.

**Comment by kiaking** [comment]
So I went ahead and created PR #1648 for this. Hope that will make sense.

**Comment by ktsn** [comment]
fixed via #1648
