### ISSUE TITLE
Change of state not dispatch to component

### ISSUE THREAD

**Issue by galenyuan** [vuejs/vuex#1658]
### Version
3.1.2

### Reproduction link
[http://jsfiddle.net/sx9e7fav/](http://jsfiddle.net/sx9e7fav/)

### Steps to reproduce
Open the reproduce link.

### What is expected?
should display email list

### What is actually happening?
The placeholder value 「-」 displayed

---
jsfiddle can not use Vue  devtool, so you can copy this code in a html file and run a HTTP Server.
```html
<html>
  <head>
    <title>demo</title>
    <script src="https://unpkg.com/vue@2.6.11/dist/vue.min.js"></script>
    <script src="https://unpkg.com/vuex@3.1.2/dist/vuex.min.js"></script>
  </head>
  <body>
    <ul id="demo">
      <li v-for="item in list">{{ users[item.userid] ? users[item.userid].email : '-' }}</li>
    </ul>
    <script>
      Vue.config.devtools = true
      const getUserById = (id) => {
        return new Promise((resolve) => {
          setTimeout(() => {
            resolve({
              id,
              email: `${id}@email.com`
            })
          }, 1000)
        })
      }
      const store = new Vuex.Store({
        state: {
          users: {}
        },
        mutations: {
          addUser(state, user) {
            state.users[user.id] = user
          }
        },
        actions: {
          async getUser(ctx, id) {
            if (id in ctx.state.users) return
            ctx.commit('addUser', { id, email: '-' })
            const user = await getUserById(id)
            ctx.commit('addUser', user)
          }
        }
      })
      const app = new Vue({
        store,
        el: '#demo',
        data: {
          list: [
            { userid: 1 },
            { userid: 2 },
            { userid: 3 },
            { userid: 4 },
            { userid: 5 },
          ]
        },
        computed: {
          ...Vuex.mapState(['users'])
        },
        methods: {
          ...Vuex.mapActions(['getUser'])
        },
        created() {
          this.list.forEach(item => {
            this.getUser(item.userid)
          })
        }
      });
    </script>
  </body>
</html>
```
Let's check in Vue devtool, we can find mutaion has triggered and state changed:
![image](https://user-images.githubusercontent.com/10335062/71431526-4aba4180-270d-11ea-88c6-3e1c4f28e265.png)

Then lets try a Time Travel:
![image](https://user-images.githubusercontent.com/10335062/71431539-64f41f80-270d-11ea-9f7c-5334108adc57.png)

Then the page gose to what I want:
![image](https://user-images.githubusercontent.com/10335062/71431555-7d643a00-270d-11ea-9a23-d38a68878bc6.png)

**Comment by galenyuan** [comment]
not sure my code is clear enough or not, if anything confused, let me know pls

**Comment by ktsn** [comment]
You need to update your mutation. https://vuex.vuejs.org/guide/mutations.html#mutations-follow-vue-s-reactivity-rules
