### ISSUE TITLE
mapMutations and mapActions not usable in mixin

### ISSUE THREAD

**Issue by SunGuoQiang123** [vuejs/vuex#1659]
### Version
3.1.2

### Reproduction link
[https://codepen.io/sungunguoqiang/pen/vYEZmpN?editors=1112](https://codepen.io/sungunguoqiang/pen/vYEZmpN?editors=1112)

### Steps to reproduce
App component created hook executed, the error emit  `this.TEST is not a function`

### What is expected?
no error happen

### What is actually happening?
an error emitted when called in created hook, and also mapActions also has the same problem.
if call by the `this.$store.commit('TEST')`, it's right

---
`mapState ` and `mapGetters` are right, but `mapMutations` and `mapActions` are not right

**Comment by ktsn** [comment]
It is not `method` but `methods`

https://vuejs.org/v2/api/#methods
