### ISSUE TITLE
vuex不支持多store模式

### ISSUE THREAD

**Issue by niluanxy** [vuejs/vuex#166]
自己的项目比较复杂，然后不同的功能都是写在各自的store里面，但是vuex却不支持多store模式，比如一个vue对象中只能传入一个store

**Comment by ACookieBear** [comment]
一个store，多个模块，请仔细看示例项目中的购物车https://github.com/vuejs/vuex/tree/master/examples/shopping-cart

**Comment by niluanxy** [comment]
@ACookieBear 谢谢，我看看
