### ISSUE TITLE
Vuex 3.1.2 shows TSlint Error

### ISSUE THREAD

**Issue by phymo** [vuejs/vuex#1660]
### Version
3.1.2

### Reproduction link
[https://codepen.io/phymo/pen/bGNrJVQ](https://codepen.io/phymo/pen/bGNrJVQ)

### Steps to reproduce
vuex 3.1.2 shows tslint error: 
/node_modules/vuex/types/helpers.d.ts(8,85):
TS2370: A rest parameter must be of an array type.
/node_modules/vuex/types/helpers.d.ts(8,120):
TS2370: A rest parameter must be of an array type.

### What is expected?
no error

### What is actually happening?
updated to 3.1.2 then error occurs

**Comment by Danielg212** [comment]
+1

**Comment by kiaking** [comment]
Haven't look into deep yet, but this might be the issue...?
https://github.com/Microsoft/TypeScript/issues/23440

@phymo By the way, how did you get this error? I've using Vuex with TS in several projects and never encountered this.

**Comment by phymo** [comment]
@kiaking it just happens when building the code.
vuex: 3.1.2,  typescript: 2.9.2
`T extends (fn: any, ...args: infer Args) => infer R`
is it because we can not use the inffered type to a rest parameter?

**Comment by kiaking** [comment]
Oh OK... hmmm not sure why I haven't got this error 🤔  However, tslint is also deprecated so maybe we wouldn't need to do anything...?

**Comment by kiaking** [comment]
I'll be closing the issue due to;

1. Seems like the latest TS would have no problem.
2. TSLint is deprecated, and we should be using ESlint anyway.
