### ISSUE TITLE
Typescript下webpack热更新 actions多次执行

### ISSUE THREAD

**Issue by wangqiang66** [vuejs/vuex#1664]
### Version
3.1.2

### Reproduction link
[http://localhost:9529/login](http://localhost:9529/login)

### Steps to reproduce
1. typescript 正常书写modules 例如添加
@Action
public login() {}
2. webpack 采用热更新方式
3.修改modules代码 例如public login() { console.log(test)} 保存

### What is expected?
执行login的时候的用更新的代码

### What is actually happening?
以前的方法和新的方法都执行

---
热更新才会出现，需要动态的修改源码， 无法提供重现链接

正常打包不会出现这个问题，热更新的时候才会出现

查看store._actions 发现login对象是一个数组，有两条数据

**Comment by kiaking** [comment]
@wangqiang66 Do you have any update on this one? Sorry I don't understand Chinese so not sure what this issue is 😅

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please open another issue if there's anything!
