### ISSUE TITLE
dispatch interface returns pending promise instead of resolved

### ISSUE THREAD

**Issue by vicglarson** [vuejs/vuex#1668]
### Version
3.1.2

### Reproduction link
[https://jsfiddle.net/jtzqmxk3/](https://jsfiddle.net/jtzqmxk3/)

### Steps to reproduce
in this request insterface of dispatch changed
Look at this https://github.com/vuejs/vuex/pull/1115/files#diff-3bf35cd41da51153dcca3003656f7c67R139

it returns now pending promise for returned true from action instead of resolved. You can see it at jsfiddle console.

### What is expected?
untouched Promise.resolve(true) returned by action wrapper
when no any action subscribers added

### What is actually happening?
returned pending promise

---
also you can look at 
https://github.com/vuejs/vuex/issues/1572
which targets the same pull request

Perhaps I have bad assumptions. But behavior for trivial action response is not specified here https://vuex.vuejs.org/ru/guide/actions.html

**Comment by LinusBorg** [comment]
> it returns now pending promise for returned true from action instead of resolved. You can see it at jsfiddle console.

I get a fullfilled promise, see the screenshot:

![grafik](https://user-images.githubusercontent.com/1444526/73069366-d4486500-3ead-11ea-8eb7-0c801c18cadc.png)

I generally have problems following your problem description.

**Comment by vicglarson** [comment]
![image](https://user-images.githubusercontent.com/222960/73071106-057f6000-3ec3-11ea-984f-4cfb97b80052.png)
not sure fiddle depends on browser but in opera i see this

**Comment by ktsn** [comment]
As you synchronously log the Promise object, it is in pending state at that moment. It will be fulfilled immediately on the next tick. I'm not sure what is the problem on this behavior.

**Comment by LinusBorg** [comment]
Works in Opera 66.035 (Mac) as well:

![image](https://user-images.githubusercontent.com/1444526/73119737-a96e1780-3f66-11ea-8be8-cfc8d1f6bd4c.png)

**Comment by vicglarson** [comment]
@ktsn yep it's fulfilled on next tick so i think i'm wrong
