### ISSUE TITLE
Slow performance using getter references other getter

### ISSUE THREAD

**Issue by tbetous** [vuejs/vuex#1669]
### Version
3.1.2

### Reproduction link
[https://jsfiddle.net/tbetous/y4m0keav/53/](https://jsfiddle.net/tbetous/y4m0keav/53/)

### Steps to reproduce
1 - Write a getter `myGetter` that use another getter `otherGetter` by using `getters` argument

```js
myGetter: (state, getters) => {
      console.time('myGetter')
      const t0 = performance.now();
      for(let i = 0; i < 100; i  ) {
        const foo = getters.otherGetter
      }
      console.timeEnd('myGetter')
      const t1 = performance.now();
      return t1 - t0
    },
```

2 - Write a getter `myGetterOptimized` that use another getter `otherGetter` by destructuring `getters`

```js
myGetterOptimized: (state, {otherGetter}) => {
      console.time('myGetterOptimized')
      const t0 = performance.now();
      for(let i = 0; i < 100; i  ) {
        const foo = otherGetter
      }
      console.timeEnd('myGetterOptimized')
      const t1 = performance.now();
      return t1 - t0
    },
```

3 - Compare time execution

### What is expected?
Time execution should be the same.

### What is actually happening?
Time execution is different :
- getterOptimized : 0.21999999989930075
- getterNotOptimized : 494.8850000000675

**Comment by kiaking** [comment]
@tbetous This is because getters are JS getter. Your example `myGetter` is calling the getter method inside the loop where else myGetterOptimized is calling the getter during the destructuring. Try fetching getter before doing the loop.

```js
myGetter: (state, getters) => {
  console.time('myGetter')
  const otherGetter = getters.otherGetter // Here
  const t0 = performance.now();
  for(let i = 0; i < 100; i  ) {
    const foo = otherGetter
  }
  console.timeEnd('myGetter')
  const t1 = performance.now();
  return t1 - t0
}
```

The above will result in the same performance. I don't think there's anything we can do about this. It's how JS work.

**Comment by tbetous** [comment]
Yep totally ! Thanks ! 

However I wonder what happen in the JS getter that take so much time. I put  console.count in otherGetter and it is called only one time, not each time. may  VueX customize JS getter to get the result from cache ?

**Comment by kiaking** [comment]
@tbetous Not 100% sure if I'm understanding it correctly, but yes Vuex Getters caches the result. It works similar to how Vue computed property works. It tracks the dependent states and only evaluates when the state is changed.

**Comment by tbetous** [comment]
Thanks a lot @kiaking ! You answered to my question ! I guess I can close the issue.

**Comment by Kasheftin** [comment]
> @tbetous This is because getters are JS getter. Your example `myGetter` is calling the getter method inside the loop where else myGetterOptimized is calling the getter during the destructuring. Try fetching getter before doing the loop.
> 
> ```js
> myGetter: (state, getters) => {
>   console.time('myGetter')
>   const otherGetter = getters.otherGetter // Here
>   const t0 = performance.now();
>   for(let i = 0; i < 100; i  ) {
>     const foo = otherGetter
>   }
>   console.timeEnd('myGetter')
>   const t1 = performance.now();
>   return t1 - t0
> }
> ```
> 
> The above will result in the same performance. I don't think there's anything we can do about this. It's how JS work.
> 
> Does it make sense to you sunglasses?

Could you please share more details about this native JS behavior? Why there's the difference?

**Comment by cuebit** [comment]
@Kasheftin native getters give you a way to define a property of an object, but they do not calculate the property's value until it is accessed. A getter defers the cost of calculating the value until the value is needed. If it is never needed, you never pay the cost.

When destructuring (as exhibited in the OP second example) the property is being accessed and the value has been calculated before the performance timeline, therefore the result is inaccurate in the given context.

**Comment by Kasheftin** [comment]
@cuebit If we track the getter's calculation, we find that it's calculated only once no matter if called in a cycle or before the cycle. 
https://jsfiddle.net/kasheftin/9oh3svn2/ - here's the slightly updated version, where getter calc included into timeline. It shows the same difference.
I would say that the real reason of this huge difference is that any vuex getter provides a Proxy, calling the getter requests Proxy.get method, and the last has some inner logic like dependency tracking.
