### ISSUE TITLE
 Cannot set reactive property on undefined, null, or primitive value: undefined when using Vuex and Storybook 5.3

### ISSUE THREAD

**Issue by steveworkman** [vuejs/vuex#1671]
### Version
3.1.2

### Reproduction link
[https://github.com/dylanbanks96/storybook-demo](https://github.com/dylanbanks96/storybook-demo)

### Steps to reproduce
Create a basic component using Vuex, and add storybook documentation. The component attempts to commit data to vuex state via an action and mutator

Essentially, I'm trying to commit input field data to my store

### What is expected?
I'm able to access and modify state

### What is actually happening?
Cannot set reactive property on undefined, null, or primitive value: undefined" and a TypeError: "index.js:47 TypeError: Cannot use 'in' operator to search for 'foo' in undefined".

---
This may be a storybook issue, but it may be a Vuex issue as well. I've also raised this on S/O https://stackoverflow.com/questions/59919325/vuex-storybook-cannot-set-reactive-property-on-undefined-null-or-primitive

**Comment by kiaking** [comment]
This is rather question about Story book usage, and I see answers in StackOverflow. Please continue discussion over there 🤝
