### ISSUE TITLE
为什么不推荐使用常量替代 action事件类型?

### ISSUE THREAD

**Issue by Candane** [vuejs/vuex#1672]
为什么不是使用常量代替 Action 类型，通常 Mutation 的类型只在一个 store 使用，如果修改 y 一个类型也在一个 store 里面修改，但是 action 的话可能在很多组件中会使用到，修改的面积会比 Mutation 大得多，为什么官方只推荐使用常量替代 Mutation 事件类型？

**Comment by Nick-Dream** [comment]
我也有这样的问题，实际开发过程中，action被复制的次数明显要多余Mutation
