### ISSUE TITLE
Default mutations for set state.

### ISSUE THREAD

**Issue by HuberTRoy** [vuejs/vuex#1673]
### What problem does this feature solve?
If I just want to set a value for one state, I must code: 

```js
const state = {
     test : 1
}

const mutations = {
      setTest(state, value) {
            state.test = value
      }
}
```

I wrote or read most of the mutations are this kind of. So If `vuex` set default mutations for all states we will reduce most of the mutations set.

### What does the proposed API look like?

```js
const state = {
    test: 1
}

const actions = {
      async setTestWhenRequest(context) {
            let res = await axios.get('http://www.new-issue.vuejs.org')
            if ( res.code === 200) {
                  context.commit('$setTest', 2)
            }
      }
}
```

**Comment by kiaking** [comment]
Interesting idea! Though, I think this is not the ideal feature to add to the Vuex. There're lots of edge-cases, for example, nested or array property handling, multiple property update, etc. It solves some problems, but I don't think it's flexible enough. Maybe it could be a plugin.

However, I do understand your pain. One idea is to create some generic mutation and call that instead.

```js
const state = {
  test: 1
}

const actions = {
  async setTestWhenRequest(context) {
    let res = await axios.get('http://www.new-issue.vuejs.org')
    if ( res.code === 200) {
      context.commit('mutate', state => { state.test = 2 })
    }
  }
}

const mutations = {
  mutate(state, callback) { 
    callback(state)
  }
}
```

What do you think?

**Comment by HuberTRoy** [comment]
@kiaking 

Thanks a lot. Your idea is great to solve the problems, and I have a question for the edge-cases.  Why this have edge-cases to consider? 

For example:

https://codesandbox.io/embed/awesome-night-ucsko?fontsize=14&hidenavigation=1&theme=dark

It just replaces the old value and it seems to run well.

Thanks your response.

**Comment by kiaking** [comment]
Well, when we think deeper, there'll be a lot more consideration to the API. I mean, if we only need a feature that relaces a single value, that might work maybe.

However, I'm pretty sure that there'll be requests wanting to merge array properties or nested objects, and so on.

```js
const state = {
  items: []
}

const actions = {
  async setTestWhenRequest(context) {
    let res = await axios.get('http://www.new-issue.vuejs.org')
    if (res.code === 200) {
      context.commit('setItems', res.data) // Override? Or merge? Something else?
    }
  }
}
```

It could be just simple override, but sooner or later, there's going to be more requests wanting to enhance this request, which will get into the point where ending up with pretty complicated API.

Or having this `setXX` "magic" mutation could easily conflict with user-defined mutations. To manage and control those conflicts, maybe we should add more options...? We're now introducing more complexity than it solves. Before, you could just write your own mutation, and that's it, but now you need to configure something. 🤔 

I'm not saying all of the things I described above are definitely going to happen. But as you can see, there're a lot more to think about when implementing such a feature.

I don't disagree with implementing your solution your self, or there can even be a plugin to do this. That's totally fine. Just that, I don't think this should be in the core library.

**Comment by HuberTRoy** [comment]
@kiaking 
Thanks! 
I agree this should be a plugin and I just want to know what edge-cases should consider. I don't have any experience that maintains a huge open-source project so I want to learn from you.
Thanks again.

**Comment by kiaking** [comment]
@HuberTRoy Great! Thank you for your feedback though 👍
