### ISSUE TITLE
Dispatching large data cause app craches

### ISSUE THREAD

**Issue by XemaA** [vuejs/vuex#1677]
### Version
3.0.1

### Reproduction link
[https://codepen.io/XemaA/pen/jOPEOqm?editors=0010](https://codepen.io/XemaA/pen/jOPEOqm?editors=0010)

### Steps to reproduce
I am trying to mutate  a file content's in the state so I can use them in different modules of the app.
```javascript
// In the action : I read file content
readFile(context, payload) {
    const readStream = fs.createReadStream(payload.filePath);
    Papa.parse(readStream, { header: true }, complete(results) { // here I use papaparse (Papa) to parse file content
        context.commit('testA', results.data); // in case of large file, when I comment this line the app doesn't stop
    });
}
// mutation
testA(state, payload) {
    state.structData = payload;
}
```

### What is expected?
file content mutated to state

### What is actually happening?
on case of 23MB size file the app craches without returning any errors or warning

---
When working with small files the process works as expected, the issue appears only with large files ( I am testing 23MB size file)
I am working on electron/vue app

**Comment by kiaking** [comment]
Hi! Do you have any update on this? I think I'm not being able to reproduce the issue here...

**Comment by XemaA** [comment]
Hello @kiaking ! Since I didn't figure out how to resolve this and I was pretty sure that it was a performance issue ... I opted for another solution; Instead of mutating the file content (parsed with papaparse), I am storing the result in a json file and only mutate the file path..

**Comment by kiaking** [comment]
Oh OK thanks. Well, 23MB is pretty huge on client side, and I understand you use electron so I think for that it's valid use case.

I think it solved for you now, there's not much we can't do if we can't reproduce it. Please feel free to open another issue if you find anything again 🙌
