### ISSUE TITLE
Yarn v2 compat: add vue to peerDependencies

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vuex#1681]
### Version
3.1.2

### Steps to reproduce
When using Typescript, vuex export types like here: https://github.com/vuejs/vuex/blob/dev/types/index.d.ts#L1 But as you can see here, it imports Vue typings to make it work. As a matter of fact `vue` should be added to peerDependencies

### What is expected?
`vue` should be a peerDependency 

### What is actually happening?
it is not, and it fails in a strict dependency-tree context

Ref: https://github.com/vuejs/vue-cli/issues/5135

**Comment by kiaking** [comment]
Thanks for the report! Yap, indeed we should have it as a peer dependency. PR on the way 👍

**Comment by kiaking** [comment]
And this is fixed at Vuex 3.1.3 🎉 
https://github.com/vuejs/vuex/releases/tag/v3.1.3
