### ISSUE TITLE
How to typescript vuex getter function?

### ISSUE THREAD

**Issue by zl7261** [vuejs/vuex#1686]
### Version
3.1.2

### Reproduction link
[ https://github.com/zl7261/vuex_study]( https://github.com/zl7261/vuex_study)

### Steps to reproduce
The vuex getters functions can return an anonymous function that can operate state of vuex .
but how to typescript annotation function param type
if I call vuex getters like this code style 

``` javascript
const getters = {
    getStateValue(state) {
        return (value) => {
            console.log(value)
            return state[value]
        }
    }
}
```
```javascript 
this.$store.getters.getStateValue('testMsg')
```
Actually, 'textMsg' is type of the Inner anonymous function param,
but if I call the getters method like this, the IDE think state is String type.

### What is expected?
Can be typescript

### What is actually happening?
I don't know how to use type annotation in this case.

**Comment by F0rsaken** [comment]
I think you should rather use `mapGetters` and overall `mapXXX` like here: https://vuex.vuejs.org/api/#mapgetters
but you want get typings with it.

I don't know if that's what you're looking for.

**Comment by F0rsaken** [comment]
Also, try writing it like this:
`this.$store.getters["getStateValue"]('testMsg')`
But I'm not sure if it will help with IDE

**Comment by kiaking** [comment]
Hmm... @ktsn Do you know anything about this?

**Comment by ktsn** [comment]
> but if I call the getters method like this, the IDE think state is String type.

Are you talking about IDE behavior? As the getters type is `any`, it accepts any type of values and `state` and `value` will be `any` type as you don't annotate their types. I'm not sure what your expected behavior is.

**Comment by kiaking** [comment]
@F0rsaken do you have any updates on this?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. As ktsn mentioned, the type is `any` so it should be accepting any call.

**Comment by zl7261** [comment]
webstorm 2020.1 add vuex support.
