### ISSUE TITLE
Bug in todomvc example

### ISSUE THREAD

**Issue by bennyyip** [vuejs/vuex#171]
[components/Todo.vue](https://github.com/vuejs/vuex/blob/master/examples/todomvc/components/Todo.vue)
```html
    <input class="edit"
      v-show="editing"
      v-focus="editing"
      :value="todo.text"
      @keyup.enter="doneEdit"
      @keyup.esc="cancelEdit"
      @blur="doneEdit">
```

When I press esc, `blur` is triggered instead of `keyup.esc`, resulting in modifying the todo instead of discarding the change

**Comment by yyx990803** [comment]
Cannot reproduce. Please follow up if you can provide more details e.g. in what browser does this happen.
