### ISSUE TITLE
多个mutations模块组合时如何分发mutations?

### ISSUE THREAD

**Issue by zhangfisher** [vuejs/vuex#172]
使用vuex时，定义mutations时，如果使用定义了两个
mutationA={M1....}
mutationB={M2....}
然后在使用这两个mutations时，这样写：
 mutations: [mutationA, mutationB]
这样问题来了，如果要分发M1该怎么写？
如果直接dispatch("M1")会提示没有定义M1

**Comment by yyx990803** [comment]
你看的旧版文档吧。看下英文版的文档
