### ISSUE TITLE
Why store() instead of just a store object

### ISSUE THREAD

**Issue by nainardev** [vuejs/vuex#1721]
### Current API
```js
import { createStore } from 'vuex'

const store = createStore({
  state () {
    return {
      count: 1
    }
  }
})
```

Why should we have store() return the state object instead of just writing the store?

### What does the proposed API look like?
```js
import { createStore } from 'vuex'

const store = createStore({
  count: 1
})
```
Is there a specific reason for having a function return store object

**Comment by kiaking** [comment]
@nainardev Because there are `getters`, `actions` and `mutations` too. We need a way to distinguish those different properties. Same as how Vue's `data` and `computed` and `methods` are separated.
