### ISSUE TITLE
ESM browser build still contains references to process.env

### ISSUE THREAD

**Issue by pearofducks** [vuejs/vuex#1730]
### Version
4.0.0-beta.1

### Reproduction link
[https://unpkg.com/vuex@4.0.0-beta.1/dist/vuex.esm-browser.js](https://unpkg.com/vuex@4.0.0-beta.1/dist/vuex.esm-browser.js)

### Steps to reproduce
Compare build from 3.3.0

https://unpkg.com/vuex@3.3.0/dist/vuex.esm.browser.js

to build for 4.0.0-beta.1

https://unpkg.com/vuex@4.0.0-beta.1/dist/vuex.esm-browser.js

### What is expected?
No references to `process.env`

### What is actually happening?
References to `process.env` which cause it to not be usable in the browser.

---
Original issue creating these builds - https://github.com/vuejs/vuex/issues/1247

Resolving this is blocking Vuex use in [Vite](https://github.com/vuejs/vite)

**Comment by kiaking** [comment]
Thank you so much for the report! I'll create a fix.

**Comment by kiaking** [comment]
OK seems like this happened when we forward port Vuex 3 to Vuex 4, where Vuex 3 uses `process.env` instead of `__DEV__`. We should just make Vuex 3 use `__DEV__` and then merge back in to Vuex 4.

I'll include the fix in #1729.

**Comment by kiaking** [comment]
OK this is actually fixed at #1729. Forgot to close it.
