### ISSUE TITLE
useStore is missing a type declaration

### ISSUE THREAD

**Issue by ChrisShank** [vuejs/vuex#1736]
### Version
4.0.0-beta.1

### Reproduction link
[https://github.com/ChrisShank/vue-next-webpack-preview](https://github.com/ChrisShank/vue-next-webpack-preview)

### Steps to reproduce
Remove the type declaration of 'useStore' I added in 'vuex-shim.d.ts', and there will be a compile-time TS error.

### What is expected?
The type for useStore to exist.

### What is actually happening?
On the line: 
```ts
import { useStore } from 'vuex'
```

There is an error: 
```bash
TS2614: Module 'vue-next-webpack-preview/node_modules/vuex/types"' has no exported member 'useStore'. Did you mean to use 'import useStore from "vue-next-webpack-preview/node_modules/vuex/types"' instead?
```

**Comment by surmon-china** [comment]
@ChrisShank Override the `vuex`'s type definition in TypeScript.

```ts
declare module "vuex" {
  function useStore<T = any>(key?: string): T
}
```

**Comment by surmon-china** [comment]
It seems that the type is difficult to cover, you can do this:

```ts
// @ts-ignore
import { createStore, useStore as useVuexStore } from 'vuex'

const store =  createStore<StoreState>({})

export default store
export function useStore(): typeof store {
  return useVuexStore()
}
```

**Comment by ChrisShank** [comment]
@surmon-china I currently am [here](https://github.com/ChrisShank/vue-next-webpack-preview/blob/master/src/shims-vuex.d.ts#L10)

I think that a type should either be included with the package (similar to the one you first mentioned) or documented that the user is expected to provide their own shim.

**Comment by kiaking** [comment]
Thanks for the report! Yea we must add this one 👍
