### ISSUE TITLE
How could I work with 3rd part UI components with vuex without modify their code

### ISSUE THREAD

**Issue by ljwrer** [vuejs/vuex#174]
Generally,when I use UI components,even if they don't dispatch any events or don't accept props through their parent components,I could use computed properties with $refs,that works well.
For example,I import tabset from vue-strap,tabset use a variable named activeIndex to manage the state,here is the code

    <template>
        <div>
            <tabs v-ref:tab>
                <tab header="one">0</tab>
                <tab header="two">1</tab>
                <tab header="three">2</tab>
            </tabs>
            <button @click="move" type="button" class="btn btn-default">{{index}}</button>
        </div>
    </template>

        methods: {
            move:(function () {
                let direction = -1;
                return function () {
                    if (this.index === this.$refs.tab.$children.length-1 || this.index === 0) {
                        direction=-direction
                    }
                    this.index += direction
                }
            })()
        },
        computed: {
            index: {
                get(){
                    return this.$refs.tab.activeIndex;
                },
                set(index){
                    this.$refs.tab.activeIndex = index
                }
            }
        }

If I want to work with vuex,I should use getters to get that **index** to my component and pass it to the tabset througth props,when the sub component should change index,they just need to call some actions to update it.In that way,I have to modify their code.
Is their any way to do it without modify their code?

**Comment by chrisvfritz** [comment]
Not that I'm aware. Even outside of vuex apps, I have a preference for copying and pasting most components (especially the relatively simple ones) instead of importing them as black boxes. It's not uncommon in bootstrap components for example, to want to do something a little special.
