### ISSUE TITLE
Multiple lists with various filters

### ISSUE THREAD

**Issue by jakobrosenberg** [vuejs/vuex#175]
Let's say I'm building a forum and this is what I need:

- A frontpage with a live feed of the 10 latest posts and the 10 most liked posts along with the posters' names.
- A Most-popular-posts-page to show the most 20 popular posts in detail.

How should this be structured in Vue/Vuex? If every view/component has it own specific query need, should each component have a separate entry in the vue state for its data?

**Comment by jonagoldman** [comment]
I don't think you need Vuex at all. The benefits of using Vuex start to show on medium/large applications where the data structure is complex. A forum structure is much simpler and Vuex is an overkill.

**Comment by FadyMak** [comment]
Hi @jakobrosenberg, you can have a look at the structure for small and medium/large applications specified in the [Vuex Docs](http://vuex.vuejs.org/en/structure.html).

This question is better suited for the Gitter or Forum.
