### ISSUE TITLE
lazy load doesn't for registerModule 

### ISSUE THREAD

**Issue by Ewelina436** [vuejs/vuex#1754]
### Version
3.3.0

### Reproduction link
[https://codesandbox.io/s/vuex-load-module-d2tss?file=/src/main.js](https://codesandbox.io/s/vuex-load-module-d2tss?file=/src/main.js)

### Steps to reproduce
1. click button 'check' - open Console

### What is expected?

access to the newly registered module

### What is actually happening?
I get the answer 'undefined'

---

When I try to import statically everything works ... However, it is very important for me to be lazy. Please help ...

In Vue.js devtools  - I see information that the module has been registered but is empty

**Comment by kiaking** [comment]
You need to add `default` to get the default export.

```js
getState().then(state => {
  this.$store.registerModule("notifications", state.default); // <- Add `default`.
});
```

It would help to console log the result of the `import` method and see what you're actually getting 👍

**Comment by Ewelina436** [comment]
Thank you very much for your answer!  I have another very important problem,  is it possible to have access to the module in created. Download data from api. I need to register the module and download user data via store. 
My code:
```
 getState().then(usersModule =>{
        this.$store.registerModule("usersModule", usersModule.default)
      });

this.$store.dispatch('usersModule/getList');
```

**Comment by kiaking** [comment]
I guess you need to put that `dispatch` method inside `then` clause.

```js
created(){
 getState().then(usersModule => {
    this.$store.registerModule("usersModule", usersModule.default);

    this.$store.dispatch('usersModule/getList');
  });
}
```

Not sure until I can see your whole code though.

However, I have to ask you to continue with the questions on Discord or at Vue Forum. GitHub issues are not for the questions but for the bug report and a new feature discussions. Hope you would understand 🙏
