### ISSUE TITLE
Vuex getters are not type checked in typescript

### ISSUE THREAD

**Issue by karel-3d** [vuejs/vuex#1756]
### What problem does this feature solve?
This feature will correctly check types of store getters.

Currently, getters have type `getters: any`.

### What does the proposed API look like?
vuex getters are defined (maybe) correctly in https://github.com/ClickerMonkey/vuex-typescript-interface/blob/master/index.d.ts

```ts
export type GetterKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, never, P>
}[keyof T];


export type GetterInputFor<T> = {
  [K in GetterKeys<T>]: T[K];
};

export type MergedGettersFor<T> = {
  [M in MergedModuleKeys<T>]: 
    T extends { modules: { [P in M]: infer E } } 
      ? GettersFor<E> 
      : never;
};

export type GettersFor<T> = 
  GetterInputFor<T> & 
  Flatten<MergedGettersFor<T>>;
```

~I am not sure if this is actually correct. I can try it and make a PR if there is interest.~

**Comment by karel-3d** [comment]
Eh, that type definition is so wildly different from the current one that it cannot really be reused.

**Comment by kiaking** [comment]
Yes the getters are `any` at the moment. It's kinda hard to type this in clean way. We should be doing much better in Vuex 5.

We're keeping TS issue open at https://github.com/vuejs/vuex/issues/564 so let's move it over there unless there's some simple type improvements can be done in Vuex 3 or 4 👍
