### ISSUE TITLE
[doc] 更新中文文档

### ISSUE THREAD

**Issue by qiansen1386** [vuejs/vuex#176]
打算基于 d5737d2027ceee27af5a93f96be247c6d42dac99 快照，更新下中文文档。可以在这里占个坑么？
- [x] [目录](https://github.com/vuejs/vuex/blob/master/docs/zh-cn/SUMMARY.md)
- [x] [什么是 Vuex?](/vuejs/vuex/blob/master/docs/zh-cn/intro.md)
- [x] [快速开始](/vuejs/vuex/blob/master/docs/zh-cn/quickstart.md)
- [x] [教程](/vuejs/vuex/blob/master/docs/zh-cn/tutorial.md)
- 核心概念
- [x]  - [State 和 Getters](/vuejs/vuex/blob/master/docs/zh-cn/state.md)
- [x]  - [Mutations（突发事件）](/vuejs/vuex/blob/master/docs/zh-cn/mutations.md)
- [x]  - [Actions](/vuejs/vuex/blob/master/docs/zh-cn/actions.md)
- [ ] [数据流](/vuejs/vuex/blob/master/docs/zh-cn/data-flow.md)
- [ ] [应用结构](/vuejs/vuex/blob/master/docs/zh-cn/structure.md)
- [ ] [中间件](/vuejs/vuex/blob/master/docs/zh-cn/middlewares.md)
- [ ] [严格模式](/vuejs/vuex/blob/master/docs/zh-cn/strict.md)
- [ ] [表单处理](/vuejs/vuex/blob/master/docs/zh-cn/forms.md)
- [ ] [测试](/vuejs/vuex/blob/master/docs/zh-cn/testing.md)
- [ ] [热重载](/vuejs/vuex/blob/master/docs/zh-cn/hot-reload.md)
- [ ] [API 参考文档](/vuejs/vuex/blob/master/docs/zh-cn/api.md)

**Comment by yyx990803** [comment]
👍

**Comment by stonexer** [comment]
需要的话报个名，可以一起合作。。

**Comment by qiansen1386** [comment]
@stonexer  所以呀，就这边放一个表，大家想更新哪里随便选啊。
改动不大的篇幅，比如`intro.md`，可以直接提交PR。
不过后面文档的结构有变化，直接提交会导致文档的版本错乱，造成误解。（尤其是`concept.md`被删了）
所以我开了一个新 branch 当缓冲区，打算大体捋一遍再提交PR。
https://github.com/qiansen1386/vuex/tree/patch/chinese-translation-update

**Comment by qiansen1386** [comment]
https://github.com/vuejs/vuex/compare/master...qiansen1386:patch/chinese-translation-update?expand=1

Have a look, dudes~

**Comment by lymanlai** [comment]
文档似乎更新比较混乱。。。  
基于1.0写了部分程序，写的过程感觉到比如action应该返回promise等等，现在看到2.x想切换过来。但是文档似乎不同步。
也许直接看源代码或者示例代码直接点。
然后等正式发布，再一次性大家集中翻译会好点，不然感觉很混乱。

**Comment by qiansen1386** [comment]
需要咨询下尤雨溪大大的意见。vue 2 之后，会不会同步再更新状态管理和后端渲染等方案。

**Comment by fuchao2012** [comment]
报名1.0，主要是看到过期两个字不顺眼

**Comment by MAYDAY1993** [comment]
报名2.0  掘金翻译计划的译者

**Comment by Ilookgood** [comment]
为什么运行不起来？？

**Comment by qiansen1386** [comment]
@Ilookgood 已经都翻译完了好像
