### ISSUE TITLE
开发模式下内存上涨严重

### ISSUE THREAD

**Issue by namelessb** [vuejs/vuex#1777]
### Version
3.4.0

### Reproduction link
[https://codesandbox.io/s/black-dust-d5jor?file=/src/App.vue](https://codesandbox.io/s/black-dust-d5jor?file=/src/App.vue)

### ***链接内有截图***
1. 开发环境
  * electron:7.3.0
  * vue:2.6.11
  * @vue/cli:4.3.1
  * vue-cli-plugin-electron-builder:1.4.4

2. 我有一个WebSocket服务, 会不停的向客户端发送数据, 接收到的数据存入store中
开发模式下, 此时内存直线飙升, 短时间内可达到一两个G, 内存快照中占用量最多的是字符串，这些字符串全部是整个状态树的JSON字符串。
生产模式下没有问题

### What is expected?
占用内存正常

### What is actually happening?
占用内存过高, 经常导致crash

---
只在开发模式下有此问题

**Comment by kiaking** [comment]
Hi! Thanks for the report. At my environment, I don't see any memory increase to GB size. Is this reproduction link working for you...?

The code looks pretty straight forward, I don't know how it's causing the problem.

**Comment by namelessb** [comment]
找到了内存泄漏的真正原因, 引发问题的是vue-devtools, 不是vuex
https://github.com/vuejs/vue-devtools/issues/210
