### ISSUE TITLE
Vuex state updated，but the page never change，before data change

### ISSUE THREAD

**Issue by shirakagi** [vuejs/vuex#1785]
### Version
3.4.0

### Reproduction link
[https://codesandbox.io/s/vuetest-un9jv?file=/src/App.vue](https://codesandbox.io/s/vuetest-un9jv?file=/src/App.vue)

### Steps to reproduce
1.refresh page
2.wait 2000ms  (data changed)
3.change page's data

### What is expected?
vuex state改变时页面数据自动更新

### What is actually happening?
vuex state更新后 页面数据并没有自动更新，
当页面的data更新后 才更新

**Comment by kiaking** [comment]
@shirakagi It happens because you are adding a new object property `test` which Vue's reactivity doesn't support. You must either predeclare the `test` property like;

```js
{
  state: {
    library: {
      test: {}
    }
  }
}
```

Or, use `Vue.set` method on mutation, or create a new object and assign it:

```js
{
  GET_DICT_LIBRARY: (state, data) => {
    state.library = { test: data.test };
  }
}
```
