### ISSUE TITLE
"types/logger.d.ts" file is missing from npm package

### ISSUE THREAD

**Issue by jgerigmeyer** [vuejs/vuex#1788]
### Version
3.5.0

### Reproduction link
[https://github.com/vuejs/vuex/blob/v3.5.0/package.json#L11-L16](https://github.com/vuejs/vuex/blob/v3.5.0/package.json#L11-L16)

### Steps to reproduce
Run `tsc` or `vue-cli-service build` on repo with Vuex 3.5.0 installed.

### What is expected?
No errors.

### What is actually happening?
```
7:26 Cannot find module './logger' or its corresponding type declarations.
     5 |
     6 | import { mapState, mapMutations, mapGetters, mapActions, createNamespacedHelpers } from "./helpers";
  >  7 | import createLogger from "./logger";
       |                          ^
     8 |
     9 | export * from "./helpers";
    10 | export * from "./logger";
```

```
10:15 Cannot find module './logger' or its corresponding type declarations.
     8 |
     9 | export * from "./helpers";
  > 10 | export * from "./logger";
       |               ^
    11 |
    12 | export declare class Store<S> {
    13 |   constructor(options: StoreOptions<S>);
```

---
Fix: Add `"types/helpers.d.ts",` to `package.json` `files` config (https://github.com/vuejs/vuex/blob/v3.5.0/package.json#L11-L16).

**Comment by kiaking** [comment]
Thanks for the report! Will close this one due to duplication. The PR #1789 is open so we'll make a new release soon 🙏
