### ISSUE TITLE
logger.d.ts wrong location

### ISSUE THREAD

**Issue by olamedia** [vuejs/vuex#1790]
### Version
3.5.0

### Reproduction link
[https://codesandbox.io/s/solitary-surf-s268j](https://codesandbox.io/s/solitary-surf-s268j)

### Steps to reproduce
1. npm install
2. check vuex/types/index.d.ts

### What is expected?
vuex/types/index.d.ts contains the following line
```import createLogger from "./logger";```
Expected logger.d.ts location is vuex/types

### What is actually happening?
logger.d.ts is located at vuex/dist

**Comment by kiaking** [comment]
Thanks for the report! This issue should been solved with 3.5.1, which was released right after 3.5.0 😓 

Please feel free to reopen it if you still have the same problem with 3.5.1 👍

**Comment by olamedia** [comment]
Oh... I see it's fixed in 3.5.1
nuxt's template vue-app still uses 3.5.0, that's why I met this problem

**Comment by kiaking** [comment]
Ah I see. Thanks for the confirmation. I think it will updated soon at Nuxt side too 👍
