### ISSUE TITLE
Component watch "$store.state.xxx" does not work on v4

### ISSUE THREAD

**Issue by xPaw** [vuejs/vuex#1799]
### Version
4.0.0-beta.4

### Reproduction link
[https://jsfiddle.net/gbach1eu/](https://jsfiddle.net/gbach1eu/)

### Steps to reproduce

I have code like this:

```js
export default {
	name: "Mentions",
	watch: {
		"$store.state.mentions"() {
			this.isLoading = false;
		},
	},
}
```

And there is a mutation like so:

```js
mentions(state, mentions) {
	state.mentions = mentions;
},
```

Which is triggered with `store.commit("mentions", data);`

### What is expected?
Watch is triggered.

### What is actually happening?
watch for store state change is not triggering. This worked on vue2 (vuex 3).

---
I don't know if it was intended that watch actually worked on vue 2 like this, and it's hard to find info if this was intentionally changed for vue 3.

**Comment by xPaw** [comment]
Appears to be related to this? https://github.com/vuejs/vue-next/issues/671#issuecomment-579818159

**Comment by kiaking** [comment]
Thanks for the report! Seems like Vue 3 docs has dropped this syntax, but not sure if this is still supported or not. Trying to finding it.

The comment you mentioned shouldn't be related since that behavior was changed after that discussion.

**Comment by kiaking** [comment]
@xPaw OK indeed the behavior was changed. You must use `watch` function to do this. So the below should work.

```js
export default {
  data () {
    isLoading: true
  },
  mounted () {
    this.$watch(
      () => $store.state.mentions,
      () => {
        this.isLoading = false;
      }

      this.$store.commit('setMentions')
    )
  }
}
```

**Comment by xPaw** [comment]
Yeah that's quite lame. Now I have to manually write these $watch statements (keep track of them, and then unwatch in destroyed?).

**Comment by kiaking** [comment]
Well, yeah, the unwatching part is bit of work but watching part isn't that different I guess. Not much we can do as a Vuex side, since this is Vue's behavior change 🙏

**Comment by xPaw** [comment]
Do you have a link to any discussion or rfc on this? I couldn't find anything besides the 1 comment I linked above.

**Comment by kiaking** [comment]
Sorry I couldn't find it either. But there is a statement at Vue 3 docs.

> Component watch option and instance method $watch no longer supports dot-delimited string paths, use a computed function as the parameter instead

https://v3.vuejs.org/guide/migration/introduction.html#breaking
