### ISSUE TITLE
useStore() type definition is missing parameter for storeKey.

### ISSUE THREAD

**Issue by DerAlbertCom** [vuejs/vuex#1807]
### Version
4.0.0-beta.4

### Steps to reproduce
In the Vue4 type definition the useStore function is defined as

https://github.com/vuejs/vuex/blob/83bc26fe55417692f386db9b76634eb58794282e/types/index.d.ts#L48

but in the source you can provide a key, to enable more then one store in the application.

https://github.com/vuejs/vuex/blob/83bc26fe55417692f386db9b76634eb58794282e/src/injectKey.js#L5

### What is expected?
The type definition should match the function

### What is actually happening?
It does not match ;) so only one store can be used with typescript

**Comment by euaaaio** [comment]
PR is already made 🤘🏻

**Comment by kiaking** [comment]
Closing due to the PR is already merged!
