### ISSUE TITLE
vuex mapstate shows only the latest new value

### ISSUE THREAD

**Issue by bitquality** [vuejs/vuex#1813]
### Version
4.0.0-beta.4

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vuex](https://new-issue.vuejs.org/?repo=vuejs/vuex)

### Steps to reproduce
I have a mapstate which i am using to map vuex store changes for a particular variable 'newmessage' state change.following is the code for the same.

				 computed: mapState('myStore1', {
					newMessageReceived: state => state['newmessage'],
				  }),

				  watch: {
					newMessageReceived(newVal, oldValue) {
					  //newValue and oldValue are populated
					}
				  }

I have one component i push three messages as shown below:

				  const message1 = "Object 1 here"
				  const message2 = "Object 2 here"
				  const message3 = "Object 3 here"

				  this.$store.dispatch('myStore1/setNewMessage', message1);
				  this.$store.dispatch('myStore1/setNewMessage', message2);
				  this.$store.dispatch('myStore1/setNewMessage', message3);

In mutations.ts file the set method gets called three times.

				   const mutations = {
					  SET_NEW_MESSAGE(state, payload) {
						const newPayload = Object.assign({}, payload);
						state.newMessage = newPayload;
					  },
					};
					export { mutations };

But i always receive the third newMessage object back in my component where i have mapState used to consume newMessage. watch is called only once in this scenario. Not sure what is causing the issue here.

### What is expected?
I am expecting the watch method to show me all the mutations or updates to the state variable 'newMessage'

### What is actually happening?
mutations is called three times when setNewMessage is called three times. But the watch i have for state variable 'newMEssage' is called only for third message . This is happening when we have three consecutive calls to 'setNewMessage' action. But if i have three consecutive calls to 'setNewMessage' from three different components it works fine or even from single component when there is delay

**Comment by kiaking** [comment]
Please provide a valid reproduction link! 🙏
