### ISSUE TITLE
Move project to typescript (not just add a definition file)

### ISSUE THREAD

**Issue by lil5** [vuejs/vuex#1820]
### What problem does this feature solve?
Any overlooked type errors in the current project

The internet is full of reasons to move to typescript.

### What does the proposed API look like?
Moving all *.js files to *.ts
And adding a tsconfig.json file to build the js files

**Comment by pikax** [comment]
Check [v4 branch](https://github.com/vuejs/vuex/tree/4.0).

**Comment by lil5** [comment]
@pikax A quick look at the src directory in branch shows .js files
https://github.com/vuejs/vuex/tree/4.0/src

**Comment by pikax** [comment]
My mistake.

Renaming the files to `.ts` is not a good solution.

**Comment by lil5** [comment]
@pikax how so?

**Comment by kiaking** [comment]
We're planning to do it in Vuex 5! Currently, just changing Vuex 4's `.js` to `.ts` file will not improve any typings so I believe it's not worth it. Vuex 5 will still take some more time but stay tuned 👍
