### ISSUE TITLE
Getters are re-evaluated on every access

### ISSUE THREAD

**Issue by Fuzzyma** [vuejs/vuex#1823]
### Version
4.0.0-beta.4

### Reproduction link
[https://codesandbox.io/s/hopeful-sanne-kv7r2?file=/src/main.js](https://codesandbox.io/s/hopeful-sanne-kv7r2?file=/src/main.js)

### Steps to reproduce
Open the link and open your console to see "recomputed getter" every second

### What is expected?
"recomputed getter" should print once and never again

### What is actually happening?
It prints every second

---
In vuex 3 getters were cached. Isn't that a thing anymore?

**Comment by mcrapts** [comment]
I am also facing this issue. After migrating to Vuex 4.0.0-beta.4 my getters get re-evaluated everytime they are accessed. This has slowed down my application a lot, as my application logic relies on the fact that getters are cached.

**Comment by mcrapts** [comment]
I am still experiencing this issue. Is it really fixed?

**Comment by cuebit** [comment]
[This](https://github.com/vuejs/vuex/commit/c3a695e10682ab1b7288e72669861c9ca959df76) fix was reverted due to scope issues in Vue. When the issue is resolved there, this fix will be rolled back. 

@kiaking should this issue be reopened and keep the bug label?

**Comment by mcrapts** [comment]
I see, thanks! At least I'm happy to see that it is clear what the issue is.

**Comment by chuski1212** [comment]
Hey! Any news about this? Vue 3.1 has officially released and I'm still experiencing this issue.

**Comment by mcrapts** [comment]
Interested in the follow-up as well. Vue 3 is basically unusable for me with this bug.
