### ISSUE TITLE
registerModule + serverPrefetch + unregisterModule

### ISSUE THREAD

**Issue by Mitch-i** [vuejs/vuex#1829]
### Version
4.0.0-beta.4

### Reproduction link
[https://github.com/Mitch-i/vue-ssr](https://github.com/Mitch-i/vue-ssr)

### Steps to reproduce
Navigate from one to another page.

```js
serverPrefetch () {
    // return the Promise from the action
    // so that the component waits before rendering
    this.$store.registerModule('Locale', Locale);
    return this.getUsers();
},

// Client-side only
// beforeMount() {
//     this.$store.registerModule('Locale', Locale, { preserveState: true });
// },

mounted () {
    alert('bm home');
    this.$store.registerModule('Locale', Locale, { preserveState: true });
    // If we didn't already do it on the server, we fetch the users
    if (!this.users.length) {
        this.getUsers();
    }
},

methods: {
    getUsers () {
        return this.$store.dispatch('getUsers');
    }
},

destroyed() {
    alert('destroyed home');
    this.$store.unregisterModule('Locale');
},
```

Cannot read property 'locale' of undefined

I try different hooks and get different errors.

### What is expected?
can use registered module.

### What is actually happening?

Module is registered after is destroyed on navigation to other page and not reloaded (Cannot read property 'locale' of undefined)in the best situation, now and that not work

**Comment by kiaking** [comment]
Please provide a valid reproduction. You're using Vue 2 and Vuex 3 but this issue seems targeting Vuex 4.
