### ISSUE TITLE
Undeprecate Vuex.createLogger()

### ISSUE THREAD

**Issue by NicolasParada** [vuejs/vuex#183]
I'm using Vuex from a cdn, so I'm not importing it like a module.
I cannot use
```js
import createLogger from 'vuex/logger'
```
and `Vuex.createLogger()` right now throw me an error: **`Unable to get property 'snapshot' of undefined or null reference`**.

But if I copy the code from here (this repo) and paste on my store middlewares, it just works. So why not expose it in the dist files?

**Comment by LinusBorg** [comment]
it's in 1.0.0-rc and 2.0.0-rc versions: http://vuex.vuejs.org/en/plugins.html#builtin-logger-plugin
