### ISSUE TITLE
State changes not being rerendered when updating object

### ISSUE THREAD

**Issue by JanDevDE** [vuejs/vuex#1839]
### Version
3.4.0

### Reproduction link
[https://jsfiddle.net/q32df9tj/45/](https://jsfiddle.net/q32df9tj/45/)

### Steps to reproduce
Overwrite object with new object using state.object = newObject -> No rerender

Overwrite object with state.user = Object.assign({}, user) ->  Should work instead, but doesn't -> That's the issue, why?

Object.assign(state.user, user) <- Works, but should be the same as Object.assign({}, user) because .assign should know which object to assign due to state.user = Object.assign

### What is expected?
state.user = user <- Should rerender, but apparently it doesn't because it's passing the value apparently.

state.user = Object.assign({}, user) <- Should work instead, but doesn't -> That's the issue, why?

Object.assign(state.user, user) <- Works, but should be the same as Object.assign({}, user) because .assign should know which object to assign due to state.user = Object.assign

### What is actually happening?
Only Object.assign({state.user}, user) assigns the value and causes Profile.vue to refresh

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/11694#issuecomment-701930453
