### ISSUE TITLE
Dispatching object

### ISSUE THREAD

**Issue by CthulhuDen** [vuejs/vuex#184]
Documentation says, the whole dispatched object gets sent to the mutation, and so do the release notes for 0.6.2, and says that 

> Note when using the object-style, you should include all arguments as properties on the dispatched object

But in fact only the `payload` field gets passed, and the arguments must be in the payload array, not as some properties. https://github.com/vuejs/vuex/blob/master/src/index.js#L83

**Comment by dddomin3** [comment]
I made a PR to fix the documentation to match the functionality you pointed to here.

**Comment by CthulhuDen** [comment]
On the second thought, it seems even worse: the payload field in the dispatched object is passed as a single argument into mutation (see the code I linked in the first post).

**Comment by LinusBorg** [comment]
> On the second thought, it seems even worse: the payload field in the dispatched object is passed as a single argument into mutation (see the code I linked in the first post).

@CthulhuDen [No. the payload variable will is passed to the mutation using the spread operator](https://github.com/vuejs/vuex/blob/master/src/index.js#L93):

`mutation.forEach(m => m(state, ...payload))`

**Comment by CthulhuDen** [comment]
@LinusBorg But a few line before we see that the payload array will contain only one value (whatever the payload field was)
https://github.com/vuejs/vuex/blob/master/src/index.js#L83

**Comment by LinusBorg** [comment]
Oh, after reading your statement in the comments of the pull request I see what you mean about [[10]] ... odd.

**Comment by CthulhuDen** [comment]
Ok maybe I'm missing something here, please bear with me.

First, you call 

```
store.dispatch({
  type: 'INCREMENT',
  payload: ['firstargument', {second: 'argument'}, 3]
})
```

Then, this (https://github.com/vuejs/vuex/blob/master/src/index.js#L83) happens, so the `payload` is `[['firstargument', {second: 'argument'}, 3]]` (note: this is an array containing array)

So after https://github.com/vuejs/vuex/blob/master/src/index.js#L93 you will have this:

```
mutations: {
  INCREMENT (state, [aString, anObject, aNumber]) {
    state.someString = aString // 'firstargument'
    state.someObject = anObject  // { second: 'argument'}
    state.someNumber = aNumber // 3
  }
}
```
(not that all the payload is in array in second argument)
What am i missing?

**Comment by LinusBorg** [comment]
Yeah I got that right after I finished my comment ... don't really get what's going on there ...

**Comment by LinusBorg** [comment]
Okay, here is my assumption: 
* when not using object syntax, `payload` will be an array because of the spread argument in the function head `(type, ...payload)`
* when using object syntax, Evan intended the payload to be an object, or a single string/number etc. 
* therefore, when object syntax is detected, `payload` is wrapped in an array, so that for both scenarios, line 93/95 will work, as payload is an array either way:

```
mutation(state, ...payload)
```

Which means you were correct - when using object syntax, the content of the `payload:` property will arrive as one argument in the mutation.

**Comment by stealthybox** [comment]
I didn't see the discussion on this issue -- sorry @CthulhuDen.
I think your assumptions are correct @LinusBorg.
That does seem like what Evan intended.

It's a bit of a strange difference, though.
[Here's my thoughts](https://github.com/vuejs/vuex/pull/199#discussion_r65449545).
Ultimately, the difference is kind of hard to work with.

**Comment by yyx990803** [comment]
This turns out to be an incorrect implementation of what the doc described. Fixed and will be out in next release.
