### ISSUE TITLE
On vue-router beforeEach Vuex store lost state after call next()

### ISSUE THREAD

**Issue by phlegx** [vuejs/vuex#1842]
### Version
3.5.1

### Reproduction link
no link at the moment.

### Steps to reproduce
1) In the Vue router function `router.beforeEach` I check (with `console.log`) for a store state (e.g. `store.getters['base/getLocale']`). Output: `de`
2) After the check I call `next()`
3) In the loaded component from the new route I re-check `this.$store.getters['base/getLocale']` and I get `en` that is default locale.

### What is expected?
No Vuex state lost after next() call.

### What is actually happening?
Lost of Vuex state after next() call.

---
It is a related issue to vue-router. But I don't know, if it is a vue-router bug, a Vuex bug or something else.

**Comment by posva** [comment]
https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro

**Comment by uncodable** [comment]
@phlegx Did you find anything on this, i'm running into the same issue now.

**Comment by phlegx** [comment]
@uncodable no sry.

**Comment by uncodable** [comment]
@phlegx If I access the state directly it works; just not with a getter which is weird, as this was working like two weeks ago.

Vuex getter (module):
```ts
const getters = {
  loggedIn: (state: State) => {
    return state.authenticated;
  }
};
```

Vue router:
```ts
router.beforeEach((to, from, next) => {
  // not working (should work):
  const loggedIn = store.getters["authentication/loggedIn"];
  console.log(loggedIn);
  // working:
  const loggedIn = store.state.authentication.loggedIn;
  console.log(loggedIn);
});
```

@posva Can you re-open this issue? The new issue bot just auto closes with things created from that link.

**Comment by cuebit** [comment]
It's impossible to offer assistance without a reproduction. At the beefy least, try to replicate the issue in a barebone app. If you can't reproduce it, there is a side effect in your app that only you can debug. Or provide a repo link and maybe someone can find time to look into it.

**Comment by bekwam** [comment]
Also, what's described here as "working" is not the same as the getter code.

**Comment by cuebit** [comment]
@bekwam it's valid. What makes the state lookup indifferent to the computed getter?

**Comment by cuebit** [comment]
@uncodable is your module namespaced?

**Comment by uncodable** [comment]
Hey,

I did manage to replicate the issue. Might be able to upload tomorrow night when I'm back on my machine. 

I have a namespace, it sets the login via an action, it then commits to a mutator of then which changes the state to true. The example was showing I could access the state directly to get the result of true. However when used in beforeEach on the vue router (next) it cannot access the getter on the next route (login -> do login -> take me to the dashboard as a workflow)

Thanks in advance
