### ISSUE TITLE
Offer types for `getters` on the Store instance

### ISSUE THREAD

**Issue by leerw4** [vuejs/vuex#1843]
### What problem does this feature solve?
The `getters` key of the Store instance has type `any` which is not useful. While type casting can be used, it's just a pain to have to do every single place you would want to reference a getter.

### What does the proposed API look like?
One solution would be to offer a second (optional) generic type of the `Store` type that would default to `any`, and have that value be used for the type of the `getters` key.

```js
export declare class Store<S, G = any> {
  constructor(options: StoreOptions<S>);

  readonly state: S;
  readonly getters: G;

  ...
}
```

I've tested the above solution and it works and should also be backwards compatible.

**Comment by kiaking** [comment]
Thanks for the feedback! I think we should come back to the typings once TS 4.1 is out. It might change quite a bit (in a good way). See #1831 for more details.

**Comment by jouni-kantola** [comment]
For codebases that use Options API it'd be nice to expose type parameters for getters, as it enables getter typings in components. 

Currently, in `vue-shim.d.ts` we can expose the store to components with `typeof`, but that still leaves getters as  `any`.
