### ISSUE TITLE
Property  does not exist on type

### ISSUE THREAD

**Issue by lihaotian0607** [vuejs/vuex#1848]
### Version
4.0.0-beta.4

the console can print, but the compilation fails the check!!!

```ts
<script lang="ts">
import {Vue} from "vue-class-component";
import {useStore} from 'vuex'
import {AppState} from "@/types/state";

export default class Test extends Vue {

  private store = useStore<AppState>();

  public mounted(): void {
    console.log(this.store.state);
    console.log(this.store.state.app.count);
  }
}
</script>
```
![image](https://user-images.githubusercontent.com/32523475/96245306-63b01e00-0fd1-11eb-995d-3c9d4ee87b34.png)

![image](https://user-images.githubusercontent.com/32523475/96245145-36637000-0fd1-11eb-82cb-a7ade8cb831c.png)

**Comment by kiaking** [comment]
Please provide a valid reproduction. And also, it might be an issue with class component? Either way, we need to repro to look into it.
