### ISSUE TITLE
Try root module first, then namespaced module

### ISSUE THREAD

**Issue by goeh** [vuejs/vuex#1849]
### What problem does this feature solve?
We're developing modularized application(s) for our customers with separate Vue projects for each module. Each customer have a custom main application with different sub-applications/modules in package.json. Each sub-application have their own namespaced Vuex store. We want to have a default implementation of some actions in the sub-applications, then be able to override the default action in the main application.

Our current workaround/hack is to try them both:

`this.$store.dispatch('actionName', payload, { root: true }) || this.$store.dispatch('moduleName/actionName', payload)`

That way Vuex will look for the action in root module first, and if not found there it will look in the namespaced module and use that (default) action. It works but in dev mode we get a console error  about module not found if we don't have an action in root.

### What does the proposed API look like?
It would be nice to have an option that tells Vuex to look in root module first (without namespace) and then in local module if the action is not found in root module. I can't come up with a good name for the option. When the option is true Vuex should remove the module name and try to find the actionName in root module. If not found there it should do as normal use the full actionName as specified.

`this.$store.dispatch('moduleName/actionName', payload, { namespaced: false  }`

Another way would be to allow for an array of actions and Vuex would try each action in order.

`this.$store.dispatch(['actionName', 'moduleName/actionName'], payload, { root: true  }`

That would actually be a more flexible solution because I could specify as many action names as I want.

`this.$store.dispatch(['tryThisFirst', 'moduleA/thenThis', 'moduleB/andFinallyThis'], payload, { root: true  }`

Or is there another way to solve this problem? We want a default implementation in imported module, but possible to override action in the main application.

**Comment by kiaking** [comment]
I think this feature is bit too off to be included in the core. I don't think this use case is quite usual.

I think you can create a plugin to do this, by adding something like `dispatchIf` method. By combining `hadModule` method, you can also suppress warning in dev mode. It might look something like this?

```js
const plugin = (store) => {
  // dispatchIf('actionName', ['moduleA', 'moduleB'])
  store.dispatchIf = function (action, modules) {
    for (const module in modules) {
      if (store.hasModule(module)) {
        return store.dispatch(`${module}/${action}`)
      }
    }

    return store.dispatch(action)
  }
}
```

Not sure if the above would work, but I think you'll get the idea.

Maybe someone might benefit from this plugin, but I don't think it should be in the core.

**Comment by goeh** [comment]
Is there a way (will there be a way) to replace the `dispatch` function with our own implementation? Because we don't want to call `dispatchIf` in every component.

**Comment by kiaking** [comment]
No I don't think there's an easy way to do that. But when you extend some feature, I think you shouldn't have the same name. I mean, what if you want to call plain `dispatch` right?

If you're calling only `dispatch`, I think it would be easy to just update all `dispatch` call to `dispatchIf`. Either way, you need to adjust the arguments I think, so you need to rewrite dispatch calls anyway.

**Comment by goeh** [comment]
Ok, thanks. We need to re-think some architecture decisions. But that's good. No worries. Keep up the good work! 👍
