### ISSUE TITLE
Nested modules

### ISSUE THREAD

**Issue by rustunn** [vuejs/vuex#185]
That would be really helpful for huge platform-ish like apps to have possibility to nest modules, not just have modules of the root store #

**Comment by chrisvfritz** [comment]
@rustunn Can you give an example of the architecture you're thinking of? It's already possible to split the initial state, mutations, actions, etc each into many submodules that are then combined into the single store.

**Comment by rustunn** [comment]
@chrisvfritz Sure, let's say a platform from which other "apps" might be launched. In this case I'm either need a multiple stores for platform add each app (which make things quite complicated if there is a deep integration between an app and platform) or I need nested modules

**Comment by simplesmiler** [comment]
Thumbs up for this one. Use case is making reusable "higher order modules" (undo/redo, optimistic updates).

**Comment by mattjneuber** [comment]
I find myself needing something like this as well. Or if it isn't in the cards, some sort of advice for how to go about using Vuex with the structure of my application would be helpful.

It's an SPA. At the highest level is user data and things like notifications, etc. Then there's page-level data. Each page is made up of many components, often with many subcomponents, and many of which need to share data. The goal is to load all data for a particular page at once into the store when navigating to a particular page, and have the subcomponents update with the data they need from there. Would it be better for each page to be a module, and then propagate data and actions within the page via props?

**Comment by chrisvfritz** [comment]
@mattjneuber The solution I use for cases like this is similar to what's done in the JSON API spec. Here's an example of the structure of a blog post from their docs:

``` json
{
  "type": "articles",
  "id": "1",
  "attributes": {
    "title": "JSON API paints my bikeshed!"
  },
  "relationships": {
    "author": {
      "links": {
        "self": "http://example.com/articles/1/relationships/author",
        "related": "http://example.com/articles/1/author"
      },
      "data": { "type": "people", "id": "9" }
    },
    "comments": {
      "links": {
        "self": "http://example.com/articles/1/relationships/comments",
        "related": "http://example.com/articles/1/comments"
      },
      "data": [
        { "type": "comments", "id": "5" },
        { "type": "comments", "id": "12" }
      ]
    }
  },
  "links": {
    "self": "http://example.com/articles/1"
  }
}
```

As you can see, all the relations are kept in a `relationships` property, where we store only what we need in order to fetch more information about that model. Then in getters, you can rehydrate any relationships, so that you still have the convenience of a nested tree structure when reading that data, but behind the scenes, there's still a only a single source of truth for each piece of information.

Does that make sense?
