### ISSUE TITLE
Vue Toggle  Chaining Request Like Cascading

### ISSUE THREAD

**Issue by roborock** [vuejs/vuex#1852]
### What problem does this feature solve?
I have a issue about toggle 

When ı click each plus api generate child data from parent like a cascade dropdown , but ı want to toggle all with a button when i try it my toggle just open two level not effect every levels so

I dont know why its reason

I want to tell how toggle all button works: When i clicked a button first of all first request sending to api then im watching firstdata parameter inside component request sending to api then all data comes from api and filling related variable then i have second state variable for trigging next level. im commit nextlevel status variable true in when request done next component inside watch this variable for request but this is not work properly Im sorry for bad english ı hope i could tell my problem

Who can help me :(

Thanks

### What does the proposed API look like?
.

**Comment by cuebit** [comment]
https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro
