### ISSUE TITLE
A basic workflow question

### ISSUE THREAD

**Issue by Sopamo** [vuejs/vuex#187]
Hi,

I'm currently working on an order management system with vuex. I have this basic workflow:

 * User sees a list of orders
 * User clicks on a list entry and the corresponding item is displayed in a detail view showing more information

I have my store setup and already have a list of all entries. How do I fetch the selected entry from the list? I have my detail view in a subroute and want to fetch the order with the given id in the Details Component.

Now my question: How do I get the entry with id x from the store? I can't use a getter because I can only access store variables there. Would I just have a selectedOrder variable in my store? But then I wouldn't be able to display multiple order details at once. I'd just like to be able to write code that fetches my order from the store and when it doesn't exist it fetches it via ajax. Where would I place that code?

A first idea I'm having is to have a computed property which iterates over the store.orders array and if the item isn't in there it executes a getProductById action. Is there a better solution?

**Comment by LinusBorg** [comment]
The computed property is the right idea to get the corect item from the store.

But in the case that the item isn't there, I would catch that up front: when setting the `selectedItem` value in the store (which I assume you do...), the action should check weither that item exists, and if not, call the API. 

The computed property in the details component then does not have to care about actions and API calls - once the list item is in the store, the computed property is updated and the data can be properly shown in the template.

**Comment by Sopamo** [comment]
Thanks for your explanations and sorry for the wrong place to post my issue. I wasn't aware of forum.vuejs.org.
