### ISSUE TITLE
match getter signature to actions

### ISSUE THREAD

**Issue by yaquawa** [vuejs/vuex#1871]
### Version
v4.0.0-rc.1

The current signature of getter
```ts
type Getter<S, R> = (state: S, getters: any, rootState: R, rootGetters: any) => any;
```

if I want to use `rootState` and `state` only, I have to write the `getters` in the 2nd parameter even if I'll never use it. 
```
getFoo(state, getters, rootState) {
}
```

I think this is better, just like the signature of action handlers.
```
getFoo({state, rootState}) {
}
```

**Comment by kiaking** [comment]
We did had similar issue before (I don't remember where). However, we are keeping this signature in Vuex 4 to keep it compatible with Vuex 3. We're planning to publish Vuex 5 RFC soon so let's discuss it there if we have to 👍
