### ISSUE TITLE
Documentation style bug

### ISSUE THREAD

**Issue by jessuni** [vuejs/vuex#1876]
### Version
4.0.0-rc.1

### Reproduction link
[https://next.vuex.vuejs.org/#what-is-a-state-management-pattern](https://next.vuex.vuejs.org/#what-is-a-state-management-pattern)

### Steps to reproduce
Shrink viewport to less than 959px wide, there's an additional `margin-left` that squeezes the docs to the right and leave a blank block in the center. Same for viewport-width <= 719px, the left padding squeezes the whole docs.

### What is expected?
Normal article layout just like https://vuex.vuejs.org/

### What is actually happening?
Styling bug

**Comment by kiaking** [comment]
Thanks for the report! This was fixed in VitePress 0.7.4 and we just need to update the package. But, I'm planning to release 0.7.5 soon so I'll update as soon as 0.7.5 is out 👍

**Comment by jessuni** [comment]
That would be great. Thanks!

**Comment by kiaking** [comment]
This is fixed 👍
