### ISSUE TITLE
Which version of vuex should I use directly in the browser?

### ISSUE THREAD

**Issue by jaoord** [vuejs/vuex#1877]
### Version
4.0.0-beta.2

### Reproduction link
[https://jsfiddle.net/tda81ybc/](https://jsfiddle.net/tda81ybc/)

### Steps to reproduce
html:
`<script src="https://unpkg.com/vue@3.0.2/dist/vue.global.js"></script>
<script src="https://unpkg.com/vuex@3.5.1/dist/vuex.global.js"></script>
<div id="app">
  <p>{{ message }}</p>
</div>
`

js:
`
const store = new Vuex.Store({
    state: function() {
        return {
            filter: {
                roofType: ''
            }
        }
    }
});

const app = Vue.createApp({
    data: function () {
        return {
           message: 'Hello World'
        }
    },
    methods: {
    }
});

app.use(store);
const mountedApp = app.mount('#app');
`

### What is expected?
no reference to process

### What is actually happening?
reference to process:

Uncaught ReferenceError: process is not defined
    at new Store (vuex.global.js:290)
    at ?editor_console=true:120

---
the naming of the builds is quite confusing. there is for example a vuex.esm-browser.js, a vuex.esm.browser.js file, and cjs and commonjs files.

**Comment by kiaking** [comment]
You need to use Vuex 4 with Vue 3.

```html
<script src="https://unpkg.com/vuex@4.0.0-rc.1/dist/vuex.global.js"></script>
```
