### ISSUE TITLE
memory leak with socket.io and vue devtools 

### ISSUE THREAD

**Issue by weishijun14** [vuejs/vuex#1881]
### Version
vuex 4.0.0-beta.4
vue 3.0.0
socket.io 2.3.1

### Reproduction link

**no links**

### Steps to reproduce
I'm use socket.io , and I have a big Json data, more than 100kb per 3 second,
```javascript
 socket.on('someEvent', function(data) {
       // data almost 100kb -- 150kb
       _this.$store.commit('someMutationsName', data);
  })

```

### What is expected?
Chrome momery keep normal.

### What is actually happening?
Chrome momery usage keep increasing.

---
When I **comment this code** :
```javascript
this._subscribers
    .slice() // shallow copy to prevent iterator invalidation if subscriber synchronously calls unsubscribe
    .forEach(function (sub) { return sub(mutation, this$1.state); });
```

or **uninstall Chrome vue devtool**  which I use this version:

6.0.0 beta 2

It's back to normal.

**Comment by kiaking** [comment]
Oh yeah it makes sense. DevTools records all of the mutations, so you get 100kb states per 3 sec. You can disable devtools via `devtools` option. I think the best way for you is to limit how much data you fetch in your dev environment. It should work fin in production mode 👍 

```js
new Vuex.Store({
  devtools: false
})
```
