### ISSUE TITLE
how to write vuex modules unit test?

### ISSUE THREAD

**Issue by MillerRen** [vuejs/vuex#189]
like this:
```export default new Vuex.Store({
  modules: {
    demo,
    logs
  },
  strict: debug
})```

How how to get the mutations? The mutations field is missing.

**Comment by stealthybox** [comment]
Evan has a page on this in the Vuex docs: http://vuex.vuejs.org/en/testing.html

Your store should have the mutations field exported with it. 
I'm not sure why your code is missing that.

In the future, questions like this probably belong on http://forum.vuejs.org/ or https://gitter.im/vuejs/vue.
Hope this helps you test your code!

**Comment by LinusBorg** [comment]
Hello @MillerRen , 

thank you for your interest in this project.

However, Github Issues are reserved for bug reports and feature requests. 

For support, please refer to our community forum at forum.vuejs.org
