### ISSUE TITLE
Vuex fails to update state object with new object

### ISSUE THREAD

**Issue by millansingh** [vuejs/vuex#1898]
### Version
3.5.1

### Reproduction link
[https://codepen.io/millansingh/pen/dypOBjb](https://codepen.io/millansingh/pen/dypOBjb)

### Steps to reproduce
Just hit the button to run the mutation, but nothing will change which is the issue.

### What is expected?
The mutation should change the object in store, making the "output" div show 3 instead of 1.

### What is actually happening?
Nothing changes.

---
In my personal project, the state itself is unchanged, rather than a reactivity issue. I couldn't open the Vue dev tools on Codepen to check this, but I think the same thing is happening. I would expect the object in the state to be replaced with the new object, but instead it doesn't change. I've tried the Object.assign method, object destructuring, and a simple stateObj = newObj type statement. All do nothing.

Note that I can effectively get around this by looping through Object.keys of the state object and replacing them with the new object keys, but this should be possible by just replacing the object instead of using my workaround.

**Comment by cuebit** [comment]
The repro you've provided isn't setup correctly.

1. Remove the imports (you're already loading Vue + Vuex in pen settings)
2. Use the correct casing i.e. `Vue`/`Vuex`, not `vue`/`vuex`
3. `newObj` should also be spread into the new assignment i.e. `state.obj = { ...state.obj, ...newObj }`

With the above said and done, here's a working example of your pen: https://codepen.io/cuebit/pen/gOwgOWa

**Comment by millansingh** [comment]
Thanks for that. First time using Codepen, my bad.

However, the method you're using does not work for me in my local project. That said, upon looking at it again, I think the issue may have something to do with the fact that the object in question in my local project is part of an array. It's actually nested a few layers deep in several objects/arrays. I'm using a function to find it based on some keys and return the reference to the object itself, and then I'm setting that to a new object using your method above. And now I'm figuring that because this is an object within an array, it won't actually update it like that, whereas when I was just replacing keys on it, it works fine.

I think that given how my code is structured now, I'd rather just use the Object.keys work-around than re-factor to make it work the way I originally hoped. Thanks for your help!
