### ISSUE TITLE
The test case fails to pass the test in the local environment.

### ISSUE THREAD

**Issue by Alanscut** [vuejs/vuex#1899]
### Version
4.0.0-rc.2

### Reproduction link
[https://github.com/vuejs/vuex/tree/v4.0.0-rc.2](https://github.com/vuejs/vuex/tree/v4.0.0-rc.2)

### Steps to reproduce
1. `npm install` 
2. `npm run test:e2e`  or   `yarn test:e2e`

### What is expected?
All test cases pass in local environment.

### What is actually happening?
test case todomvc failed

---
ENV: <br >Ubuntu 18.04.5 LTS<br >
          node: v12.20.0<br >
          npm: v6.14.8<br >
          yarn: 1.22.10<br >

it's show failed by this:
```shell
FAIL test/e2e/todomvc.spec.js
          e2e/todomvc > todomvc app
          expect(received).toBe(expected) //  Object.is equality

          Expect: "edited!"
          Received: "test"

               123 |            await click('footer') //  blur
               124 |            expect(await count(' .todo.editing')).toBe(0)
               125 |            expect(await text('.todo:nth-child(1) label')).toBe('edited')
```

**Comment by kiaking** [comment]
Can't reproduce in my environment. Could you test using `yarn` instead of `npm` and see how it goes?

**Comment by Alanscut** [comment]
@kiaking ubuntu is not always failed, please reproduce it in `Windows`, whether using `npm` or `yarn`, the test result is same:
![image](https://user-images.githubusercontent.com/21104054/103595851-7b93a000-4f37-11eb-9411-3322c4de8a27.png)

**Comment by kiaking** [comment]
Hah, OK. Hmmm... might be puppeteer limitation...? Could you test updating puppeteer to the latest version and see if anything changes? I don't have windows env so not so easy for me to debug this 😢
