### ISSUE TITLE
Vuex - check if data really can be stored in localstorage

### ISSUE THREAD

**Issue by tobiberlin** [vuejs/vuex#1900]
### What problem does this feature solve?
We run into the following issue: 

 - An app built with Vue/ vuex works fine
 - The issue appears when the app is embedded into another third party page with an iframe
 - when the user configured the browser to reject third party cookies the browser also rejects third parties (our app) from saving data in localstorage
 - this leads to an error in browser's console and the app is not rendered, the iframe stays empty

Is there a way to check if localstorage can be used by the app? It would be helpful to avoid vuex to try to use the localstorage before really saving anything to it to avoid such problems.

### What does the proposed API look like?
No idea

**Comment by cuebit** [comment]
Googling this yields copious amounts of solutions. [Here's one](https://stackoverflow.com/q/16427636/2150268) of many.

This is something outside the scope of Vue/Vuex and something a plugin would likely resolve.

**Comment by kiaking** [comment]
Yap, this is out of scope for Vuex. We can't cover all of the plugins or libs out there if those are compatible with Vuex or not 👍
