### ISSUE TITLE
tree shaking not work because of vuex.mjs

### ISSUE THREAD

**Issue by fangbinwei** [vuejs/vuex#1906]
### Version
4.0.0-rc.2

### Reproduction link
[https://github.com/fangbinwei/vuex-next-issue](https://github.com/fangbinwei/vuex-next-issue)

### Steps to reproduce
1. yarn build
2. search `prev state` in dist/main.js to validate if bundle contains `createLogger`

https://github.com/vuejs/vuex/blob/bb7885700d7bd7afd4d12fc8be7f5b3eeaa58b0e/src/plugins/logger.js#L33

**main.js**
```js
// tree shaking not work because of vuex.mjs
import {Store} from 'vuex'

console.log(Store)
```
output(external vue)
```bash
[webpack-cli] Compilation finished
asset main.js 12.1 KiB [emitted] [minimized] (name: main) 2 related assets
orphan modules 400 bytes [orphan] 1 module
runtime modules 221 bytes 1 module
built modules 35.6 KiB [built]
  ./src/index.js   1 modules 567 bytes [built] [code generated]
  ./node_modules/vuex/dist/vuex.cjs.js 35 KiB [built] [code generated]
  external "Vue" 42 bytes [built] [code generated]
webpack 5.11.0 compiled successfully in 713 ms
✨  Done in 3.59s.
```

**main.js**
```js
// tree shaking work
import {Store} from 'vuex/dist/vuex.esm-bundler.js'

console.log(Store)
```
output(external vue)

```bash
[webpack-cli] Compilation finished
asset main.js 9.8 KiB [emitted] [minimized] (name: main) 2 related assets
orphan modules 35.1 KiB [orphan] 2 modules
runtime modules 221 bytes 1 module
./src/index.js   2 modules 35.3 KiB [not cacheable] [built] [code generated]
webpack 5.11.0 compiled successfully in 797 ms
✨  Done in 2.47s.
```

### What is expected?
 drop `createLogger` from the bundle

### What is actually happening?
bundle contains `createLogger`

---
I think tree shaking not work because of  two reasons, (I know vuex.mjs wrap vuex.cjs.js because of some rules in node)

1. vuex.mjs use `default import`
2. vuex.mjs import CommonJS(vuex.cjs.js) 

Maybe we can do like below
```diff
  "exports": {
    ".": {
+      "module": "./dist/vuex.esm-bundler.js",
      "require": "./dist/vuex.cjs.js",
      "import": "./dist/vuex.mjs"
    },
    "./": "./"
  },
```

nodejs don't support `module` in `exports`, so it can execute `dist/vuex.mjs`

[webpack support `module` in `exports`](https://webpack.js.org/guides/package-exports/#conditions), it will use `dist/vuex.esm-bundler.js` first if it is valid, since the order of `"module"` is in front of the `"import"`

### Moreover
since `vuex.mjs` wrap CommonJS which contains `require('vue')` and it let vuex doesn't compatiable with [webpack externals script](https://webpack.js.org/configuration/externals/#script), check [this issue](https://github.com/vuejs/vue-cli/issues/6149). [Reproduction link](https://github.com/fangbinwei/vuex-next-issue-external-script)

**Comment by kiaking** [comment]
The fixed is merged. This should be fixed in new release!
