### ISSUE TITLE
ShoppingCart.vue : incorrect usage of :key attribute

### ISSUE THREAD

**Issue by jguillod** [vuejs/vuex#1918]
### What problem does this feature solve?
This following correction will help developers better understand your example and eliminates confusion.

### What does the proposed API look like?
Line 6 to 8 of `ShoppingCart.vue` file is :

```
      <li
        v-for="product in products"
        :key="product.id">
```

but since `product.id` is undefined in result of computed getters `cartProducts` the `:key` attribute should be dropped. Code should simply be written:

```
      <li
        v-for="product in products">
```

**Comment by Alanscut** [comment]
if remove the `key`, and enable the eslint check, it will report error like this:
**Elements in iteration expect to have 'v-bind:key' directives.eslint-plugin-vue**

**Comment by kiaking** [comment]
Oh you're right, but in this case we should return `id` from `cartProducts`. It is always good to have `:key` on `v-for` element 👍
