### ISSUE TITLE
Documentation: error in the example 'Testing Actions'

### ISSUE THREAD

**Issue by lazystone** [vuejs/vuex#192]
Disclaimer: I'm quite a newbie in the javascript world and especially in vue/vuex.

I believe [this page](http://vuex.vuejs.org/en/testing.html) has a mistake in the example:
```javascript
 // check if no mutations should have been dispatched
  if (count === 0) {
    expect(expectedMutations.length).to.equal(0)
    done()
  }
}
```

If I understand it correctly this always should fail in case when you have async functions and expectedMutations.length>0 - there is a big chance that count is not updated at the moment of processing ```if (count === 0)``` condition.

Probably it should be something like
```javascript
  // check if no mutations should have been dispatched
  if (expectedMutations.length === 0) {
    expect(count).to.equal(0);
    done();
  }
```

**Comment by yyx990803** [comment]
That's true - feel free to submit a PR to fix it!

**Comment by yyx990803** [comment]
Thanks for the PR!
