### ISSUE TITLE
Expose storeKey for unit test mocking when using useStore

### ISSUE THREAD

**Issue by jlgoff3** [vuejs/vuex#1921]
### What problem does this feature solve?
When unit testing Composition API style components, the developer may want to mock the Vuex store for testing purposes. However, due to the Vue instance not being available at setup() time, the useStore method is used in place of this.$store. This requires the developer to inject their Vuex mock, rather than using the traditional instance mocking option of the vue-test-utils mount function. Provide/inject requires a key, which, unlike $store, is not visible to the end user.

### What does the proposed API look like?
Export the default storeKey. For devs who use the default storeKey rather than providing a custom key on plugin installation, this will provide a more durable testing solution. While the key is currently the string "store", this could change in the future, leaving end users with unexpected failing tests. Vue-router has similarly exported their provide keys. I'm willing to create a PR for this.

**Comment by kiaking** [comment]
Ah good point! I though we already did expose the `storeKey` but yeah it's hidden. I think we should expose it.

**Comment by jlgoff3** [comment]
Awesome - is this something I should put in a PR for?

**Comment by kiaking** [comment]
Sorry for the late response yes! I'll just expose them right a way 👍

**Comment by kiaking** [comment]
Fixed by 8b077e8
