### ISSUE TITLE
Is possible to intercept the dispatcher?

### ISSUE THREAD

**Issue by djom202** [vuejs/vuex#1935]
In my project currently I have around of 400 dispatch and I saw that the big part of that implementation has the same code: 

```
this.$store.dispatch('action', this.payload).catch(e => {
   console.log(e)
    this.$notify.error(e.message)
})
```

So in order to reduce that code I'd like to intercept the dispatcher to throw the error once, and remove the extra code but I'm not sure if it's possible to do that. So just let me know if it's possible or there any other way to do it.

Thanks in advance.

**Comment by cuebit** [comment]
Create a helper function, for example:

```js
export const dispatch = (component, action, payload) => {
  return component.$store.dispatch(action, payload || component.payload).catch(e => {
    component.$notify.error(e.message)
  })
}

dispatch(this, 'action') // w/o payload
dispatch(this, 'action', { ... }) // w/ payload
```

Or add a prototype method, for example:

```js
Vue.prototype.$dispatch = function(action, payload) {
  return this.$store.dispatch(action, payload || this.payload).catch(e => {
    this.$notify.error(e.message)
  })
}

this.$dispatch('action') // w/o payload
this.$dispatch('action', { ... }) // w/ payload
```

**Comment by djom202** [comment]
@cuebit Thanks for you answer. I'd like to implement the prototype function, but where should I put it? into the main.js or in the index store?

**Comment by cuebit** [comment]
> @cuebit where should I put it? into the main.js or in the index store?

In your entry file (main.js) before you instantiate Vue (i.e. `new Vue({})`)
