### ISSUE TITLE
methods object in component disables all inherited Vuex actions

### ISSUE THREAD

**Issue by jakobrosenberg** [vuejs/vuex#194]
```
router.start({
  store,
  vuex: {actions},
  components: {App}
}, '#app')
```

The above works perfectly fine in all routes/components. But if I add ``methods: {}``  in a component, all its inherited actions from Vuex disappears .

This works
```
export default {
  created() {
    this.myVuexAction()
  }
}
```

This doesn't work
```
export default {
  methods: {} // <-- removes inherited Vuex actions
  created() {
    this.myVuexAction()
  }
}
```

**Comment by simplesmiler** [comment]
Hi. What you are describing should not work in the first place, because components do not inherit any assets (including methods and actions) from parents.

Please provide a repro where assets are inherited, so that we can fix it :grinning: 
Also never forget to specify the Vue and Vuex versions.

**Comment by jakobrosenberg** [comment]
Vue 1.2.4 and Vuex 0.6.3

I've been unable to reproduce the inheritance outside my project.

**Comment by simplesmiler** [comment]
If you want actions to be available in the component, make sure to declare them in the component.

If you want to avoid writing the same thing over and over, then you can use mixins. But you still have to declare used mixins, so it's not worth it if you import a single object with all the actions.

You can also write a global mixin, but do this with caution: https://vuejs.org/guide/mixins.html#Global-Mixin

**Comment by jakobrosenberg** [comment]
Thanks simplesmiler,  would it be bad practice to use the actions through ``this.$root.myAction()``?

**Comment by simplesmiler** [comment]
I would not personally recommend it for a big project, but if it works for you -- that fine.

**Comment by jakobrosenberg** [comment]
Thanks again. I'll close this issue.
