### ISSUE TITLE
Vuex 4 devtools integration

### ISSUE THREAD

**Issue by Akryum** [vuejs/vuex#1942]
The API for Vue Devtools 6.x is now documented [here](https://devtools.vuejs.org/plugin/api-reference.html).

I open this issue so we can keep track of the Vuex 4 integration.

- [x] Custom inspector with the module tree on the left & module state/getters on the right
- [x] Timeline layer: mutations
- [x] Inspect state after a mutation
- [x] Timeline layer: actions (with event groups)

**Comment by sgallino** [comment]
Thank you @Akryum for answering! :smile:

**Comment by wwwhickup** [comment]
How to resolve vuex problem in devtool

**Comment by marcelruiter** [comment]
It is very annoying that vue3 is out for a long period now and still other components not working well like Vuex. Is it so very hard to implement this? I think that there are a lot of developers who love to see it working asap. Please take priority of this issue.

**Comment by geoidesic** [comment]
Yes, your majesty. At once, your majesty!

**Comment by dhruvkb** [comment]
In the meantime, while this has not been merged and rolled out, is there a workaround we can use to debug the Vuex store?

**Comment by Anubarak** [comment]
@dhruvkb you could fork the repo, merge the pull request and use your forked vuex version.

**Comment by davidrunger** [comment]
@dhruvkb : You can use `createLogger` to debug Vuex. There's an example of how to use `createLogger` [here](https://github.com/vuejs/vuex/blob/4.0/examples/composition/chat/store/index.js).

**Comment by erdemefe07** [comment]
https://github.com/erdemefe07/vuex4-devtools-support

**Comment by Akryum** [comment]
Released in 4.0.1

**Comment by MrMitch** [comment]
Thank you @Akryum for your dedication on this !
