### ISSUE TITLE
Implementing store typings in vuex3 with vue2

### ISSUE THREAD

**Issue by tbhaxor** [vuejs/vuex#1947]
### What problem does this feature solve?
This is moreover a question rather than feature.

How do I implement type intellisense in vuex3 with vue2? If there is no augmentation feature like vuex 4, Then could we add in vuex3 also?

### What does the proposed API look like?
N/A

**Comment by tbhaxor** [comment]
Any updates on this?

**Comment by meiliujun** [comment]
Won't you encounter the problem of finding code with IntelliSense when using commit dispatch in vuex?
