### ISSUE TITLE
State can be mutated outside the Store and without call mutation

### ISSUE THREAD

**Issue by maxxdev** [vuejs/vuex#1950]
### Version
3.6.2

### Reproduction link
[https://jsfiddle.net/maksim_dev/jsgkhL83/3/](https://jsfiddle.net/maksim_dev/jsgkhL83/3/)

### Steps to reproduce
Click to the Trigger button

### What is expected?
count = 1 

### What is actually happening?
- count encreases
- getter returns mutated state

**Comment by cuebit** [comment]
State can be mutated when strict mode is disabled. In your example, you're using a distributed bundle which eliminates any assertions. Therefore errors will not be thrown preventing you from mutating the state outside mutations, as it would if it was enabled.

**Comment by maxxdev** [comment]
But mutation happens even if we clone array by spread `const stuff = [...this.$store.getters.stuff]`
