### ISSUE TITLE
{root:true} 的作用是什么？

### ISSUE THREAD

**Issue by ZhouZiXuan-imb** [vuejs/vuex#1961]
官网上介绍的commit调用放的时候 options里可以有{root:true}，没看懂是什么意思，请问能详细描述一下 {root:true} 的作用吗？

**Comment by Alanscut** [comment]
Please see the follow unit tests:
https://github.com/vuejs/vuex/blob/96a265a345c76ec7d0f81a115aef74b7eda89452/test/unit/modules.spec.js#L486-L527

when calling `commit` or `dispatch` with option `{root: true}`, indicating that you can access the mutations and actions defined **`outside the module`**.

```js
                dispatch('foo')  // a/foo, foo in module a, line 503
                expect(moduleActionSpy).toHaveBeenCalledTimes(1)
                dispatch('foo', null, { root: true })  // foo, in root store, line 495
                expect(rootActionSpy).toHaveBeenCalledTimes(1)
```
