### ISSUE TITLE
Can't use `this`  with helpers function

### ISSUE THREAD

**Issue by ThomasKientz** [vuejs/vuex#1968]
### Version
3.6.2

### Reproduction link
[https://codesandbox.io/s/aged-feather-stzbi?file=/src/App.vue](https://codesandbox.io/s/aged-feather-stzbi?file=/src/App.vue)

### Steps to reproduce
Use `this` inside of parameters in vuex helpers 

```
computed: {
    ...mapGetters('page/'  +  this.$route.params.id, ['foo']),
 }
``` 

### What is expected?
The map getters to map to the submodule "page/{id}"

### What is actually happening?
This throw en error :

> Cannot read property '$route' of undefined

### Some context

I am using <keep-alive/> to store multiple "pages" in instance. Each page is triggered by the router. So when the route change, current page goes to sleep, and the one with the proper id goes awake.
Each page registers its own vuex "page" module.

Today I am doing
```
// page.vue

computed: {
  foo() {
      return this.$store.state.page[this.$router.route.params.id].foo
    },
}
```
But it's verbose. And I don't need to react on `this.$router.route.params.id` as each page has its own module.

**Comment by Alanscut** [comment]
`computed` is initiated before `beforeCreate` lifecycle,  so `mapGetters` function will execute before `beforeCreate`, 
However, at this moment `this.module` or `this.$router` is not initialized completely and is `undefined`. 

So the verbose way maybe the better choice.

**Comment by ThomasKientz** [comment]
@Alanscut thanks for the explanation. Is it documented somewhere ? I don't see it on the [Vue's official Lifecycle Diagram](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram)

**Comment by cuebit** [comment]
@ThomasKientz this has nothing to do with lifecycle operations and computed properties. In your case it’s simply the incorrect usage of `this` keyword. 

Using `this` in your second example is more relevant to context, not verbosity, and is the correct and recommend usage.
