### ISSUE TITLE
__VUE_PROD_DEVTOOLS__ is not defined When SSR with prod mode

### ISSUE THREAD

**Issue by CokeMine** [vuejs/vuex#1991]
### Version
4.0.1

### Reproduction link
[https://github.com/cokemine/vuex-reproduce](https://github.com/cokemine/vuex-reproduce)

### Steps to reproduce
clone the repo.
```
yarn
yarn build
yarn start
```

### What is expected?
prod mode works well like dev mode.

4.0.0 works normal

### What is actually happening?
ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined

 at Store.install (E:\vuex-reproduce\node_modules\vuex\dist\vuex.cjs.js:911:50)

**Comment by ysj151215** [comment]
I met this issue too. 
My current solution is changing Vuex dependency version from `"vuex": "^4.0.1"` to `"vuex": "4.0.0"`.

**Comment by CokeMine** [comment]
> I met this issue too.
> My current solution is changing Vuex dependency version from `"vuex": "^4.0.1"` to `"vuex": "4.0.0"`.

Yes. 4.0.0 can work.
It because 4.0.1 added setup devtools integration, #1949.
As I mentioned in the PR, it seems that https://github.com/vuejs/vuex/blob/4.0/rollup.config.js#L64 is not correct

**Comment by kiaking** [comment]
Fixed by #1992 🎉

**Comment by loremru** [comment]
problem still exist, 4.0.0 is ok

**Comment by casadelaweb** [comment]
What bundler do your project use?

If it's webpack, try adding this into your webpack.config.ts / webpack.config.js

```
// import webpack
const webpack = require('webpack')
// OR import webpack from 'webpack' if the project supports ES Modules

// then add plugin to your configuration
plugins: [
  'your plugins ...',
  new webpack.DefinePlugin({ __VUE_PROD_DEVTOOLS__: 'false', }),
],
```
