### ISSUE TITLE
Coffee-/ plain JavaScript?

### ISSUE THREAD

**Issue by dspangenberg** [vuejs/vuex#20]
Could you please give an example in Coffeescript or plain JavaScript? Thanks!

**Comment by yyx990803** [comment]
It is plain JavaScript, just using the latest syntax. It would probably take less time for you to just search for a quick ES2015 tutorial/video than for me to rewrite the examples.

**Comment by dspangenberg** [comment]
With plain JS I've meant something without the ES6 stuff (imports etc.). But it was not intended to steal your rare time. I've searched and traid for hours without success, otherwise I havn't asked here. Sorry for bothering you!

**Comment by skyrpex** [comment]
You could transpile it using babel website in order to see the equivalent in ES5 (https://babeljs.io/repl/)

**Comment by dspangenberg** [comment]
Thanks for the advice. But I've tried it yesterday and the transpiled code is a mess. Finally I get Vuex running in coffeescript. Only the store/index.js from the cart example is still JS.

**Comment by FranzSkuffka** [comment]
@dspangenberg do you have a public repository of vuex in coffeescript ?

**Comment by kticka** [comment]
Does anyone knows how to implement namespacing for getters/actions in coffeescript?

**Comment by mshahbazi** [comment]
@kticka I have the same issue with coffeescript+vuex. wondering if you have came up with a solution.

**Comment by LinusBorg** [comment]
What exactly is the problem with namespaces and coffeescript?

**Comment by mshahbazi** [comment]
in `computed` section, I cannot map more than once. See this:
```
computed:
  Vuex.mapState 'ns1', ['data1'],
  Vuex.mapGetters 'ns2', ['data2']
```
Actually I cannot say it is a namespace issue, since putting `data1` and `data2` in `root` does not work as well:
```
computed:
  Vuex.mapState ['data1'],
  Vuex.mapGetters ['data2'] <this raises error>
```
I came up with "the splats syntax is not mature in coffeescript yet".

**Comment by LinusBorg** [comment]
Oh, so the problem is that coffeecript doesn't support/ have a object rest spread operator.

Seems there's a PR open for this, but not merged: https://github.com/jashkenas/coffeescript/pull/4473

You will have to use an equivalent of Object.assign() (no idea how to write that in CS):
```javascript
computed: Object.assign(
Vuex.mapState ['data1', 'data2'],
{
  // normal computed props go here...
})
```

**Comment by mshahbazi** [comment]
Thank you @LinusBorg. It works. Just wondering if there is any cleaner way.
