### ISSUE TITLE
ts dispatch and commit  open type

### ISSUE THREAD

**Issue by uinio** [vuejs/vuex#2007]
### Version
4.0.2
easy to use template literal types
https://github.com/vuejs/vuex/blob/4.0/types/index.d.ts#L22-L23
```ts
dispatch<T = string>(type: T, payload?: any, options?: CommitOptions): void;

commit<T = string>(type: T, payload?: any, options?: CommitOptions): void;
```

**Comment by cuebit** [comment]
Thanks for opening this issue. However, I don’t follow, where are the template literal types demonstrated? 

If this is a feature request or a bug report, please fill out the necessary fields through the [Issue Helper](https://new-issue.vuejs.org/) to get appropriate assistance.
