### ISSUE TITLE
Not able to get access to global variable for Vue 3

### ISSUE THREAD

**Issue by darkman97i** [vuejs/vuex#2008]
### Version
4.0.2

### Reproduction link
[https://filetransfer.io/data-package/YpufVgC3#link](https://filetransfer.io/data-package/YpufVgC3#link)

### Steps to reproduce
* In the project I have shared a README.md where I'm trying to explain the issue.
* Not clear for me if it is a bug or wrong configuration from my side. I only get working in half times ( maybe is something with hooks? )

Thanks for your time.

### What is expected?
standard way to access a global variable from vuex

### What is actually happening?
Not able to access a global variable from vuex 4.0.2 with vue 3.x. Not found sample or documentation to get working with vue 3.x

---
* I have other projects working with Vue 2 and I succeed get working but with vuex version 4.x and Vue 3 I do not succeed to get working in all cases.
* If you share some documentation section where explain how doing it, will be perfect, because I do not succeed on find it and I think this should be a standard feature.

**Comment by cuebit** [comment]
Thanks for opening an issue. 

We don’t accept issues with downloadable links. Could you please create a new issue and provide a reproduction on CodePen, CodeSandbox or a GitHub repo?

Thanks!
