### ISSUE TITLE
createStore with key get error after vite hot updated

### ISSUE THREAD

**Issue by qiuyaofan** [vuejs/vuex#2019]
### Version
4.0.1

### Steps to reproduce
main.js

```
// main.ts
import { createApp } from 'vue'
import { store, key } from './store'

const app = createApp({ ... })

// 传入 injection key
app.use(store, key)

app.mount('#app')
```

store.js

```
import { InjectionKey } from 'vue'
import { createStore, useStore as baseUserStore, Store } from 'vuex';

// 为 store state 声明类型
export interface State {
  count: number
}

// 定义 injection key
export const key: InjectionKey<Store<State>> = Symbol('admin-store')

const store = createStore<State>({
  state: {
    count: 0
  }
})

export default store;

export function useStore<T = State>(): any {
    return baseUserStore<T>(key);
}
```

index.vue

```
import { useStore } from 'vuex'

export default {
  setup () {
    const store = useStore() //  undefined

  }
}
```

### What is expected?
when I change index.vue and save, vite finish hot update can correct to get useStore() in setup function

### What is actually happening?
when I change index.vue and save, vite finish hot update
useStore() return undefined, and warnning injection "Symbol(admin-store)" not found

---
but I remove key，it‘s work fine.

**Comment by web-zhangbo** [comment]
in *.vue use import { useStore } form 'xxx/store.js'

**Comment by lulu-lei** [comment]
I had the same problem.

**Comment by Alanscut** [comment]
@qiuyaofan you just need import `key` from `store.js` and pass the `key` to `useStore`:

```js
// index.vue
import { useStore } from 'vuex'
import { key } from './store'  // import key from store.js

export default {
  setup () {
    const store = useStore(key) //  pass the imported key to useStore

  }
}
```

**Comment by kiaking** [comment]
Yap, this is either https://github.com/vuejs/vuex/issues/2019#issuecomment-876046730 or https://github.com/vuejs/vuex/issues/2019#issuecomment-881809833.

Feel free to open another issue if there's anything 👍

**Comment by qiuyaofan** [comment]
@kiaking 
I use the method in the official document，because Having to import InjectionKey and passing it to useStore everywhere it's used can quickly become a repetitive task;I want to aviod it
https://next.vuex.vuejs.org/guide/typescript-support.html#typing-usestore-composition-function

**Comment by kiaking** [comment]
Can't you use [Simplifying useStore usage](https://next.vuex.vuejs.org/guide/typescript-support.html#simplifying-usestore-usage)?

**Comment by AustinQin** [comment]
I have the same problem.

**Comment by fxjs** [comment]
I had the same problem, is there a final solution? thanks.
@qiuyaofan

**Comment by normanfan** [comment]
``` TS
export const key: InjectionKey<Store<State>> = Symbol('admin-store')
```

can you fix it by   taking   `Symbol` to `Symbol.for` ?

**Comment by PolanZ** [comment]
same problem at component hot updated time.

**Comment by github-weibo** [comment]
临时解决办法
```ts
// 定义 injection key
export const storeKey: InjectionKey<Store<State>> = '__app_store_key__' as any
```

**Comment by Fleeck** [comment]
> ```ts
> export const key: InjectionKey<Store<State>> = Symbol('admin-store')
> ```
> 
> can you fix it by taking `Symbol` to `Symbol.for` ?

This! Thanks @normanfan

**Comment by AustinQin** [comment]
> ```ts
> export const key: InjectionKey<Store<State>> = Symbol('admin-store')
> ```
> 
> can you fix it by taking `Symbol` to `Symbol.for` ?

This worked for me! Thanks

**Comment by fxjs** [comment]
> 



> 

原因：我是在store模块里引用了vue-router导致的，去掉就好了。

**Comment by kshitijsubedi** [comment]
> ```ts
> export const key: InjectionKey<Store<State>> = Symbol('admin-store')
> ```
> 
> can you fix it by taking `Symbol` to `Symbol.for` ?

Works for me by changing Symbol('..') to Symbol.for('..')

**Comment by Ribeiro-Tiago** [comment]
I'm also running into this issue, changing `Symbol` to `Symbol.for` doesn't work for me, but using a string instead as suggested in https://github.com/vuejs/vuex/issues/2019#issuecomment-1063710001 does

"vue": "^3.4.21",
"vuex": "^4.1.0",
"vite": "^5.1.5",


```
plugins/store/index.ts

interface StoreState { 
  ..
} 
export const storeKey: InjectionKey<Store<StoreState>> = Symbol();

export const store = createStore<StoreState>({ ... })
```

store registration 

```
import { store, storeKey } from "./store";

... 

app
    .use(store, storeKey)
```

my composable 

```
composables/store.ts
import { useStore as baseUseStore } from "vuex";

import { storeKey } from "@/plugins/store";

// define your own `useStore` composition function
export const useStore = () => baseUseStore(storeKey);
```

```
components with composition api

import { useStore } from "@/composables/store";

const $store = useStore();
```

first render works well and dandy, hot reload breaks it. 

Also happens with my axios configuration, where the axios instance i export to use every is suddenly undefined

**Comment by weier910** [comment]
你的邮件我已收到！
