### ISSUE TITLE
InBuild persistance

### ISSUE THREAD

**Issue by derHodrig** [vuejs/vuex#2029]
### What problem does this feature solve?
Hello, the common problem is, vuex states are not persistent. So we rely on other third-party libraries. To bring us a single source of truth, can we just get inbuilt persistence? Even the Vue Devtools has problems with third party persistence as stated out here https://github.com/vuejs/devtools/issues/1456#issuecomment-879155842

### What does the proposed API look like?
At least the vuex should stored inside a cookie. SSR should be supported too.

**Comment by LinusBorg** [comment]
https://github.com/vuejs/rfcs

**Comment by JunjieLl** [comment]
也许您可以使用插件，比如这个https://github.com/robinvdvleuten/vuex-persistedstate
同时为更多插件和工具，您可以查看https://github.com/vuejs/awesome-vue#persistence

**Comment by JunjieLl** [comment]
Maybe you can use a plugin like this: https://github.com/robinvdvleuten/vuex-persistedstate
Also for more plugins and tools, you can check out: https://github.com/vuejs/awesome-vue#persistence
