### ISSUE TITLE
vuex4当中已经不需要严格模式了！直接把store.state变成readonly就行了

### ISSUE THREAD

**Issue by masx200** [vuejs/vuex#2039]
### What problem does this feature solve?
我认为vuex4当中已经不需要严格模式了！直接把实例属性store的get state变成readonly(state)就行了

I think strict mode is no longer needed in vuex4!  Just change the get state of the instance attribute store to readonly(state)

https://github.com/vuejs/vuex/blob/4.0/docs/zh/guide/strict.md

### What does the proposed API look like?

https://github.com/vuejs/vuex/blob/9bd64911eb17bd9d705acb7e1d55a90000bac9c9/src/store.js#L85

```js

import {readonly}from "@vue/reactivity"
export class Store {
get state () {
    return readonly(this._state.data)
  }
}
```

**Comment by Devifish** [comment]
vuex的严格模式，本就是调试用的。  state只读属于写法规范问题

> 引用文档:
> 不要在发布环境下启用严格模式！严格模式会深度监测状态树来检测不合规的状态变更——请确保在发布环境下关闭严格模式，以避免性能损失。

**Comment by kiaking** [comment]
I think we can't do this since we can on/off strict mode via options, so if we do this it's going to be braking change.
