### ISSUE TITLE
Deprecation Warning: Use of deprecated folder mapping "./" in the "exports" field module

### ISSUE THREAD

**Issue by hamidyfine** [vuejs/vuex#2047]
### Version
4.0.2

### Reproduction link
[github.com](https://github.com/hamidyfine/vuex-issue)

### Steps to reproduce
- Create Vue-CLI project including `vuex` and `Unit Test`
- Run the test command: `pnpm run test:unit`

### What is expected?
Running the test task without warning.

### What is actually happening?
There is `DeprecationWarning` before running the test task.

**Comment by cuebit** [comment]
Duplicate #2040
