### ISSUE TITLE
Vuex does not provide an export named 'createStore'

### ISSUE THREAD

**Issue by HaloElite** [vuejs/vuex#2050]
### Version: 
4.02

### Steps to reproduce:
`yarn add vuex@next --save` using vite and Vue3
`import { createStore } from 'vuex';` in store.js doesn't work as expected.

### Output
`the requested module '/vite-dev/@fs/home/app/node_modules/.vite/vuex.js?v=f336efac' does not provide an export named 'createStore'`

**Comment by Alanscut** [comment]
Hi @HaloElite , could you provide your project link? Following your reproduction steps, it works well for me.
