### ISSUE TITLE
Vuex 4 accesing action names directly

### ISSUE THREAD

**Issue by andrei-cacio** [vuejs/vuex#2062]
I don't know if this was posted before but after reading the Vuex 4 docs about actions I can see that:

in Vue2 we had:
```javascript
{
   methods: { 
         ...mapActions('someStoreModule', ['actionName']
         handleClick() { this.actionName(); }
   }
 }  
```

in Vue3 + Vuex4 we now have:

```javascript
{
   setup() {
       const store = useStore();
       return { handleClick() { store.dispatch('someStoreModule/actionName'); }
  }  
}
```

I was a big fan of calling actions right by their name instead of dispatching strings. So this is more of an open question, would there be interest in having this in Vuex 4 as well?

It would look something like:

```javascript
{
   setup() {
       const store = useStore();
       return { handleClick() { store.someStoreModule.actionName() }
  }  
}
```

**Comment by cuebit** [comment]
This is still available in Vuex 4 but is only compatible with the Options API.
