### ISSUE TITLE
 [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package

### ISSUE THREAD

**Issue by RejDev** [vuejs/vuex#2064]
Hello,

I would like to report a small warning during the build phase, which can easily be removed.

### Version
4.0.2

### Reproduction link
no need for a link in this case
[localhost/](http://localhost?msg=no need for a link in this case)

### Steps to reproduce
Node / Electron Build process

### What is expected?
Build without warnings
, just change this in the "package.json" file :
```
  "exports": {
    ".": {
      "module": "./dist/vuex.esm-bundler.js",
      "require": "./dist/vuex.cjs.js",
      "import": "./dist/vuex.mjs"
    },
    "./": "./"  <----------------------- by "./*": "./*"
  },
```

### What is actually happening?
 [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at package.json

Update this package.json to use a subpath pattern like "./*".

---
Thanks in advance.

**Comment by cuebit** [comment]
Duplicate #2040
