### ISSUE TITLE
How to use promise to set initial state data

### ISSUE THREAD

**Issue by mrgodhani** [vuejs/vuex#21]
Hi

I am using NeDB in my project and also vuex. I am having issue to set initial data using promise since nedb returns value inside callback.

So how do we set initial state Data if we have a callback or either using a promise.

**Comment by yyx990803** [comment]
Use empty/stubbed initial state, and have a dedicated action/mutation for "got initial data". (See the shopping cart or chat example)

**Comment by dschissler** [comment]
The Vue 2.0 examples don't seem to have a initialize data action anymore.
