### ISSUE TITLE
可以在vuex中写computed吗？

### ISSUE THREAD

**Issue by flyoverGu** [vuejs/vuex#212]
在文档[forms.md](https://github.com/vuejs/vuex/blob/master/docs/en/forms.md)中看到这样写 
![](http://ww2.sinaimg.cn/large/72f96cbagw1f4x02nrphxj20ty0msmyw)
但是我试了，好想不行啊

**Comment by fnlctrl** [comment]
文档错了 computed应该和vuex同级
