### ISSUE TITLE
Documentation: Vue 2 Support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vuex#2122]
### What problem does this feature solve?

Improve docs

### What does the proposed API look like?

The [Github Release notes](https://github.com/vuejs/vuex/releases/tag/v4.0.0) and the [Migration guide](https://next.vuex.vuejs.org/guide/migrating-to-4-0-from-3-x.html) in the docs do not explicitly mention if Vuex 4 is compatible with Vue 2.6+. This is important when you have dozens of dependencies in your large Vue 2 app and need to plan out what can be updated in advance, what needs updated with Vue, and what needs to wait until after Vue is updated in your codebase. If Vuex 4 is compatible (with some minor code tweaks shown in the migration guide), then it can be done sooner, making the transition to Vue 3 easier.

**Comment by Akryum** [comment]
Veux 4 has the same API as vuex 3, so I don't see the point ?

**Comment by TheJaredWilcurt** [comment]
Just to be explicit on version support. I've heard it explained as:

* Vuex 3 is for Vue 2
* Vuex 4 is for Vue 3

But would be nice for the docs to correct that to say

* Vuex 3 is for Vue 2
* Vuex 4 is for Vue 3 and Vue 2

**Comment by TheJaredWilcurt** [comment]
Actually, if the API is the same, then I'm not sure if Vue 3 will also work with Vuex 3 too. meaning it would need to be:

* Vuex 3's API is compatible with Vue 2 & 3
* Vuex 4's API is compatible with Vue 2 & 3

> I don't see the point ?

That is the point, I'm uncertain of these thing unless they are explicitly documented.

**Comment by yshrsmz** [comment]
+1, I'd like to know if I can use Vuex4 with Nuxt/Bridge, or Vue2 with `@vue/composition-api`

**Comment by Akryum** [comment]
**Vuex 4 isn't compatible with Vue 2.**

- Vue 2 => use Vuex 3
- Vue 3 => use Vuex 4

If you want to migrate a Vue 2 app to Vue 3, change Vuex version to Vuex 4 and make the small [necessary changes](https://vuex.vuejs.org/guide/migrating-to-4-0-from-3-x.html). The rest of the API is basically the same.

If you are still on Vue 2, you can still use Vuex 3.

**Comment by andy0130tw** [comment]
Sorry for reviewing this issue. In English documentations, the section mentioning that Vuex 4 is only compatible with Vue 3 is now be replaced with "[Pinia is now the new default](https://vuex.vuejs.org/index.html)." In this note, it implicitly tells that for Vue 2 projects you may also switch to Pinia, which implies that you should not upgrade to Vuex 4 under that circumstance. I think it is better to preserve the original section, as seen in all other languages, to make people who still use Vue 2 less confused.
