### ISSUE TITLE
vue组件化问题

### ISSUE THREAD

**Issue by dongyang03** [vuejs/vuex#214]
你好，诚如我们在vuex文档中说 “为了更好的解决在大型应用中状态的共用问题，我们需要对组件的 组件本地状态(component local state) 和 应用层级状态(application level state) 进行区分”
我想这是我们每个码农所追求的。
但是当我们在实际开发中遇到，一个纯前端渲染的webapp。首屏4个组件，每一个组件都有自己的私有数据（component local state），需要http和后端交互。所有的组件通过vuex共享数据、通讯。
有个问题：
4个组件，4个http请求如何做到良好的用户体验高性能？

**Comment by dongyang03** [comment]
希望能得到大家的回复

**Comment by zhangzan** [comment]
升级到  http2

**Comment by yyx990803** [comment]
local state 通常用于纯粹的展示状态，比如菜单的开关之类。需要后端通信的通常放到 vuex store 中管理。http 请求层面的优化需要你自己做，因为这和后端 API 是如何组织的有关。理论上来说此类优化在 REST 下本来就不容易做，需要 GraphQL，但那不是 Vuex 关心的范畴了。
