### ISSUE TITLE
Update documentation to mention maintenance/EOL/etc

### ISSUE THREAD

**Issue by cfjedimaster** [vuejs/vuex#2146]
### Version
4.0.2

### Reproduction link
[https://vuex.vuejs.org/](https://vuex.vuejs.org/)

### Steps to reproduce
According to the Vue.js documentation, Vuex is no longer being worked on. As documented here, https://vuejs.org/guide/scaling-up/state-management.html#pinia, it says:

"With Pinia serving the same role in the ecosystem, Vuex is now in maintenance mode. It still works, but will no longer receive new features."

However, nothing on Vuex's main page (https://vuex.vuejs.org/) states this.

### What is expected?
I would add something with a highlight of some sort, close to the top of the homepage, that makes it clear Vuex is no longer being updated. 

### What is actually happening?
It doesn't say this.

---
This form requires a URL that links to a reproduction of the bug. However I'm reporting an issue with documentation. Perhaps this form should be updated to clearly state how someone reports a doc bug?

**Comment by WhereJuly** [comment]
The future of vuex is pretty important to know as Pinia does not serve well for projects more complex than say 5+ data entities (e.g. user, organization, product, cart, orders etc.). 

Just for instance in some of our applications we have ~20 entities including nested dictionaries etc. living in vuex store.

Pinia does not allow for store modules (what it allows is just a quick workaround, not a grown up solution) neither it allows for appropriate breaking the store actions into separate file.

It looks like with seeming discountinuation of Vuex the really complex applications lose the sense of using Vue 3 at all.

Does anyone responsible for such decisions gave a considerations to these concerns?

**Comment by IlCallo** [comment]
In my experience, since Composition API came out, the need for a dedicated state management package isn't that critical anymore, especially for medium/big projects

Unless you need SSR support oob or you think stores time travel is essential, creating plain Composition API stores provides you all the flexibility you need for bigger projects.
You get more freedom and flexibility at the cost of less initial guidance

**Comment by cfjedimaster** [comment]
To be clear, I'm making no statement on Pinia vs Vuex or whether or not it makes sense for Vuex to be in maintenance. It's really simple. The Vue.js docs say it is. The Vuex docs do not. If the Vue.js docs are wrong, I'll happily close this bug and file one there.
