### ISSUE TITLE
Why don't you move the TypeScript definition file to DefinitelyTyped?

### ISSUE THREAD

**Issue by ktsn** [vuejs/vuex#215]
I think it would be better to move Vuex's TypeScript definition file to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/).

Because the current Vue's definition file is maintained on DefinitelyTyped. And we can use the definition as dependency.
e.g. We can add `$store` property on the Vue instance definition.

How do you think about this?

**Comment by kazupon** [comment]
I think so too.

**Comment by ktsn** [comment]
@kazupon Thank you!

I'd like to move d.ts file with some improvements if there are no any opposite opinions :)

**Comment by yyx990803** [comment]
It seems the new official type repo is https://github.com/typings/typings

**Comment by ktsn** [comment]
Ah, it's definitely better to register to typings, thank you.

So, should we make a new repository like `typed-vuex` and register it to typings?
I understand we can register the d.ts file in this repository to typings but I think it is noisy to maintain it in this repository.
(It seems to need typings.json, test cases and other stuff of TS for quality)

**Comment by yyx990803** [comment]
Hmm, not sure about the separate repo idea. I'm fine with types living in the same repo if that makes maintenance easier.

**Comment by yyx990803** [comment]
Oh actually, if you mean a separate repo with the type-related files only, that seems ok too.

**Comment by ktsn** [comment]
If you don't care to maintain type-related files in same repository, it's good to do that!
I had worried that the repository becomes mess by type-related files.
But I realize we can separate them to a sub directory and can register it to typings.

I will send a PR to improve the d.ts in this repository and register it later 😄
