### ISSUE TITLE
Question: Access store getters from router in vex 4

### ISSUE THREAD

**Issue by PierreBrisorgueil** [vuejs/vuex#2169]
Hey, just a question, since the migration to Vuex 4 I couldn't find a clean example of accessing the getters from the view-router, like in beforeEach 🤔

Any suggestion/example? 

Thx fo your time.

**Comment by PierreBrisorgueil** [comment]
Issues Helper doesn't allow us to ask questions. & discussion section is not activated.

**Comment by cuebit** [comment]
Jump on the Discord channel if you have questions https://chat.vuejs.org
