### ISSUE TITLE
How to ensure that the promise of the layout component obtains the value before the route component sends the request

### ISSUE THREAD

**Issue by hyahm** [vuejs/vuex#2171]
### What problem does this feature solve?
When this page is refreshed. In the layout component, I get some information and store it in vuex. The component in Vue router needs to get this value to make the next request,

### What does the proposed API look like?
Is there an API that can block a value in vuex from executing the request only after it is updated

**Comment by cuebit** [comment]
Issues are applicable when an issue is relevant to the library codebase or feature requests. 

For genera questions, discussions and troubleshooting, please head over to https://chat.vuejs.org
