### ISSUE TITLE
mac系统 node版本17，uniapp vue3.0 + vite 版本 vuex编译报错

### ISSUE THREAD

**Issue by You00** [vuejs/vuex#2177]
版本：4.0.2
重现步骤：uni-app（vue3/vite版本）使用vuex，启动项目
期望：项目正常启动
实际结果：报错：[vite] [plugin:vite:import-analysis] Package subpath './dist/vuex.esm-bundler.js' is not defined by "exports" in /uni-app-vue3.0/node_modules/vuex/package.json
补充意见：针对这个问题，目前是说动更改vuex依赖的package.json文件（./改成./*）
以上，希望官方可以解决一下

**Comment by 123jiacheng123** [comment]
解决了吗？我这也报错这个，uni-app升级，从vue2升级到vue3时，vuex一直报错这个，
