### ISSUE TITLE
In the <script setup>  use vuex mapMutations  erro

### ISSUE THREAD

**Issue by jiekechens** [vuejs/vuex#2184]
<script setup lang="ts">
import { onMounted } from 'vue'
import { useStore, mapState, mapMutations } from 'vuex'

  
 let store=useStore()
 const count=store.state.count
 let { increment }=mapMutations({increment:'increment'})
 
onMounted(()=>{ increment.bind({$store:store})  })
 
</script>

<template>
  
  <h1>{{couns}}</h1>  
  <h1>{{count}}</h1>
  
  <button @click="increment">count++</button>
  
</template>

![Snipaste_2022-07-04_15-37-05](https://user-images.githubusercontent.com/100945843/177105573-045ecc8b-33cd-4a5e-a4b8-2cb4da144572.png)
![Snipaste_2022-07-04_15-37-54](https://user-images.githubusercontent.com/100945843/177105578-6266eecb-f625-489c-b1ad-b03fcfd3c7e9.png)

// The first I  think  the this about , but  i  join  to the this for store  。 it still  report errors massge “Cannot read properties of undefined (reading 'commit')”  so  in tht  <script setup> we can't  use mapMutations ?

**Comment by jiekechens** [comment]
help

**Comment by memoryseven** [comment]
var increment = mapMutations(["increment"]).increment.bind({$store:store});

**Comment by memoryseven** [comment]
or u can use：
var {add} = mapMutations({add:'increment'});
var increment=add.bind({ $store: store });

**Comment by jiekechens** [comment]
thanks bro ，i get‘t
