### ISSUE TITLE
Will using vuex in nuxt affect the performance of the program?

### ISSUE THREAD

**Issue by bianliuzhu** [vuejs/vuex#2190]
My colleagues and I are discussing whether the use of Vuex in Nuxt will affect performance, but we have not reached a unified opinion. Because we do not know much about the bottom implementation and operating principle of NUXT. If we can hope that you can give it We have some pointers
1. Will using Vuex reduce performance?
2. Will Vuex run on the server? and will vuex data be downloaded from the server to the client?
3. Does the use of Vuex increase the memory?
4. The same state, what is the difference between storing in vuex and storing in components

Thank you for your answer

**Comment by wangjiaoj** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，您的邮件我已经收到，我尽快给您回复。

**Comment by weier910** [comment]
你的邮件我已收到！
