### ISSUE TITLE
Please consider reaching 1.0

### ISSUE THREAD

**Issue by szkrd** [vuejs/vuex#222]
The 0.7 release deprecates vue 1.x support, which is a breaking change. I do get that pre 1.0 releases in semver can break api anytime, but as a consumer of this library, it would be nice to know if a simple version update would break a whole Vue app. If you think using 1.0+ versioning is contraproductive, please close this issue. Thanks!

**Comment by miljan-aleksic** [comment]
I also find it confusing and frightening that suddenly Vue 1 support is deprecated. Perhaps 0.6.x will be keept updated for Vue 1 while ongoing will support Vue 2. Never the less, using a semantic versioning will avoid this and other confusions.

**Comment by yyx990803** [comment]
You should assume breaking changes on `0.x` increments, this is why `^0.6.3` will **not** give you `0.7.0`. If it's a patch release, it would be `0.6.4`. I think the semantics is pretty clear.

**Just want to make it clear this is proper semantic versioning.** It will be 1.0 when it really should be.

**Comment by miljan-aleksic** [comment]
Semantic versioning is:

- MAJOR version when you make incompatible changes.
- MINOR version when you add functionality in a backwards-compatible manner.
- PATCH version when you make backwards-compatible bug fixes.

Vuex is not following it so we must assume is instead following a custom concept of it, which is fine as long as it comes with some documentation.

**Comment by yyx990803** [comment]
@miljan-aleksic please read http://semver.org/#spec-item-4

It's not 1.0 exactly because the API is not stable yet.

**Comment by miljan-aleksic** [comment]
I see what you mean, it is valid semver. Good, although you may consider as well the http://semver.org/#how-do-i-know-when-to-release-100 point.

**Comment by yyx990803** [comment]
As I said, it will be 1.0 when it should be - which implies there will likely be breaking changes coming soon.

**Comment by yyx990803** [comment]
As a side note - there's no reason to be "frightened" because 0.6.x will still receive bug fixes and updates. It's technically the same if you think of `0.6.x` as `1.0` and `0.7.x` as `2.0`. They are parallel tracks. Also, the actual `1.0` will most likely support both Vue 1.x and 2.0.

**Comment by miljan-aleksic** [comment]
Ok @yyx990803, that works for me. Thanks.

**Comment by szkrd** [comment]
That's good to hear, thank you!
