### ISSUE TITLE
Error in Vuex document link

### ISSUE THREAD

**Issue by heygsc** [vuejs/vuex#2230]
### Version

4.x

### Describe the bug

Vuex's document, edit this page on GitHub, link to error

### Reproduction
![image](https://github.com/vuejs/vuex/assets/103993866/0dbbc561-4f52-4ddb-81db-629d41fd501f)

![image](https://github.com/vuejs/vuex/assets/103993866/ae20278b-a589-4b55-b322-a7a2bc3a025c)

Any page in the document, click to edit this page on GitHub.

### Expected behavior

The issue comes from the configuration issue with VuePress. 
The original configured document branch was 4.0, but this branch is no longer visible. It is recommended to change to the default branch.
I have submitted pr.   https://github.com/vuejs/vuex/pull/2229 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vuex.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by heygsc** [comment]
I have submitted pr. https://github.com/vuejs/vuex/pull/2229

**Comment by cuebit** [comment]
resolved by #2229
