### ISSUE TITLE
Can't use ES6 Symbol as mutation types.

### ISSUE THREAD

**Issue by xream** [vuejs/vuex#224]
Browser: Chrome 53.0.2767.4 dev (64-bit)
Platform: Mac OS 10.11.5

TypeError: Cannot convert a Symbol value to a string.

**Comment by simplesmiler** [comment]
As far as I can say, Symbols are not a good fit to mutation types, because Symbols are not serializable, i.e. `symbol !== JSON.parse(JSON.stringify(symbol))`.
See: https://github.com/reactjs/redux/issues/4

**Comment by yyx990803** [comment]
Yeah, this is not supported because Symbols cannot be serialized.

**Comment by crimx** [comment]
@yyx990803 How about the global symbol registry? `Symbol.keyFor()` can be used for serialization.

**Comment by yyx990803** [comment]
@crimx AFAIK that requires the symbols to be created with `Symbol.for()`. Won't work for all Symbols :/
