### ISSUE TITLE
Passing by reference vs normalizing data

### ISSUE THREAD

**Issue by JasonHoffmann** [vuejs/vuex#226]
I'm dealing with some nested data, for instance a list of sections, each with a list of posts, all of which are editable from one screen (so no real activeSection use case). Something like (with an example of what data looks like).

    state: {
        sections: [ { 
                       id: '',
                       title: '',
                       posts: [ { id: '', title: '', content: '' }]
                   }]
    }

In my application, I'm noticing that if I am editing a post, and then pass that post to the mutation, then I'm actually able to update it. So in my component I would have:

`this.updatePost(post, newPostData)`

And then the action would pass this to the mutator which works like:

    UPDATE_POST(state, post, newPostData) { 
       post = Object.assign({}, post, newPostData);
    }

And this actually works. I'm wondering, is this because as properties are passed down they are passed by reference? Am I mutating the state properly? The only other way I can think of is to use a tool like normlizr that was mentioned in #144 and instead query the entire state for the proper post and update it that way. Is there a performance difference or a best practice?

**Comment by LinusBorg** [comment]
#
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by JasonHoffmann** [comment]
Got it, thanks!
