### ISSUE TITLE
Per-component mutations?

### ISSUE THREAD

**Issue by sleewoo** [vuejs/vuex#230]
Would it be a bad practice to have per-component mutations beside "global" ones?

Actually i'm using a dirty hack inside components with "custom" mutations:

```js
  created() {
    merge(this.$store._mutations, mutations)
  }
```

It's all great to have mutations defined in same place and modules makes this really awesome.
But there may appear scenarios(like mine one) when per-component mutations would make sense.

In my scenario a wrapper is collecting components from app then creating a vm based on them, so component builders just provides components as objects and can not affect vm nor store creation.

I could of course provide mutations object with each component then the wrapper is collecting(then deleting to not alter `$options`) them and create a store. 
But i'd feel very dirty this way :) 

Another scenario would be when various components has various functionality for same mutation, e.g. global DELETE mutation will delete the current item but DELETE mutation of Photos sub-container would delete item's photos rather than item itself.

Of course, a DELETE_PHOTO mutation is recommended for this case, but having appropriate mutations inside container itself feels somehow warmer, does not it?

And when going to reason about what happens in components, rather than scanning through multiple global mutations we'd look inside component's mutations first.

What about providing custom mutations in `vuex` object, along `actions` and `getters`?

```js
vuex: {
  actions,
  getters,
  mutations
}
```

I could provide a PR if this proposal makes sense to you.
Forgive me if my vision on this is somehow screwed.

Thanks.

**Comment by yyx990803** [comment]
This is a bad idea. Components should not be able to affect how the store functions. They can only read state or trigger state change. You can divide your mutations into vuex modules though.

**Comment by sleewoo** [comment]
thanks, will create store on userland and provide it up to wrapper
