### ISSUE TITLE
Proposal: Implement generic mutations

### ISSUE THREAD

**Issue by chrismbeckett** [vuejs/vuex#234]
I really like the integration of Vuex with VueJS, especially the time travelling support in DevTools. But I find the current system of having to write mutations to modify every different path of the state tree adds a lot of unnecessary bloat to what could be a very simple flux implementation.

I would like to propose adding, possibly as simply an optional included module, a generic set of mutation interfaces like set, unset, pop, push, splice, etc., like [Freezer](https://github.com/arqex/freezer) or [Baobab](https://github.com/Yomguithereal/baobab).

I would be willing to work on a pull request.

**Comment by yyx990803** [comment]
Explicitly writing mutations and triggering them via dispatch separates the intention from the actual mutation, which is the while point of the library. Without this it would become very difficult to track and time-travel in devtools, and while your code becomes easier to write, it becomes harder to read and reason about (at the application level).

If you just want to have some global state without the tracking/time-travel capabilities and architectural scalability, just use the [store pattern described here](http://vuejs.org/guide/application.html#State-Management).

**Comment by chrismbeckett** [comment]
I think you are overstating the benefits of explicit mutations, and I am hardly the only one who thinks so. Both Freezer and Baobab are gaining popularity in the React community.

- If components have to know the complete path and shape of the state data to bind to, there is no real separation of concern with regard to how state is changed and how it is consumed. If a component knows the shape of the data to get, there is a good argument that there is no reason action creators can't directly know the shape of the state they want to modify. The extra layer of mutations is not adding much benefit.

- Both Freezer and BaoBab provide immutable state with 'newState' and 'prevState' capabilities with events. Unlike directly manipulating shared state, it still provides the ability to intercept or interrupt state mutation with middleware, etc.

- Baobab already provides time travelling because you can maintain state history and undo state mutations.

My point is that there is actually a *middle* ground between the ``store`` pattern you linked to in the documentation (just a shared reactive data source), and the full implementation of Vuex with actions -> mutations -> state. Implementing standard mutations does not undermine the *point* of the library. It still provides a bunch of benefits above and behind a shared reactive state implementation because it still implements interfaces for mutation and creates immutable state changes.

**Comment by chrismbeckett** [comment]
Is this (and have to implement a custom SHOW_SPINNER mutation)

```js
store.dispatch({
  type: 'SHOW_SPINNER',
  payload: 1
})
```
so much easier to reason about than using a generate mutation (INCREMENT)

```js
store.dispatch({
  type: 'INCREMENT',
  path: 'ui.overlays.spinner.count',
  payload: 1
})
```
or this (custom mutation to push to an array vs. generic):

```js
store.dispatch({
  type: 'ADD_PRODUCT',
  payload: {...}
})
```
vs this:

```js
store.dispatch({
  type: 'PUSH',
  'path': 'cart.products'
  payload: {...}
})
```

Yes, in some cases a mutation may implement more complex state modification behavior, which is why for those specific cases, custom mutations that are aware of their particular sub-tree will always be necessary, but in my experience, most of the time mutations end up just being duplicate code performing the same simple operations like push, pop, increment, decrement, etc. for nothing more than a different part of the state tree. Do we really need to write the same mutations over and over for every different array structure in our state tree:

ADD_PRODUCT
REMOVE_PRODUCT
UPDATE_PRODUCT

ADD_USER
REMOVE_USER
UPDATE_USER

You are still required to dispatch a mutation to change state which still provides the ability to:

- record the state change for time travelling
- provide *before* interception for plugins
- provide *after* events for plugins (like auto-persist)

The mutation layers primary responsibility is really just to enable the observer pattern and raise events from a store to views so they know state has mutated. A *standard* set of mutation functions:

- still ensures the benefits of the mutation layer are preserved
- provides convenience to developers to avoid duplicating code for similar mutations
- doesn't stop developers from writing custom mutations when called for

A standard set of mutation functions that take a path would simply avoid a lot of developer duplication. Sure, every developer right now could create their own set of these types of mutations (I already am), but why make everyone write the same code over and over when these *convenience* mutation methods would add little overhead to the Vuex library and save everyone a lot of time.

**Comment by yyx990803** [comment]
You can easily auto-generate such mutations in userland, e.g.

``` js
new Vuex.Store({
  mutations: {
    ...createCrudMutations('products'),
    ...createCrudMutations('users')
  }
})
```

I don't see a need to include it as built-in.

**Comment by chrismbeckett** [comment]
It seems like such a waste of resources that every (or at least many) developers who want to use Vuex have to code up those same generic generators over and over. If Vuex included a set of generic mutations, my guess is that almost everyone would use them for at least a portion of their state tree.

Don't you think this is even worth collecting some community feedback on to see if other people like this proposal? Please re-open this issue.

**Comment by yyx990803** [comment]
Because leaving it in userland gives you the flexibility to write it the way you want it, and most likely I'd perfer a different set of default mutations than yours. Also, I think it's weird to have the mutations namespaces polluted by these built-ins by default, because I personally would never use them, for me they are just extra things to remember.

I don't have the obligation to consider every proposal, especially when what is proposed can be implemented in userland. If you feel strongly about it, you can publish it as 3rd party library so that others can reuse what you've created, but that will not be in Vuex core.

**Comment by chrismbeckett** [comment]
Well, from that perspective, Vuex itself could be implemented in userland so why don't we all just code our own flux implementations from scratch, and our own SPA frameworks for that matter, and our own package managers.... but hey, sharing and reuse might actually be cool.

No, you are not under any obligation, which is why the subject was *Proposal* and not *Demand*, but many open source project leads like to give the community a voice. I did say I was willing to do a pull request, so this wasn't a demand that somebody else code this up and deliver it to me.

If this is they way you want to lead the VueJS community so-be-it. Thank you for developing a good SPA implementation and sharing it. I won't waste my time attempting to contribute again.

**Comment by NicolasParada** [comment]
On redux, there is a [promise middleware](https://github.com/pburtchaell/redux-promise-middleware). So cool. Avoid a lot of code duplication.
In the same way, something like that could be implemented on Vuex **like a plugin**.

**Comment by NicolasParada** [comment]
Btw, so nice that example you gave, Evan:
```js
new Vuex.Store({
  mutations: {
    ...createCrudMutations('products', 'users', ...)
  }
})
```
I'm gonna implement it <3

**Comment by yyx990803** [comment]
@chrismbeckett that's a slippery slope argument. Obviously there is a fine line on what should be in userland and what should not - and that is the kind of decisions I've been making all the time. I believe what you proposed is better off left in userland, and I made that decision exactly because **I believe it's better off for the community to not include this in Vuex core.**

There is also a fine line on what should be left open for community feedback and what should not. For example every major version of Vue.js core goes through multiple long discussion threads on potential API changes. But it is my call whether to engage in a discussion or not, and if I leave every feature request open for discussion, I will get nothing done. So I will be closing requests that I think is not worth discussing to maximize my productivity. You are free to disagree with my opinion, but as I said, you could've just authored a plugin, and now you are getting passive-aggressive because your proposal was not considered. Grow up.

**Comment by chrismbeckett** [comment]
You closed the issue before you even understood my proposal, let alone gave it any consideration. Now you are just lying and throwing insults to mask your immature behavior and arrogance. Consider taking your own advice.

**Comment by yyx990803** [comment]
I did close it before I understood it, for that you are correct and I've already admitted that. However, the decision of not re-opening it has been well-explained and you continued rambling with passive-aggressive slipprry slope arguments out of your personal frustration. Please do the community a favor and stop wasting my time.
