### ISSUE TITLE
port to weex

### ISSUE THREAD

**Issue by transtone** [vuejs/vuex#237]
Is there a plan to get vuex work in weex?

redux + react-redux can use in react-native like this: https://github.com/alinz/example-react-native-redux/tree/master/Counter

**Comment by LinusBorg** [comment]
The Vue team is not working on that at the moment. Weither the weex team is working on that, we don't know currently.

**Comment by yyx990803** [comment]
It should already work in Weex because Vuex is not coupled with what rendering platform you use.

**Comment by kmCha** [comment]
@yyx990803
尤大你好 请问我想把vuex用在weex中有什么办法吗 https://github.com/vuejs/vuex/issues/237 我找到了这个issue 里面您说跟渲染框架无关 但是我初始化vuex的store实例的时候 报错说vuex must call Vue.use(Vuex) before creating a store instance.
版本是v2.0.0-rc3
