### ISSUE TITLE
How do we handle failure or success of async requests?

### ISSUE THREAD

**Issue by altitudems** [vuejs/vuex#24]
Imagine I have a simple login.vue component with a username and password field.

I attempt a login by calling store.actions.login(this.username, this.password)

I want to be able to hide a loading overlay, close the login screen, and provide reasons for login failure.

1. Should I watch a store.state.isAuthenticated variable and react accordingly?
2. Should the action be returning a promise?
3. How can I get a return value on error, so that I can display an error message?

**Comment by Phunky** [comment]
I'm currently stuck on this myself, my initial thoughts we're to $broadcast a success or failure event so all components can respond how they like but don't have access to the App instance within Vuex.

For now i'm just going to use store.state.response but it feels very wrong.

**Comment by jonagoldman** [comment]
The way I am doing it is that I return a promise from the action:

```js
// Vuex Store
export const storeActions = {

  someAction(store) {

    // return a promise from an api service
    return someService.someMethod(function(response) {
      store.dispatch(ACTION, response);
    });

  }

}
```

```js
// Somewhere in your app
const { someAction } = store.actions

someAction().then(function() {
  // request successful
})
```

I let the mutation change the state but in parallel I also listen to that promise resolve.

**But notice**, I only use the promise to know the request finished and do something like  [render a component] (https://github.com/vuejs/vuex/issues/26).
I **do not** use the response inside the resolve, all data is still managed by the Vuex store.

I'm not sure this is the best way, but I can't find a better solution so that`s what I'm doing right now.

**Comment by altitudems** [comment]
It seems to me the whole idea of using a centralized store is to avoid having to broadcast messages.

Promises seem very reasonable as long as we can remember to stay away from directly altering response data. @jonagoldman's approach seems like the best to me at the moment.

I still feel like using promises feels a bit like going backwards somehow. But I can't really bring myself to add new variables to the state that are there just to store error messages and isDone type flags.

**Comment by yyx990803** [comment]
It's in general better to treat the failure as just another state mutation: if it failed, something should happen, and that should be reflected in the store's state.

An example here: https://github.com/vuejs/vuex/blob/master/examples/shopping-cart/store/actions.js#L6-L14

The `buyProduct` API call may fail, and when it does, it simply dispatches `CHECKOUT_FAILURE` instead of `CHECKOUT_SUCCESS`. And here's the `CHECKOUT_FAILURE` mutation: https://github.com/vuejs/vuex/blob/master/examples/shopping-cart/store/modules/cart.js#L40-L44

**Comment by yyx990803** [comment]
If your API is promise-based, it also possible to write a simple helper to simplify this - e.g. automatically dispatch mutations based on the returned promise.

**Comment by coulix** [comment]
Interesting. In my case I have several promised based API call where, if a `401` is returned, a new token should be fetched and the API call that failed replayed with the new token.

~Pseudo code.

```
function APICall1() {
  return fetch('http://foobar.com/api/')
  .then((response) => {
    dispatch('GO_MUTATE', response.json());
  })
}

function APIActionHelper(apiFunction) {
  apiFunction()
  .catch((err) => {
    if (err.response.status === 401) {
      dispatch('INC_401_ERROR');

      fetchNewToken()
      .then() {
        APIActionHelper(apiFunction);
      }
    }
  }).
  catch((err) {
    throw(err);
  })
} 


That feels a bit wrong.

**Comment by srhise** [comment]
@yyx990803 Great explanation. Keep it simple!

**Comment by tiaod** [comment]
But what should I do if I want to redirect to an other page when I was login succeed?

**Comment by yyx990803** [comment]
@tiaod if you are using `vue-router`, then it will have to rely on the work-in-progress integration between the two. If it's a full page jump then it should not be a vuex action.

**Comment by tiaod** [comment]
@yyx990803 thanks for your answer. Yes I'm using `vue-router`, and finally I just import the router object and use `router.go()` method to redirect. Am I hacking?:-)

**Comment by nicolas-t** [comment]
> If your API is promise-based, it also possible to write a simple helper to simplify this - e.g. automatically dispatch mutations based on the returned promise.

Hi @yyx990803 

Can show a quick example of how you would handle promises with vuex ?
Given that you don't recommand the use of middlewares for such operations.

Thanks a lot :)

**Comment by yyx990803** [comment]
@nicolas-t a minimal example:

``` js
export function checkout (store, products) {
  api.checkout(products).then(
    () => store.dispatch('SUCCESS'),
    (e) => store.dispatch('FAILED', e)
  )
}
```

**Comment by nicolas-t** [comment]
Yes of course,
But in case I have a rest api with douzen of ressources, plus GET, POST, PUT and DELETE calls ?

What's the best way to automate it?
Should I really create three types per couple resource/http_method ?
like : 
```
RESOURCE1_GET_PENDING
RESOURCE1_GET_SUCCESS
RESOURCE1_GET_FAIL

RESOURCE1_POST_PENDING
RESOURCE1_POST_SUCCESS
RESOURCE1_POST_FAIL
....

RESOURCE2_GET_PENDING
RESOURCE2_GET_SUCCESS
RESOURCE2_GET_FAIL
...
```
Each of the `..._PENDING` mutations containing some very similar code:
`state.resource1.status = 'pending'`
pretty much the same for each `..._SUCCESS` and `..._FAIL` mutation.

How would you handle such mutations ? Or do you have any article about this topic (even with flux or redux), I didn't find anything.

Thanks a lot :3

**Comment by yyx990803** [comment]
It depends on whether the result status is significant enough to be displayed to your user. If you want to display different messages/interface to the user for each resource, then this is what you need to do; however, if you just want some generic indicator for request pending/success/failure (for example a top loading bar + a toast message), then you can reuse the same set of mutations for all api calls.

**Comment by nicolas-t** [comment]
Ok thanks ! I'll try something :)

Nicolas,

**Comment by blake-newman** [comment]
We keep all state mutations that may happen from an action.  If the action is to return the promise we strictly say that the promise handling from the component should not further call anything that may mutate state or call actions.

We allow thing like routing to be handled ect,  as this is not state driven.  A notification component can be dispatched to for example,  however depending on preference the notification component could be built to use the store. 

Sometimes actions may have to be returnable,  such as to decide routing.  It's then acceptable to act upon an action,  but in a refined amount.  Too much causes complexity.

**Comment by jbruni** [comment]
This discussion reminds me of "Command Query Separation" - http://martinfowler.com/bliki/CommandQuerySeparation.html

**Comment by danielschmitz** [comment]
Hello guys, im usign a callback function, and its ok for me....

component:
```
 <div class="progress" v-show="loading">
                            <div class="indeterminate"></div>
</div>
.............
export default{
    data () {
        return {
            username:'',
            password:'',
            loading:false
        }
    },
.....
 methods:    {
        tryLogin(){
            this.loading = true
            let user = {'username':this.username,'password':this.password}
             //doLogin is a action
            this.doLogin(user,()=>{
                this.$data.loading=false;
            })
        }
    }
..............
```
action:

```
export function doLogin({dispatch}, user, handler) {
    this.$http.post(`${URI}/auth/login`,user).then((response) => {
           let token = "todo.....";
           dispatch("LOGIN", user, token);
           handler();
      }, (response) => {
        console.log(response);
        message(`Error ${response.data.error`);
        handler();
      });
}
```

**Comment by wensonsmith** [comment]
Although this topic was closed,  i think this answer is usefull :  [Vuex Actions in a callback](https://forum.vuejs.org/t/vuex-actions-in-a-callback/1813/5)
