### ISSUE TITLE
vuex@2.0.0-rc.1 'strict' mode and 'store.module' mutation error

### ISSUE THREAD

**Issue by karol-f** [vuejs/vuex#243]
Hi, using vuex@2.0.0-rc.1 and 'strict' mode, after adding new store module using `store.module(...)` I got warning:

> Uncaught Error: [vuex] Do not mutate vuex store state outside mutation handlers.

Code: **http://www.webpackbin.com/VJ91GduIZ**

**What should happen**
Adding store module should not raise error in strict mode.

Regards!

**Comment by blake-newman** [comment]
@karol-f Are you using `vuex-route-sync`. If you are please see: https://github.com/vuejs/vuex-router-sync/pull/18

This will fixed with release `vuex@2.0.0-rc.2` and `vuex-router-sync@2.0.1`

**Comment by blake-newman** [comment]
This is working as expected currently. For 3rd party modules, we recommend you create an optional vuex   modules that users can import. Therefore allowing multiple workflow paths to use your 3rd party library. 

@evan would you agree?

**Comment by karol-f** [comment]
@blake-newman I'm not sure if I understand. 

- I am using "Nested Modules Improvements" as described [here](https://github.com/vuejs/vuex/releases/tag/v2.0.0-rc.1)
- this are in-library/in-app modules, used for decoupling store
- different components may be lazy loaded when needed and I don't want to initiate 'store' with it's state beforehand
- I think it's really nice idea to structure app/library in such way that all components are self sustaining - you can just copy/paste component with all things included (like store/state initialization)

Regards.

**Comment by LinusBorg** [comment]
@blake-newman I think you meant to mention @yyx990803 instead of the github user "evan" ;)

**Comment by aios** [comment]
thanks for that issue. that is solution of my cause on 1.0.0.rc-2. i will update to latest.
