### ISSUE TITLE
Dynamic module registration.

### ISSUE THREAD

**Issue by blocka** [vuejs/vuex#247]
When moving state out of the the local component state into the global store, we run into a situation where the state is persisting passed the component lifecycle.
Think about an autocomplete widget which maintains its state in a vuex module. When that component is destroyed, the state is still there. If the widget is recreated again, you will see what you left off with. This is besides the (somewhat) annoying fact that the module has to be "registered" at the beginning of the app.

That works great for data which is not local to one component, and which is needed for the lifetime of the app.

We can of course ignore global state, but we lose other benefits of vuex.

In the redux world, the problem was felt and there are some solutions to colocating global state next to a component [here is an example](https://github.com/threepointone/redux-react-local).

Is there a way to dynamically register a module, when a component is created, and then remove that module when the component is gone?

**Comment by piknik** [comment]
The best way to remove a module is to make a sort of "reset" mutation. This is what I did at least in Vuex 1.0. The mutation would just set all of the state variables to their initialization state (null or 0), and other code would pick up on that.

**Comment by blocka** [comment]
That's what I'm doing now. But seems there could be a nicer built in solution to this.

**Comment by piknik** [comment]
I can see where you're coming from. However, I thing there would need to be a larger change to Vuex than just removing modules.

Maybe like this, there would be a module of sorts in the vuex store, which can be automatically created somehow when the component is created, and it will store a map  of each of those specific components. Each map listing of the component will contain the state for that specific component, that way you will have the ability to add and remove multiple components for a single 'module' but without having to actually remove the module from Vuex, which is difficult and inconsistent I think.

However, I think that when you get to the point where a module is directly tied to some state, that its best to rethink how you manage the data. Perhaps access the data through a prop object on the component? I was actually thinking that I should for one of my own components, but that was some time ago and I can't remember off the top of my head...

**Comment by blocka** [comment]
There are definitely use cases for making one to one mapping between the vuex state and a component. Besides the autocomplete widget case I mentioned, let's say you had a form who's state you would want to keep in the store. If you simply v-modeled everything with local state, you would lose the time travelling/debug possibilites that vuex offers. Now it's true that only this component cares about this state, but I think that other benefits that vuex comes with weigh in here.

Same thing with modals and dropdowns. There are times when keeping these in vuex state is overkill, but other times not. Especially if the modal contains an import form in the UI.

It definitely feels awkward to keep this state for the lifetime of the application.

**Comment by blocka** [comment]
Seems this is addressed in vuex 2.0, so I'm closing this.
