### ISSUE TITLE
Setter not called when binding multiple checkboxes to the same array

### ISSUE THREAD

**Issue by chrome-cgi** [vuejs/vuex#249]
Hi,

I like [the form handling style using computed property setter](https://github.com/vuejs/vuex/issues/38), for its less verbosity.
But when I use it with multiple checkboxes bound to the same array, the property setter is never called and I got an error: "[vuex] Do not mutate vuex store state outside mutation handlers" if strict option is set to be true.

Here is an example:
https://jsfiddle.net/chrome_cgi/37q0h6xa/4/

This may be because Vue pushes the value directly into the model in [its checkbox listener function](https://github.com/vuejs/vue/blob/746e17aec159e2bb7e286d85a6c384038461cfa1/src/directives/public/model/checkbox.js#L39).

I somehow got to work by [patching](https://github.com/chrome-cgi/vue/commit/8b6e3e7351a52b1b82a5600ed0055933478885e7) Vue to call the setter with newly created array, but I'm not sure if this is an appropriate way.

Is this a bug or an intended behavior, and should I avoid using setter with an array typed v-model?

Thanks.

**Comment by yyx990803** [comment]
This is because `v-model` when bound to a checkbox array, directly mutates the array with `push` instead of replacing the array. You probably want to use a watcher instead.

**Comment by chrome-cgi** [comment]
I got it, thanks a lot!
