### ISSUE TITLE
npm installs version 2.0.0-rc.3

### ISSUE THREAD

**Issue by tralves** [vuejs/vuex#250]
I just spent 3 hours trying to get vuex to work based on the documentation and the examples (from `master`). The problem was that `npm install vuex` installs version 2.0.0-rc.2, which *is not* the version in `master` and it *is not* documented in [http://vuex.vuejs.org/](http://vuex.vuejs.org/).

This may cause confusion to someone that, like me, is working on a fresh vue/vuex project.

I have a couple of suggestions for your consideration:

1. Update the documentation to include install instructions that match the version being documented. E.g, in the [Getting Started](http://vuex.vuejs.org/en/getting-started.html) add the corresponding npm command `npm install vuex@^1.0.0-rc.2 --save`.
2. Update the documentation to match the new syntax. I understand this could be a lot of work...
3. Set the default version back to 1.0.0-rc.2 in npm (probably not the route you want to take).

I can PR the option 1 tomorrow, if that helps.

Thanks!

**Comment by Rookiewan** [comment]
me too, I can't find  any documentation, so I have to back to 1.0.0-rc2

**Comment by LinusBorg** [comment]
Hello @tralves,

Thanks for filing this issue. I will discuss this internally. I think that the latest release for npm should indeed be 1.0.0-rc2.

@Rookiewan About documentation for 2.0: Complete docs are indeed not ready yet, but you can get the most important concepts from the "2.0 Design proposal" (#236) as well as the Release note for [2.0.0-rc1](https://github.com/vuejs/vuex/releases/tag/v2.0.0-rc.1) and [2.0.0-rc3](https://github.com/vuejs/vuex/releases/tag/v2.0.0-rc.3)

**Comment by blake-newman** [comment]
@LinusBorg @tralves  @Rookiewan This is how npm works.... yay npm. I suppose in future we should be using `alpha` and `beta` versions, i think npm will then ignore these versions as it does for `vue` npm module.

**Comment by LinusBorg** [comment]
@blake-newman 

`npm tag vuex@1.0.0-rc2 latest` should be enough afaik.

**Comment by blake-newman** [comment]
oooo @LinusBorg Did not know about this

**Comment by yyx990803** [comment]
apologies, forgot to add `--tag next` when publishing 2.0.0-rc.3.
