### ISSUE TITLE
Actions don't show up on component.

### ISSUE THREAD

**Issue by reinvdwoerd** [vuejs/vuex#251]
I'm getting the following warning:
`[Vue warn]: v-on:mouseleave="closeSidebar" expects a function value, got undefined`

Inspecting the VM reveals that actions registered on components don't show up on the component at runtime.

I'm using Vuex `2.0.0-rc3` and Vue `1.0.26.`

Even copying the exact code from the tutorial gives the same result.

**Comment by reinvdwoerd** [comment]
I've discovered the issue, NPM installs `2.0.0-rc3` by default.
Installing `vuex@^1.0.0-rc.2` solved the issue.

**Comment by LinusBorg** [comment]
> NPM installs 2.0.0-rc3 by default.

Ref: #250
