### ISSUE TITLE
Add ability to unload dynamic modules

### ISSUE THREAD

**Issue by blocka** [vuejs/vuex#252]
Dynamic registration of modules is a crucial feature that was lacking in vuex 1.0. However, shouldn't there be a way to remove modules when you're done with them? The dynamic modules will just keep piling up in the store, with no way to remove them.

**Comment by sleewoo** [comment]
was wondering the same

**Comment by LinusBorg** [comment]
First, that's not what I would all a "memory leak" -there's no memory being blocked over and over when calling the same function or sth.

If you work with huge amounts of data in a module and worry about them hogging memory, you can simply whipe the module's state to a clean slate with a RESET mutation. all that will be left then will be the mutations/actions/getters, which even for a big module hardly leave a print in memory.

With the above, I don't see a need to make modules remove-able, but we can discuss it as a feature proposal.

**Comment by blocka** [comment]
We're not talking about storing huge amounts of a data in module. We're talking about even a module with a lot of data, but which could be created several time over the lifespan of your app.
In my particular instance, I have a widget which creates a new module every time it is created. The new module is namespaced based in the component's `uid`, so the store get's cluttered with these.

I guess it's technically not a "memory leak", at least not any more then a redux immutable store is (as in a datastructure which is "append only" for the lifetime of the app, although I think it definitely makes sense to be able to clean that up.

**Comment by yyx990803** [comment]
Now supported in [2.0.0-rc.4](https://github.com/vuejs/vuex/releases/tag/v2.0.0-rc.4)
