### ISSUE TITLE
Add property to object in vuex

### ISSUE THREAD

**Issue by franccro** [vuejs/vuex#259]
Hi,
I am trying to add property to object stored in vuex here is the code

```
[SET_PROJECT_GROUPS] (state, project, groups) {
    let projectIndex = state.all.indexOf(project);
    $set(state.all[projectIndex].groups, groups)
  },
```

What is the right way of doing this?

**Comment by arthurkirkosa** [comment]
Vue's set signature is `set(obj, key, val)`

**Comment by franccro** [comment]
Already tried that and got
             Uncaught (in promise) ReferenceError: set is not defined

**Comment by LinusBorg** [comment]
Answered here: http://forum.vuejs.org/topic/4714/add-property-to-object-in-vuex

**Comment by anthonygore** [comment]
@LinusBorg that link is dead now, can you explain as this is not documented

**Comment by LinusBorg** [comment]
Please use forum.vuejs.org

**Comment by ssantanuberaa** [comment]
use Vue.set();
or vm.$set()

**Comment by mauriciopazpp** [comment]
Use spread operator
```
state.obj = { ...state.obj, newProp: 123 }
```
https://vuex.vuejs.org/guide/mutations.html

**Comment by luatnd** [comment]
@LinusBorg Can you explain how Vue.$set work? Is that O(1)?

**Comment by pravchuk** [comment]
@mauriciopazpp  thank you so so much!!!! It took many hours to get here.

**Comment by tarekadam** [comment]
> state.obj = { ...state.obj, newProp: 123 }

If you need a dynamic prop name too, this works...
```
let obj = {}
obj[dynamic] = value
state.obj = {...state.obj, ...obj}
```

**Comment by Gator92** [comment]
@tarekadam A pretty common thing to do... props for your dynamic prop syntax.

**Comment by LucaDiba** [comment]
> If you need a dynamic prop name too, this works and preserves all my intended getters, setters, listeners, etc
> 
> ```
> let obj = {}
> obj[dynamic] = value
> state.obj = {...state.obj, ...obj}
> ```

You can also use [computed propery names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names) starting from ES6.

```
state.obj = { ...state.obj, [dynamic]: value }
```
