### ISSUE TITLE
hot reloading in webpack

### ISSUE THREAD

**Issue by davidmoshal** [vuejs/vuex#261]
Hi, I'm following the instructions for hot reloading with webpack, on this [page](https://github.com/vuejs/vuex/blob/master/docs/en/hot-reload.md) but it's not working.

is this correct?   
why are we not passing old state back into the store?

```js
if (module.hot) {
  // accept actions and mutations as hot modules
  module.hot.accept(['./mutations', './modules/a'], () => {
    // require the updated modules
    // have to add .default here due to babel 6 module output
    const newMutations = require('./mutations').default
    const newModuleA = require('./modules/a').default
    // swap in the new actions and mutations
    store.hotUpdate({
      mutations: newMutations,
      modules: {
        a: newModuleA
      }
    })
  })
}
```

**Comment by ktsn** [comment]
I tested on my environment and it works. The project is [here](https://github.com/ktsn/vuex-hot).
How do you configure your webpack and dev server?

**Comment by davidmoshal** [comment]
thanks! will try shorly

**Comment by davidmoshal** [comment]
confirmed that the state (vuex and non-vuex) is maintained during hot-reload, and that the UI and vue-devtools work too!

thanks SO much for sharing!

**Comment by ktsn** [comment]
Oh, I'm happy to hear that :smile:
