### ISSUE TITLE
文档中getters和computed的疑惑

### ISSUE THREAD

**Issue by 275287902** [vuejs/vuex#262]
1.在http://vuex.vuejs.org/zh-cn/state.html中，【在多组件中共享 getter 函数】标题这个下面，写filteredMessages用getters属性执行的。
2.在http://vuex.vuejs.org/zh-cn/structure.html中，【提取共用的 Computed Getters】同样的代码，被放到computed这里。
3.我知道这两个都可以，但是我不清楚建议放到哪里？以及会有什么样的区别？

**Comment by yyx990803** [comment]
你好，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请确保有完整的重现步骤。不符合要求的 issue 会被直接关闭。
