### ISSUE TITLE
jQuery promise: Uncaught TypeError: res.catch is not a function | Release v2.0.0-rc.3

### ISSUE THREAD

**Issue by spoptchev** [vuejs/vuex#263]
When I return a jQuery promise in an action I get `Uncaught TypeError: res.catch is not a function`.

```javascript
action = function() {
        var deferred;
        deferred = $.Deferred();
        deferred.resolve({});
        return deferred.promise();
}
```

```javascript
// vuex.js:308
if (store._devtoolHook) {
  // res does not respond to catch with a jquery promise
  return res.catch(function (err) {
    store._devtoolHook.emit('vuex:error', err);
    throw err;
  });
} else {
  return res;
}
```

**Comment by fnlctrl** [comment]
jquery's so called 'promise' is not a valid ES6 promise, which is non-standard and will not be supported.

**Comment by ktsn** [comment]
As @fnlctrl says, vuex only supports ES promise.
You can use jQuery 3's promise, it is compatible to ES promise.
https://jsfiddle.net/bufjo3q3/1/

**Comment by spoptchev** [comment]
ok, thanks
