### ISSUE TITLE
non-existent mutations not reported

### ISSUE THREAD

**Issue by davidmoshal** [vuejs/vuex#265]
Non-existent mutations can be dispatched without error

**Comment by davidmoshal** [comment]
sorry missed that in the console, closing

**Comment by AngryElephant** [comment]
I have the same probleme here, my action function is called and commit a mutation but nothing happen, i then try to commit a random name and i have no error ...

**Comment by ktsn** [comment]
Closing because new issue is created by @AngryElephant  (#291)
