### ISSUE TITLE
What is a right way to sanitize values?

### ISSUE THREAD

**Issue by sanex3339** [vuejs/vuex#266]
For example i have an input with value which should be inserted into a store.

I want to correct this value, for example:
* if value is not a number (contains non-numeric chars) - convert it to the number
* if value is empty - set it to the default value

My question is where i should sanitize the values? In actions, mutators, computed properties or methods?
Right now i doing it in the actions:

```js
export const someAction = ({dispatch}, value, defaultValue) => {
    if (defaultValue) {
        dispatch(SOME_MUTATION_TYPE, Sanitizer.number(value).notEmpty(defaultValue).get());

        return;
    }

    dispatch(SOME_MUTATION_TYPE, Sanitizer.number(value).get());
};
```

**Comment by chrisvfritz** [comment]
This is a good place for it. 👍  Mutations should only be responsible for the actual mutation.
