### ISSUE TITLE
IDE warning: Calling action with store instance as parameter

### ISSUE THREAD

**Issue by Blueblau** [vuejs/vuex#268]
Hi,

When calling an action with the store instance as first parameter, PHP Storm gives a warning.

![skaermbillede 2016-08-03 kl 13 37 43](https://cloud.githubusercontent.com/assets/1536598/17364277/905a9f46-597f-11e6-9f67-5d4976f14f4c.png)

*This is the [/vuex/examples/chat/main.js](https://github.com/vuejs/vuex/blob/master/examples/chat/main.js#L19) file on line 19.*

**Comment by LinusBorg** [comment]
Well, the IDE seems to have a problem with ES6 destructuring. 

Not sure what vuex could do about that.
