### ISSUE TITLE
Trying to access non-existent property **** while rendering.

### ISSUE THREAD

**Issue by FKobus** [vuejs/vuex#269]
Hi,

I'm trying to get Vuex working with the new Vue.js 2.0.0 build. But when I'm running the counter example I keep getting the following errors after building the code with webpack:

```vue.common.js:2232[Vue warn]: Trying to access non-existent property "count" while rendering. Make sure to declare reactive data properties in the data option. (found in component <Counter>)```
The same error occurs for: ```increment```, ```decrement```, ```incrementIfOdd```, ```incrementAsync```

It seems that vuex is not working as expected... I can upload my code to a github repo if needed

I'm using:
"vue": "^2.0.0-beta.6",
"vuex": "^2.0.0-rc.4",

**Comment by ktsn** [comment]
I cannot get the error when I run the examples in this repo.
Can you share the reproduction code?

**Comment by FKobus** [comment]
https://github.com/FKobus/vuerry/

I uploaded my project. It's just a copy of the example to a more real setup for a project. I'm currently maintaining a project in Vue 1.0.26 with an elastic search backend. I want to rebuild the app to Vue 2.0 with Vuex

**Comment by ktsn** [comment]
`vuex` option in Vue's component option is deprecated on Vuex 2.0. And also actions and getters API is changed.
You can use `mapGetters` and `mapActions` instead.

Please see [2.0.0-rc.1 release note](https://github.com/vuejs/vuex/releases/tag/v2.0.0-rc.1), [2.0 design discussion thread](https://github.com/vuejs/vuex/issues/236) and [examples on *next* branch](https://github.com/vuejs/vuex/tree/next/examples).

**Comment by FKobus** [comment]
Got it working.. Probably copy pasted the 'old' example.
