### ISSUE TITLE
Documentation link is uncorrect

### ISSUE THREAD

**Issue by alicePan** [vuejs/vuex#271]
When i get vuejs/vuex official github page(https://github.com/vuejs/vuex/),  I find the link of Documentation is point to http://vuejs.github.io/vuex/ while the correct link is http://vuex.vuejs.org/ .  This little mistake may make first time  visitor confused. Hope to fix it.

**Comment by fnlctrl** [comment]
Navigating to  http://vuejs.github.io/vuex/ actually redirects to  http://vuex.vuejs.org/  now, so I think this issue is fixed
