### ISSUE TITLE
Plugins not working

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vuex#273]
I'm following the plugin implementation from the docs, but plugins simply don't seem to be ever loaded.

I use modules in Vuex because of the size of my app, similar to the shopping cart example, but really nothing happens with the plugin.

Any thoughts what could be causing this?

```js
// vuex/store.js
import Vue from 'vue'
import Vuex from 'vuex'

import app from './modules/app'
import modal from './modules/modal'
import user from './modules/user'
import cart from './modules/cart'
import product from './modules/product'
import notifications from './modules/notifications'

Vue.use(Vuex)

// Just for testing purposes
const myPlugin = (store) => {
  console.log('myPlugin loaded')
  store.subscribe((mutation, state) => {
    console.log(mutation)
  })
}

export default new Vuex.Store({
  modules: {
    app,
    modal,
    user,
    cart,
    product,
    notifications
  },
  plugins: [myPlugin]
})
```

**Comment by TheDutchCoder** [comment]
Okay, so apparently NPM installs 0.8.2 instead of 1.0.0, so the docs are not inline with that.

**Comment by LinusBorg** [comment]
npm installs 1.0.0-rc.2 by default in a fresh install. the semver definition in your `package.json`probably keeps it from installing it.

<img width="421" alt="bildschirmfoto 2016-08-08 um 18 22 32" src="https://cloud.githubusercontent.com/assets/1444526/17487439/19afca78-5d95-11e6-888f-6b597be5f5ed.png">

**Comment by TheDutchCoder** [comment]
Hm, that could be the case.
I thought a manual install didn't take the semver into account, but I guess it does.

Thanks anyway, it's all sorted now!
