### ISSUE TITLE
[vuex@2.0.0-rc4] 'registerModule' with 'path' parameter (array.length > 1) looses 'state' in computed properties

### ISSUE THREAD

**Issue by karol-f** [vuejs/vuex#276]
##### _Please open examples links one at a time as there are some issues with webpackbin.com when all links are opened in background tabs at once_

When registering modules with `registerModule` and first parameter (`path`) is set to array (like ['some', 'path']), you loose `$store.state` in computed property.

- [x] Firstly check working example - http://www.webpackbin.com/NJ6JBqUtb
In `widget.js`we are using:
```
this.$store.registerModule([`widget${this._uid}`], ...)
```
There are no issues - `count` value in HTML output shows correct value.

- [ ] When we add more parameters to `path` array in `registerModule` method, `$store.state` in computed property is undefined - http://www.webpackbin.com/4JUsD9IFZ

```
this.$store.registerModule(['widgets', `widget${this._uid}`], ...)
```

As we can see, `count` value is not available in HTML output.

_BTW `widgets` path/parameter is already added to store root state (when store registers in `store.js`) so it's not an issue._

- [ ] Suprisingly, it's partly working when not using component's computed function - http://www.webpackbin.com/4yahPFUFZ. We have added `{{$store.state | json}}` to HTML and it works, while computed property not.

**Comment by ktsn** [comment]
Looks like you miss `widgets` member in your computed function?

The store has the registered module's state `state.widgets.widget1` but you try to access to `state.widget1`.

```js
  computed: {
    state() {
      return this.$store.state[`widget${this._uid}`] // <-
    },
    // ...
  },
```

**Comment by karol-f** [comment]
Thank you @ktsn . You are right. Sorry for such easy mistake!
