### ISSUE TITLE
[2.0] Move silent flag of commit method out of payload

### ISSUE THREAD

**Issue by ktsn** [vuejs/vuex#277]
Currently, silent flag of commit method is allowed in its payload, but I think it has two problem.

1. It can restrict usage of commit method because of `silent` is reserved word in payload.
2. It possibly causes breaking changes when a new option will introduce to the commit method in the future.  
  e.g. If Vuex added `disable` option to forbid later commits for a mutation (it's non sense but just example :) ), users that use `disable` property in payload would face the unexpected behavior.

### Suggestion
Separate commit options to 3rd argument.
It can avoid above problems and can clearly separate data and options.

```js
store.commit('increment', { amount: 1 }, { silent: true })

// Object style
store.commit({
  type: 'increment',
  amount: 1
}, { silent: true })
```

If it is reasonable, I would like to work for this :)

**Comment by yyx990803** [comment]
Yes, makes sense!
