### ISSUE TITLE
vuex@2.0.0-rc.4 - store.watch regression when using it before store.registerModule

### ISSUE THREAD

**Issue by karol-f** [vuejs/vuex#279]
##### _Please open examples links one at a time as there are some issues with webpackbin.com when all links are opened in background tabs at once_

When registering modules with `registerModule`, if you add `store.watch` before it, watch callbacks woun't fire (code in `widget.js`).

- [x] Working example using vuex@2.0.0-rc.3 - http://www.webpackbin.com/NJ5S9RFtW
Console logs are shown when you click button and `count` value changes.

- [ ]  Not working example with vuex@2.0.0-rc.4 - http://www.webpackbin.com/Ek--y0FFZ
There are no console logs when you click button and `count` value changes.

But when you change order of `store.watch` and `store.registerModule` callbacks fire as it should.

### Expected result
`store.watch` callbacks fire even when registered before `store.registerModule`

**Comment by ktsn** [comment]
I think it's bug of v2.0.0-rc.4.
It probably be because the inner store vm is recreated by `registerModule`.

**Comment by karol-f** [comment]
Thank you @ktsn! can I ask for a release to test changes on npm package? 

Regards!
