### ISSUE TITLE
vuex 2.0.rc.4 not work with standalone build vue/dist/vue.js(but work well with vue.common.js version)

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vuex#280]
Hi, i have tested the counter example in this repo's next branch. 
I found one bug : if I try to write root vue init code  without a render option, vue always complain:
```
Trying to access non-existent property "$store" while rendering. Make sure to declare reactive data properties in the data option. (found in component <counter>
```
The code is here for app.js:
```
import 'babel-polyfill'
import Vue from 'vue/dist/vue'          // here I must import this way, otherwise, error with "Failed to mount component: template or render function not defined." will be there
import Counter from './counter.vue'
import store from './store.js'
new Vue({
  el: '#app',
  store,
    components: {
        Counter
    } // here i'd like to init root vue instance in older way
  //render: h => h(Counter)
})
```
the code here is index.html:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vuex counter example</title>
  </head>
  <body>
    <div id="app">
        <p>this is app p tag content</p>
        <counter></counter>   
<!--  here i add the counter component manually in html page -->
    </div>
  </body>
</html>
```

Please fix it or give me workaround solution for it!
Thanks!

**Comment by fnlctrl** [comment]
What's in your `store.js`? Are you importing the same vue?

**Comment by cnweibo** [comment]
@fnlctrl , thanks for your reply.  I have import the same version vue: "standalone build vuejs version" via 
```
import Vue from 'vue/dist/vue'
import Vuex from 'vuex'
...
other code is the vuex official counter example code
```

**Comment by fnlctrl** [comment]
Did you use Vue.use(Vuex) in store.js?

**Comment by fnlctrl** [comment]
I am currently using standalone version and vuex, and encountered no problems..

**Comment by fnlctrl** [comment]
`Trying to access non-existent property "$store" while rendering.`
Are you using $store directly in your template?

**Comment by ktsn** [comment]
This may be same problem of #264.
Please try https://github.com/vuejs/vuex/issues/264#issuecomment-236948474

**Comment by fnlctrl** [comment]
Oh I see.. I'm not using vue-loader currently.
I guess @ktsn 's solution will work.

**Comment by cnweibo** [comment]
@ktsn 
@fnlctrl 
thanks for your hint, the solution mentioned by @ktsn really works for me. It is the issue of webpack vue-loader , not vuejs/vuex itself!
