### ISSUE TITLE
should add Vuex.installed init state to false rather than undefined

### ISSUE THREAD

**Issue by cycold** [vuejs/vuex#283]
Vuex as a great plugin of Vue. It should have a init state of installed. 
VueRouter has a init state VueRouter.installed is false
VueValidator has a init state VueValidator.installed is false
But Vuex doesn't have a init state Vuex.installed is undefined.

If Vuex has a installed state that can make all plugins more consistent.

```
// install route
// http://router.vuejs.org/en/installation.html
VueRouter.installed || Vue.use(VueRouter)   

// install vue-validator
// http://vuejs.github.io/vue-validator/en/installation.html
VueValidator.installed || Vue.use(VueValidator)
```

Sorry, forgive my poor English.

**Comment by fnlctrl** [comment]
1. undefined is falsy (in the example above you can treat it like false)
2. You don't need to access `installed` yourself. It is managed by the plugins.
Just do
```
Vue.use(VueRouter);
Vue.use(VueValidator);
```

**Comment by cycold** [comment]
Ok, I got it,  thanks.
