### ISSUE TITLE
在编译生命周期ready()之前不能获取到vuex:{}里面的值或者动作

### ISSUE THREAD

**Issue by mosker** [vuejs/vuex#290]
在编译生命周期ready()之前不能获取到vuex:{}里面的值或者动作，只有在ready()之后才能获取的到，是不是就是这样的，还是可以有优化的呢？

**Comment by fnlctrl** [comment]
不是的 1.0中vuex的值和动作是[在init的时候被加载的](https://github.com/vuejs/vuex/blob/master/src/override.js#L12-L18) 如果你碰到了不一样的情况，请使用jsfiddle/codepen之类的网站给出重现

**Comment by ktsn** [comment]
As @fnlctrl said.
