### ISSUE TITLE
Miss tutorial with get data from server side

### ISSUE THREAD

**Issue by netroby** [vuejs/vuex#297]
I read the document. but got problem while try to get data from server side. not the client side.

The counter increment very useless for real web application development.

For me . I need check user if it logged in. so i try to store user login data with cookie.

How can i use vuex with ajax request with server side ?

How to write the code?

```
// store.js
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

// app initial state
const state = {
  count: 0 // we need to check user loggin information here? maybe an ajax request should performance here. but i do not know how to do it 
}
```

**Comment by netroby** [comment]
I can see there be example called chat. but can not understand how it works. and i can not find async request in chat example. so  please guide me how to do it.

**Comment by ktsn** [comment]
You can use actions for async requests.
In the chat example, async requests are triggered in [actions](https://github.com/vuejs/vuex/blob/master/examples/chat/vuex/actions.js). 
When the action finishes the request, it dispatch mutation with given data.

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
