### ISSUE TITLE
v2.0.0-rc.5 `this` context in actions

### ISSUE THREAD

**Issue by Astray-git** [vuejs/vuex#298]
`this` is undefined in action function, how to access to methods like `this.$http.get`?
Or I shouldn't to access instance props in an action ?

**Comment by ktsn** [comment]
Hi, please use our [gitter chat room](https://gitter.im/vuejs/vue) or [the forum](http://forum.vuejs.org/) for asking usage questions. 
The issue list is reserved for bug reports or feature request.

FYI: you can use `Vue.http` out of vue instance or use other standalone ajax libraries like axios.
