### ISSUE TITLE
Regarding store data connection

### ISSUE THREAD

**Issue by fmoyses** [vuejs/vuex#299]
Hi. I'm facing some design issues regarding vuex for a more complex application.
I'll try to exemplify with a simpler situation.

We have a list of contacts for each customer.
This list is retrieved from an API as I switch between customers.
I have 4 components and each of them shows different information about that list.
They're rendered together, like a dashboard.

2 components show the top 10 hottest contacts on a specific attribute (like job title),
1 component shows details about the hottest one on another attribute (like page views in the company website) and
1 component shows the list ordering it on yet another attribute (like a "star rating")

All the components rely on a store that holds the contacts list and must update if the contact list is updated. 
What I want is to have separated stores for the filtered-reordered lists, that must listen to changes on the main contact store.  
Every component will listen to the correspondent store through a getter.

My doubt is how to make the stores listen to the main contacts store changes without having to nest actions to update every store.

Is there a viable solution for that? 

Thanks.

**Comment by ktsn** [comment]
Hi, @fmoyses.
Please use [our gitter chat room](https://gitter.im/vuejs/vue) or [official forum](http://forum.vuejs.org/) to ask usage / support questions.
The issue list is exclusively reserved for bug reports or feature requests.
Thanks.

**Comment by fmoyses** [comment]
Sorry about that. Already posted in the forum.
