### ISSUE TITLE
Firebase Integration 

### ISSUE THREAD

**Issue by niallobrien** [vuejs/vuex#302]
Hi, just wondering if there are plans for creating an easy to use integration with Firebase?

Thanks in advance.

**Comment by LinusBorg** [comment]
Weither or not we will officially support these or other bindings for other solutions (horizon, whatever) is still under concideration - and will alsop depend on the demand from the users. (Obviously, we can't support official bindings for every solution out there).

Meanwhile, @posva already created such a binding: https://github.com/posva/vuexfire

**Comment by posva** [comment]
Yeah, feel free to refer to vuexfire for that. I'm open to feature requests and contributions :)
@FadyMak can also help there

PS: this can be closed

**Comment by niallobrien** [comment]
Awesome stuff, thanks guys.
