### ISSUE TITLE
Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by guoerwei** [vuejs/vuex#303]
尝试了在 mutation-types.js 里定义的时候，使用Symbol()，比如SOME_ACTION=Symbol()

在actions里面dispatch会是成功的，

const test = ({dispatch}, action) => { dispatch(SOME_ACTION), action };

但是在非actions里，比如我参考vux，在router那边使用了dispatch来操作。

store.dispatch(SOME_ACTION, param)

这个时候就会报出Cannot convert a Symbol value to a string，如果不用Symbol()就可以

**Comment by fnlctrl** [comment]
显然不可以，都提示你不能把symbol转成string了。dispatch第一个参数必须是字符串。

**Comment by guoerwei** [comment]
对的，提示是这么提示的，但是感觉这里用Symbol不是挺好的么，为啥要限制String
而且在actions里直接dispatch的时候，用Symbol也是可以工作的

**Comment by fnlctrl** [comment]
有道理。。你可以提一个feature request，记得用英文。。

**Comment by ktsn** [comment]
Symbol is not supported because it cannot be serialized. See #224, reactjs/redux#4
