### ISSUE TITLE
Add module after initialization

### ISSUE THREAD

**Issue by jbruni** [vuejs/vuex#304]
Please let me know if it is possible to include a new module into the store after initial setup.

Something like:

```javascript
let store = new Vuex.Store({ modules: initialModulesConfig })

// stuff happens

store.addModule(anotherModuleConfig)
```

**Comment by LinusBorg** [comment]
You can in 2.0, not in 1.0.

> ### New API methods
>
> `store.module(path, moduleOptions)`
>
> Register a module into the store. The path argument can be either a string, or an Array of strings. When registering a nested module, its direct parent state tree must already be present.

**Comment by ktsn** [comment]
FYI, `store.module` is renamed to `store.registerModule` in rc.4

**Comment by LinusBorg** [comment]
Ooops, thanks! @ktsn

**Comment by jbruni** [comment]
Current syntax is

```
store.registerModule(path, moduleOptions)
```
