### ISSUE TITLE
Accessing store.state.enabled directly from v-if or v-show

### ISSUE THREAD

**Issue by nueverest** [vuejs/vuex#306]
Lets say my vuex store looks like this:

```javascript
var store = new Vuex.Store({
  state: {
    enabled: true
  },
  mutations: {
    TOGGLE (state) {
      state.enabled = !state.enabled
    }
  }
})
```

Now when I declare my component in HTML I use:

`<my-component v-show="store.state.enabled"></my-component>`

I tried this and it didn't work.

**Is there any way to access store.state.enabled directly?**

I had to use a computed property which seemed more verbose than I was expecting.

```javascript
computed: {
  StoreStateEnabled () {
    return store.state.enabled
  }
}
```

**Comment by fnlctrl** [comment]
this.$store is injected to components so you can just use $store in templates.

**Comment by nosus** [comment]
I don't think this is true anymore, I can use $store in my template and it works.
