### ISSUE TITLE
Unexpected token .. on mapGetters

### ISSUE THREAD

**Issue by cxlab-owner** [vuejs/vuex#314]
Hi, I', getting 'Parsing error: Unexpected token ..' error when trying to use mapGetters spread:

``` 
computed: {
  local() {},
  ...mapGetters(['a']),
},
```

but spread operator itself works, like func arg for example: ```method(...a) {}``` - works just fine

My .babelrc:
```
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```

Any ideas guys?

**Comment by fnlctrl** [comment]
That error is probably given by eslint, please check if you've set `experimentalObjectRestSpread: true`.
http://eslint.org/docs/user-guide/configuring#specifying-parser-options

**Comment by cxlab-owner** [comment]
That worked! Thanks a lot!
