### ISSUE TITLE
What is the "correct" way to sequentially call actions where one implicitly relies on the other's success?

### ISSUE THREAD

**Issue by kylestlb** [vuejs/vuex#323]
Hi,

I am working on an app where a certain collection in the store depends on the retrieved values from another collection in the store.  Currently, whenever I make a call to an action to retrieve A (the first collection), if the http request is successful, I make a call to action B in the promise resolution callback.  This seems like a code smell - is there a more 'vuex' way to chain actions?  Also, I know the actual solution is better API design, but I'm handling this in the front end for now :)

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved
for bug reports and feature requests only, so please use our dedicated
[gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/)
to ask questions. Thanks!

------

Callback problems in javascript can be solved by using promises, so you can
just return a promise in  the async action, and use `.then` in other
actions.  (Hint:ES7 async functions are even better)
