### ISSUE TITLE
Update vuex forms document with instructions on how to handle radio buttons, checkboxes and select boxes in vuex

### ISSUE THREAD

**Issue by nicolechung** [vuejs/vuex#329]
It seems like you can get `select` boxes, `radio` buttons and `check` boxes working with `:checked` but this isn't explained/documented in the `forms` document.

We managed to get select boxes working with:

```js
<select name="birth_year"
                  @change="actionYEAR"
                  :checked="year" aria-labelledby="birth_date">
            <option value="">YYYY</option>
            <option v-for="(key, value) in year " :value="value">
              {{ value }}
            </option>
          </select>
```

Radio buttons/checkboxes with

```
<input type="radio" name="frequency" :value="0" :checked="selectedFrequency === '0'" @change="updateFrequency" />
```

**Comment by ktsn** [comment]
Thank you :)
We will consider to include more info about form handling in the documentation.

**Comment by ktsn** [comment]
Rethinking about this, adding description about `select`, `radio` and `checkbox` would let the docs to be verbose and it is not essential for this section. (the behavior is just the DOM behavior)

And we sometimes bind the store state to value of `select`, `radio` or `checkbox`.

So, I think it would be better to keep the form handling section on current form.
I am sorry I could not comply with your request.

**Comment by kdekooter** [comment]
I am sorry, folks I would happily accept verbose docs over a day of fruitless googling. At the moment it is a total mystery how vuex deals with radios.

**Comment by alansaldivar87** [comment]
@kdekooter total agree with you, it's a shame. Until now haven't found something using only native vuex, but instead purposes with 3rd party plugins. Have you found something useful?

**Comment by RedShift1** [comment]
Completely agree that the docs should provide these kinds of examples. In the long term it will be easier for new devs to pick up an existing project if a standard way of handling these kinds of things is provided. Besides that, documentation is supposed to be verbose...

**Comment by johndatserakis** [comment]
I'd like to add that I have had many issues using Vuex with checkboxes. The Vuex docs show an example using text inputs - but I'm finding that the way the browser handles the `checked` toggle state of a checkbox interferes with Vuex's store.

I think it would be very beneficial to have an example showing how to simply bind a checkbox to a Vuex object/property of that object.

**Comment by GufNZ** [comment]
`<input type="checkbox" :checked="checked" :data-wug="checked"/>` renders to `<input type="checkbox" data-wug="true"/>` and not `<input type="checkbox" checked data-wug="true"/>` as expected.
