### ISSUE TITLE
Browser history doesn't work in todomvc example?

### ISSUE THREAD

**Issue by PaulCapestany** [vuejs/vuex#33]
Is browser history supposed to work properly in the todomvc example as it currently stands? Because it doesn't seem to. Or would fully functioning browser history require integrating vue-router, or something else entirely?

**Comment by yyx990803** [comment]
The example is just for demonstrating the usage of Vuex in the TodoMVC scenario, there's no routing, so no browser history support. In there future we might improve the example to demonstrate integrating Vuex with a router and persisting history state.

**Comment by PaulCapestany** [comment]
Cool, thanks for the amazingly quick reply :)
