### ISSUE TITLE
Found a way to modify store state directly

### ISSUE THREAD

**Issue by SevenOutman** [vuejs/vuex#330]
Today I find that assigning a vuex getter to a property leads to a direct modification on store state.
My code was like:
```js
    export default {
        data() {
            return {
                selectedItems: []
            }
        },
        vuex: {
            getters: {
                favorite: state => state.favorite
            }
        },
        methods: {
            edit() {
                this.selectedItems = this.favorite
            }
        }
    }
```
After i ran `edit` when I modify `selectedItems`, there's no error reporting from console, and I can see in vue-devtools that the value of `favorite` is changing, with a `vuex getter` tag still following.

Check that please.

**Comment by ktsn** [comment]
Please enable strict mode if you want Vuex to notify when direct mutation is happened out side of store.
http://vuex.vuejs.org/en/strict.html

**Comment by SevenOutman** [comment]
If it's only about strict mode, why can I still get error reports when I tried to directly modify `favorite`? The problem only happens if I assign a getter to another then modify the property its assigned to.

**Comment by ktsn** [comment]
Oh, you already enable strict mode but there are no reports only when you mutate `this.selectItems`?
If so, how do you update `this.selectItems`?
If you can, please provide a reproduction by jsfiddle and it helps us solving the problem quickly.

**Comment by SevenOutman** [comment]
No, I didn't use strct mode, and the problem won't happen under strict mode.
But I really wonder why, when i try to update `favorite`, i will get notifications, but not one when i update `selectItems`. They should be the same dont they.

**Comment by ktsn** [comment]
What error did you get? If it is `Uncaught Error: vuex getter properties are read-only.`, it is not related to strict mode because vuex getters will be registered as read-only property to the store.

**Comment by ktsn** [comment]
Read-only properties in JavaScript means "you cannot **assign** any value to this **property**", so when you get a value from a vuex getter and assign it to another property, it is no longer read-only.
In your case, `this.favorite` is read-only but `this.selectedItems` is not read-only. Then updates for `this.selectedItems` does not cause any errors.

Is this answer make sense for you?
