### ISSUE TITLE
Incorrect links in Vuex docs

### ISSUE THREAD

**Issue by andreimoment** [vuejs/vuex#332]
In the documentation at https://vuex.vuejs.org/en/index.html, the following links are incorrect in the sidebar (and correct in the body of the page):

Looking for 1.0 docs?
sidebar:  https://vuex.vuejs.org/github.com/vuejs/vuex/tree/1.0/docs
should be:  https://github.com/vuejs/vuex/tree/1.0/docs 

Release notes
sidebar: https://vuex.vuejs.org/github.com/vuejs/vuex/releases
should be: https://github.com/vuejs/vuex/releases

**Comment by ktsn** [comment]
Thank you for your report. PR would be appreciated :)

**Comment by yyx990803** [comment]
Seems to be fixed now after re-deploy.
