### ISSUE TITLE
Vuex 2.0 module's actions and getters namespacing

### ISSUE THREAD

**Issue by jxlarrea** [vuejs/vuex#335]
The documentation is quite vague regarding namespacing actions and getters from a module. Can someone please elaborate on how to achieve this?

**Comment by Namek** [comment]
I guess it's something like this:
```
export const UPDATE_PROPERTY = '*/UPDATE_PROPERTY'

export const CREATE_DAY_DATA = 'day/CREATE_DAY_DATA'
export const LOAD_DAY_DATA = 'day/LOAD_DAY_DATA'

export const FILTER_PRODUCTS = 'products/FILTER_PRODUCTS'
export const SELECT_PRODUCT = 'products/SELECT_PRODUCT'
```

where `/` splits between module name and mutation/action type name.

**Comment by jxlarrea** [comment]
@Namek honestly that convention doesn't seem too elegant. It would be good to have in the documentation some best practices when it comes to namespacing.

**Comment by Namek** [comment]
Well, then I don't know what kind of "namespacing" the docs refer. I got this from some older examples.

**Comment by ktsn** [comment]
Namespacing in the doc means adding prefix or suffix to getters, actions and mutations names to avoid name conflict.

**Comment by jxlarrea** [comment]
@ktsn Do you have some sample code with prefixed actions, getters, etc.?

**Comment by ktsn** [comment]
Like this? https://jsfiddle.net/bjahdbx5/1/

**Comment by jxlarrea** [comment]
Thank you for the code. That is exactly the result I'm trying to achieve. But it does seem that it would get extremely verbose adding this code to all actions, getters and mutations per module. Is there any way to automate the generation of the prefix either in the module.js file?

**Comment by ktsn** [comment]
Do you mean that you do not want to write `namespace` function each definition?
If so, you can just rewrite the helper function.
https://jsfiddle.net/bjahdbx5/2/

Vuex does not concern about how to define getters, actions and mutations names since it is userland issue.
We should create own helpers as our needs if we suffer to define the constants.

**Comment by jxlarrea** [comment]
Thanks for the help @ktsn. Your code helped me to create a helper utility to namespace getters, actions and mutations in Vuex 2.0 modules. This functionality really should be included in Vuex itself. Large application need this, and leaving this for the user to deal with only adds a huge amount of unnecessary boilerplate code.

**Comment by ktsn** [comment]
I think it should not be included into Vuex because it can be solved by external library and using constants is optional.
But anyway, the description of namespace in docs can be improved as you said.
We will consider to add more concrete description and some examples to docs :)

**Comment by ktsn** [comment]
The doc is updated with the description and example about namespace. 
http://vuex.vuejs.org/en/modules.html#namespacing

**Comment by jxlarrea** [comment]
Thanks @ktsn. Since namespacing is a must in large size applications, here is how we are doing it with the least amount of boilerplate code:

```
// namespace.js helper utility

function mapValues (obj, f) {
    const res = {}
    Object.keys(obj).forEach(key => {
        res[key] = f(obj[key], key)
    })
    return res
}

export default (module, types) => {
    let newObj = {};

    mapValues(types, (names, type) => {       
        newObj[type] = {};
        types[type].forEach(name=> {
            var newKey = module + ':' + name;             
            newObj[type][name] = newKey;
        });
    })   
    return newObj;
}

```

```
// types.js

import namespace from 'utils/namespace'

export default namespace('auth', {
    getters: [
        'user'
    ],
    actions: [
        'fetchUser'
    ],
    mutations: [
        'receiveUser'     
    ]
})

```

```
//module.js

import * as accountApi from 'api/account'
import types from './types'

const state = {
    user: null
}

const actions = {
    [types.actions.fetchUser]: context => {
        return accountApi.me().then(response => {
            context.commit(types.mutations.receiveUser, response)
        });
    }
}

const getters = {
    [types.getters.user]: state => state.user
}

const mutations = {
    [types.mutations.receiveUser]: (state, apiResponse) => {
        state.user = apiResponse.payload;
    }
}

export default {
  state,
  actions,
  getters,
  mutations
};
```

The above automatically namespaces getters, actions and mutations using the `module:action` format automatically, without having to manually set the types string constants.

**Comment by gyc1299339354** [comment]
Mark~You guys are so cool!

**Comment by morficus** [comment]
@jxlarrea - if I understand what you shared correctly, when using your `namespace.js`utility function, there would be no need to set `namespaced: true` in the store its self right?

**Comment by rickyruiz** [comment]
Since [Vuex 2.4.0 release](https://github.com/vuejs/vuex/releases/tag/v2.4.0), you can use the helper method `createNamespacedHelpers`.

Here's an example taken from the [docs](https://vuex.vuejs.org/en/modules.html#binding-helpers-with-namespace):

```
import { createNamespacedHelpers } from 'vuex'

const { mapState, mapActions } = createNamespacedHelpers('some/nested/module')

export default {
  computed: {
    // look up in `some/nested/module`
    ...mapState({
      a: state => state.a,
      b: state => state.b
    })
  },
  methods: {
    // look up in `some/nested/module`
    ...mapActions([
      'foo',
      'bar'
    ])
  }
}
```

**Comment by wdews** [comment]
The issue with not using `namespaced: true` would really come down to the use of something like `getters` (foreseeing a scenario where a component leverages `mapGetters` and two separate modules have an `id` prop).

**Comment by patrickdorival** [comment]
@morficus I'm wondering the same thing.
One thing I did notice was that if you change the dynamic key from `var newKey = module + ':' + name;` using a `:` to using `/` then it seems to namespace it by default.

If you leave the module namespacing set to true, then it will double namespace when using the `/` separator. 

I'm still testing it out but I think this is the way to go
