### ISSUE TITLE
Vuex 1.0.0-rc2 not update data in IE10

### ISSUE THREAD

**Issue by sparkmorry** [vuejs/vuex#337]
I have such code to get replayVideos, and fetch data from ajax request. The state is updated in mutations while watch function never triggers. Is that because of the browser compatibility?
```
    vuex: {
      getters: {
        replayVideos: state => state.replayVideos,
      },
      actions: actions
    },
    watch: {
      replayVideos() {
        lib.img()
      },
    }
```

I have search around and failed to find the compatibility of vuex. Could you please mention it in the doc?

**Comment by ktsn** [comment]
Hi, thank you for filing this issue!

> Is that because of the browser compatibility?

Vue.js reactivity system works on IE >= 9, so I think the watch should work.
Can you please provide reproduction code on jsfiddle? It helps us to solve the problem.

Thanks.

**Comment by sparkmorry** [comment]
@ktsn sorry, the project replies on some private modules which makes it not work on jsfiddle. I tried to put the replayVideos list in vue data instead of store, however the list length is not updated. The following is my template code:
```
      <div id="J_more-live" class="lr-group appear-more-videos">
        <h3 class="live-title">
          <span class="live-title-txt live-title-txt-big">replay list</span>
          <span>{{moreVideos.length}}</span>
        </h3>
        <div class="more-live-list f-justify">
          <lr-morelive-item v-for="i in 8" v-bind:more-item="moreVideos[$index]" v-if="moreVideos[$index]"></lr-morelive-item>
          <div class="lr-content-empty" v-show="moreVideos.length === 0">no more videos</div>
        </div>
      </div>
```

**Comment by ktsn** [comment]
It's OK.
How do you update the list data?

**Comment by sparkmorry** [comment]
@ktsn I fetch the data from a ajax request through a promise object (with polyfill in ie), and I do get the data. Below is the ajax function.
```
        var promise = new Promise((resolve, reject) => {
            var xhr = new XMLHttpRequest();
            var success = params.success;
            var error = params.error;
            var p = this.getParams(params.data);
            let url = params.url.split('?')[0],
                queryString = params.url.split('?')[1] ? '&' + params.url.split('?')[1] : '';

            if (params.type && params.type.toUpperCase() == 'POST') {
                xhr.open("POST", params.url, true);
                if (params.enctype == 'multipart/form-data') {
                    xhr.send(params.data);
                } else {
                    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=" + (params.charset || 'UTF-8'));
                    xhr.send(p);
                }
            } else {
                xhr.open('GET', url + '?' + p + queryString ,true);
                xhr.send(null);

            }
            xhr.onreadystatechange = function() {
                if (xhr.readyState == 4) {
                    let status = xhr.status;
                    let resp = xhr.responseText;
                    if (typeof resp == 'string') {
                        resp = JSON.parse(resp);
                    }
                    if (status >= 200 && status < 300) {
                        **resolve(resp, xhr.responseXML);**
                    } else {
                        reject(resp, xhr.responseXML);
                    }
                }
            }
        });
```
And here is how I update the data:
```
ajax({
        type: 'get',
        url: '/api/video_list/1.0',
        data: {
          accountId: lib.env.params['userId']
        }
      }).then(resp => {
        if (resp.success) {
          this.moreVideos = resp.result.data.dataList.filter(item => (item.type === 'video' && item.data.accountId != this.video.accountId)) || []; //I also tried let vm=this, not work anyway.
        }
      }).catch(err=>{
        alert(err)
      }); 
```

**Comment by ktsn** [comment]
Thank you for providing the code.
Did you certainly initialize `this.moreVideos` before fetching the data? Because there are common issue that reactive system does not work due to people forgot to initialize their data.
Also, does it works for other browsers?

**Comment by sparkmorry** [comment]
yes I did(coz I have suffered from it in alot of times), in:
```
    data() {
      return {
        showcaseIndex: 0,
        showcaseLen: 10,
        moreVideos: []
      }
    },
```

**Comment by ktsn** [comment]
Thanks, we will look into it!

**Comment by ktsn** [comment]
@sparkmorry 
I'm afraid I could not reproduce the problem from your code. The cause seems to be in other part...
Could you minimize your code that happens this problem and provide it to us executable format?
We cannot help you until we reproduce the problem in our environment...

BTW, this issue is suitable to report to Vue core repository since it happens on Vue's instance data.

**Comment by yyx990803** [comment]
What polyfill are you using? If that's causing nextTick to not fire then the polyfill is buggy.

**Comment by sparkmorry** [comment]
@yyx990803 I had [this mutationobserver-shim](https://github.com/megawac/MutationObserver.js) before (haven't deeply dive into yet, but seem like it should work in IE10). A confusion I come up when debugging vue source is the timerFunc check promise support first(native code required) and for MutationObserver is typeof check. As for my case, the problem is cause by the polyfill(switched to another polyfill, and vue works), though it's so hard to find out. Or do u think I should not set the MutationObserver polyfill global?

**Comment by yyx990803** [comment]
@sparkmorry hmm, that polyfill uses setTimeout? I'd say it doesn't even qualify as a polyfill if the behavior is not correct. You should probably use the polyfill in web-component.js. Anyway next patch we will ensure only using native MutationObserver.
