### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by tremendus** [vuejs/vuex#34]
The project failed on install for me. After cloning the repos:

```
$ npm install 

> vuex@0.2.0 prepublish /Users/xxx/yyy/aaa/bbb/vuex
> babel src --out-dir lib --presets es2015 --plugins add-module-exports

The CLI has been moved into the package `babel-cli`. See http://babeljs.io/docs/usage/cli/
```

From package.json [scripts]: 
`"prepublish": "babel src --out-dir lib --presets es2015 --plugins add-module-exports",`

This fails with an error ... but works with `npm install -g babel babel-cli` 

Additionally, the index.js file shows: 

``` 
let Vue

// then in constructor
this._vm = new Vue({
    data: state
})
```
Generates an error in console at runtime: 
`Uncaught TypeError: Vue is not a function`

**Comment by yyx990803** [comment]
This repo assume you have `babel-cli` installed globally. It should work after you do `npm install -g babel-cli`.

**Comment by zdz1993** [comment]
get

**Comment by rasliche** [comment]
Installing babel and babel-cli globally did not seem to solve the install problem for me. Any other ideas?

**Comment by zdz1993** [comment]
you can try to write in package ,like this 
![image](https://cloud.githubusercontent.com/assets/10647321/12543859/de3889c8-c36e-11e5-879e-f4cb0bcab956.png)
