### ISSUE TITLE
Bind dynamically created module with dynamically instantiated component?

### ISSUE THREAD

**Issue by Namek** [vuejs/vuex#341]
So, there are two questions around the topic:

1. how do I do bind dynamic module with dynamic component? I'd like to have separated context in component. There may be multiple instances of it, dynamically created. So there will be same getters/mutations in multiple instances, how do I make sure to call getter on specific instance pair of component+module?
2. does Vuex track module un/registration? Can I travel back in time between dynamic modules creation/destroyal?

Ad. 1st question I believe my only option is to pass module name into component through a prop and then explicitly call getters for this module. And I would have to dynamically make prefixes for names of mutations/getters.

**Comment by ktsn** [comment]
Hi, please use [the gitter](https://gitter.im/vuejs/vue) or [the forum](http://forum.vuejs.org) to ask usage question.
The issue list is reserved for bug reports or feature requests of Vuex itself and its docs.
Thanks.
