### ISSUE TITLE
Does logger.js file need to be hosted on CDN?

### ISSUE THREAD

**Issue by PeterDaveHello** [vuejs/vuex#349]
Hi all,

I'm Peter from @cdnjs, one of the most famous free and open source CDN for web libraries, we've hosted your awesome vuex for a while, we used to host all the files in the `dist` folder, and recently just found that there are two more `logger` files under `dist` since `2.0.0-rc.6`, I'm wondering if we also need to host `logger.js` (I guess not for logger.ts)? Thank you!

Best,
Peter

**Comment by LinusBorg** [comment]
Hi @PeterDaveHello,

Thanks for gettingin touch, awesome!

Moving logger.js was intentional:

> The logger is now exposed at `vuex/dist/logger.js` instead of `vuex/logger.js`. It is now built as UMD so can be used in browsers directly. It exposes the createVuexLogger global when used via <script> tags.

Since it now can used in a browser directly, logger.js should be available via CDN imho.

The Typescript typings (logger.ts) can stay out, of course.

**Comment by PeterDaveHello** [comment]
Hi @LinusBorg thanks for your reply, if it can be used in browsers directly, maybe we shuold provide minified files as the main file, what do you think?

**Comment by yyx990803** [comment]
@PeterDaveHello the logger is intended and only will be used in development mode, so non-minified is fine.

**Comment by PeterDaveHello** [comment]
@yyx990803 if it's only for development usage, I think maybe we don't need to host it?

**Comment by yyx990803** [comment]
Closing as outdated - I think it's fine to not host the logger on CDN.
