### ISSUE TITLE
Question --- Is Vuex compatible with Vue 2.0

### ISSUE THREAD

**Issue by predhme** [vuejs/vuex#350]
This is a question rather than an issue. I apologize if this is addressed in another ticket or is clearly labeled somewhere in the documentation, but is the current release of Vuex compatible with the new 2.0 version of Vue? We are considering using Vue, Vuex, and Vue Router as a replacement for Angular 1.5.

**Comment by LinusBorg** [comment]
Vuex 1.0 and Vuex 2.0 are both compatible with Vue 1.0.x and Vue 2.0

The relevant API (for Plugins) did not change at all.
