### ISSUE TITLE
Strict mode exception while updating nested array

### ISSUE THREAD

**Issue by mlanin** [vuejs/vuex#352]
I have a page where user can edit multiple segments. Every segment has a name and an array of filters that he can added/removed.

```javascript
{
  segments: [
    {
      name: 'Mac',
      filters: [
        {
          field: 'os',
          value: 'mac'
        },
        {
          field: 'browser',
          value: 'chrome'
        }
      ]
    }
  ]
}
```

Index.vue
```vue
<template>
  <div class="segments">
    <segment
      v-for="segment in segments"
      :id="segment.id"
      :name="segment.name"
      :filters="segment.filters">
    </segment>
  </div>
</template>

<script>
import Segment from './Segment'
export default {
  vuex: {
    getters: {
      segments
    }
  },
  components: {
    Segment
  }
}
</script>
```

Segment.vue
```vue
<template>
  <div class="segment">
    <input type="text" class="name" v-model="name" />
    <filters :filters="filters"></filters>
    <button @click="save()">Save</button>
  </div>
</template>

<script>
import Filters from './Filters'
export default {
  props: ['id', 'name', 'filters'],
  vuex: {
    methods: {
      updateSegment({dispatch}, id, segment) {
        dispatch(SEGMENT_UPDATE, id, segment)
      }
    }
  },
  methods: {
    save () {
      this.updateSegment(this.id, {
        name: this.name,
        filters: this.filters
      })
    }
  }
}
</script>
```

Filters.vue
```vue
<template>
  <ul class="filters">
    <li v-for="filter in filter">
      {{ filter.name }} <button @click="remove($index)">Remove</button>
    </li>
  </ul>
</template>

<script>
export default {
  props: ['filters'],
  methods: {
    remove (index) {
      this.filters.splice(index, 1)
    }
  }
}
</script>
```

Every time I remove a filter, I get `Do not mutate vuex store state outside mutation handlers.` error. And I know why, because no matter how many times I pass filters array through components properties, they still remain reactive and their change in Filters component propagates down to the vuex store that throws an error. 

Same will be with segments names in inputs. But there is an example how to handle forms in docs.

But how can I make filters work? Make separate stores for filters? But it will be a mess because there will be multiple segments with their own filters on the page... I'm stuck :(

**Comment by LinusBorg** [comment]
I'm not sure I understand what you *want* do to. 

* Do you want to remove the filter from the store?
* Or do you simply remove it from the "local" list in the filters component?

**Comment by mlanin** [comment]
@LinusBorg I want to edit list of filters locally and then by Save button click sync them to the store.

**Comment by LinusBorg** [comment]
Okay I guess I understand it now. You want to remove filters, but only apply the changes to the store once the user hits *save* in the parent component.

In this case, the usual thing I do íse use a deepClone function to make a copy of the data locally. When you save, you send that locally changed copy to the store.

*(Technically, `Filters.vue` could stay as it is, but I always like to not spread data manipulation over multiple places. Therefore, Filter.vue should only emit an event, and Segment.vue is in full control over the changes to both segments and filters - because it's also responsible for saving them)*

#### Segment.vue
```html
<template>
  <div class="segment">
    <input type="text" class="name" v-model="name" />
    <filters :filters="localFilters" @remove="removeFilter"></filters>
    <button @click="save()">Save</button>
  </div>
</template>

<script>
import Filters from './Filters'
import cloneDeep from 'lodash.clonedeep'

export default {
  props: ['id', 'name', 'filters'],
  data() {
    return { localFilters: cloneDeep(this.filters) } //cloning filters array here.
  },
  vuex: {
    actions: {
      updateSegment({dispatch}, id, segments) {
        dispatch(SEGMENT_UPDATE, id, segment)
      }
    }
  },
  methods: {
    save () {
      this.updateSegment(this.id, {
        name: this.name,
        filters: this.localFilters
      })
    },
    removeFilter(index) {
      this.localFilters.splice(index, 1)
    }
  }
}
</script>
```

#### Filters.vue
```html
<template>
  <ul class="filters">
    <li v-for="filter in filter">
      {{ filter.name }} <button @click="$emit('remove', $index)">Remove</button>
    </li>
  </ul>
</template>

<script>
export default {
  props: ['filters'],
}
</script>
```

**Comment by mlanin** [comment]
@LinusBorg I thought about such approach, but was doing it using `JSON.parse(JSON.stringify())` way. But I hoped there can be more vueish way, so to speak.

Anyway, thanks for the help! I'll try deepClone.

**Comment by LinusBorg** [comment]
Since objects and arrays are always passed by reference in Javascript, we always have to activly make a copy if we want to change such objects locally, but not in the source.

using `_.cloneDeep()` or `JSON.parse(JSON.stringify())` or another lib are all usual approaches in any app to meet that challenge.

**Comment by mlanin** [comment]
@LinusBorg one more question, if you don't mind. Am I right that in vue2 I won't have an ability to send and catch `remove` event like you did in your example?

I mean send it like this:
```vue
<button @click="$emit('remove', $index)">Remove</button>
```
And catch like this:
```vue
<filters :filters="localFilters" @remove="removeFilter"></filters>
```

**Comment by LinusBorg** [comment]
Vue 2.0 can do this - in fact, it's the only way to send events from the child to the parent as `$dispatch` was deprecated.

**Comment by mlanin** [comment]
@LinusBorg Just found the answer in docs, but your were faster :) But anyway thank you for the answer!
