### ISSUE TITLE
多个文件的Action怎么导入？

### ISSUE THREAD

**Issue by zhangjingl02** [vuejs/vuex#354]
actionsA.js
```
export const progress = ({
    commit
}, num) => {
    commit(types.GLOBAL_PROGRESS, num)
}
```

actionsB.js

```
export const getData = ({
    commit
}) => {
   console.log('getData')
}
```

store.js
```

import * as actionsA from 'actionA.js'
import * as actionsB from 'actionB.js'
export default new Vuex.Store({
    
    /**在这里怎么同时把actionsA actionsB，作为Actions选项导入进来  **/
   
  actions:[actionsA,actionsB],  /**?
    modules: {
        xxx
    }
})
```

**Comment by zhangjingl02** [comment]
补充下使用的是 vue2.0 + vuex2.0

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！

------

用ES6对象展开[(Object rest spread)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)
`actions:[...actionsA, ...actionsB]`
https://babeljs.io/docs/plugins/transform-object-rest-spread/
