### ISSUE TITLE
use vuex1.0.0-rc.2 not working

### ISSUE THREAD

**Issue by nodece** [vuejs/vuex#355]
![default](https://cloud.githubusercontent.com/assets/16235121/18994183/370deec2-8759-11e6-8127-9910d9e0fc2c.png)
in actions
![default](https://cloud.githubusercontent.com/assets/16235121/18994268/8cfc317c-8759-11e6-800a-2e85ab6b9e29.png)

in login.vue
![default](https://cloud.githubusercontent.com/assets/16235121/18994217/5c1d8826-8759-11e6-922a-921637e5896f.png)
![default](https://cloud.githubusercontent.com/assets/16235121/18994234/6d84af22-8759-11e6-9d51-b9d2898fbf99.png)

**Comment by blake-newman** [comment]
This is a little difficult to diagnose without a full reproduction, please follow the [Vue.js issue template](https://github.com/vuejs/vue/edit/dev/issue_template.md). 

Briefly an issue should contain:
- Dependency versions
- Steps necessary to reproduce the issue you are running into.
- A JSFiddle/JSBin/Codepen to demonstrate your issue. You could start with [this template](http://jsfiddle.net/5sH6A/) that already includes the latest version of Vue.

Thanks.

**Comment by nodece** [comment]
sorry , i can't use JSFiddle/JSBin/Codepen,
package.json
"vue": "^1.0.26",
"vue-resource": "^0.9.3"
"vue-router": "^0.7.13",
"vuex": "^1.0.0-rc.2"

in vuex/actions.js
![default](https://cloud.githubusercontent.com/assets/16235121/18995611/7b9626f8-875f-11e6-9144-f646685e42e1.png)
in login.vue
<form @submit.stop.prevent="login(this,email,password)">
//do....
</form>
![default](https://cloud.githubusercontent.com/assets/16235121/18995688/d04b0b32-875f-11e6-8f26-36eb059673a4.png)

error 
i click submit
![default](https://cloud.githubusercontent.com/assets/16235121/18995709/e437c266-875f-11e6-8c46-3f6be7d72459.png)
