### ISSUE TITLE
Better typings support

### ISSUE THREAD

**Issue by kristianmandrup** [vuejs/vuex#358]
Having trouble installing the type definitions using the `typings` CLI:

```
$ typings install vuex=github:vuejs/vuex/types/index.d.ts --global --save
typings WARN badlocation "github:vuejs/vuex/types/index.d.ts" is mutable and may change, consider specifying a commit hash
typings ERR! message Attempted to compile "vuex" as a global module, but it looks like an external module. You'll need to remove the global option to continue.
```

So far only got it "working" without `--global` and using commit hash:

`typings install vuex=github:vuejs/vuex/types/index.d.ts#4a6dee4a83f49dcbb24043ae1a3f08a85eb1fd45 --save`

**Comment by ktsn** [comment]
You don't need `typings` to use Vuex type definitions.
You can just use it via `npm install vuex`.
