### ISSUE TITLE
Computed properties inside stores

### ISSUE THREAD

**Issue by thelinuxlich** [vuejs/vuex#36]
This would be useful for i18n. I wouldn't need to pass down a computed property consuming the store to every component.

**Comment by yyx990803** [comment]
See http://vuex.vuejs.org/en/structure.html#extracting-shared-computed-getters

**Comment by thelinuxlich** [comment]
I still need to initialize it as computed and pass along any interested components

**Comment by yyx990803** [comment]
That's just how it would have to work - the store should only hold plain state. These standalone-computed getters are easy to compose though.

**Comment by thelinuxlich** [comment]
understood

**Comment by uptownhr** [comment]
@yyx990803 appears the link is no longer pointing to the shared computed getters example. Is there a new one?

**Comment by yyx990803** [comment]
@uptownhr this no longer applies in latest version of Vuex. See http://vuex.vuejs.org/en/getters.html
