### ISSUE TITLE
mapActions default payload value is MouseEvent when undefined is expected

### ISSUE THREAD

**Issue by chandmk** [vuejs/vuex#360]
I have a component with two buttons.  Firs onc increments the counter by 1.  Second one increments the counter by user typed amount.

I like to use a single acton for both.  Following is mysetup.  When I dispatch an action with no amount value, Vue is passing "MouseEvent" as the payload. 

**Component**

```
<template>
    <div>
        <button @click="increment">+</button>
     <div>
        <input type="text" v-model.number="amount">
        <button @click="tryincrement">increment</button>
    </div>
    </div>
</template>
```

```
methods: {
 ...mapActions([ 'decrement']),
 tryincrement() {
    this.$store.dispatch('increment', this.amount)
 }}
```

**Actions**:

```
const actions = {
    increment: ({commit}, amount) => commit('increment', amount),
}
```
**Mutations**

```
const mutations = {
    increment(state, amount) {
        state.counter += amount || 1;
}}
```

**Comment by ktsn** [comment]
Because vue will pass the Event object implicitly when you does not specify any argument for v-on function.
