### ISSUE TITLE
I need  vue + vuex + vue-router example

### ISSUE THREAD

**Issue by shijunti19** [vuejs/vuex#361]
laravel+vue
vue-hackernews-2.0:
gulp+browserify：
error：already installed. Vue.use(Vuex) should be called only once.

I need  vue + vuex + vue-router example！
where？

**Comment by shijunti19** [comment]
vue-hackernews-2.0:
gulp+browserify：
already installed. Vue.use(Vuex) should be called only once.

**Comment by LinusBorg** [comment]
Please use forum.vuejs.org for support questions.
