### ISSUE TITLE
does vuex 2.x work with vue 1.x?

### ISSUE THREAD

**Issue by beeplin** [vuejs/vuex#364]
(and how about vue-router 2.x with vue 1.x?)

I am really fond of the new vuex2 and vue-router2, but currently vue2 itself lacks 3rd-party plugin supports. can I just upgrade vuex and vue-router to 2.x and hold vue at 1.x?

**Comment by LinusBorg** [comment]
Vuex 1 and 2 work with Vue 1 and 2.

Vue-router 2 only works witjh Vue 2, Vue-router 0.7 only works with Vue 1

**Comment by beeplin** [comment]
good news! 👍

**Comment by mkdesignn** [comment]
thx god
