### ISSUE TITLE
Bug with Vuex or am I doing something wrong ?

### ISSUE THREAD

**Issue by amant** [vuejs/vuex#365]
I have a simple store with 2 properties in state, a number type and an array type
demo: https://jsfiddle.net/amantul/7qvmrx0q/

`state: {
  count: 0,
  notification: ['foo']
}` 

When I watch over `count` and `notification` inside a component, 
`newValue` and `oldValue` argument is same for notification (array type). 
And as expected they are different for count(number type). 

`...watch: {
    notifications (val, oldVal) {
      console.log('notifications:', 'isEqual', val === oldVal);
    }
 }`

My understanding of vuex/redux was it creates copies of each state change in store. 
Am I using vuex incorrectly, or this is a bug? Hope I made my question clear.

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, you don't modify the reference to `notifications`, so it stays the same (`===`). If you would do `store.state.notifications = store.state.notifications.concat(['bar'])`, then the reference would in fact change.

Vuex is different to Redux in that sense, it does not enforce immutable data and copying.

**Comment by jbruni** [comment]
@amant

In fact, it is the **same** array - this is why the comparison evaluates to **true** (despite the array now has one additional element).

It won't be the case if you were using "immutable" objects/arrays.

**Comment by jbruni** [comment]
@amant - watch a bit of this video and you will fully understand: https://www.youtube.com/watch?v=I7IdS-PbEgI
