### ISSUE TITLE
mapActions with local Component methods?

### ISSUE THREAD

**Issue by junerockwell** [vuejs/vuex#367]
I get a module build failed: SyntaxError:
![screen shot 2016-10-05 at 11 53 58 am](https://cloud.githubusercontent.com/assets/5051574/19127029/25bba80c-8af2-11e6-9cf7-aba3dbbb94b9.png)

I'm using Vuex with Vuex-Router-Sync. Versions below:
````
"dependencies": {
    "vue": "^2.0.1",
    "vue-router": "^2.0.0",
    "vuex": "^2.0.0",
    "vuex-router-sync": "^3.0.0"
  }
````

This is my `counter.js` module:
````
const state = {
  count: 0
};

const mutations = {
  increment (state) {
    state.count++;
  }
};

const getters = {
  count (state) {
    return state.count;
  },
}

const actions = {
  increment ({state, commit}) {
    commit('increment')
  }
}

export default {
  state,
  mutations,
  getters,
  actions
}
````
My main `store.js`:
````
import Vue from 'vue';
import Vuex from 'vuex'

import counter from './modules/counter';
Vue.use(Vuex);

export default new Vuex.Store({
  modules: {
    counter
  },
  strict: process.env.NODE_ENV !== 'production'
});
````

My `Page1.vue`
````
<template>
<p>{{ count }}</p>
<button @click="increment()">Increment</button>
<button @click="toggle()">Show Modal</button>
<my-modal :show="show"></my-modal>
</template>

<script>
import MyModal from '../components/MyModal';
import { mapActions } from 'vuex';

export default {
  components: {
     MyModal
  },
  computed: {
     count () {
        return this.$store.getters.count
     }
  }, 
  data() {
    return {
      show: false
    }
  },
  methods: {
     mapActions(['increment']),
    toggle() {
       this.show = !this.show;
    }
  }
}
</script>
````

The above `methods` property for `Page1.vue` gives the `Module build failed: SyntaxError`. But if change that `methods` to this:
````
methods: mapActions(['increment])
````
...there's no error.  And, I can do `@click="increment()"`. **But how do I make local component methods like `toggle()` if I have to do it this way?** 

There are times when I would want to declare local component methods. So I tried using `...` before `mapActions` that a few examples are doing:
````
methods: {
 ...mapActions(['increment']),
 toggle() {
   this.show = !this.show;
 }
}
````
I get a new error:
![screen shot 2016-10-05 at 2 45 14 pm](https://cloud.githubusercontent.com/assets/5051574/19132785/147b818a-8b0a-11e6-89d3-2f280880881c.png)

And when I click the Increment button, I get an error saying that "increment" is not defined on the instance and a TypeError that increment is not a function:
![screen shot 2016-10-05 at 2 46 57 pm](https://cloud.githubusercontent.com/assets/5051574/19132878/6e4d6cdc-8b0a-11e6-893e-e2cb8abdf499.png)

When I click the Show Modal button, I get the same error: 
![screen shot 2016-10-05 at 2 51 39 pm](https://cloud.githubusercontent.com/assets/5051574/19133005/0f32c1ba-8b0b-11e6-863a-fb59d895c58f.png)

For now, what works for me is not using `mapActions`:
````
methods: {
  increment() {
     this.$store.dispatch('increment')
  },
  toggle() {
    this.show = !this.show;
  }
}
````

**Comment by NicolasParada** [comment]
The correct way is
```js
methods: {
 ...mapActions(['increment']),
 toggle() {
   this.show = !this.show;
 }
}
```
or
```js
methods: Object.assign({}, 
  mapActions(['increment']),
  {
    toggle() {
      this.show = !this.show;
    }
  }
}
```
In the first case you need the correct [plugin](https://babeljs.io/docs/plugins/transform-object-rest-spread/).

**Comment by ktsn** [comment]
As @NicolasParada says.

**Comment by junerockwell** [comment]
I installed the Object Rest Spread (version 6.16.0) you recommended and the es2015 Destructuring (version 6.16.0) to use it. I installed them as `devDependencies`. Then modified the `.babelrc` file's `"plugins"`:
````
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime", "transform-es2015-destructuring","transform-object-rest-spread"],
  "comments": false
}
````
But I still get this error:
![screen shot 2016-10-05 at 2 45 14 pm](https://cloud.githubusercontent.com/assets/5051574/19158652/6414d5ae-8b9e-11e6-829a-956eb4a5ea85.png)
And I have `Cannot GET / ` on the browser.

**Comment by junerockwell** [comment]
Ok I fixed it! Thanks for the hint @NicolasParada!

For anyone who can't get it to work, I had to do these additional things:

So the `Webpack@2.x` template via Vue-CLI came with `babel-core@6.0.0` and `babel-preset-es2015@6.0.0`. I installed their latest versions; `babel-core@6.17.0` and `babel-preset-es2015@6.16.0`.

**Comment by emiranda04** [comment]
Great job @nicolasparada!!

**Comment by manavm1990** [comment]
Love how @nicolasparada wrote it the 'fancy' way and also the 'long' way. That makes it more clear what is going on for those of us who are not quite 'ninja status' with the ES2015/18 syntax.
