### ISSUE TITLE
Watching for state changes

### ISSUE THREAD

**Issue by sgenoud** [vuejs/vuex#37]
I was trying to watch for the change of the store, I relied on the very hacky `store._vm.$watch`. Does it make sense to use this? 

If there is no better way to do it, would you accept a PR what exposes $watch in the public API?

**Comment by yyx990803** [comment]
What are you trying to achieve? Directly watching store changes kind of defeats the purpose of Vuex.

**Comment by uwe** [comment]
I have the same question. Here is my use case: I store real-time option quotes (stock market price data). And I have complex positions (like 1 of this and -2 of that, etc.) and would like to show the sum of this equation. Before using Vuex this was easy with watchers. Now I moved to Vuex and don't know how to port this.

**Comment by yyx990803** [comment]
@uwe do the sum calculation in a computed property?

**Comment by uwe** [comment]
This is dynamic, the user can change it. So I would have to add this at runtime.

Could you please give me a hint how to achieve that? (I'm more a backend guy than JS guy.)

**Comment by yyx990803** [comment]
@uwe I'm not sure if I understand your use case - you should probably ask the question on the forum with some code samples illustrating what you are trying to do.

**Comment by sgenoud** [comment]
I had a component with a method that updated the component state asynchronously. In that case I could not rely on a dynamic property (as far as I know), I needed a method that changed a standard field. 
I wanted a change of the store state to trigger this async call – and the only way to do that was to watch for changes.

**Comment by uwe** [comment]
Regarding "do the sum calculation in a computed property?":
I now understand what you mean and also implemented it. It works!
Thanks for this suggestion.

**Comment by barnabas-szekeres** [comment]
An another use case: 

I want to store realtime the states in webstorage. Currently I use a watcher in the component and when the page reloading I check the sessionstorage and if it's exist then I load that. I think is not good approach.

Check this:
https://gist.github.com/barnabas-szekeres/391be5ca90fc145019c6

**Comment by yyx990803** [comment]
In 0.4.x you can use `store.watch(...)` which follows the same usage as `vm.$watch`.

**Comment by sgenoud** [comment]
NIce, thanks!
