### ISSUE TITLE
Why vuex2.0 action function only support one argument?

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vuex#373]
```js
actions: {
  actionB ({ dispatch, commit }, a, b) {

  }
}
```
The param b is undefined

**Comment by leaves4j** [comment]
I think actions are the handle of state exposed to user, we shouldn't limit how to user use those functions, I can understand the mutations support one param, it's a payload for state, but it is necessary to limit user to use actions with one param?

**Comment by yyh1102** [comment]
I agree with you. But i guess Vuex2.0 maybe encourage developers to define new functions in property 'methods' in vm instead of using actions directly to bind to the DOM. In this case, one payload and a couples of arguments are the same.

**Comment by ktsn** [comment]
Because variadic arguments restrict the extensibility of `dispatch` and `commit`.
We can add options to their 3rd argument in the future (e.g. `commit` already has `silent` option the 3rd argument).

**Comment by superevanzhu** [comment]
how stupid design

**Comment by tamtm** [comment]
> How stupid design,i must do more,more,more stupid things ,when migrate vuex from 1.0 to 2.0. omz!

Yes, vue is cool but vuex is so stupid
