### ISSUE TITLE
运行查看examples报错

### ISSUE THREAD

**Issue by seric705** [vuejs/vuex#374]
进入http://localhost:8080/counter/报错
app.js:1 Uncaught SyntaxError: Unexpected token import

报错代码行：
examples/counter/app.js:1 import 'babel-polyfill'

求帮忙解决

**Comment by YamiOdymel** [comment]
你的 JS 不支援 `import` 方式，你用什麼方法執行的？

**Comment by seric705** [comment]
npm run dev后，浏览器打开http://localhost:8080，之后选择页面内counter，进入http://localhost:8080/counter/，就报这个错了

**Comment by fnlctrl** [comment]
请清空node_modules后重新安装依赖包 (npm install)
