### ISSUE TITLE
How to deal with dynamic nested data?

### ISSUE THREAD

**Issue by kticka** [vuejs/vuex#377]
Hi guys, im trying to male building estimate calculator. Estimate have array of jobs. Each job have array of resources. Every resource got price and quantity. So you can calculate 'total' of resource. Jobs total is sum of its resources totals. Estimate total is sum of jobs totals. So basicaly it is 3 level tree. If i could use nested stores, I would create separated store for each job and each resource. I tried this, it worked, but in strict mode my browser dev tools crashing, so probably this isn't the right way..

**Comment by ktsn** [comment]
> in strict mode my browser dev tools crashing

What do you mean? Is this warning like `Do not mutate vuex store state outside mutation handlers `?
If so, you are trying to mutate some state in your store. Stopping it may solve your problem.

**Comment by kticka** [comment]
No it's not. I know I can't mutate state from outside. And it's not that warning. It's not warning at all. Browser crash in strict mode when I put job store in to estimate store. (Two nested Vuex.Store({}) objects) 'Stopping it' may not resolve my problem. Be cause I need to calculate totals in somehow anyway.

**Comment by ktsn** [comment]
Are you creating three stores? I guess dev tool does not assume such case and we should not do it since Vuex is rely on *single source of truth* pattern...

Why cannot you solve the thing what you want to do by (nested) modules?
Could you explain your use case and the problem you had faced more clearly with actual (simplified) codes?

**Comment by kticka** [comment]
Yes, I was trying to nest different stores. Modules aren't arrays, so I'm not sure if I will be able to iterate throught them to calculate totals.

This is simplified code/idea how I imagine everything:

```
EstimateStore = {
    state: {
        jobs: ['Array of JobStore stores']
    },

    getters: {
        total(state) {
            return state.jobs.reduce(function (carry, item) {
                return carry += item.getters.total
            }, 0);
        }
    }
};

JobStore = {
    state: {
        resources: ['Array of ResourceStore stores']
    },

    getters: {
        total(state) {
            return state.resources.reduce(function (carry, item) {
                return carry += item.getters.total
            }, 0);
        }
    }
};

ResourceStore = {
    state: {
        price: 1
        quantity: 1
    },

    getters: {
        total(state) {
            return price * quantity;
        }
    }
};
```

As you can see, I need to iterate through nested stores to access their getters. Modules seems to be static, I don't see how could I iterate through them.

**Comment by ktsn** [comment]
OK I see, in your case, I recommend you to create some classes instead of stores.
We had better to define our own models for complex data structure because Vuex does not support about data structure.

```js
class Estimate {
    constructor (jobs) {
        this.jobs = jobs
    }

    get total () {
        return this.jobs.reduce(function (carry, item) {
            return carry += item.total
        }, 0);
    }
}

class Job {
    constructor (resources) {
        this.resources = resources
    }

    get total () {
        return this.resources.reduce(function (carry, item) {
            return carry += item.total
        }, 0);
    }
}

class Resource {
    constructor (price, quantity) {
        this.price = price
        this.quantity = quantity
    }
     
    get total () {
        return this.price * this.quantity;
    }
}
```

For further question, please post to [the forum](forum.vuejs.org), I will answer for you.
If you think there is something better to include to Vuex, please create new issue as feature request.
