### ISSUE TITLE
Spread operator (...obj) in computed?

### ISSUE THREAD

**Issue by YamiOdymel** [vuejs/vuex#378]
Let's say I've got these states:

```js
    login : 
    {
        error: false
    },
    register : 
    {
        error : false,
        steps: 
        {
            ...
        }
    }
```

and I was trying to _explode_ them by using **spread operator** like this 

```
computed:
{
    ...state.register
}
```

**So I can** use the states inside of the `register` _directly_ like this:

```
<div v-show="error"> ... </div>
```

but the real situation is the **state was undefined**, so **I couldn't do something like this**,

even if I use `mapState` is still the same result (because you still cannot use spread operator in `mapState`),

is there any possible way to do this or there's no such feature?

**Comment by egoist** [comment]
The value of computed property should be a function, so you can't spread states. `mapState({})` should work in your use case.

**Comment by YamiOdymel** [comment]
Thanks for your advice but I will still have to use `register.xxx` if I use
`mapState({register: ({register} => register)`,

I have no clue about how to spread the `register` object and access my
`register.error`, `register.steps` directly.

2016年10月8日 下午7:40，"EGOIST" <notifications@github.com>寫道：

The value of computed property should be a function, so you can't spread
states. mapState({}) should work in your use case.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vuejs/vuex/issues/378#issuecomment-252420046>, or mute
the thread

**Comment by YamiOdymel** [comment]
Thanks for your advice but I will still have to use `register.xxx` if I use
`mapState({register: ({register} => register)`,

I have no clue about how to spread the `register` object and access my
`register.error`, `register.steps` directly.

**Comment by egoist** [comment]
@YamiOdymel eh.. why not `mapState({error: ({register} => register.error)`

**Comment by YamiOdymel** [comment]
@egoist If I got 6 child states then I will have to do something like this (Which is I'm trying to avoid):

```
mapState
({
    a: state => state.register.a,
    b: state => state.register.b,
    c: state => state.register.c,
    d: state => state.register.d,
    e: state => state.register.e,
    f: state => state.register.f,
    // ...
})
```

**Comment by ktsn** [comment]
@YamiOdymel 
You can pass string array to `mapState` helper.
http://vuex.vuejs.org/en/state.html#the-mapstate-helper

For further question, please use [the gitter](https://gitter.im/vuejs/vue) or [the forum](forum.vuejs.org).
The issue list is reserved exclusively bug reports and feature requests.

**Comment by YamiOdymel** [comment]
String array for `mapState` is not what I looking for, I read the documentation before,

the documentation _doesn't_ talk about how to deal with the child state by using `mapState`,

for example if I have a state like this

```
state:
{
    register:
    {
        a: ...
        b: ...
        c: ...
        d: ...
        e: ...
    }
}
```

and use the `mapState` like this:

```
computed: mapState
([
      'register.a', 'register.b', 'register.c', 'register.d', 'register.e'
])
```
It gives me nothing, 

Do I miss anything in the documentation or there's no such way to do it now?

If there's no way to do it now, I would like to make this as a feature request.

**Comment by ktsn** [comment]
> If there's no way to do it now, I would like to make this as a feature request

Yes, please.
