### ISSUE TITLE
IE浏览器报错

### ISSUE THREAD

**Issue by qq524007127** [vuejs/vuex#383]
在IE浏览器中报错，报错信息如下：vuex requires a Promise polyfill in this browser.需要怎么处理

**Comment by Alex-fun** [comment]
@qq524007127 U need a Promise polyfill. Search it in github!

**Comment by qq524007127** [comment]
不知道怎么样使用

**Comment by qq524007127** [comment]
找了一个，https://github.com/taylorhakes/promise-polyfill但是不知道怎么集成到vue项目中

**Comment by egoist** [comment]
@ktsn you can close this 😉

**Comment by suifengfengye** [comment]
how to resolve this problem?

**Comment by tonytangau** [comment]
@suifengfengye Follow the instruction here: https://babeljs.io/docs/usage/polyfill/

> To include the polyfill you need to require it at the top of the entry point to your application.
> require("babel-polyfill");

> If you are using ES6’s import syntax in your application’s entry point, you should instead import the polyfill at the top of the entry point to ensure the polyfills are loaded first:
> 
> import "babel-polyfill";

> With webpack.config.js, add babel-polyfill to your entry array:
> 
> module.exports = {
>    entry: ['babel-polyfill', './app/js']
> };

eg. if you use webpack, in `webpack.config.js` you can replace your
```
module.exports = {
  entry: {
    app: './src/main.js'
  },
```
with
```
module.exports = {
  entry: {
    app: ['babel-polyfill', './src/main.js']
  },
```

**Comment by SuperAL** [comment]
我的解决方式（两步）：
首先：
```bash
npm install es6-promise -S
```
其次，在入口文件 main.js：
```js
// 文件最上方
import 'es6-promise/auto'
```

参考：
[es6-promise](https://github.com/stefanpenner/es6-promise#auto-polyfill)
["vuex requires a promise polyfill in this browser"](https://github.com/vuejs-templates/webpack/issues/474)
