### ISSUE TITLE
Can't change select box with arrow keys in certain cases

### ISSUE THREAD

**Issue by rightaway** [vuejs/vuex#387]
I've uploaded a simple standalone project to https://github.com/rightaway/demo that explains the situation. 

If you focus the select dropdown and try to use the up/down arrow keys to change it, it doesn't work. In the console the 'oninput' does get printed though for every key press.

But if you comment out https://github.com/rightaway/demo/blob/master/src/Page1.vue#L32, then it does work. Or if you leave that uncommented but instead remove the `:class` part in https://github.com/rightaway/demo/blob/master/src/Page1.vue#L5, it does work as well.

I'm working against the latest stable Chrome, and have tried to figure out what could be causing such strange behavior but no luck.

**Comment by LinusBorg** [comment]
as this is a UI problem, this is, if anything, a bug in Vue, not vuex.

Please consider opening an issue in that repo: github.com/vuejs/vue
