### ISSUE TITLE
Working on french translation 🇫🇷

### ISSUE THREAD

**Issue by darenju** [vuejs/vuex#388]
I have decided to contribute to Vuex, but since I can't help with code (not good enough for now), translating docs seems okay.

About half of the pages are already translated, as you can see on [my repo](https://github.com/darenju/vuex/tree/translate-fr/docs/fr).

Some sentences are not translated literally as better options are possible in french.

Anyway, if any french speaker is interested, they can take a look at what's already done.

**Comment by ktsn** [comment]
👍

**Comment by ktsn** [comment]
Deployed :tada: http://vuex.vuejs.org/fr/index.html
