### ISSUE TITLE
Add description for 'mapGetters ' in doc

### ISSUE THREAD

**Issue by languanghao** [vuejs/vuex#389]
import { mapGetters } from 'vuex'
	
	export default {
		// ...
		computed: {
			// mix the getters into computed with object spread operator
			...mapGetters([
			'doneTodosCount',
			'anotherGetter',
			// ...
			])
		}
	}

Please add description for how to use `object spread operator`

Install babel plugin [transform-object-rest-spread](http://babeljs.io/docs/plugins/transform-object-rest-spread/)

Add the plugin to babel

	{
		"presets": ["es2015"],
		"plugins": ["transform-object-rest-spread"]
	}

**Comment by ktsn** [comment]
It is already described on [the state section](http://vuex.vuejs.org/en/state.html).
And we won't add about the detail of it because it's just ECMAScript feature.
