### ISSUE TITLE
VueX store not injected into child components

### ISSUE THREAD

**Issue by AdamNiederer** [vuejs/vuex#393]
Hi there,
It looks like VueX's `$store` injection into Vue components is only accessible from child components of the root component, and not children of those components' children.

For example, with a component structure of `root -> cart -> cartSubcomponent`, any children of `cart` will not have `$store`.

Here's my root component invocation

```coffeescript 
Vue.use(VueX)

new Vue
  el: '#app',
  store: require "store.coffee"
  render: (render) => render require "./root.vue"
```

Is this intended? It's terribly inconvenient.

**Comment by ktsn** [comment]
All descendants should be injected a Vuex store.
Could you provide a reproduction for this?

**Comment by LinusBorg** [comment]
did you by any chance do this: `import vue from 'vue/dist/vue'` ?

**Comment by AdamNiederer** [comment]
My apologies, I was importing a `VueX.store` (rather than `VueX.Store`) and it was somehow uncaught in the build process. No idea why it was working in the root component, but it's fixed now.

**Comment by lixinliang** [comment]
> version
```
vue 2.1.3
vuex 2.0.0
```

> html file
```html
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="format-detection" content="telephone=no,address=no,email=no">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <title> <%- title %> </title>
<body>
    <app></app>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.3/vue.min.js" charset="utf-8"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vuex/2.0.0/vuex.min.js" charset="utf-8"></script>
    <script src="js/index.js" charset="utf-8"></script>
</body>
</html>
```

> js file
```js
import test from './index/test.vue';

let store = new Vuex.Store({
    state : {
        test : '',
    },
});

window.vue = new Vue({
    store,
    el : 'app',
    render : ( createElement ) => createElement(test),
});
```

> vue file
```vue
<script>
export default {
    beforeCreate () {
        console.log(this.$store);
    },
};
</script>

<template>
    <div id="app">test</div>
</template>
```

> run time

![image](https://cloud.githubusercontent.com/assets/9375027/23194678/850ad8d0-f8ea-11e6-9ff6-3e7e71c10d7d.png)
