### ISSUE TITLE
What is the meaning of "Use Vue.set(obj, 'newProp', 123), or -"?

### ISSUE THREAD

**Issue by dear-lizhihua** [vuejs/vuex#396]
From: Vuex - Mutations #Mutations Follow Vue's Reactivity Rules
What is the meaning of "Use Vue.set(obj, 'newProp', 123), or -"?
"Use Vue.set(obj, 'newProp', 123), or -"
This may be a problem with the documentation. I think ", or -" is also superfluous.

Well, why not make it like this?

- Use Vue.set(obj, 'newProp', 123).
- Or replace that Object with a fresh one. For example, using the stage-2 object spread syntax we can write it like this:

**Comment by fnlctrl** [comment]
That is valid English.
