### ISSUE TITLE
Vuex without mutation_types. See proposal

### ISSUE THREAD

**Issue by happierall** [vuejs/vuex#398]
Apps with mutation_types very ugly and monsters.
Look, without:
```javascript
// Module counter
const counter = {
  state: { count: 0 },

  getters: {
    count (state) {
      return state.count
    }
  } 

  actions: {
    increment ({ commit }) {
      commit("counter.increment")
    }
  }

  mutations: {
    increment (state) {
      state.count++
    }
  },

}
```

```javascript
// In component
export default {
   // ...
   methods: {
    ...storeActions([ // instead mapAction (more cleaner)
      'counter.increment' // or { increment: 'counter.increment' }
    ]),
     ...storeGetters([ // instead storeGetters
      'counter.count' 
    ]),
  }

  mounted() {
    this.counter.increment()
    console.log(this.counter.count)
  }
}
```

**Need changes in Vuex:**
 - prefix all keys in loaded module (increment -> counter.increment)
 - mapActions, mapGetters replace name to storeAction, storeGetters 
 - update module registraion for write nested names (nested objects, not string like this "module.action": 
``` javascript
// this.$store.dispatch('counter.increment') 
let _type = type.split('.')
if (_type.length > 1) {
   let module, key = _type[0], _type[1]
   var action = getModuleAction(module, key)
} else {
   var action = getAction(type)
}

// ... other like before
```

**Comment by ktsn** [comment]
Hi, thanks for your opinion.

> prefix all keys in loaded module (increment -> counter.increment)

This seems to be duplicate to #380. Please move on it and leave your opinion ;)
And also, automatic prefixing by module name is rejected the beginning of 2.0 design. #236 

> mapActions, mapGetters replace name to storeAction, storeGetters

We cannot accept this change because it is unnecessary breaking change.
BTW, I think helpers' name are intuitive because they map (state|getters|actions|mutations) to a component.

> update module registraion for write nested names (nested objects, not string like this "module.action"

I'm not sure about this. Looks like a proposal for internal implementation and does not change userland API?

**Comment by happierall** [comment]
I understood you. It will break API.

**Comment by happierall** [comment]
But It will more comfortable, than now.
Vue = comfort framework, isn't? 
May be add on the next version?

**Comment by ktsn** [comment]
I'm not sure if this is worth changing while introducing confusion to current users.
I think current name is clear enough. Why do you want to change the helper names?

**Comment by happierall** [comment]
Pls forget about change name.
Just need nested names of (actions, getters, mutations) like "counter.increment", not the "counter/increment".
It's not work just now, because, private function written ugly:
```javascript
// https://github.com/vuejs/vuex/blob/dev/src/index.js#L183
function resetStore (store) {
  store._actions = Object.create(null)
  store._mutations = Object.create(null)
  store._wrappedGetters = Object.create(null)
  const state = store.state
  installModule(store, state, [], store._options, true)
  Object.keys(store._runtimeModules).forEach(key => {
    // key.split('.') it's break name like 'counter.increment'
    installModule(store, state, key.split('.'), store._runtimeModules[key], true) 
  })
  resetStoreVM(store, state)
}
```

**Comment by happierall** [comment]
Huh, dot separated modules have difficulties with current API.
Need create other store-pattern, not flux style. 
I believe, that it's possible.

**Comment by happierall** [comment]
Look, live example [dotted-vuex](https://github.com/happierall/dotted-vuex)
