### ISSUE TITLE
Add 'lazy load' in module

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vuex#407]
I find the file's size is bigger with the project increases in size, why not support lazy load in module?
code like this:
```js
const store = new Vuex.Store({
  modules: {
    a: resolve => resolve(moduleA),
    b: moduleB
  }
})
```
There maybe also have a problem with the right loading timing in this way, but if we add namespace in module , we could solve this problem .

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
I believe we already have dynamic module registration for that.
http://vuex.vuejs.org/en/modules.html#dynamic-module-registration
You only need to lazy load the module and then register it dynamically.
