### ISSUE TITLE
[feature request] deep watch over state

### ISSUE THREAD

**Issue by KingMario** [vuejs/vuex#408]
For example, while fetching a product info from a shopify store, I'd like to insert it to a products field in the state, but the insertion doesn't trigger a responsive update of DOM.

A clone-n-re-assign of the products field will fix it, but I'd like to have an official solution to this problem.

Thx.

**Comment by ktsn** [comment]
Vuex already do that.
Make sure to follow Vue's reactivity rules when you update the state.

http://vuex.vuejs.org/en/mutations.html#mutations-follow-vues-reactivity-rules
