### ISSUE TITLE
setTimeout make an error

### ISSUE THREAD

**Issue by changexbc** [vuejs/vuex#41]
`Uncaught Error: [vuex] Do not mutate vuex store state outside mutation handlers.`
use `Vuex.createLogger`

when I change the state in an `setTimeout` function  in mutation

like this:
```javascript
import { SET_MSGTIP } from '../mutation-types'

// initial state
// shape: [{ id, quantity }]
const msgTipInitialState = {
    text:''||'😂',
    show:false,
    timer:0
}

// mutations
const msgTipMutations = {
    [SET_MSGTIP]({ msgTip }, text) {
        clearTimeout(msgTip.timer)
        msgTip.text = text
        msgTip.show = true
        msgTip.timer = setTimeout(() => {
            msgTip.show = false
        },2500)
    },
}

export { msgTipInitialState, msgTipMutations }
```
Is unable to change state in the setTimeout method ?

**Comment by skyrpex** [comment]
Mutations cant be async... You should do the async thingy using an action

**Comment by changexbc** [comment]
@skyrpex thank you

**Comment by changexbc** [comment]
I change the state use action but still have a problem

like this 

```javascript
const setMsgTip = ({ dispatch, state }) => {
  dispatch(types.SET_MSGTIP)
  setTimeout(() => {
     state.msgTip.show = false
  },2500)
}
```

**Comment by yyx990803** [comment]
This is the point: separating async and actual state mutations. Otherwise you never know when the hide message thing happened.
