### ISSUE TITLE
vuex2 in webview of android4.4.2 cannot initialize

### ISSUE THREAD

**Issue by itfkaps** [vuejs/vuex#415]
vuex2 in webview of android4.4.2 cannot initialize, it makes the hold project failing to run

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

**Comment by ktsn** [comment]
Are you using `Promise` polyfill? Vuex requires `Promise` and Android 4.4.2 does not seem to support it in native.

**Comment by itfkaps** [comment]
Thanks

**Comment by ziolau** [comment]
@ktsn thanks for this information
