### ISSUE TITLE
[Docs] Incorrect description about dispatch method

### ISSUE THREAD

**Issue by jonathan-roy** [vuejs/vuex#417]
Is is said in the doc that:

> The first thing to know is that store.dispatch returns the value returned by the triggered action handler, so you can return a Promise in an action.
> 
> Dispatch: Dispatch an action. Returns the return value of the triggered action handler, or a Promise if multiple handlers are triggered.

It seems like actually every call to dispatch() returns a Promise even when there is only one handler which does not return a Promise.

**Comment by ktsn** [comment]
Actual behavior is correct. We'll fix the docs later.
Thanks for your report :)

note:
http://vuex.vuejs.org/en/actions.html#composing-actions
http://vuex.vuejs.org/en/api.html#vuexstore-instance-methods
