### ISSUE TITLE
How to watch any state change and then run callback function?

### ISSUE THREAD

**Issue by dariuszsikorski** [vuejs/vuex#419]
I would like to implement following code:

```
storage.onChange(function (key, from, to) {
  /* example values:
      key - 'storage.myKey1.mySubkey'
      from - 'my name is Ben'
      to - 'my name is Mark'
   */

  localStorage.setItem(key, to);
});
```

**Comment by fnlctrl** [comment]
http://vuex.vuejs.org/en/api.html#vuexstore-instance-methods

**Comment by dariuszsikorski** [comment]
@fnlctr I have seen that, thanks. What store.subscribe returns is a state of entire store with all it's key/value pairs, what if i want to get the value which actually changed?

```
store.subscribe((mutation, state) => {
  console.log('mutation.type: ', mutation.type) // reutrns 'increment'
  console.log('state: ', state) // returns all the data in store
})
```

**Comment by fnlctrl** [comment]
> watch(getter: Function, cb: Function, options?: Object)

> Reactively watch a getter function's return value, and call the callback when the value changes. The getter receives the store's state as the only argument. Accepts an optional options object that takes the same options as Vue's vm.$watch method.

> To stop watching, call the returned handle function.

**Comment by dariuszsikorski** [comment]
Both `.subsribe()` and `.watch()` return state of entire store, not the changed value.
![Image](https://www.evernote.com/l/APTJunP15iZLq4OLkAZS59YleA69GAEQlMA)

**Comment by fnlctrl** [comment]
The point is people may need other values from the state inside the callback, that's why the state is passed, instead of just the changed value. Since you already know what value you're watching, it's trivially easy to get the value from the state.

**Comment by dariuszsikorski** [comment]
Ah, so it's intended to watch only the picked values.

What I'm writing is the realtime mirror of Vuex storage in localStorage, so every opened tab would have access to the same data. Rewriting entire store when single counter value is changed sound like not a good idea, that's why i need to pick only this data which actually has changed, no matter what key-value pair are in store that is and how deep it's nested.

So my conclusion is that on every store change i should compare the Vuex state with all the data in localStorage, after comparison is finished - pick only the ones which changed and write them to localStorage once again. Repeat that process while any state change occurs.

Other option is to loop through all states in store when application is loaded, and then set watcher for every value.

**Comment by simplesmiler** [comment]
@dariuszsikorski why not transmit mutation records instead of state?

**Comment by dariuszsikorski** [comment]
@simplesmiler You mean commiting changes and sending the change event to another tab? If so, how will i know what parameters did i pass to mutation commit. Also when i would open second tab 5 minutes later it would synchronize only with the future commits, not this which have been already made.

**Comment by simplesmiler** [comment]
You would send mutation name and the payload (assuming it's possible).
Regarding a new tab, it's much easier to send current state once when the new tab is opened, rather then syncing continuously.

**Comment by dariuszsikorski** [comment]
@simplesmiler your idea is very good! It could be done this way.
Subscription methods gives both _mutation.type_ and _mutation.payload_ information.
