### ISSUE TITLE
what u choose coding convenience or robust 

### ISSUE THREAD

**Issue by zppro** [vuejs/vuex#423]
i don't know how many guys use strict mode to vuex in dev?
i found that the document give the way use strict for v-model binding is too verbose.
you know for form binding in a view ,there's more than ten fields to use data binding.
can provider one helper function like  

> mapGetters

 to use in `computed` properties and let us contiue use
`<input v-model="obj.message">`

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!

**Comment by zppro** [comment]
ok,sure
