### ISSUE TITLE
2.0 from list view to details view auto scroll

### ISSUE THREAD

**Issue by zppro** [vuejs/vuex#425]
details.vue
```
<template lang="jade">
  .product-details
    {{ticket.introduction_url}}
    router-view(name="info" , :product="scenicSpotInDetails")
    router-view(name="intro", :introduction-url="scenicSpotInDetails.introduction_url")
</template>

<script>
  import { mapGetters, mapActions } from 'vuex'
  export default {
    data () {
      return {
        ticket: {}
      }
    },
    computed: {
//      ticket () {
//        return this.scenicSpotInDetails
//      },
      ...mapGetters(['scenicSpotInDetails'])
    },
    beforeRouteEnter (to, from, next) {
      next(vm => {
        vm.fetchScenicSpotInfo(to.params).then(p => {
          vm.ticket = vm.scenicSpotInDetails
          console.log(vm.ticket)
          console.log('vm.ticket')
        })
      })
    },
//    created () {
//      this.fetchScenicSpotInfo(this.$route.params).then(() => {
//        this.ticket = this.scenicSpotInDetails
//      })
//    },
    methods: {
      ...mapActions(['fetchScenicSpotInfo'])
    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="less" scoped>
  .product-details {
    width:100%;
  }
</style>

```
strangely when i use 

> scenicSpotInDetails

 to bind the subView's prop 

> product

 and the view is always on the top,and change it to the 

> ticket

 to the subView's prop 

> product
the view is not on the top
what's wrong with it?
the only difference's between 

> scenicSpotInDetails

 and 

> ticket

 is that

> scenicSpotInDetails

 is the vuex's getter and 

> ticket

 is the local data assigned by 

> scenicSpotInDetails

**Comment by ktsn** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines).
The issue list is exclusively reserved for bug reports and feature requests.
We encourage you to ask your question on our [forum](http://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue).
Thanks.
