### ISSUE TITLE
Flow definitions

### ISSUE THREAD

**Issue by mickdekkers** [vuejs/vuex#432]
Are [flow](https://flowtype.org/) definitions planned for vuex?
The vue repo [has definitions](https://github.com/vuejs/vue/tree/dev/flow), so it would be great if vuex were to have them too.

**Comment by ktsn** [comment]
Yeah, I'm actually thinking about that. It's nice idea.
/cc @yyx990803

**Comment by scottbedard** [comment]
+1 I'd like to see these as well

**Comment by retrocede** [comment]
+1 here as well!

**Comment by GoodeUser** [comment]
+1

**Comment by achiandet** [comment]
+1

**Comment by yyx990803** [comment]
@ktsn feel free to go ahead!

**Comment by piehei** [comment]
I found this: https://github.com/carney520/vue-flow-definitions
Seems to have definitions for "vue2.x/vue-router/vuex"

**Comment by griest024** [comment]
What do you think about adding flow to the source itself? libdefs are much harder to maintain.

**Comment by kiaking** [comment]
We'll be closing this issue since it's a very old one, and at least for now, committing mutation inside Vue Component is really up to developers.

**Comment by sobolevn** [comment]
Just for the record: here's the working set of definitions for `vue@2`, `vuex` and `vue-router`.
https://github.com/sobolevn/vue-flow-typed

It is not perfect, but works.

However, I recommend to use [TypeScript](https://github.com/wemake-services/wemake-vue-template) instead.
