### ISSUE TITLE
Setting computed property value to data.

### ISSUE THREAD

**Issue by san4io** [vuejs/vuex#435]
Holla,
I have some issue with user profile page.
In that page user can change email, password and some settings.
I'm using Vuex to store user state, what I want is to grab user data from store, and set some properties to form which contains some inputs and checkboxes.
```
        data() {
            return {
                form: {}
            }
        }
        computed: {
            user() {
                return this.$store.state.user;
            }
        },
        mounted() {
            this.form = this.$form({
                email: this.user.email,
                settings: this.user.settings,
                password: '',
                password_confirmation: '',
            })
            console.log(this.user, this.form);
        }
```
![image](https://cloud.githubusercontent.com/assets/12079341/19875605/b8afa552-9fd6-11e6-97c2-75de3a34efea.png)

What is interesting is that in this.user i have email and settings values, while in this.form they are missing. 
I'm 100% sure that I'm doing something wrong, maybe you can help me?

P.S. I know workaround just to call API and set needed data, but I want to get it from store, so i could save one request. Ha ha. :)

P.P.S. this.$form - is Vue-Laravel-Validator plugin

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!
