### ISSUE TITLE
Directly changing the state doesn't throw an error. [Is this expected?]

### ISSUE THREAD

**Issue by kiran916vanam** [vuejs/vuex#440]
I have a hotel object in state. Hotel has pricing array & each pricing object has rooms array.
``` 
hotel: {
    pricing: [ 
           { rooms: [ ] },
       ],
}
 ```
In my vue, I am deep copying the hotel object into localHotel object and while adding a pricing object, I mistakenly added the same object into the state's hotel object & localHotel object.

Now, when I add a room to the pricing object in localHotel object, it is reflecting in the state's hotel object and vuex doesn't throw any error/warning  as the state is being modified outside mutations.

Is this behaviour expected?

**Comment by ktsn** [comment]
If you enabled strict mode, it's not expected behavior.
Could you provide a live reproduction of this by jsfiddle?

**Comment by kiran916vanam** [comment]
Vuex throws error on enabling strict mode. Thank you @ktsn.
