### ISSUE TITLE
Vuex Relational Logic

### ISSUE THREAD

**Issue by mcordingley** [vuejs/vuex#441]
I have a project where I need to build up and dynamically manage relations between my Vue models. I have [a rough working model](https://gist.github.com/mcordingley/3f9322be2f33ea8ed0a90f0bcbd2141b) implemented outside of Vuex, but would like to formalize it, hammer out greater usability and features, and integrate it into Vuex so others can make use of it, be it as a plug-in or integrated into the base.

How should I proceed with building this? And, is anyone else interested in helping me to work out the kinks in it? JavaScript feels more like a second language to me, so the help of someone who works more extensively in it would help expedite the process.

My thoughts with regard to what I've built and where it needs to be:

- The code works by creating a map of id to object for each registered object type that it uses to look up related models whenever a model gets added or updated. It then sets a direct reference to that related object and registers itself in an array on the related object to make the relationship two way. Unfortunately, this does preclude relationship types that are one-to-one or many-to-many.
- Vuex, like Vue, doesn't mandate much about how the data appears. This does. That may be a problem and it'd be nice to move to a more data-agnostic approach, though the notion of unique identifiers cannot go away entirely.
- The code as it stands cannot handle when one type of object has multiple relations to another type of object. This is currently a blocker on one of my projects.
- A very-nice-to-have is for the code that resolves a related object to make use of Promises and user-supplied callbacks to fetch a local copy of the related object if it exists in the store and fall back to the potentially asynchronous callback to fetch the missing object.

**Comment by ktsn** [comment]
Hi, @mcordingley. Thank you for your interest in this project.

Just clarify, what problem are you facing concretely? As you said, Vuex does not have concern for data model itself so much but manages data flow. So, I think you can loosely couple your store and Vuex somehow. For example, actions can query or save data related to each Vuex module like ajax request with `RelationalStore`.

**Comment by LinusBorg** [comment]
@mcordingley Is this issue still relevant to you? It has been inactive for over a month now.

If not, I will close it.

**Comment by mcordingley** [comment]
It is, but I don't think it's going to end up in scope for Vuex, per @ktsn's comment.

**Comment by LinusBorg** [comment]
Okay, then I will close this.

Maybe a discussion on the [forum](http://forum.vuejs.org) would be better?

**Comment by mcordingley** [comment]
Yeah, it seems like something that could use input from multiple people for better definition.
