### ISSUE TITLE
Questions SPA

### ISSUE THREAD

**Issue by GlauberF** [vuejs/vuex#445]
Hello,
I'm new to VUE.js and VUEX development precisso develop a SPA to communicate with my api done in lumen, like some material, videos, to assist me in building des from beginning to end of the SPA, if the Portuguese- language en best, can not be English.

**Comment by ktsn** [comment]
Hi, @GlauberF 
Please use our [forum](https://forum.vuejs.org) or [gitter](http://gitter.im/vuejs/vue) to ask usage/support question.
The issue list is exclusively reserved for bug reports and feature requests.
Thanks.

**Comment by vinicius73** [comment]
@GlauberF for portuguese help you can use we cominutes also
telegram https://telegram.me/vuejsbrasil
slack http://slack.vuejs-brasil.com.br/
facebook https://www.facebook.com/groups/vuejsbr/

we will be happy in help you
