### ISSUE TITLE
[Docs] Russian Translation

### ISSUE THREAD

**Issue by gbezyuk** [vuejs/vuex#446]
We're currently close to finishing Russian translation for the core library documentation. Vuex docs are next in the queue, I guess. So, first of all, I need to ask: is anybody working on the translation already?

See #447 for details on work in progress, if there were no one before us.

**Comment by gbezyuk** [comment]
Translation is completed, #447 is basically ready to be merged. There still may be some minor typos, though, but I've called people for proof-reading, so hopefully nothing will hide from their eyes.

**Comment by ktsn** [comment]
It's already deployed. Thank you so much!
