### ISSUE TITLE
Return value in actions

### ISSUE THREAD

**Issue by jianfei** [vuejs/vuex#46]
I tried to return some value in actions. But i found out that the value received in components is always undefined. (For some reason I don't want to use states here.) Is it a bug?

**Comment by yyx990803** [comment]
You should not care about the return value of actions. They should be fire or forget. Maybe it's better to explain your reason why you don't want to state. If you don't want to use state then why use Vuex?

**Comment by jianfei** [comment]
Sorry, I didn't explain myself clearly. I am using state for the project, but for this one particular action, I  try to do some operations on the state and local storage, and then return success: true / false.  I just think that it will be more convenient if actions can return value.

**Comment by yyx990803** [comment]
So what do you plan to do when you get the success result? If you are applying more side effects, then the success/failure should both be explicit mutations and be dispatched inside that action you just called.

An [example](https://github.com/vuejs/vuex/blob/master/examples/shopping-cart/store/actions.js#L6-L14): when we call the `checkout` action, we don't expect a return value or give it a callback to know whether it succeeds - instead, it will dispatch corresponding mutations.

**Comment by jianfei** [comment]
Okay. I think I didn't follow the data flow of vuex very well. I just need to improve my coding. Thanks a lot, 尤大大.

**Comment by CodeLookBook** [comment]
Is there possibility to return Promises  from Actions or Mutations?

**Comment by Nicholaiii** [comment]
@CodeLookBook Yes, but even better, you can use async/await: [https://vuex.vuejs.org/en/actions.html#composing-actions](https://vuex.vuejs.org/en/actions.html#composing-actions)

**Comment by habemusne** [comment]
I am interested in this question as well. With limited knowledge in Redux or Vuex, I am concerned about security of redux/vuex.

I have some contents on the webpage that are supposed to be visible only by logged in users. In order to simplify the backend code, I want to control this visibility on the frontend rather than on the backend. Now I want to check "whether user is logged in" in Vuex

Since this is a Vuex action, I can't simply return a boolean value -- I have to store this boolean in the state, and fire a mutation to mutate this state. I am just wondering if hackers are able to mutate the state themselves in the browser.

**Comment by xlcrr** [comment]
A response from an action would be nice because it doesn't seem possible to mutate a query string from vue-router from inside an action. This is particularly true when updating query strings dynamically.

**Comment by the-owl** [comment]
I think that returning values from actions can actually be useful in some cases. In my application there are global modals that are controlled via VueX store. An action is fired to open a modal, and I wanted to return some kind of modal ID from action. This ID could be later used as a "handle" to control this modal, query its state, etc. Also, this will allow to implement wait-for-close behavior without storing `onClose` callbacks in store.

**Comment by Nicholaiii** [comment]
> I think that returning values from actions can actually be useful in some cases. In my application there are global modals that are controlled via VueX store. An action is fired to open a modal, and I wanted to return some kind of modal ID from action. This ID could be later used as a "handle" to control this modal, query its state, etc. Also, this will allow to implement wait-for-close behavior without storing `onClose` callbacks in store.

You can store handles in Vuex, maybe in a lookup table fashion, and subscribe to mutations for your wait-for-close?

**Comment by ssanyal** [comment]
> So what do you plan to do when you get the success result? If you are applying more side effects, then the success/failure should both be explicit mutations and be dispatched inside that action you just called.
> 
> An [example](https://github.com/vuejs/vuex/blob/master/examples/shopping-cart/store/actions.js#L6-L14): when we call the `checkout` action, we don't expect a return value or give it a callback to know whether it succeeds - instead, it will dispatch corresponding mutations.

take is use case , where the submit cart action creates an order through a rest service which generates the unique order id. the response from the backend service can be added to the state through the mutation , however how will the component get the order id (yes getter can be used but what if the order is an Array and it contains the previously created orders , the getter should be a lookup by order id , but to use the getter the component method needs to get the order id reference after dispatching the action to the store) whats the best practice here ?
