### ISSUE TITLE
Doc section on testing mutations would benefit from an example of using constants for mutator names

### ISSUE THREAD

**Issue by kastork** [vuejs/vuex#461]
The doc section on unit testing mutations does a good job of explaining how to test mutations when they are defined directly as object properties, but it doesn't show how to test them when you use constants to define mutation types, like

```javascript
// store/mutation-types.js
export const RECEIVE_TITLES = 'RECEIVE_TITLES'

// store/index.js

import * as mt from './mutation-types'

// ...

const mutations = {
  [mt.RECEIVE_TITLES]: function (state, { titles }) {
    state.titles = titles
  }
}
```

The tests in the vuex repository all create their own store just for testing and then "commit" rather than just calling the mutator.  I don't see any mutator tests in example projects like Hacker News or shopping-cart.

**Comment by ktsn** [comment]
Why is this necessary? I think you can just replace string literal with constant.

**Comment by kastork** [comment]
The current docs have you call the mutator directly as a function (the store, or a mock for it, is not part of the approach). If you followed the docs, but  substituted the constant for the function name you would get something like this:

```javascript
mt.RECEIVE_TITLES(state, { titles:["one","two"] })
```

or this

```javascript
'receiveTitles'(state,  { titles:["one","two"] })
```

Also. I don't think this would work either:

```
export const mutations = {
  [mt.RECEIVE_TITLES]: function (state, { titles }) {
    state.titles = titles
  }
}
```

**Comment by ktsn** [comment]
Why not write like this:

```js
import * as mt from './mutation-types'
import { mutations } from './store'

mutations[mt.RECEIVE_TITLES](state, payload)
```

**Comment by kastork** [comment]
I'll try it, thanks
