### ISSUE TITLE
store.state.module.property and store.state.module.getter

### ISSUE THREAD

**Issue by titouandk** [vuejs/vuex#463]
We can write this:
`store.state.module.propety`

But we cannot write this:
`store.getters.module.getter`

I'm asking myself why are getters put on a common namespace:

`store.getters.gameIsActivated`
`store.getters.userIsActivated`

and not namespaced like:

`store.getters.user.isActivated`
`store.getters.game.isActivated`

Global namespacing is not (so) strange for setters (commits & actions). But I don't see the utility for getters.

**Comment by ktsn** [comment]
This is discussed a number of times in the past. 
https://github.com/vuejs/vuex/issues/385#issuecomment-252910990
