### ISSUE TITLE
Get the wrong data when use mapGetters

### ISSUE THREAD

**Issue by yeyuqiudeng** [vuejs/vuex#464]
In vuex, the data is like this
![1](https://cloud.githubusercontent.com/assets/10278227/20453449/9eb03994-ae60-11e6-9a9b-461458d1d701.png)

when i use mapGetters，the data is like this

![2](https://cloud.githubusercontent.com/assets/10278227/20453451/bd8b36ac-ae60-11e6-9dae-7c2101851851.png)

The ParentID totally change and all the ParentID become the same one(`10001`).

here is my getter

```
areaList: (state) => {
        console.log(state)
        return state.baseLookUp.areaList
    },
```

actions,use lodah `differenceBy`
```
getAreaList: ({commit,state},pid) => {
        const areaList = state.baseLookUp.areaList
        ajax.getRegionList(pid).then((result) => {
            commit(types.GETAREA,differenceBy(result,areaList,'RegionID'));
        })
    },
```

mutations
```
[types.GETAREA](state,areaList) {
        state.areaList.push(...areaList)
    },
```

state
```
const state = {
    areaList: [],   // 所有地区
}
```

computed

```
...mapGetters([
                'areaList',
            ]),
```

But when i defined the data directly in state, it works well. Is there anything wrong

**Comment by ktsn** [comment]
Could you provide minimal reproduction of this by jsfiddle, codepen or so on?
Github project is also ok.

**Comment by yeyuqiudeng** [comment]
@ktsn i'm sorry, i make a stupid mistake, when i use filter, i use '=' instead'===', so the 'ParentID' change
