### ISSUE TITLE
Would you recommend to create action type?

### ISSUE THREAD

**Issue by standup75** [vuejs/vuex#466]
It is recommended in the doc to create a mutation-types.js file containing all the available mutation for a store (as shown in the [shopping cart example](https://github.com/vuejs/vuex/blob/dev/examples/shopping-cart/store/mutation-types.js))
Since Actions are also global to the store, wouldn't it make sense to also create an action-types.js file for the same reason?

**Comment by ktsn** [comment]
Yes, if you think it worth creating, you should do that. But it is totally optional.

**Comment by standup75** [comment]
it's totally optional, I agree. It just confused me that the doc suggested it for mutations but not for actions. Thanks for clarifying
