### ISSUE TITLE
this.$store.dispatch如何调指定modules下的actions方法？

### ISSUE THREAD

**Issue by longzb** [vuejs/vuex#469]
比如store下面2个模块c和d，我想把请求都放在action里，为了方便以后复制粘贴，比如2个组件同是查询，都取名query,2个模块里的action都有个query方法，

我在组件里通过this.$store.dispatch('query')时，发现2个都调到了。
有什么办法指定调c或者d里的actions不？

**Comment by YamiOdymel** [comment]
Actions, Getters, Mutations 並沒有分模塊，你需要用命名空間（Namespace）。請參閱 #335。

**Comment by fnlctrl** [comment]
^ As above, thanks for the explanation @YamiOdymel
