### ISSUE TITLE
当我刷新浏览器地址的时候，state里面的内容被清空了。

### ISSUE THREAD

**Issue by shinygang** [vuejs/vuex#47]
hi all,
        我们项目中最近准备引用vuex，但是发现一个问题：当我刷新浏览器地址的时候，state里面保存的数据被清空了。请指导一下怎么解决。

**Comment by jianfei** [comment]
刷新相当于App重载了 数据当然会清空 你可以把数据存在cookie, session或者localstorage

**Comment by shinygang** [comment]
@jianfei 如果这样子的话，我感觉vuex意义不大了啊。

**Comment by yyx990803** [comment]
@shinygang 你是不是理解错 vuex 的意义了...

**Comment by shinygang** [comment]
@yyx990803 我理解的是用vuex做全局状态管理，比如登录后的一些用户信息全局缓存，不用在组件的props上传了。我想用他来替代localStorage之类的本地缓存。

**Comment by ryanwangtian** [comment]
@shinygang 那你想多了。。。

**Comment by yyx990803** [comment]
状态管理是为了可维护性和可扩展性，和本地缓存没有任何关系。但是你可以在 middleware 中将状态存入 localStorage。

**Comment by 598220654** [comment]
楼主,vuex刷新给清楚了是什么回事!!

**Comment by YiBanCangBai** [comment]
@yyx990803 有道理
