### ISSUE TITLE
Add support of tracking ES6 Map state.

### ISSUE THREAD

**Issue by libreoscar** [vuejs/vuex#471]
IIUC, vue/vuex currently support tracking changes of a Object state, but not an ES6 Map state. This is a feature request of that.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by jxiaox** [comment]
+1

**Comment by ktsn** [comment]
This issue should be tracked on Vue's issue list since Vuex completely rely on it's dependency tracking system.
Let's move on vuejs/vue#2410
