### ISSUE TITLE
vuex not throwing error when state is mutated outside mutation handlers

### ISSUE THREAD

**Issue by SpareShade** [vuejs/vuex#472]
hi,
i'm using vue and vuex with typescript, and I just can't figure out why vuex is **not** throwing the
```Do not mutate vuex store state outside mutation handlers```
when it really should.

```javascript 
strict: is set to true 
```
and I can see that 
```javascript
 enableStrictMode(store) is firing
```
and also in
```javascript
assert (condition, msg) 
condition evaluates to false which should throw the error but it doesnt
I can log the the correct error msg in the console
```
argh!

I'd much appreciate if anyone has got any pointers!!!

thank you for the great work!!!

**Comment by LinusBorg** [comment]
The actual code that should throw this warning might be helpful...

**Comment by SpareShade** [comment]
hello @LinusBorg 
thank you for looking into it!
i'm just doing the tests at the moment, essentially just directly mutating the state, so the code is very basic.

however, i've traced the "culprit" back to vue's error handling (on Watcher.prototype.run) and I can see that 
```istanbul ignore else``` is preventing error throwing in the ```else``` block.

setting the ```errorHandler() in Vue's config``` solves the problem for me.

Thanks again!
