### ISSUE TITLE
Same action in different modules will execute when i use mapAction

### ISSUE THREAD

**Issue by wszgxa** [vuejs/vuex#478]
In module a
``` js
const actions = {
  setTip (context, tip) {
    console.log(123)
  }
}
export default {
  state,
  mutations,
  actions
}
```

In module b
``` js
const actions = {
  setTip (context, tip) {
    console.log(234)
  }
}
export default {
  state,
  mutations,
  actions
}
``` 
If I use mapActions,will print 123 234.

I think it should throw a wraning as [this issues](https://github.com/vuejs/vue-router/issues/828).

**Comment by wszgxa** [comment]
Or action_types?

**Comment by ktsn** [comment]
This is intentional. Because sometimes we want to execute all actions/mutations that having the same name unlike routing name.
