### ISSUE TITLE
[IE9]  EventSource polyfill either missing or not working correctly

### ISSUE THREAD

**Issue by Nickvda** [vuejs/vuex#480]
Greetings,

With a standard project which is generated using the Vue-CLI, IE11 in IE9 emulation mode reports the following:

```
polyfill-eventsource added missing EventSource to window
SCRIPT5007: Unable to get property 'isReady' of undefined or null reference
localhost:8080 (183,13)
```

In the regular IE10/11 it seems to work as intended. As I'm not sure what breaks or stops
working due to this I can't report anything more (as I am completely new to Vue).

This happens with hot-reload from Webpack, but with hard refreshing as well.
[Forum link](https://forum.vuejs.org/t/ie9-mistake-during-initialization-of-the-project-or-something-else/3341)

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. 
`polyfill-eventsource` isn't vue's dependency, it's used by webpack-hot-middleware for development, and it won't affect production code. You should simply not use IE11 in IE9 emulation mode for development.

**Comment by Nickvda** [comment]
I know, our customers use IE9 and in order for us to use VueJS, we have to know if everything works-as-supposed in IE9 ;) 

But thanks.

**Comment by fnlctrl** [comment]
Don't get me wrong, vue/vuex works fine on IE9. It's just that you shouldn't develop on it because modern development tools doesn't support it. Simply use Edge in normal mode for development.
