### ISSUE TITLE
Iterating through a list of users returns undefined on actions

### ISSUE THREAD

**Issue by DevEclipse** [vuejs/vuex#486]
```
    async setAuth({state,commit,dispatch},uid) {
      let user = await _.find(state.busers,['uid',uid])
      setTimeout(() => {
        commit('SET_AUTH', auth);
      },1000)
    }
```

im using lodash for finding a user by uid but it doesnt find it 
im passing the uid by dispatching setAuth

and iterate through the list of users but it returns undefined

**Comment by ktsn** [comment]
Seems not related to Vuex.
If `_.find` does not returns expected value, the cause would be in lodash.

Please clarify where the problem is. If it really is Vuex's issue, please reopen this with a reproduction.
