### ISSUE TITLE
mapState string shortcut with modules

### ISSUE THREAD

**Issue by ArielGueta** [vuejs/vuex#499]
I have auth module for example:

```
export default {
  state    : {
    isLoggedIn: true
  },
  mutations: {
    [SIGN_IN]( state ) {
      state.isLoggedIn = true;
    },
    [SIGN_OUT]( state ) {
      state.isLoggedIn = false;
    },
  }
}

new Vuex.Store({
  modules: {
    auth: authModule
  },
})
```

Before working with modules I was able to do this:
` ...mapState(['isLoggedIn'] )`

Now in my component I tried to do this and it's not working:
` ...mapState(['auth.isLoggedIn'] )`

There is a way to do the same thing without the long way?
```
   ...mapState({
        isLoggedIn: state => state.auth.isLoggedIn,
      }
    )
```
Thanks.

**Comment by ktsn** [comment]
Duplicated with #459
