### ISSUE TITLE
How do you pronounce "Vuex"?

### ISSUE THREAD

**Issue by jemminger** [vuejs/vuex#500]
Pretty sure I'm not the only one.

**Comment by ludo237** [comment]
Like `vue` with an x

**Comment by jemminger** [comment]
@ludo237 So, "viewks"?  Or, "view-eks"?

**Comment by cannap** [comment]
vue-ex for me in german

**Comment by ktsn** [comment]
Please use [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) for asking such topic.
The issue list is reserved for bug reports and feature requests.
Thanks.

**Comment by yyx990803** [comment]
To be honest, I pronounce it like `viewks` but `view-eks` is growing on me ;)

**Comment by jemminger** [comment]
@yyx990803 Yeah, I think I like `view-eks` a little more.  Regardless, it's awesome and thanks for your work!

**Comment by bcass** [comment]
My team is pronouncing it like `vux`, so it rhymes with `tux`, `flux`, and `ree-dux`. It's more fun to say that way.

**Comment by feizhaojun** [comment]
V-U-E-[tʃɑr], Chinese
