### ISSUE TITLE
Uncaught TypeError: Cannot read property 'commit' of undefined (vuex.js?90cb:92)

### ISSUE THREAD

**Issue by Biarity** [vuejs/vuex#501]
Stack trace:
```
mappedMutation	@	vuex.js?90cb:92
boundFn	@	vue.common.js?e881:127
(anonymous function)	@	vue.common.js?e881:2186
Vue.$emit	@	vue.common.js?e881:3183
click	@	vue-material.js?ec92:6
(anonymous function)	@	vue.common.js?e881:2186
```

I got this error when using Vue with Vuex. Particularly when using `...mapMuations([...])` in my root component and passing the mutation as a prop to another component.

**Comment by ktsn** [comment]
Can you please provide a minimal live reproduction on jsfiddle, codepen or etc?

**Comment by LinusBorg** [comment]
Closed for inactivity. Feel free to open a new issue when you have an interactive reproduction.

**Comment by iBestKevin** [comment]
i meet a question too. could you share your resolve absolution?

**Comment by LinusBorg** [comment]
There's no resolution, he didn't even post a reproduction. Please use forum.vuejs.org for usage questions.
