### ISSUE TITLE
how to get root state in modules

### ISSUE THREAD

**Issue by bensonlove** [vuejs/vuex#506]
```
const state = {
	requesting: false
}
```
I want to get requesting in modules?

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, `context.rootState` in actions and the third argument in getters.
