### ISSUE TITLE
关于dispatch执行顺序问题

### ISSUE THREAD

**Issue by superchangme** [vuejs/vuex#511]
我在app.vue路由里发起dispatch存储了数据，page.vue created 函数读取vuex发现数据是空的，请问有解决方案吗

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
