### ISSUE TITLE
using vue-cli implement npm run test script appear error

### ISSUE THREAD

**Issue by ruofeng086** [vuejs/vuex#513]
hi all. I using vue-cli development project, implement test script appear error
as follows:

`> karma start test/unit/karma.conf.js --single-run

08 12 2016 17:58:56.562:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
08 12 2016 17:58:56.565:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
08 12 2016 17:58:56.593:INFO [launcher]: Starting browser PhantomJS
08 12 2016 17:58:58.689:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#ASROG2X5wloM9CDpAAAA with id 27300944
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
Error: [vuex] vuex requires a Promise polyfill in this browser.
at webpack:///~/.2.0.0@vuex/dist/vuex.js:145:0 <- index.js:16625

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.218 secs / 0 secs)

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.004 secs / 0 secs)

=============================== Coverage summary ===============================
Statements : 43.8% ( 60/137 ), 1 ignored
Branches : 27.27% ( 12/44 ), 2 ignored
Functions : 16.67% ( 3/18 )
Lines : 29.91% ( 32/107 )
================================================================================`

version as follows:
"phantomjs-prebuilt": "^2.1.3"
"karma": "^1.3.0", "karma-coverage": "^1.1.1", "karma-mocha": "^1.2.0", "karma-phantomjs-launcher": "^1.0.0", "karma-sinon-chai": "^1.2.0", "karma-sourcemap-loader": "^0.3.7", "karma-spec-reporter": "0.0.26", "karma-webpack": "^1.7.0",

I hope get help, thank in advance!

**Comment by ktsn** [comment]
Please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) to ask usage/support questions. The issue list is reserved for bug reports and feature requests.

---

As for your question, Vuex requires Promise like the error says. Just use Promise polyfill on the environment that does not support it. https://github.com/stefanpenner/es6-promise
