### ISSUE TITLE
在vuex的多个module中的getters里存在相同的方法名，使用mapGetters会报错？

### ISSUE THREAD

**Issue by wx-wangxiang** [vuejs/vuex#514]
比如：listmodule.js中：
`getters: {
		tableList: state => {
			return state.tableList;
		},`
searchmodule.js中：
`getters: {
		tableList: state => {
			return state.tableList;
		},`

store.js中：
`import searchStore from "./search_module"`
`import listStore from "./list_module"`
`Vue.use(Vuex)`
`const store = new Vuex.Store({`
	`modules: {`
		`search: searchStore,`
		`list: listStore`
	`}`
`})`,

app.vue中：
`computed: {
			...mapGetters({
				tableList: "tableList"
			})
		},`
这样写会报错，要怎么解决，难道要取不同的方法名？

**Comment by ktsn** [comment]
Please see https://vuex.vuejs.org/zh-cn/modules.html#命名空间

**Comment by youzaiyouzai666** [comment]
添加： list_module.js,search_module.js，中添加属性`namespaced: true`
则可以在使用 `computed: { ...mapGetters({ tableList: "search.tableList" }) },`

**Comment by gmailzj** [comment]
> 添加： list_module.js,search_module.js，中添加属性`namespaced: true`
> 则可以在使用 `computed: { ...mapGetters({ tableList: "search.tableList" }) },`

search.tableList => search/tableList  要改成斜杠?
