### ISSUE TITLE
Mobile UC Browser issue

### ISSUE THREAD

**Issue by kevinongko** [vuejs/vuex#519]
My [site](https://kevinongko.com) doesn't seems to work in android mobile [UC Browser](http://www.ucweb.com/ucbrowser/). it only show white screen, but when I remove Vuex it does work, any ideas?

build using vue-cli:
vue 2.1.4
vue-router 2.1.1
vuex 2.0.0

**Comment by yyx990803** [comment]
Are you using a Promise polyfill?

**Comment by kevinongko** [comment]
Adding babel-polyfill to webpack entry point solved this, thank for the advice @yyx990803

**Comment by liyanlong** [comment]
Thanks, I also have the same problem
