### ISSUE TITLE
Introduce getter consolidation to Vuex.Store property

### ISSUE THREAD

**Issue by blake-newman** [vuejs/vuex#52]
Introduce a getter consolidation like that of mutations to pass through the state object. 

```
export function isPasswordInvalid({user}) {
  if (user.password < minPasswordLength) return false;
  return false;
}
```

**Comment by blake-newman** [comment]
I'm currently creating a PR for this. The aim making getters more defined to the Store,  encouraging better flow of application structure. 

I was thinking also that actions could become more seperated,  by introducing object properties in the actions property.

**Comment by yyx990803** [comment]
Sounds like a good idea, although it'd be great to see some examples of API usage after the change before the PR.

**Comment by blake-newman** [comment]
So decided that separating the actions would cause too much diversity and may cause more confusion that good. 

However the getters is still a good idea to me, as it will make it less likely for people to dispatch actions from getters as it won't be publically available. 

Also im not too familiar with hot reloading api's.  Do you believe that getters will need to be affected by this?

**Comment by blake-newman** [comment]
Furthermore, i was thinking to make the API accessible to components like this.$router does, so importing the store is not necessary, and making it possible to have a store configuration file like the `vue-router` plugin does.

Is there any reason this shouldn't be done?

**Comment by yyx990803** [comment]
@blake-newman `this.$store` is already implemented, just not published yet: https://github.com/vuejs/vuex/commit/5fe5305b891ba6e850c873867da597335fe001f2

**Comment by blake-newman** [comment]
@yyx990803 Awesome my code is exactly the same haha

**Comment by blake-newman** [comment]
@yyx990803 [Issue with computed api passing payload](https://github.com/blake-newman/vuex/commit/c1697cf568c7f29fee0ae0cce05b0d1fa80269b1)

On this commit i have updated the hot reload example, however the computed property is passed the instance, is this intended and what the reason for this?

**Comment by yyx990803** [comment]
Why are you expecting payload inside getters? Computed getters do not take any arguments.

**Comment by blake-newman** [comment]
Good point,  wasn't thinking clearly,  makes sense for them not to expect any arguments. Making it a simple getter property.

**Comment by blake-newman** [comment]
Added PR: https://github.com/vuejs/vuex/pull/53
