### ISSUE TITLE
设置state为Map类型，在子组建无法获取值

### ISSUE THREAD

**Issue by xiongxliu** [vuejs/vuex#527]
@state是这样的 
``const state = {
  types: [],
  product: new Map(),
  banners: []
 }``

在子组件的computed中：
![qq20161217-2](https://cloud.githubusercontent.com/assets/17661296/21283996/35410df4-c449-11e6-8faa-3b5eccf7ff87.png)
打印this.$store.state.product结果：
![qq20161217-1](https://cloud.githubusercontent.com/assets/17661296/21283983/ed1c3e68-c448-11e6-9aed-304d967efa22.png)
打印this.$store.state.product.get(this.id)为undefined
可以给我点帮助吗？谢谢@yyx990803

**Comment by xiongxliu** [comment]
id是没错的。

**Comment by yyx990803** [comment]
目前 Vue 的响应式系统不支持 Map 类型，先用对象吧

**Comment by xiongxliu** [comment]
👌，加油，希望尽快实现

**Comment by MwumLi** [comment]
@yyx990803 
state 这样设置, `const state = { types: [], product: {}, banners: [] }`  
后面通过获取到数据去设置 product, 结果出现两个 state.product,  在 chrom 那个 devtool 插件上可以看到一个为 empty, 一个是我们设的数据, 然后使用的时候, 获取不到我之前为 state.product 设置的数据
所有的设置数据都是通过 mutation 去操作 : state.product = { ...data }
这是怎么回事?

**Comment by yyx990803** [comment]
Closing since the actionable items are Vue core related.

@MwumLi 具体问题请带重现开新 issue。
