### ISSUE TITLE
Is there a simple way to define multiple mutations with the same code

### ISSUE THREAD

**Issue by vedmant** [vuejs/vuex#529]
Maybe this is a noob question, however I cannot find anything about this in documentation nor google it.

For example I want to set loading state to true for all mutations that start async request, all this mutations are handled in modules, however global loading state is kept in different (global) module. With Redux I'd do just something like this:

    switch (action.type) {

      case 'LOGIN_STATUS':
      case 'LOGIN':
      case 'LOAD_PHOTOS':
      case 'UPLOAD_PHOTO':
        return merge({}, state, { loading: true });

      case 'LOGIN_STATUS_OK':
      case 'LOGIN_OK':
      case 'LOAD_PHOTOS_OK':
      case 'UPLOAD_PHOTO_OK':
        return merge({}, state, { loading: false });

      default: return state;
    }

How can this be achieved with Vuex?

Thanks!

**Comment by ktsn** [comment]
Since vuex module is just a plain object, you can create a helper to achieve that.
https://jsfiddle.net/p9avwLcp/

**Comment by vedmant** [comment]
Thanks! I was thinking about helper. But I hoped it has some built-in method to do something like this, maybe catch all mutation, where I can run switch statement and check mutation name Redux way. I'll use helper for now, thanks!

**Comment by ktsn** [comment]
I'm not sure if catching all mutations and using switch statement is suitable for vuex. 
Maybe store.subscribe is what you need? You can observe all mutations and commit another mutation by using it.

**Comment by vedmant** [comment]
Thanks, that may work. Is there a way to use it within a module? I don't have store instance in module file and I think subscribe method will get global state instead of module state.

**Comment by ktsn** [comment]
Currently, there are no way to do that in modules, but there is a proposal (#467).

**Comment by ktsn** [comment]
Closing since original issue can be solved by #467.
If it is not suffice for you, please open new issue with some proposal or comment to #467.
