### ISSUE TITLE
怎么运行里面的例子啊

### ISSUE THREAD

**Issue by helloqingfeng** [vuejs/vuex#537]
clone项目到本地，然后npm install，npm run dev，不能运行啊。
小白一个，请简单指导下，谢谢了。

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！

**Comment by helloqingfeng** [comment]
原来是遇到端口问题了，在examples文件下，修改server.js里面的端口为8090，然后在该文件夹下，npm run dev即可运行
