### ISSUE TITLE
A mapbox map in vuex store state

### ISSUE THREAD

**Issue by musicformellons** [vuejs/vuex#542]
I am trying to use vuex having a central state for a mapbox map, but run into (rather fundamental, as far as I can see) problems. Any suggestions if this will work at all?

I posted it here:
http://stackoverflow.com/questions/41308177/how-to-setup-a-centralized-state-for-a-mapbox-map-in-vuex/41310002?noredirect=1#comment69827849_41310002

**Comment by ktsn** [comment]
Please use [our forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue/) to ask usage/support questions.
The issue list is exclusively reserved for bug reports and feature requests.
Thanks.
