### ISSUE TITLE
项目中应用了vuex，es6,vue,vue-router，webpack打包之后发现在部分安卓机型下的webview中打不开，原因是js代码执行不了，就一行行的找原因，最后发现是在引用了vuex，然后const store = new Vuex.Store({})这样使用了之后就不行了。版本高的安卓手机和ios的webview没有这问题，谢谢🙏🙏🙏

### ISSUE THREAD

**Issue by Liqihan** [vuejs/vuex#544]

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！

-------------------------------

ES6需要用babel/buble之类的工具编译到ES5

**Comment by yyx990803** [comment]
少了 Promise polyfill.

**Comment by Liqihan** [comment]
谢谢，打扰了
