### ISSUE TITLE
need new feature: get state from another module

### ISSUE THREAD

**Issue by mygaochunming** [vuejs/vuex#548]
#539 

hi,i ask the question in the forum as you told me,but no one answered.

i find that some others ask the same question on stackoverflow too.

i think may be we need a new feature,

**Comment by LinusBorg** [comment]
1. I didn't see a post on the forums.
2. you can already get state from other modules both via getters (which are global) and via the `rootstate` property in actions and mutations, see the API: http://vuex.vuejs.org/en/api.html
