### ISSUE TITLE
use with react

### ISSUE THREAD

**Issue by weepy** [vuejs/vuex#550]
is it possible to use Vuex with React ?

**Comment by ktsn** [comment]
As Vuex is well optimized for Vue.js, we cannot use Vuex without Vue.js. So you should not use it with React.

**Comment by anish000kumar** [comment]
@weepy  You can't use vuex outside vue, but [redux-box](https://github.com/anish000kumar/redux-box) provides you similar API (not the same exactly) as the vuex. It also allows you to organise your store in modules,  has mutations, actions(called sagas) and state in each module. It also allows you to use dispatch and commit methods in the components, as in the case of vuex.

**Comment by dennybiasiolli** [comment]
Hi, I've just published [`react-vuex`](https://github.com/dennybiasiolli/react-vuex). It allows to use Vuex store manager with React.
More examples coming soon, any help is welcome 😃
