### ISSUE TITLE
Feature Request: provide "watch" method in action's context

### ISSUE THREAD

**Issue by jbruni** [vuejs/vuex#563]
So, I'm willing to use store's `watch` for the very first time.

In my case, I will start a watcher (and later stop/destroy it) from inside an action.

To my surprise, this didn't work:

```
    myAction ({ commit, watch, getters }, payload) {
        let unwatch = watch(getters.myGetter, myCallback, myOptions)
        // et cetera
    }
```

I checked documentation, as well as `makeLocalContext` source code, and, indeed, store's `watch` is not available in the context provided to the action.

Thus, my request: please include store's `watch` in the context, so we can reach and use it.

Thank you.

**Comment by LinusBorg** [comment]
Can you explain your usecase? 

FWIW, for now you can simply import the watch method from the store:
```javascript
import { watch } from './store'
```

**Comment by jbruni** [comment]
There is nothing special in my case. Just like we have `commit`and `dispatch` and `getters` available to use, as properties/methods of the first parameter given to the action function, I expected to find `watch` there.

Yes, we can import the store and use not only `watch` but also all the above directly from it.

I think the main difference would be on testing, but I'm not sure about this.

I made the request believing it would be something simple/trivial to implement, but this may be a wrong assumption.

**Comment by ktsn** [comment]
The action context is totally different thing with the store. 
I think we should not add the feature that does not have any usecases since it just bloat the API. Imagine the situation that there are many number of unused API, it makes harder to understand Vuex for beginners.
