### ISSUE TITLE
Commit mutation to a namescaped module

### ISSUE THREAD

**Issue by migueljteixeira** [vuejs/vuex#566]
Hi!
So i'm following this approach to mutate a vuex variable. (presented here https://vuex.vuejs.org/en/forms.html)

```
computed: {
  message: {
    get () {
     // "auth" is a namespaced module.
      return this.$store.state.auth.message
    },
    set (value) {
      // Not working
      // this.$store.commit('updateMessage', value)
      // this.$store.commit('auth/updateMessage', value)
    }
  }
}
```

So how can i commit a mutation that changes the value of the variable 'message' on this namescape?

Thank you.

**Comment by ktsn** [comment]
You already seems to write the solution by yourself... Just add namespaced string to mutation type.

Please use our [forum](https://forum.vuejs.org) or [gitter](https://gitter.im/vuejs/vue) to ask usage/support questions in the future. The issue list is exclusively reserved for feature requests and bug reports.
Thanks.

**Comment by jl-** [comment]
Explicitly concat with the namespace doesn't seem to be a good practice though, which means we need to know how namespace works under the hood ('auth/xx' or 'auth:xx' or ...), can we have something like this?
`this.$store.commit('updateMessage', value, { module: 'auth' })`

**Comment by ktsn** [comment]
Please open a new issue if you want to request a new feature. 🙂

**Comment by balazserdos** [comment]
I'd need this as well, or some solution how a higher module can invoke a deeper's mutation

**Comment by stephantabor** [comment]
For anyone that discovers this in the future via googling namespaced mutations in components, this is roughly how I ended up doing it (using the code in OP for example)

```js
import { mapMutations, mapState } from 'vuex';
export default {
  // "auth" is a namespaced module.
  methods: {
    ...mapMutations('auth', ['updateMessage']),
  },
  computed: {
    ...mapState('auth', ['message']),
    message: {
      get() {
        return this.message;
      },
      set(value) {
        this.updateMessage(value);
      },
    },
  },
};
```

**Comment by travisbotello** [comment]
@stephantabor solution looking good. Only thing which is not working for me is:

```
get() {
     return this.message;
}
```

causing `vue.esm.js?efeb:1741 RangeError: Maximum call stack size exceeded`

I have to use `return this.$store.auth.message`. However I am not sure if this is right solution since we are calling the namespaced module to use with` mapState`

**Comment by stephantabor** [comment]
yeah you're right, i tried to adapt my solution to the other person's code. In my components I don't have overlapping names a la `message`

**Comment by valterbarros** [comment]
@stephantabor Thank you
