### ISSUE TITLE
State.obj doesn't work

### ISSUE THREAD

**Issue by angelbotto** [vuejs/vuex#57]
I tried inside a mutation to to `state.obj = defaultStateBuilder()` that return a fresh object with the initial default state but it doesn't work as the docs say it should. In the end I had to do this:

```javascript
_.pairs(newState).map((x) => Vue.set(state, x[0], x[1]))
````

But I would assume that `state.obj = newState` should work according to the section "Mutations Follow Vue's Reactivity Rules" in http://vuex.vuejs.org/en/mutations.html

**Comment by yyx990803** [comment]
`state.obj` must be declared upfront.

**Comment by davidpelaez** [comment]
In this case 'obj' was an example, not a literal pointer to `obj`, right? So it could be `state.myComment`...? There's nothing special about 'obj' then?
