### ISSUE TITLE
 error  in ./~/babel-loader/lib?{"cacheDirectory":true,"presets":[["es2015",{"modules":false}]]}!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/chat/Chatbox.vue

### ISSUE THREAD

**Issue by jericopulvera** [vuejs/vuex#574]
when I move to ubuntu 16.04 I received this error

 error  in ./~/babel-loader/lib?{"cacheDirectory":true,"presets":[["es2015",{"modules":false}]]}!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/chat/Chatbox.vue

SyntaxError: Unexpected token (18:2)

  16 | 	components: ['user-list', 'message'],
  17 | 	computed: {
> 18 | 		...mapState({
     | 		        ^
  19 | 			chatStore: state => state.chatStore
  20 | 		})
  21 | 	},

**Comment by ktsn** [comment]
It's not related to Vuex. You should include [babel-plugin-transform-object-rest-spread](https://babeljs.io/docs/plugins/transform-object-rest-spread/) in your `plugins` field of `.babelrc`.

**Comment by jericopulvera** [comment]
@ktsn where is the .babelrc file located?

**Comment by ktsn** [comment]
It is the config file you will create.
If you are writing the babel config in the webpack config, you should write in it instead.

**Comment by fanibig** [comment]
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/stocks/Stocks.vue
Module not found: Error: Can't resolve '@/Stock.vue' in 'E:\vertrigo\www\vue-webpack\src\components\stocks'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/stocks/Stocks.vue 8:0-32
 @ ./src/components/stocks/Stocks.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
