### ISSUE TITLE
Vuex state not updating the components. Again

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vuejs/vuex#578]
Hi have a big store with the follow state:

```
state:{
   comments: {
   id1:{},
   id2: {},
   ...
}
}
```

Then I have a function that searches into the comments and updates one field in the matches ones. The field is called "displayText". Here a snippet

```
  if (commentText.match(query) != null) {
          // add an bold tag
          const highlightQuery = "<b>" + query + "</b>"
          const highlightText = comment.displayText.replace(query, highlightQuery)
          comment.displayText = highlightText
          comment.find = true
          Vue.set(state.comments, comment.id, comment)
 }
```

I tried to use Vue.set but I cannot see any update in my DOM. The comments field of the state is a classic JSON tree composed by the ids of the comments.

In the doc you suggest to do something like this:

`state.comments = {...state.comments,comment.id: comment}
`

But it triggers and error:
`Unexpected token (96:53)`

I have, of course, stage-3 activated. So it seems that I cannot refer to a custom object property with the spread operator.

Thank you.

**Comment by yyx990803** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by LinusBorg** [comment]
`state.comments = {...state.comments, [comment.id]: comment}`

**Comment by FrancescoSaverioZuppichini** [comment]
It seems that I'm not able to reproduce the error. I've tried this basic example without Vuex and it actually works:

http://jsfiddle.net/yyx990803/vjvMp/1/

**Comment by LinusBorg** [comment]
You tried to set an object key dynamically, but forgot the brackets: [comment.id]

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you. I think this can be labeled as closed.
