### ISSUE TITLE
疑问：使用mapActions或mapMutations时如何传参？

### ISSUE THREAD

**Issue by AndyFightting** [vuejs/vuex#579]
疑问：使用mapActions或mapMutations时如何传参？

```
      ...mapActions({
        delTaped: 'numDelAction'
      }),
```

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！

**Comment by AndyFightting** [comment]
https://forum.vuejs.org/t/vuex-mapmutations/2455

**Comment by fnlctrl** [comment]
论坛的那个答案理解错你的问题了。
mapActions/mapMutations只是把action/mutation函数绑定到你的methods里了。你调methods里的方法的时候照常传参就可以了。
你的原始例子里直接用
```js
this.decrement({ amount: 1})
```
就行了。

例子: https://jsfiddle.net/7c191c86/

**Comment by AndyFightting** [comment]
@fnlctrl  哦~~就是把方法名对应上，然后参数照样传！ 非常感谢~~

**Comment by binarySortTree** [comment]
...mapActions({
        delTaped: 'numDelAction'
      }),
mapActions前的...是什么意思啊？

**Comment by JavanTang** [comment]
与上面那个老哥问题一样  mapActions前的...是什么意思啊？

**Comment by renfufei** [comment]
mapActions() 返回的是一个对象, 用了 ... 扩展符后，才可以放进一个对象里，和其他组件内定义的 method 在同一个 methods 对象。
请参考: <https://segmentfault.com/q/1010000009658513>

**Comment by GREENPEANS** [comment]
> 与上面那个老哥问题一样 mapActions前的...是什么意思啊？

这个是ES6 语法
