### ISSUE TITLE
Unexpected behaviour of mapActions

### ISSUE THREAD

**Issue by znck** [vuejs/vuex#583]
Vuex v2.1.1

Source:

```js
...
methods: { ...mapActions('connections', { list: 'getConnections' }) },
...
```

Expected:

The component should have `getConnections` method.

Actual:

The component has a `list` method instead. See screen shot.

![screen shot 2017-01-16 at 08 58 09](https://cloud.githubusercontent.com/assets/2596484/21970178/17d17afe-dbca-11e6-874a-313739d5e5f3.png)

**Comment by ktsn** [comment]
It's expected behavior. `mapActions` helper will create methods as the name of object keys (and the methods dispatch the action that specified by object values).
