### ISSUE TITLE
给中文文档翻译的一条建议

### ISSUE THREAD

**Issue by getlinerm** [vuejs/vuex#585]
Action的文档，有一条翻译不准确。
The first thing to know is that store.dispatch can handle Promise returned by the triggered action handler and it also returns Promise:
旧：第一件事你需要清楚的是 store.dispatch 的返回的是被触发的 action 函数的返回值，因此你可以在 action 中返回 Promise：
新：首先，你需要明白store.dispatch可以处理被触发的action的回调函数返回的Promise，并且store.dispatch仍旧返回Promise。

**Comment by yyx990803** [comment]
是的，旧翻译不准确。欢迎提 PR！

**Comment by fnlctrl** [comment]
Closing as the PR is merged.
