### ISSUE TITLE
Error thrown at registerAction in Vuex.js with devtoolHook enabled for zepto-based handler.

### ISSUE THREAD

**Issue by DongShi** [vuejs/vuex#589]
check the following code in registerAction

```javascript

function registerAction (store, type, handler, local, path) {
  var entry = store._actions[type] || (store._actions[type] = [])
  entry.push(function wrappedActionHandler (payload, cb) {
    var res = handler({
      dispatch: local.dispatch,
      commit: local.commit,
      getters: local.getters,
      state: getNestedState(store.state, path),
      rootGetters: store.getters,
      rootState: store.state
    }, payload, cb)
    if (!isPromise(res)) {
      res = Promise.resolve(res)
    }
    if (store._devtoolHook) {
      return res.catch(function (err) {  //Uncaught TypeError: res.catch is not a function
        store._devtoolHook.emit('vuex:error', err)
        throw err
      })
    } else {
      return res
    }
  })
}

```

handler could return a promise with no 'catch' interface, one example would be the [zepto's deferred](https://github.com/madrobby/zepto/blob/master/src/deferred.js#files) module.

**Comment by LinusBorg** [comment]
> handler could return a promise with no 'catch' interface, one example would be the zepto's deferred module.

Promises with no `.catch` interface are not ES6-compliant. I don't think we should work around non-standard-compliant PRomise implementations.

**Comment by DongShi** [comment]
Fair enough.
Just checked on the zepto side, indeed it is not following the promise/A+ standard. So I am closing this one.

Thanks for the help.
