### ISSUE TITLE
Vuex Dist?

### ISSUE THREAD

**Issue by Gomah** [vuejs/vuex#59]
Hello @yyx990803, do you plan to release a dist build for vuex ?

I use [tonicdev](https://tonicdev.com/npm/vuex) at the moment as a playground but would love to see vuex integrated in cdnjs to embed it as an external resource on JSFiddle/Codepen.

Thanks in advance :+1:

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by miljan-aleksic** [comment]
:+1: 

In my scenario I'm using different components that use Vuex and including vuex on each one of them is redundant. Treating vuex as an external asset seems correct in this situations.

**Comment by pierrebonbon** [comment]
:+1:

**Comment by yyx990803** [comment]
Now available: https://github.com/vuejs/vuex/tree/master/dist

Jsdelivr PR created: https://github.com/jsdelivr/jsdelivr/pull/10222

If someone wants to put it on CDNjs, feel free to do so.
