### ISSUE TITLE
unpkg.com returning most-recently-released version, not highest version

### ISSUE THREAD

**Issue by jordanlev** [vuejs/vuex#591]
I'm not sure if this is the right place for this (it might be a problem with unpkg.com as opposed to how Vuex was packaged up)...

If you load https://unpkg.com/vuex ... it redirects to https://unpkg.com/vuex@1.0.1 instead of https://unpkg.com/vuex@2.1.1 (presumably because v1.0.1 was released more recently than 2.1.1?)

Feature or bug?

**Comment by steambap** [comment]
it seem that someone messed up npm tags. version 2.1.1 should be latest.

**Comment by alexpetroni** [comment]
The same problem here, 
└── vuex@1.0.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


Trying to install with latest node v7.4.0 and npm v.4.1.1 and the vuex@1.0.1 installed

**Comment by yyx990803** [comment]
Fixed now

**Comment by alexpetroni** [comment]
still does not work, vuex@2.1.1 invalid

**Comment by yyx990803** [comment]
@alexpetroni likely your npm cache issue. Tested with `npm install` and unpkg.com both working fine for 2.1.1.
