### ISSUE TITLE
Unexpected token on mapMutations

### ISSUE THREAD

**Issue by marianvlad** [vuejs/vuex#595]
Hi,

I use mapMutations in methods property and I have an error. My webpack can't recognise three dots.

```
...mapMutations([
    'deleteTodo'
]),
```

**Comment by ktsn** [comment]
This is not related to Vuex.
Please make sure to enable to transform object rest spread operator for your transpiler.
For babel: https://babeljs.io/docs/plugins/transform-object-rest-spread/
