### ISSUE TITLE
Vuex documentation enhancement - return functions in getters

### ISSUE THREAD

**Issue by mudrz** [vuejs/vuex#598]
Request for enhancing the documentation

This has been discussed in several other Issues (for example https://github.com/vuejs/vuex/issues/526 and https://github.com/vuejs/vuex/issues/456), and as someone who is learning Vue + Vuex who just went through the same issue, it would be very helpful to have such common cases in the official docs, instead of in the closed issues

Accessing array data is not an isolated use-case, but instead an absolute necessity for larger applications

<details> 
  <summary>Reasoning below (if there is another, better Vuex way, please share it)</summary>
vuex is playing the role from one side as a simple abstraction of the application data

```js
//the state, similar to the DBContext layer in the ORM world
const state = {
    products = [
          { id:1, fullName:'foo', price: 200, color: 'red' },
          { id:2, fullName:'bar', price: 999, color: 'blue' }
    ]
}
//and the abstraction over direct data access, similar to the DBSets in ORMs
const getters = {
    products(state){
      return state.products
    },
    //or simply
   products: state=> 
}
```

But also as a repository pattern substitute, where data changes are done through mutations.
```js
const mutations = {
     //addProduct(state, payload)
     addProduct(state, { fullName, price, color }){
        state.products.push({
            fullName,
            price,
            color,
            id: generateProductId()
        })
     }
}
```
In that sense, I felt that Vuex is in an odd spot (I was comparing Vuex with a standard data repository pattern) where data changes are abstracted within the scope of vuex (mutations), but data getting of array items is supposed to be carried out by a separate application layer, instead of having commonly used getters with arguments:
```js
const dynamicGetters = {
     getProductById: (state, getters, payload) => {
      return getters.products.find(x=> x.id === payload)
    },

     getProduct: (state, getters, { name, color }) => {
      return getters.products.find(x=> x.fullName === name && x.color === color)
    }
}
```
so that queries used from different parts of the application can be cached in a centralized location (the ORM/DB way of thinking, obviously not valid in the Vue + Vuex world) and only specific, non-standard queries are moved to their own layer
</details>

> It is fairly obvious that getters can return functions once you see it, but not so much when you have OOP background

Hopefully this helps others - the upper dynamicGetters (these don't exist in vuex) represented as standard getters that return functions, as suggested by @ktsn :
```js
const getters = {
    //ES6
    getProductById: (state, getters) => (id) =>{
           return getters.products.find(x=> x.id === id)
    },
   //function syntax
   getProductById: function(state, getters){
      return function(id){
           return getters.products.find(x=> x.id === id)
        }
    },
     getProduct: (state, getters) => ( { name, color } ) {
      return getters.find(x=> x.fullName === name && x.color === color)
    }
}
//and then used in the vue instance (state and getters get automatically injected)
//where preferably the output product should be a computed property instead of direct methods
let product1 = this.$store.getters.getProductById(2)
let query = {
 name: 'foo',
 color: 'red'
}
let product2 = this.$store.getters.getProduct(query)
```

**Comment by ktsn** [comment]
PR welcome!

**Comment by antonstefanov** [comment]
I'll look into that, I am very new to github (and open source in general, ASP.NET)

**Comment by andreiglingeanu** [comment]
I've also noticed a small glitch with the getters having to return a function. It is very inconvenient to just import the getters somewhere in your mutations to gather a small piece of data (just to continue @antonstefanov example):

```javascript
import { getProductById } from './getters';

// I'll have to use it like that in my mutations, the syntax is a bit weird
getProductById(state)(2); // 2 here representing the actual ID
```

That's why I often find myself writing simple functions that I'll be able to call both in wrapped with a closure getters and in my mutations/actions. 

I expect there's some elegant way of currying the existing getters but I haven't really explored that too much, would love to see something about that!

**Comment by LinusBorg** [comment]
> It is very inconvenient to just import the getters somewhere in your mutations to gather a small piece of data 

That should not happen in the mutation, that should happen in the action. And in the action, you have access to getters:
```javascript
'ADD_PRODUCT_TO_CART' ({commit, getters}, { id }) {
  const product = getters.getProductById(id)
  commit(''ADD_PRODUCT_TO_CART'', product)
}
```

**Comment by ktsn** [comment]
Closing (#601 is merged)

**Comment by andreiglingeanu** [comment]
> That should not happen in the mutation, that should happen in the action. And in the action, you have access to the actual getters:

That's a very good point, thank you. I was really thinking about actions as a way to dispatch async operations. And because the whole point of my app was to manipulate a big data structure in-memory, without a need for syncing with a server, I avoided actions allover, for some reason and I was mistaken.

Thanks once again for pointing that out.
