### ISSUE TITLE
Watchers leaked when component destroyed

### ISSUE THREAD

**Issue by thatguystone** [vuejs/vuex#599]
It seems that when a component watches anything in a $store, the watchers stick around once the component has been destroyed. I'm curious if it wouldn't be better to track watches per-component (in the Vuex mixin) and remove them once the component is destroyed.

Relevant fiddle: http://jsfiddle.net/thatguystone/zz727dhb/

**Comment by ktsn** [comment]
I'd say that this is expected behavior because Vuex cannot detect in which component you call `$store.watch` method. But I'm not sure if I'm correct.

/ping @yyx990803

**Comment by thatguystone** [comment]
In its current state, it can't detect it, but I believe it would be possible to override the watch method in each components `$store` so that it can catch and handle new watches in components.

**Comment by ktsn** [comment]
I don't think we can override the `watch` method as the `$store` is shared instance among all components... I think it would be better to create a plugin to add dedicated field for watching the store state in component options object instead if you would like to destroy the watchers automatically.

**Comment by yyx990803** [comment]
`$store.watch` returns an `unwatch` handle. You should store the handle and call it in the destroyed hook of your component.
