### ISSUE TITLE
using .map to an array getter loses the reactivity when passed on the component

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vuex#606]
example
```js
const state = {
   tests: {
      test:{
          data: ['a',b','c']
      },
      test2: {
         data: ['c','b','a']
      }
   }
}
const getters = {
    test(state) {
         return key => state.tests[key].data
    },
    $test2(state,getters) {
           return getters.test('test2');
    },
    $test(state,getters) {
         return getters.test('test').map(t => {
              return {
                 t,
                 test2: getters.$test2.find(t2 => t2[0] == t)
              }
          });
     }
}
```

Purpose of this is im not joining the two objects to one which i can isolate every part of it

also doing this for the sake of using my firebase binding library using vuex and use the getters to the components using mapGetters  then .splice it but doesn't rerenders

**Comment by ktsn** [comment]
I just copy & paste your code but I could not find any problem. https://jsfiddle.net/0k08yomd/1/
Could you provide complete reproduction by jsfiddle?

**Comment by ralphchristianeclipse** [comment]
@ ktsn ok

**Comment by ralphchristianeclipse** [comment]
here

https://jsfiddle.net/0k08yomd/3/

**Comment by ktsn** [comment]
You shouldn't mutate the return value of getters (and also computed property) because they are derived value of original state. You should update original state instead.
