### ISSUE TITLE
cordova

### ISSUE THREAD

**Issue by 1736103466** [vuejs/vuex#608]
cordova打包后白屏，移除vuex后正常
只要使用Vue.use(Vuex)
模拟器就会白屏，游览器中没问题

**Comment by LinusBorg** [comment]
Hello @1736103466,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted.


Thank you.
