### ISSUE TITLE
webpack2 error - export 'mapActions' was not found in 'vuex'

### ISSUE THREAD

**Issue by vinicius73** [vuejs/vuex#610]
testing the update [vue template webpack](https://github.com/vuejs-templates/webpack), which now comes with webpack2, I have these warnings.

`export 'mapGetters' was not found in 'vuex'`
`export 'mapActions' was not found in 'vuex`
`export 'mapState' was not found in 'vuex`

Initially I ignored the problem, but the project does not work.

I'm reporting the problem here, because I believe it's a problem with vuex + webpack2.

**Comment by LinusBorg** [comment]
The template does not include vuex, so you added it yourself. 

Please provide the code you used to include it and especially the cod that raised these errors, preferably in a repository.

**Comment by vinicius73** [comment]
I'll arrange a test repo using only Webpack 2

As I mentioned, the error is not from the template, but from the code generated by webpack2
Probably something related to tree shaking

**Comment by yyx990803** [comment]
Working as intended with a fresh vue-cli install. Please open the issue at the template repo with proper reproduction.

**Comment by wanerta** [comment]
i have the same problem , install the vuex@2.0.0 may solve this temporarily

**Comment by Doeke** [comment]
Downgrading to 2.0.0 fixed it for me, does anyone know why the imports broke in new version?

**Comment by transtone** [comment]
vuex@2.2.0 has the same problem. but vuex@2.1.3 works.

**Comment by SeoFood** [comment]
fixed it temporary with   `import {mapGetters} from 'vuex/src/helpers'`

**Comment by yyx990803** [comment]
@transtone @SeoFood Will be fixed in 2.1.1.

**Comment by jjhesk** [comment]
@SeoFood i got error even with import {mapGetters} from 'vuex/src/helpers'

**Comment by nafihnfh** [comment]
I try with import {mapGetters} from 'vuex/src/helpers'
then I got an error like this Module not found: Error: Can't resolve 'vuex/src/helpers' in
