### ISSUE TITLE
mapActions helper how to pass payload

### ISSUE THREAD

**Issue by ArielGueta** [vuejs/vuex#611]
There is a way to pass payload to the mapActions helper?

For example:
```js
 Vue.component('login', {
       template: template,
	data() {
		return {
			email: "",
			password: ""
		}
	},
	methods: {
		...mapActions("auth", ["login"]) 
	},
});

```

How can I pass the email and password to the action without doing this:
`    this.$store.dispatch("auth/login", {email: this.email, password: this.password});
`

**Comment by CodinCat** [comment]
`mapActions` will just, **map actions**.

It creates shorthands for you, and you call the methods like any other normal methods. (You still need to pass the payload to your method.)

after `...mapActions('auth', ['login'])`

`this.login(yourPayload)`  is equal to `this.$store.dispatch('auth/login', yourPayload)`

so just do this

```js
this.login({
  email: 'foo',
  password: 'bar'
})
```

and questions are better to ask on stackoverflow or the official vue forum.

**Comment by ktsn** [comment]
^ As @CodinCat said.

**Comment by Y0geshsharma** [comment]
you can call the map action in the component or view, which makes the action available in your local view so you can simply use the action where ever you want to and pass the params there:
eg:
...mapAction("ACTION_NAME")
function name(){
this.ACTION_NAME(PARAMS)
}

**Comment by shashinvision** [comment]
> `mapActions` will just, **map actions**.
> 
> It creates shorthands for you, and you call the methods like any other normal methods.
> 
> after `...mapActions('auth', ['login'])`
> 
> `this.$store.dispatch('auth/login', yourPayload)` is equal to `this.login(yourPayload)`
> 
> so just do this
> 
> ```js
> this.login({
>   email: 'foo',
>   password: 'bar'
> })
> ```
> 
> and questions are better to ask on stackoverflow or the official vue forum.

Excelente, work very nice :D
