### ISSUE TITLE
Weird reactivity of mapState with localState (modules)

### ISSUE THREAD

**Issue by trunda** [vuejs/vuex#614]
Hi there, I believe this is a bug.

These two styles have different behavior:

```
const Cmp = {
   // ...
   computed: {
      ...mapState('test', ['stateProp']),
   }
   // ...
}
```

```
const Cmp = {
   // ...
   computed: {
      ...mapState({'stateProp': (state) => state.test.stateProp }),
   }
   // ...
}
```

When `store.replaceState` is called the first style is not reacitve anymore. I made a fiddle reproducing this issue: https://jsfiddle.net/jtrunecek/qp5or4uu/2/

**Comment by rdunk** [comment]
I'm also seeing this issue, workaround I'm currently using is to define getters and use mapGetters instead of mapState. Not ideal, but see fiddle: https://jsfiddle.net/nod8sveg/

**Comment by yyx990803** [comment]
Should be addressed by https://github.com/vuejs/vuex/pull/528 - will get a release out soon.

**Comment by trunda** [comment]
@rdunk or just use `mapState` without namespace (with arrow function) 
@yyx990803 Thanks!
