### ISSUE TITLE
Reusable store modules with namespaces does not work as expected 

### ISSUE THREAD

**Issue by hultberg** [vuejs/vuex#615]
Hello!

First of all, thanks for all the hard and awesome work on vue and vuex, keep on rocking! 🎸 

Tried out the namespace feature. In q project I have several different addresses and created one single address store (`address-store.js`) that was added as a modules in the main store. As these different modules serve different purposes (different addresses), I added `namespaced: true` in `address-store.js`. However, when calling commit on one of the address modules, all the address modules in the main store update their values instead of the one I called commit on (getters are mapped using `mapGetters` with the namespace as first argument).

It seems to me that namespaced stores used as modules is not correctly separated. I'm only able to reproduce the bug when the module exist in it's own file and not inline.

To showcase this bug, I tried to re-create this on webpackbin.com. However, seems the service does not handle vue 2.0 so well, so I created two new examples (counter2 and counter3) in an own fork of vuex that showcases the bug.

### Prerequisite:
1. Clone down my fork at https://github.com/hultberg/vuex/
2. Checkout the branch `eh-namespace-modules-bug`
3. Install node dependencies `npm install` and start the local server: `npm run dev`.
4. Open `http://localhost:8080` and notice the two example below the original example provided by vuex.

### Steps to reproduce and explanation of the examples
Open `http://localhost:8080/counter2`, this page has two date stores in their own file that are modules in the `store.js`. The purpose of the date stores in this example is to catch the date the increment and decrement buttons are triggered, respectively. However, when triggering either the increment button, or decrement button, both dates update.

Now, open `http://localhost:8080/counter3`. This example is a copy+paste of counter2 with one difference as the date store is now inline in `store.js`, rather than in an own file. As you can observe, date capturing is working as expected.

I tried looking if this has already been reported, but no luck.

Thanks!

**Comment by yyx990803** [comment]
This is not a bug... because you are reusing the exact same `DateModule`, they are sharing the same state object by reference. If you want to "reuse" the same module in multiple places, use a factory function that returns a fresh copy of the module:

``` js
modules: {
  a: createModule(),
  b: createModule()
}
```

**Comment by hultberg** [comment]
@yyx990803 Aha, I see. I was quick to tag this as a bug. Thank you so much! :smile:
