### ISSUE TITLE
mapGetters and modules

### ISSUE THREAD

**Issue by ianfieldarsclinica** [vuejs/vuex#620]
I commented on closed issue #336 - should I delete that and move the comment over here, or?  New to this stuff...

**Comment by znck** [comment]
Your issue seems usage/support question. If you want to ask such question, please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). The issue list is reserved exclusively for bug reports and feature requests.

Thanks.
