### ISSUE TITLE
How to use vuex to build chrome extension

### ISSUE THREAD

**Issue by cawa-93** [vuejs/vuex#622]
In my extension, there are two processes:
Background and popup
For both processes you need to keep general State and react to changing it.
For example:
* The background process accesses to the API and changes the state. Popup should respond to this change.
* User, in Popup, performs some action and changes the state. Background processes must react to this change.

Data can be stored using:
* chrome.storage API
* localStorage API

Both methods synchronize data between processes.
But the change of state in the same process causes no reaction elsewhere.

**Comment by ktsn** [comment]
Please read [issue reporting guideline](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. The issue list is exclusively reserved for bug reports and feature requests.
Usage/support questions should be posted on our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We will be glad to help you on there.
Thanks.

**Comment by jdinartejesus** [comment]
I would be interested on this topic, I don't find anything on the web.

**Comment by cawa-93** [comment]
@jdinartejesus I myself did not find a solution either. The best thing that came to mind is to combine the vuex with the chrome.storage.onupdate to synchronize the state of the storage on background and popup views

**Comment by jdinartejesus** [comment]
Thanks @cawa-93, I didn't think about that. I was trying to use https://github.com/ivantsov/redux-webext/ but also without success. I guess your solution is the best for now. Thanks

**Comment by terry90** [comment]
For people on this issue, you may want to take a look at https://github.com/tshaddix/react-chrome-redux and see how he manages to create a proxy to build a shared store with chrome event messages.

**Comment by cawa-93** [comment]
Hello everybody. I propose  **[vuex-shared-mutations](https://github.com/xanf/vuex-shared-mutations)** as a solution option. It uses localStorage to synchronize the state between tabs, but this should work for an extension, since the localStorage there is shared

**Comment by altinselimi** [comment]
Well so far I've only had luck using this plugin: https://github.com/MitsuhaKitsune/vuex-webextensions
It still has some drawbacks. It really sucks we have yet to have a de facto way of building chrome extensions using vue. I mean [react](https://github.com/tshaddix/react-chrome-redux) is good but as far as development goes, I feel like flying when using vue.
