### ISSUE TITLE
Why can't I use ES6 symbol to name actions nor getters

### ISSUE THREAD

**Issue by mzielinski-spartez** [vuejs/vuex#624]
I've read #224 and I understand the reason why Symbols are not allowed as names of mutations (i.e. dev tools display mutation names to the user).

At the same time I don't get why (conceptually) actions and getters can't use symbols. For me the two are the only interface between Vuex and Vue components. I export their names as consts and use them in components. It is tedious to write getter/action name twice like in `export const ACTIVE_THREAD = 'moduleName/activeThread'`. 

Technically there are places (like [here](https://github.com/vuejs/vuex/blob/dev/src/helpers.js#L58)) where names of actions and getters are converted to string. If I don't use namespaces it should not throw error. Is there a business reason why they have to be serialized?

Mateusz

**Comment by ktsn** [comment]
There is a plan to visualize actions on devtools, also. https://github.com/vuejs/vue/projects/3
I'm not sure about getters. @yyx990803 may write his thoughts here.

**Comment by mzielinski-spartez** [comment]
I see your point here. One thing to notice is that [ES 2015 specification](http://www.ecma-international.org/ecma-262/6.0/#sec-symbol-objects) calls the argument of Symbol constructor 'description' and [developer.mozilla.org](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol) (which of course is not an official language specification) says: 
>  A description of the symbol which can be used for debugging but not to access the symbol itself.

It seems reasonable for me to use ES6 symbols as names of actions and getters (and even mutations) with descriptions as an opt-in for debugging purpose.

In my opinion it solves the problem described [here](https://github.com/vuejs/vuex/issues/335#issuecomment-249481105) in even more elegant way than the "namespaced: true" module property (described in [this place](http://vuex.vuejs.org/en/modules.html#namespacing) in vuex documentation).

**Comment by dougalg** [comment]
To me this seems like a very natural use case for `Symbol`, where you'd just like to uniquely identify things.

**Comment by kiaking** [comment]
Closing the issue due to inactivity. If we still need to discuss with the Symbol usage, it might be better to open a new issue since it will involve module system impact as well.
