### ISSUE TITLE
import vuex undefined

### ISSUE THREAD

**Issue by fangxingguang** [vuejs/vuex#625]
环境：
    "vue": "^2.1.10",
    "vuex": "^2.1.2",

代码：
import Vuex from '../../node_modules/vuex'
import Vuex2 from 'vuex'
console.log(Vuex) //正常输出对象
console.log(Vuex2) //输出 undefined

问题：
为何Vuex2输出undefined，是否是bug ??

**Comment by fangxingguang** [comment]
后来发现只要把src/vuex/index.js 改成src/vuex/store.js就好了，But why？

**Comment by ktsn** [comment]
Couldn't reproduce. What module bundler are you using? Could you provide a minimal example project on github repository?

**Comment by fangxingguang** [comment]
https://github.com/fangxingguang/vue-base

只要把src/vuex/store.js 改成src/vuex/index.js就会报错

**Comment by ktsn** [comment]
Because `import 'vuex'` in `src/vuex/index.js` loads itself as you add `src` directory as module directory. https://github.com/fangxingguang/vue-base/blob/master/build/webpack.base.conf.js#L24

It should solve to just remove this line or rename `vuex` directory with other name.

**Comment by fangxingguang** [comment]
https://github.com/fangxingguang/vuex-test

**Comment by fangxingguang** [comment]
ok  thinks!
