### ISSUE TITLE
Is there a way to get the state as a raw object

### ISSUE THREAD

**Issue by pascallemoine** [vuejs/vuex#626]
Hi everybody, 

I'm wondering if there's a way to remove the observers of an object in the state to get a copy as a raw object. (shortly, to copy the state without reactivity).

Thanks in advance for your reply. ;)

**Comment by ktsn** [comment]
Just deep copy the state. (naive way is using `JSON.parse(JSON.stringify(state))`)

Please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) to ask usage/support questions in the future.
