### ISSUE TITLE
Cannot read property 'installed' of undefined at Function.Vue.use

### ISSUE THREAD

**Issue by philliperosario** [vuejs/vuex#627]
vue@2.8.1
vue-router@2.2.0
vuex@2.1.2
vuex-router-sync@4.1.2

![tela1](https://cloud.githubusercontent.com/assets/17308813/22867652/c9894992-f16a-11e6-80b8-11f9d881f100.jpg)
![tela2](https://cloud.githubusercontent.com/assets/17308813/22867654/cd07268e-f16a-11e6-8faf-ddfbe3679c9b.jpg)
![tela3](https://cloud.githubusercontent.com/assets/17308813/22867660/d1ed2ca2-f16a-11e6-97ae-589ce8f6cb86.jpg)

**Comment by ktsn** [comment]
Seems the same problem as #625

**Comment by philliperosario** [comment]
Solved removing the line 26 "resolve('src')" on build\webpack.base.conf.js! Thank you.

**Comment by kyovo** [comment]
Same problem, it happen to my in the Quasar default boilerplate cause looks like he try to import form my src before node_modules.

**Comment by omer-jan** [comment]
i have some problem too
![adfsdfsf](https://user-images.githubusercontent.com/20932799/39228749-eb48b6b4-4874-11e8-9d84-1ae00ff30d8b.JPG)

**Comment by IamCharmaineJoy** [comment]
![Image from iOS](https://user-images.githubusercontent.com/36432032/64071067-33f66780-cca4-11e9-9850-b8174255a58c.jpg)
