### ISSUE TITLE
Documentation on registering modules inside nested modules(namespaced: true)

### ISSUE THREAD

**Issue by t-sakharova** [vuejs/vuex#633]
I was trying to register dynamic module that would be related only to namespaced one and according to [documentation](https://vuex.vuejs.org/en/modules.html) first parameter should be a module name (String). 
But in [sources](https://github.com/vuejs/vuex/blob/dev/src/index.js#L134) I found that it possible to pass Array ['parent', 'myModule'] and 'myModule' will be created inside parent(that was what I needed).
Please update documentation, maybe, it will save someone's time

**Comment by ktsn** [comment]
Created a PR #634
