### ISSUE TITLE
Is there a way to reset the module state to initial state?

### ISSUE THREAD

**Issue by lyonlai** [vuejs/vuex#635]
^^

**Comment by ktsn** [comment]
Please read the [Issue Reporting Guideline](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Questions should be posted to [forum](https://forum.vuejs.org), [gitter](https://gitter.im/vuejs/vue) or StackOverflow. The issue list is exclusively reserved bug reports and feature requests.
Thanks.
