### ISSUE TITLE
Problem caused by state hydration

### ISSUE THREAD

**Issue by John0x** [vuejs/vuex#641]
Hey, I have a vue app, which uses vuex and SSR.

I call store.replaceState to replace the state of the client with the one generated by the server (dehydration).
The state is correctly replaced and the vue-devtools show the right states, but if I try to use the original instance (import the store from my js file), it shows the old states (without dehydration).
Accessing the store from within components works just fine, but I cannot rely on that in external classes.

You can use the https://github.com/vuetifyjs/webpack-ssr tempalte to reproduce the problem.

**Comment by John0x** [comment]
It seems like the store.replaceState does not work with namespaced modules. It only replaces the global states, not the states of the modules under it.

**Comment by ghjagus** [comment]
I met the same problem and i solved it by:

let __store = sessionStorage.getItem(STORE_CACHE_KEY)
if (__store) {
    store.replaceState(merge(store.state, JSON.parse(__store)))
}

one more thing: setting store.strict = false

And i would be glad to know a better way to solve this problem

**Comment by willworks** [comment]
@John0x Have you got over this problem yet?
