### ISSUE TITLE
多个页面能共享同一个store吗

### ISSUE THREAD

**Issue by 466023746** [vuejs/vuex#643]
项目中某个页面有几套代码，我想问：我有一个footer组件（公用的页脚组件），它的状态store我是每个页面都copy一份，还是就用同一个？

**Comment by wszgxa** [comment]
你应该好好看看文档，而不是问这种问题。

你可能都没有搞清楚vuex是为了解决啥问题的。

**Comment by XuXiaoGH** [comment]
vuex的为了解决一个页面内不同组件的数据流转的问题。
你一刷新，vuex store里state是会消失的。
你说的不同页面可以用 localstorage 或者 cookie解决。

**Comment by limichange** [comment]
你说的多页是单页应用里的页面吗？

**Comment by chenEdgar** [comment]
如果是单页应用的形式，不同路由下（不同页面）共享一个state， 刷新页面后，state状态会初始化。可以在mutation中改变state的时候将状态同步到 本地存储中。

如果是多页应用，状态直接后端传过来更好。

**Comment by midare** [comment]
footer 组件是分别在那几套代码中实现的吗？

**Comment by fnlctrl** [comment]
Closing as it's a usage question.

**Comment by xql279671304** [comment]
我也有同样的需求，现在有一个项目是多页应用的，但是有部分东西又是公用的，我想通过vuex来处理公用部分的状态及数据，不想用localstorage 或者 cookie ；之前就是用的这个两个东西，觉得还是不是很好，后端也不会给前端处理，vuex能做到吗？

**Comment by XuXiaoGH** [comment]
@xql279671304 记住 vuex 是一刷新存在里面的数据会消失的，再确认能不能用噢。
看看这篇。
https://segmentfault.com/a/1190000008861913

**Comment by xekri** [comment]
后端渲染其实是可以的，而且可以持久化

**Comment by Wancy-yule** [comment]
111
