### ISSUE TITLE
Dynamic store properties

### ISSUE THREAD

**Issue by kevinkleine** [vuejs/vuex#648]
Dear dev team,

First of all, congrats on all your hard work and achievements with Vue.js. Awesome work, very helpful. 

Currently I am building an app that discovers devices on the LAN, connects to them and automatically starts receiving state updates from these devices, in the form of nested objects. On receiving them, I'd like to store these device-state updates in the general Vuex store, so that the front-end can react on them. 

Unfortunately, I just found out that it is really hard to do that. The way I understand it, is that I would have to go through the device-state object recursively, adding each of these to the Vuex store with Vue.set to make the entire thing reactive, before the front-end will "know" each of these new state properties exist.

I am looking for a better way to do this... does one exist?

Thanx in advance!

**Comment by jingman** [comment]
Vue can't automatically tell when you add properties to an object (hence the need for `Vue.set`, which is a fine workaround). It _can_ tell automatically tell when you've added an element to an array - so maybe that's the best solution for you if you don't want to use `Vue.set`. But what's wrong with `Vue.set`?

**Comment by ktsn** [comment]
^ as @jingman said.
Please use [forum](https://forum.vuejs.org) or [gitter](https://gitter.im/vuejs/vue) for usage/support questions as the issue list is exclusively reserved for feature requests and bug reports.
Thanks.

**Comment by kevinkleine** [comment]
@jingman Switched to arrays! Thanks. @ktsn ok
