### ISSUE TITLE
how to dispatch module actions in different modules [not literally an issue]

### ISSUE THREAD

**Issue by reke592** [vuejs/vuex#649]
Hi!, I'm wondering how to properly dispatch my front_end module action after the authentication
in my case, I have my directory structure like:

vuex/
--actions/
--modules/
-----auth.js
-----front_end.js
--index.js

```
// actions/auth.js
export const authenticate = ({commit}, request) => {
	return authService.authenticate(request)
		.then((response) => {
			commit(AUTHENTICATE, response);
			return Promise.resolve(response);
		})
		.catch((error) => commit(AUTHENTICATE_FAILURE, error));
}

// actions/front_end.js
import { links } from '../../components/link-registry';
export const setPermittedLinks = ({commit}, response) => {
	// filter links only if successfully logged in
	if(!response.perms) return;
	
	commit(SET_PERMITTED_LINKS, _.filter(links, (link) => response.perms.hasOwnProperty(link.perm)));
}

// index.js
import auth from '../modules/auth';
import front_end from '../modules/front_end';

... export Vuex store with modules ...
```

is there a dedicated way to declare a chain or a pubsub for module actions?
like for example, in my front_end.js module:
```
const actions = {
 setPermittedLinks
}

const pubsub = ({ root }) => {
 root.module.auth.pubsub.push({ 'authenticate' : setPermittedLinks });
}
```

where instead of dispatching the front_end action itself, we make the front_end action to listen to the result of auth module action.

TIA

**Comment by ktsn** [comment]
Hi, thank you for filing this issue, however the issue tracker is exclusively reserved for bug reports and feature requests. We encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks.
