### ISSUE TITLE
Certain store mutations do not trigger updates

### ISSUE THREAD

**Issue by vnermolaev** [vuejs/vuex#654]
Hi there,

I have a pretty basic Vue+Vuex setup.
Let A be a component with a computed field which depends on the Vuex store and a lifecycle hook --- created() which dispatches an event to the store to request some data from a RESTful server.

The expected behavior and a deviation from it are as follows:

1. created() dispatches an event to the store; **goes well**
2. the store makes requests and commits data; **goes well**
3. mutation updates the state; **goes well** (this can be seen in the developers tab of Vue in Chrome)
4. computed field is updated triggering a re-render of the template; **it depends**

The last procedure goes well, i.e., the component template is re-rendered after the updates, if the field of the store being updated is an array and this array is updated with methods like push(), splice() (may be others too, but I did not investigate further).

The last procedure does not go well, if the field of the store being updated is an array and this array is updated via index access, e.g., array[n] = data. Or if the field is an object.

I made a repository containing [this example](https://github.com/quicky84/vue-update).
 It contains a restful server which gives out some data and the Vue+Vuex setup I described. There in file store.ts I present two described options --- with the array and object --- they are marked with `!!!` in the beginnings of commented line.

By default the array option is active, so everything must update as expected. If you uncomment lines related to the object and comment those related to the array, no update of the component template will happen.

**Comment by znck** [comment]
You should use: `array.splice(n, 1, data)`

**Comment by quicky84** [comment]
All right. I figured it out. But how do you go about objects? Object are musch handier if you update data in the store. Setting fileds as `object[key] = data` does not trigger updates either.

PS: I did not find docs that arrays must be modified with splice to trigger changes.

**Comment by simplesmiler** [comment]
@quicky84 `Vue.set(object, key, data)`.

Objects: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
Arrays: https://vuejs.org/v2/guide/list.html#Caveats

**Comment by znck** [comment]
IMO https://vuex.vuejs.org/en/mutations.html should have examples or more info this.

**Comment by simplesmiler** [comment]
@znck well, there is a note, https://vuex.vuejs.org/en/mutations.html#mutations-follow-vues-reactivity-rules
Maybe bringing this up a few sections will help?

**Comment by znck** [comment]
Reopening to track docs.

**Comment by quicky84** [comment]
Thanks a lot for pointing to the right piece of docs. I must have been to anxious to jump into action.

**Comment by mcorbe** [comment]
Hi all, 

Seems the doc is missing the case when updating a value in an array.

Here is a thread on the topic: https://forum-archive.vuejs.org/topic/2243/updating-an-object-in-array-inside-vuex-store-doesn-t-result-in-view-update

I am not sure what is the doc status at this stage. Should I update it ?

**Comment by tetreault** [comment]
This issue hasn't been touched in a while but i'm running into something confusing on my end when using a computed property for a textarea value. 

I have a textarea where you give input text: 

```html
            <textarea
              ref="inputText"
              :value="getInputText"
              @input="setInputText"
              class="textarea"
              placeholder="Your message goes in here"
            ></textarea>
```

On the click of a button to translate the text I call a `handleInput` method. 

```javascript
    handleInput() {
      this.$store.dispatch("translateEnglishToRussian");
    },
```

In my store I have my `translateEnglishToRussian` action: 

```javascript
translateEnglishToRussian({ commit }) {
        const TRANSLATE_API =
          "https://XXXXXXXX.us-east-1.amazonaws.com/prod/YYYY/";
        const data = JSON.stringify({ english: this.state.inputText });

        this.$axios
          .$post(TRANSLATE_API, data)
          .then(data => {
            commit("setOutputText", data.translatedText);
            commit("setMP3Track", data.mp3Path);
          })
          .catch(err => {
            console.log(err);
          });
      }
```

I see it call `setOutputText` mutation with the payload of translated text, in my vue dev tools I see the correct state with the translated text. However, my second text area that's being used purely to display the translated text _never updates!_ 

Output textarea:
```html
           <textarea
              disabled
              ref="outputText"
              :value="getOutputText"
              class="textarea"
            ></textarea>
```

Its value is bound to a computed property called `getOutputText`: 

```javascript
    getOutputText() {
      return this.$store.state.outputText;
    }
```

What am i doing wrong here! Any advice is appreciated. I thought this should be fine since i'm using `commit` in my vuex action in a synchronous way (inside the then() block).

**Comment by douglasg14b** [comment]
I'm having this same issue, but NOT with an array.

I'm updating a single, numeric, value.

__________________________________________________

I have `steps` and `stepsComplete`. These are mutated in rapid succession during route changes. They are accessed through getters from the component.

I can follow, in the devtools, each commit and store state. But they are not always represented on the component:

* Starting with: `steps: 2` `stepsComplete: 2`
* In every step, the vuex state matches what is expected

1. Set `steps = 1`, `stepsComplete = 0`
    *  Component shows: `steps: 1` `stepsComplete: 2` :x:
2. Set `steps = 2`
    * Component shows: `steps: 2` `stepsComplete: 2` :x: 
3. Set `stepsComplete = 1`
    * Component shows: `steps: 2` `stepsComplete: 1` :heavy_check_mark: 
4. Set `stepsComplete = 2`
    * Component shows: `steps: 2` `stepsComplete: 2`  :heavy_check_mark: 

As you can imagine having a loading bar going from 0 to 100%, then to 50%, then to 100% is a bit concerning, especially when the Vuex state matches, but the component doesn't always match.

**Comment by goelrohan6** [comment]
> @quicky84 `Vue.set(object, key, data)`.
> 
> Objects: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
> Arrays: https://vuejs.org/v2/guide/list.html#Caveats
> 
> Closing, as this is not a bug.

Hey @ simplesmiler but how can we cannot use $set in vuex mutations ?
I am facing a similar issue, adding a new key to an object in store
In case of array my computed property in component gets updated but doesn't work when setting the value as a string.

**Comment by kiaking** [comment]
@goelrohan6 When adding a new key to the object, and when you can't use `Vue.set`, you should recreate fresh one as described at the doc.

```js
state.data = Object.assign({}, state.data, { a: 1, b: 2 })

/// or...

state.data = { ...state.data, a: 1, b: 2 }
```

And, I'll be closing this issue for now since it's quite outdated, and the discussion isn't matching the latest topics. Please feel free to open another issue if you find anything! 👍
