### ISSUE TITLE
strict mode is slow, I had to disable it even when debugging

### ISSUE THREAD

**Issue by Lesiuk** [vuejs/vuex#659]
I'm using https://github.com/Starcounter-Jack/JSON-Patch to apply patches to state in my mutations and I noticed that with around 1 000 changes my application becomes unresponsive for 3 seconds (100% cpu usage on 1 core). When I disable strict mode I can even apply 100 000 changes without any lag.

I think It's because of this code.

> function enableStrictMode (store) {
>   store._vm.$watch(function () { return this._data.$$state }, () => {
>     assert(store._committing, 'Do not mutate vuex store state outside mutation handlers.')
>   }, { deep: true, sync: true })
> }

It probably should be noted inside documentation that stirct mode makes changing state really slow.
I lost few hours debugging it.

Anyway, vuejs & vuex are great. Thank you.

**Comment by yyx990803** [comment]
Hmm, this is because the strict mode uses a synchronous deep watcher on the entire state tree. JSON-Patch is performing many ops synchronously and each of them triggering the watcher to re-traverse the state tree. We will likely use an async watcher instead.

**Comment by yyx990803** [comment]
Actually, the watcher has to be sync - I guess we'll just make sure the docs is explicit about the cost. Thanks for pointing this out.

**Comment by OuYancey** [comment]
I have the same problem.
Once I save a large data(about 200 KB) into store, it slows all my app. (is it a right way to save data? should I save in the $root, not in the state?)
So, i thought it's better to add `unDeepFields` into `createLogger` 's options.
In this way, we can let something expensive out of deep copy.
like this:
```
export default function createLogger ({
  collapsed = true,
  filter = (mutation, stateBefore, stateAfter) => true,
  transformer = state => state,
  mutationTransformer = mut => mut,
  unDeepFields = []  // <---
} = {})
```
check the `unDeepFields` before deepcopy
```
  Object.keys(obj).forEach(function (key) {
    if (unDeepFields.indexOf(key) > -1) {
      copy[key] = obj[key];
    } else {
      copy[key] = deepCopy(obj[key], cache);
    }
  })
``
and something else changed in the `logger.js` file...
```
  // just call like this
  createLogger({
    unDeepFields: ['dataCenter']
  })
```

I just test in my own project, is this OK?

**Comment by andreiglingeanu** [comment]
I just experienced that today, disabling strict mode made mutations run at `0.04ms` from `20ms`.
