### ISSUE TITLE
How to ref a prop as the namespaced module's name?

### ISSUE THREAD

**Issue by g8up** [vuejs/vuex#661]
How to do like this:
```javascript
props: [ 'moduleName' ],
computed: {
  ...mapState( this.moduleName, { // how to ref a prop as the namespaced module's name?
    bar: state => state.bar
  }
},
```

**Comment by LinusBorg** [comment]
That's not possible, because `mapState` is being called before the component instance is created, so the prop does not have any value at that point.

If you want to dynamically access different namespaces, you can't use `mapState` here.

**Comment by onekiloparsec** [comment]
Too bad, that's exactly what I needed.
