### ISSUE TITLE
when use bluebird as default promise, return a commit show up a warning. 

### ISSUE THREAD

**Issue by FTAndy** [vuejs/vuex#664]
when I return a bluebird promise in action, like this: 
```javascript
actions: {
  [XXX] ({commit, rootState}) {
    return Promise.resolve.then(() => {return commit(XXX)})
  }
}

mutations: {
  [XXX] (state) {
    // update something
  }
}
```
come up a warning from bluebird
```
Warning: a promise was created in a handler but was not returned from it
```
it seems a promise is created in commit, and did not return. 

when it comes to native promise, it is fine. native do not warn a not return promise.

but i suggest any promise should return. is it a bug or just a normal behavior ?

**Comment by LinusBorg** [comment]
Hello @FTAndy,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))


Thank you.

**Comment by FTAndy** [comment]
from `vuex/src/store.js` 77 line:
```javascript
    this._withCommit(() => {
      entry.forEach(function commitIterator (handler) {
        handler(payload)
      })
    })
```
seems the `commit` method just call all mutations functions, and do not return a promise, which cause a bluebird warning.

add `return null` after `commit` method cancel the warning.

**Comment by LinusBorg** [comment]
`commit()` doesn't return a promise beause it's sync. 

Furthermore, actions do return a promise, always. that's handled internally in vuex. 

Bluebird warns about this, but that's just bluebird's attempt at being helpful, but the code is not "wrong" and works as intended, So I don't think there's much to do for us here.

Do you have a suggestions?
