### ISSUE TITLE
Execute actions, mutations and getters in context of the store?

### ISSUE THREAD

**Issue by JiriChara** [vuejs/vuex#665]
Hey,

I am writing a plugin for a Vuex store that should add security layer to the actions.

```js
const counterPermiter = createPerimeter({
  purpose: 'counter',

  govern: {
    'can increment': function () { return this.child && this.child.isAdmin; }
  }
});

export default new Vuex.Store {
  plugins: [
    myPlugin({
      child: store => store.state.user || null
    })
  ],

  state: {
    counter: 0
  },

  perimeters: [
    counterPerimeter
  ],

  actions: {
    incAsync({ commit }) {
      if (this.$sandbox.isAllowed('increment')) {
        // commit increment..
      }
    }
  },
  //
};
```

The problem is that `this` in context of an action is `undefined`. Do you think it would make sense to execute actions bound to current module or in context of store?

I can submit a PR, if you guys think that it's a good idea.

**Comment by ktsn** [comment]
Do you mean you want to inject some additional values into action context? If so we have a PR for it. #571

**Comment by JiriChara** [comment]
That's awesome! Closing
