### ISSUE TITLE
监听问题

### ISSUE THREAD

**Issue by pinghe** [vuejs/vuex#668]
在子组件中想监听state中某属性变化，每当这个值发生变化，触发回调执行子组件的某个方法，不知道怎么做能给个示例吗

**Comment by CodinCat** [comment]
Vuex Store 的 instance 就有 watch 方法：https://vuex.vuejs.org/zh-cn/api.html#vuexstore-实例方法

用來監聽一個 getter function 的返回值，範例：
http://codepen.io/CodinCat/pen/PpNvYr?editors=0011

但是多數情況你都不會需要使用 watch，因為 Vue 和 Vuex 本身就是 reactive 的。

另外問題請至[論壇](https://forum.vuejs.org/)或 stackoverflow 上發問，這裡是用來回報 issue 的。

----

This issue can be closed. (not a bug report nor feature request)
