### ISSUE TITLE
Node 6.10 > Error "must call Vue.use(Vuex) before creating a store instance" without any reason …

### ISSUE THREAD

**Issue by Shudrum** [vuejs/vuex#676]
Hello everyone!

I just cloned my project on a fresh machine install with the latest 6.10 version of Node.js.
Everything works fine during the webpack build but my app just didn't works anymore…

I look at the console and OH! The noob error: `[vuex] must call Vue.use(Vuex) before creating a store instance.`…

Be sure I know how to use Vuex as my project works perfectly from months.

I'll try to find out why, I really need to update my project, I hope I'll find out how.

Here is my main js file FYI:

```javascript
const theme = require('../themes/default');
const Vue = require('vue');
const Vuex = require('vuex');
const Nes = require('nes');
const app = require('./components/app');

Vue.use(Vuex);

const store = new Vuex.Store({
  state: {
    // …
  },
  mutations: {
    // …
  },
});

const vm = new Vue({
  store,
  el: '#app',
  template: '<app/>',
  components: { app },
});
```

Thank you!

**Comment by fnlctrl** [comment]
Vue has just switched to es modules for the default entry. So instead of 
```js
const Vue = require('vue');
const Vuex = require('vuex');
```
use `import` instead
```
import Vue from 'vue';
import Vuex from 'vuex';
```

-------

If your module bundler can't handle `import`,
use 
```js
const Vue = require('vue').default;
const Vuex = require('vuex').default;
```

**Comment by Shudrum** [comment]
How … missed that ><

Thank you very much, I thinked about migrate to import so … this is the time.

**Comment by Khachatour** [comment]
Hey there I do have same problem, and tried all the ways, and nothing helps!! @Shudrum  @fnlctrl guys ? any help ?

**Comment by olivbau** [comment]
Same @Khachatour

**Comment by adamzerner** [comment]
See https://github.com/vuejs/vuex/tree/dev/examples/shopping-cart for how they do it in their sample app.

**app.js**
```
import 'babel-polyfill'
import Vue from 'vue'
import App from './components/App.vue'
import store from './store'
import { currency } from './currency'

Vue.filter('currency', currency)

new Vue({
  el: '#app',
  store,
  render: h => h(App)
})
```

**store/index.js**
```
import Vue from 'vue'
import Vuex from 'vuex'
import * as actions from './actions'
import * as getters from './getters'
import cart from './modules/cart'
import products from './modules/products'
import createLogger from '../../../src/plugins/logger'

Vue.use(Vuex)

const debug = process.env.NODE_ENV !== 'production'

export default new Vuex.Store({
  actions,
  getters,
  modules: {
    cart,
    products
  },
  strict: debug,
  plugins: debug ? [createLogger()] : []
})
```
