### ISSUE TITLE
Is there a way of accessing $refs from a component in Vuex?

### ISSUE THREAD

**Issue by CoolGoose** [vuejs/vuex#677]
Is there a way of accessing $refs from a component in Vuex?
I am having vue-table-2 component, and I'm trying to trigger it's reload() function and i'd rather not pass around the status :)

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue, however the issue tracker is reserved for bug reports and feature requests only,  please use  [gitter](https://gitter.im/vuejs/vue) or [forum](https://forum.vuejs.org/) or [stackoverflow](https://stackoverflow.com) to ask questions. Thanks!

-----------

Vuex is only meant for state management, and should never be used to coupled to view (access $el, $refs etc.)
The proper approach would be passing the state to the component that needs it.

**Comment by LinusBorg** [comment]
Also, Vuex actions should not be coupled access to any component instances, that seems counter the idea of vuex. it should only care about state - deciding what to do with that state in the browser is the job of the component.
