### ISSUE TITLE
ES6的set改变为什么不能触发getter改变？

### ISSUE THREAD

**Issue by yozosann** [vuejs/vuex#678]
state：`order: new Set();`
按下一个按钮触发：`state.order.add(Math.random());`
getters：`  randomArr(state) {
    console.log(...state.order);
    return [...state.order];
  }`
点击了并没有反应。
而把order换成数组， add换成push就有反应。

**Comment by fnlctrl** [comment]
目前 Vue 的响应式系统不支持ES6的Map/Set，未来会有支持。
