### ISSUE TITLE
Vuex + vue-webpack-boilerplate (Uncaught TypeError: Vue is not a function)

### ISSUE THREAD

**Issue by jbruni** [vuejs/vuex#68]
I am getting this error:

> Uncaught TypeError: Vue is not a function

At this specific line: https://github.com/vuejs/vuex/blob/master/src/index.js#L32

I am using the [webpack template](https://github.com/vuejs-templates/webpack).

I was able to reproduce the issue applying these minimal changes to the initial template:
https://github.com/jbruni/vuex-webpack-issue/commit/50af38cfbb94dc27a6d48082d0e7ecd6d0650366

Please, take a look... I believe the solution for this issue is very simple.

(I was not sure if I should open the issue at webpack template repo or here. It seems a Vuex issue to me, so I opened here. Thank you.)

Note: the same error happens both using `npm run dev` as well as building with `npm run build` and HTTP serving the static build.

**Comment by jbruni** [comment]
Nevermind... I didn't call `Vue.use(Vuex)` ... I was able to fix it:

https://github.com/jbruni/vuex-webpack-issue/commit/4c89c86db697df79fabe4ecf6b23d76b06abc24a#diff-3bf35cd41da51153dcca3003656f7c67

**Comment by jbruni** [comment]
Anyway, I'm considering this a documentation issue... I had to take a look at skyronic blog post to figure this out...

**Comment by yyx990803** [comment]
I'd suggest holding back for a few days (and checkout `0.4.0` branch of vuex which has a different API and updated docs)

**Comment by jbruni** [comment]
Great. I'm already playing with `0.4.0`. I had to manually run `prepublish` and it requires `babel-cli`. Please consider including at `package.json`'s `devDependencies`:

```
"babel-cli": "^6.6.0",
```
Thank you, @yyx990803
