### ISSUE TITLE
It is not possible to `watch` whole state

### ISSUE THREAD

**Issue by alekbarszczewski** [vuejs/vuex#682]
When getter passed to `router.watch` returns whole state it is never called.

```vue
<script>
export default {
  created () {
    this.$store.watch((state) => (state.auth), this.handleAuthUpdate);
    this.$store.watch((state) => (state), this.handleStateUpdate);
  },
  methods: {
    handleAuthUpdate () {
      console.log('auth updated');
    },
    handleStateUpdate () {
      console.log('state updated');
    },
  },
};
</script>
```

```js
const store = new Vuex.Store({
  state: {
    auth: null,
  },
  mutations: {
    setAuth (state, auth = null) {
      state.auth = auth;
    },
  },
});

setTimeout(() => {
  store.commit('setAuth', {});
}, 3000);
```

Console output:
```
auth updated
```

I guess watching whole state is not a best idea but at least it should be noted in docs that returning whole state from getter won't work. Or maybe there is such info in docs? I couldn't find it...

* Vue 2.2.1
* Vuex 2.2.1

**Comment by ktsn** [comment]
Just use `deep` option.
Vuex store's `watch` method is same as Vue's `$watch`.
http://vuejs.org/v2/api/#vm-watch

**Comment by alekbarszczewski** [comment]
Thanks, it works!
