### ISSUE TITLE
Getters Docs Typo

### ISSUE THREAD

**Issue by ferborva** [vuejs/vuex#683]
In the getters doc (english version at least) there is an example showing a query by ID:
```
getters: {
  // ...
  getTodoById: (state, getters) => (id) => {
    return state.todos.find(todo => todo.id === id)
  }
}
```

If you look at the [.md file](https://github.com/vuejs/vuex/blob/dev/docs/en/getters.md) the example is correct. However there is a typo in the [.html deployed version](http://vuex.vuejs.org/en/getters.html):

```
getters: {
  // ...
  getTodoById: (state, getters) => (id) => {
    return getters.todos.find(todo => todo.id === id)
  }
}
```
Line: return **getters**.todos.find(todo => todo.id === id)

**Comment by ktsn** [comment]
Updated.
