### ISSUE TITLE
How to pass parameters to the function in getters

### ISSUE THREAD

**Issue by huangyanxiong01** [vuejs/vuex#688]
`store`
```js
export default  new Vuex.Store({
   getters:{
    search(state,keyword){
      //return state.items; //first question
     //second question
      return state.items.filter(item =>{
        return item.name === keyword
      });
    }
  }
})
```
`component`
```js
  export default {
    name: 'items',
    computed: {
      search () {
        return this.$store.getters.search
      }
    }
  }
```
1.It don't work,why? According to this [document](https://vuex.vuejs.org/en/getters.html)
2.How to pass parameters to the function in getters?

**Comment by znck** [comment]
You may want to do this.

```js
export default  new Vuex.Store({
   getters:{
    search(state) {
      return keyword => state.items.filter(item =>{
        return item.name === keyword
      });
    }
  }
})
```

```js
export default {
    name: 'items',
    computed: {
      search () {
        return this.$store.getters.search('foo')
      }
    }
  }
```

-------------
If you want to ask such questions, please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). The issue list is reserved exclusively for bug reports and feature requests.

Thanks.

**Comment by huangyanxiong01** [comment]
thank you very mach!

**Comment by askhat** [comment]
One more arrow, if you will

```javascript
export default {
  getters: {
    getByIndex: state => index => state.someArray[index]
  }
}
```

**Comment by hjJunior** [comment]
@znck did you know if is possible to load getters in component using mapGetters?

I mean, instead of this
`return this.$store.getters.search('foo')`

do something using the mapGetters
`...mapGetters(['something', search(params)']),`

**Comment by hjJunior** [comment]
Someone knows if is possible to load getters in component using mapGetters?

I mean, instead of this
`return this.$store.getters.search('foo')`

do something using the mapGetters
`...mapGetters(['something', search(params)']),`

**Comment by johanbaaij** [comment]
@hjJunior yeah, make sure to use the notation @askhat used, and you can just do  
`...mapGetters(['something', search']),`  
and then `this.search(params)`

**Comment by hjJunior** [comment]
That's sound good :) Thx @johanbaaij

**Comment by Harti** [comment]
Glad you all are flinging around the lambdas like they're trendy, but does anybody have an actual explanation as to how the parameters are forwarded to the arrow functions?

**Comment by askhat** [comment]
@Harti it is quite clear when you're seeing syntax

```javascript
// some store instance
getters: {
  regularGetter: state => state.someProp,
  curryGetter: state => param => state.someArr.find(el => el === param)
}

// some component instance
someInstaceMethod () {
  // it is precomputed so it hold a reference to a value in the store
  // until some of its subciptions has been invalidated
  this.$store.getters.regularGetter

  // it is called curry 'cause it is currying its params to its inner function
  this.$store.getters.curryGetter // this will just return a function so it is uselless yet
  // in order to be able to call an inner function you may use syntax below
  this.$store.getters['curryGetter'](someParam)
  // as you may observe the line above will take a function from getter
  // then call it with given param, and since it holds a reference to the store in its closure
  // it will be able to perfom desired computations
}
```

Hope it's explanins why everybody talk about lambdas.

**Comment by molerat619** [comment]
So should I move `...mapGetters[...]` to the `computed` section then or to methods? Because for me it only returns the method if I keep them in the methods and I don't want to end up doing `this.myGetter()(param)`.

**Comment by Picturk** [comment]
...Use an Action to handle the api call. Update the store with a mutation. Use a getter to ‘shape’ the data into what’s needed by your app.

**Comment by RizaHKhan** [comment]
How would this work when you have multiple store files?
```
computed: {
  format () {
    return this.$store.getters('formats/singleFormat', 15)
   }
}
```
^ does not work

**Comment by felipe-muner** [comment]
Amazing dudes, Nice job !

**Comment by xgqfrms** [comment]
# 🎩 magic

**Comment by ArtuGit** [comment]
I would add if you have a store with modules, you can invoke a getter with a parameter by this way
`this.$store.getters['storeName/getterName'](param)`
