### ISSUE TITLE
关于action的返回值

### ISSUE THREAD

**Issue by github-liuzhao** [vuejs/vuex#690]
registerAction函数中

 `if (!isPromise(res)) {
      res = Promise.resolve(res)
    }`
对一个非promise的action执行后返回值统一以Promise.resolve返回了.能否更详细一下，如果res是false，则返回Promise.reject处理？

**Comment by jackPanyj** [comment]
这个跟res是false或者true并没什么关系。
只是将res包装成Promise的形式。
![image](https://cloud.githubusercontent.com/assets/12585605/23984391/48883238-0a54-11e7-97df-972803659fa7.png)

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！

-------

同上，只是把你本来的返回值包装成promise
