### ISSUE TITLE
是否可以在不同module里调用各自的state数据

### ISSUE THREAD

**Issue by monyee** [vuejs/vuex#692]
如题：
 modules
             A-module
             B-module

B-module中调用A-module中的state是否可以行？ 该如何调用   thx~

**Comment by znck** [comment]
Your issue seems usage/support question. If you want to ask such question, please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). The issue list is reserved exclusively for bug reports and feature requests.

Thanks.
