### ISSUE TITLE
Can getters be triggered to reload the data?

### ISSUE THREAD

**Issue by FlappyHeart** [vuejs/vuex#694]
```
const getters = {
  nodeTree(state){
    return lib.listToTree(state.nodeList)
  }
}
```
The nodeTree returns data which bind with the ui component. When I update the nodeList in mutations, I want to refresh the nodeTree data directly, what can I do with this? Any help will be appreciated.

If getters cannot be triggered manually, I can just add another property in my state object.

**Comment by ktsn** [comment]
Hi, thank you for filing this issue. 
However, your issue seems usage/support question. As the issue list is exclusively reserved for bug reports and feature requests, we encourage you to use our [forum](https://forum.vuejs.org) or [gitter](https://gitter.im/vuejs/vue) to ask questions.
Thanks.
