### ISSUE TITLE
When using lambda in computed properties to access vuex state, I got undefined

### ISSUE THREAD

**Issue by chenyi** [vuejs/vuex#700]
When using function to define computed properties, everything goes fine. But if using lambda instead, I got undefined.

```
//OK
computed: {
      counter () {
        return this.$store.state.counter
      }
    }
//OK
computed: {
      counter: function () {
        return this.$store.state.counter
      }
 }
//not work
computed: {
      counter: () => {
        return this.$store.state.counter// undefined
      }
 }
```

**Comment by jkzing** [comment]
In vue doc [Properties and Methods](https://vuejs.org/v2/guide/instance.html#Properties-and-Methods), it warned `Don’t use arrow functions on an instance property or callback`, maybe this is the reason.

**Comment by simplesmiler** [comment]
Arrow functions are supposed to work this way.
