### ISSUE TITLE
id property is set to undefined on object during state mutation of array

### ISSUE THREAD

**Issue by lasernite** [vuejs/vuex#701]
It appears that on concatenating lists of objects to the state in a mutation, all of the parameters get saved except `id`, which appears to save as `undefined`. Is id a protected parameter or is something else going on?

**Comment by lasernite** [comment]
Nvm sorry... was accidentally overwriting the id on an intended equality check. Shouldn't Vuex throw warnings when the store is updated from within a component?

**Comment by ktsn** [comment]
You may want to enable strict mode. https://vuex.vuejs.org/en/strict.html
