### ISSUE TITLE
API for mapping both state and getters into a fused computed object.

### ISSUE THREAD

**Issue by YurySolovyov** [vuejs/vuex#702]
I'd like to propose a new helper method that gathers both state and getters into a single object that can be used as a computed properties descriptor:

```js
{
  // ...
  computed: Vuex.mapComputed({
    // can map getters
    getters: {
      computedProp: 'getterName'
    },
    // can map state
    state: {
      otherComputedProp: 'stateKey'
    }
    // can provide plain computed as function
    plainComputedProp: function() { ... }
  })
  // ...
}
```
If you're ok with idea, I'm totally ok to change the name of the API if needed.

The reason to have this API is that not everyone can have access to object spread or `Object.assign` with babel+webpack pipeline set up and can only use plain objects.

**Comment by ktsn** [comment]
Thanks for suggesting this feature. However this should be implemented as a third party library rather than the core library because it is a combination of the existing functionality and can completely be achieved out of the core codes.

**Comment by YurySolovyov** [comment]
@ktsn any suggestions on how to implement this? I assume this can be done as a plugin for Vuex ? And even then, what should I do? Just add a method directly on store instance? Or rather modify the prototype so that every store gets it?

**Comment by ktsn** [comment]
@YurySolovyov Here it is. https://jsfiddle.net/62e6xw8u/

**Comment by YurySolovyov** [comment]
@ktsn thanks, though I'd like to hear your high-level thoughts on implementing such helper, I can for sure implement it on my own, but what's the Right Way to do it in your opinion?.

**Comment by ktsn** [comment]
Sorry, I may not follow your point but I'd say you don't have to provide it as neither Vuex plugin or store method because it just a helper function. The example that I provided is full-contained.
