### ISSUE TITLE
Bind "this" to the current store instance in mutations

### ISSUE THREAD

**Issue by sametmax** [vuejs/vuex#703]
### What problem does this feature solve?
Often I want to refactor commun behavior from several mutations in a store method. I use "store" as the variable name to reference the store instance, and reference it everywhere because I can't use "this", which is the Window object.

Vue components rebind "this" for computed properties and methods, it would be congruent to do it in vuex mutations as well.

### What does the proposed API look like?

```
var store = new Vuex.Store({
mutations: {
   foo: function(state){
       console.log(this); // this outputs the store instance
   }
}})
```

**Comment by CodinCat** [comment]
Why a mutation needs to access the store instance? I think it is intended that A mutation receives `state` as parameter instead of `store`, simply because it doesn't need to. 
Or maybe you have to provide your use cases.

**Comment by znck** [comment]
Use https://new-issue.vuejs.org/ to create a feature request issue and provide your use case.

**Comment by zxwild** [comment]
Mutations can be relatively large, so if I place some helper method to vuex store it's impossible to use it within mutaions.

```javascript
new Vuex.Store({
    // ......
    mutations: {
        'some-mutation': function(state, payload) {
            this.my_helper_method(payload);
        }
    },
    my_helper_method: function() {
        console.log('I do much work');
    }
})
```

**Comment by afontcu** [comment]
Hi!

AFAIK [mutations](https://vuex.vuejs.org/en/mutations.html) shouldn't be "that" big, they should have a single responsibility: update `state` and that's it. Maybe you are just trying to do "too much" in your mutations and you should place your logic in other places (methods, for instance)?

None of my mutations have become so large that I needed to extract helpers. So far...!

**Comment by ianfieldarsclinica** [comment]
I'm with zxwild.  I need to conditionally lookup some properties from pretty deep inside a complex state object.  I have a function to do this that is used elsewhere.  Not being able to reuse it in my mutation is a headache.
