### ISSUE TITLE
Namespaced mapState calls return child module's state

### ISSUE THREAD

**Issue by t2t2** [vuejs/vuex#708]
### Version
2.2.1

### Reproduction link
[https://jsfiddle.net/t2t2/x48eeLor/](https://jsfiddle.net/t2t2/x48eeLor/)

### Steps to reproduce
1. Have a namespaced module with child module, both with states
2. use `mapState(parentName, ...)`

### What is expected?
Get the namespaced module state

### What is actually happening?
Get child module's state

**Comment by ktsn** [comment]
Thanks for filing this issue. It looks a bug.
