### ISSUE TITLE
mapState incorrect behavior with nested modules

### ISSUE THREAD

**Issue by barbarNik** [vuejs/vuex#712]
### Version
2.2.0

### Reproduction link
[https://jsfiddle.net/7mda66b9/9/](https://jsfiddle.net/7mda66b9/9/)

### Steps to reproduce
* create vuex namespaced module **A**
* create vuex NOT namespaced nested module **B** inside **A**
* use mapState with namespace **A**

### What is expected?
it is expected to get state of module **A** in mapState

### What is actually happening?
mapState provides state of module **B**

**Comment by ktsn** [comment]
Thanks. It is already fixed via #709

**Comment by barbarNik** [comment]
@ktsn great thanks!
