### ISSUE TITLE
[docs] Vuex version interpreted as email by Cloudflare and removed

### ISSUE THREAD

**Issue by gavinfoley** [vuejs/vuex#719]
### Version
2.2.0

### Reproduction link
[https://vuex.vuejs.org/en/](https://vuex.vuejs.org/en/)

### Steps to reproduce
1. Navigate to https://vuex.vuejs.org/en/ - observe text "Note: This is docs for vuex@2.x."
2. Click the "What is Vuex?" link on the left.
3. Click the "Introduction" link on the left to return to the first page.  Observe text "Note: This is docs for [email protected]".

### What is expected?
Text does not change.

### What is actually happening?
Cloudflare interprets "vuex@2.x." as an email address and redacts it. https://vuex.vuejs.org/cdn-cgi/l/email-protection

**Comment by ktsn** [comment]
Thanks for reporting. It should be fixed now.
