### ISSUE TITLE
Is there a reason that you chose the Flux pattern over Redux pattern for Vue?

### ISSUE THREAD

**Issue by dschissler** [vuejs/vuex#72]
I'm reviewing frameworks and watching videos and I noticed that Vuex is based upon Flux which from my beginner perspective is being phased out for Redux.  Is there a reason why Flux is being pushed?

**Comment by yyx990803** [comment]
Vuex is "Flux inspired", and similar to how Redux is different from vanilla Flux, Vuex is different from vanilla Flux too. In fact, Vuex is more similar to Redux than to original Flux.

**Comment by yyx990803** [comment]
In addition: when we talk about Flux today, it's no longer about a specific pattern, but a loose set of principles about application state management - namely uni-directional data flow enforced via action dispatching. This applies to Redux as well, because Redux evolved from Flux.
