### ISSUE TITLE
在vuex 中修改了状态 但是 vue中没有渲染

### ISSUE THREAD

**Issue by mimimi1227** [vuejs/vuex#720]
问题是vue中 初始化了 列表
在mutations 中使用splice 替换了数组的index
在vue中watch到了 arr 发生了变化 但是 页面却没有 及时更新渲染出来

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
