### ISSUE TITLE
使用webpack打包压缩logger.js时出错

### ISSUE THREAD

**Issue by fengxinming** [vuejs/vuex#725]
ERROR in vendor.2893febb.js from UglifyJs
Name expected [./~/.2.2.1@vuex/src/plugins/logger.js:5,0][vendor.2893febb.js:16942,23]

麻烦大神们瞧一瞧

**Comment by ktsn** [comment]
Hi, please follow [issue reporting guideline](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and  provide a minimal reproduction on jsfiddle, codepen or so on if you do bug report, Thanks!
