### ISSUE TITLE
Devtools throws error when using State Functions

### ISSUE THREAD

**Issue by renatodex** [vuejs/vuex#726]
### Version
2.2.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/25186/](https://jsfiddle.net/50wL7mdz/25186/)

### Steps to reproduce
1. Since Devtools doesnt works on JSFiddle, you have to copy the code to a local environment and run it on your server (like node http-server).

2. Open Devtools, go to State Panel

3. Click the "add bread" button, and generate some states.

4. On the State Panel, try to "Revert" some mutations

### What is expected?
It expected to apply the reference and return to the previous state.

### What is actually happening?
If returns an error: Store.state.Ingredients.bread is not a function

---
Its correct to use this kind of Reference at State object?
Should i use a getter instead?

![captura de tela 2017-04-02 as 16 04 34](https://cloud.githubusercontent.com/assets/68507/24590143/9f7befa4-17be-11e7-8fed-69e18efe6e7c.png)

**Comment by ktsn** [comment]
This is because devtools serializes state to retain snapshots for time-travel. You should include only serializable value in the store state.
