### ISSUE TITLE
How to get a special value from array? 

### ISSUE THREAD

**Issue by ghost** [vuejs/vuex#727]
For example, I only need one value from config array. Therefore, I do not want to use for loop. In addition, the config array is a associative array.

**Comment by ktsn** [comment]
Hi, please make sure to follow [issue reporting guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines). Usage/support questions should be posted our [forum](https://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or StackOverflow. Thanks!
