### ISSUE TITLE
Fetch API example for shopping cart

### ISSUE THREAD

**Issue by dschissler** [vuejs/vuex#73]
I'm really liking the Fetch API and I'm having a difficult time imagining how it could be cleanly written for Vuex.

**Comment by yyx990803** [comment]
In most cases you would have an extra layer of API abstraction that uses fetch as an underlying implementation detail; for example you'd use fetch for the actual HTTP request inside https://github.com/vuejs/vuex/blob/master/examples/shopping-cart/api/shop.js#L12 (replacing the fake setTimeout).
