### ISSUE TITLE
vuex.esm.js?edaa:336[vuex] unknown action type: getComeSoonList

### ISSUE THREAD

**Issue by yehoan** [vuejs/vuex#740]

**Comment by xuedongshao** [comment]
@yehoan   你好，我也遇到了相同的问题，请问您解决了吗
![2018-11-28 10 15 35](https://user-images.githubusercontent.com/32161653/49124237-95913c00-f2f6-11e8-9cd4-3ee0d6dfd768.png)

**Comment by chenkeju9933** [comment]
me to.
