### ISSUE TITLE
API documentation doesn't mention options argument for commit

### ISSUE THREAD

**Issue by JSmith01** [vuejs/vuex#742]
### What problem does this feature solve?
API misses that commit() call can have third options parameter, that can contain very important option 'root: true', making it hard to find how to commit mutations to the root store.

### What does the proposed API look like?
For the API documentation page:
commit(type: string, payload?: any, options?: object) | commit(mutation: Object)

And some note should be added to 'mutations' section of the documentation.

**Comment by ktsn** [comment]
Thank you for reporting this. I've made PR #743
