### ISSUE TITLE
vuex support for other framework 

### ISSUE THREAD

**Issue by mouafa** [vuejs/vuex#747]
### What problem does this feature solve?
I am using Vue and Vuex for a while now, but right now i'm working in an angular app, and i'm missing the way Vuex made things easy for me, is there a way to use vuex with other framework, angular as an example?

### What does the proposed API look like?
the same Vue API

**Comment by wostex** [comment]
Looks like people use Redux with angular: [link](https://medium.com/google-developer-experts/angular-2-introduction-to-redux-1cf18af27e6e).

**Comment by posva** [comment]
ATM there's no way of doing so and it's probably not something we'll look in the near future because vuex is designed around Vue reactivity, therefore having something similar in Angular will mean a complete rewrite. I also think Redux is a fair choice
