### ISSUE TITLE
dist/vuex.js not working on jsfiddle

### ISSUE THREAD

**Issue by pierrebonbon** [vuejs/vuex#75]
Not sure why, but the recently commited dist/vuex.js [isn't](https://jsfiddle.net/pierrebonbon/674z6w0h/18/) working on jsfiddle, whereas this [version](https://github.com/Atinux/vuex/blob/master/dist/vuex.js) (0.2.0) from @Atinux [is](https://jsfiddle.net/pierrebonbon/674z6w0h/17/).

**Comment by yyx990803** [comment]
Fixed in 0.4.2.
also updated your fiddle to the new API to make sure it works: https://jsfiddle.net/674z6w0h/20/

**Comment by Atinux** [comment]
Thank you @yyx990803 

I updated the code on the 0.2.0 to be able to use on a <script> tag, but you fixed it in the 0.4.2 :smile:

**Comment by pierrebonbon** [comment]
Uahh, that's lightning fast! thanks! :pray:
