### ISSUE TITLE
Vuex store not supported in IE 11

### ISSUE THREAD

**Issue by PauLeKZ1** [vuejs/vuex#753]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/fgzg1cye/](https://jsfiddle.net/fgzg1cye/)

### Steps to reproduce
Simply imported vuex, created a store and inserted it into the vue app and then none of the vuejs code is recognized in the browser IE 11. I'm using Laravel by the way.

### What is expected?
Vuex to work in IE 11

### What is actually happening?
VueJS code is no longer recognized.

**Comment by ktsn** [comment]
Vuex supports IE 11. You need to load Promise polyfill like https://github.com/stefanpenner/es6-promise.

**Comment by getsetbro** [comment]
FYI, another thing that IE11 cannot do is this
```
const app = new Vue({
el: '#app',
store,
computed:{…
```
I'm not sure what it is called but IE11 needs it to be this
```
const app = new Vue({
el: '#app',
store: store,
computed:{…
```
What is it called?

**Comment by Austio** [comment]
@getsetbro it's destructuring assignment, you will need to add a polyfill to the browser and then will be good to go.

**Comment by getsetbro** [comment]
Is it identical to this?
"store: store"

**Comment by ThomasKlessen** [comment]
Yes
