### ISSUE TITLE
Getters - reactivity problem

### ISSUE THREAD

**Issue by meMo-Minsk** [vuejs/vuex#754]
### Version
2.3.0

### Reproduction link
[http://jsbin.com/habojekadu/1/edit?html,js,output](http://jsbin.com/habojekadu/1/edit?html,js,output)

### Steps to reproduce
```javascript
  getters: {
    // DOES NOT WORK !!!
    gettedUsers (state) {
      return state.users.map(value => value.username.toUpperCase())
    }
  }
```
```javascript
  computed: {
    // BUT IT WORKS !!!
    computedUsers () {
      return store.state.users.map(value => value.username.toUpperCase())
    }
  }
```

### What is expected?
*gettedUsers* should be rendered in exactly the same way as *computedUsers*

### What is actually happening?
*gettedUsers* is empty during render

---
But if you try to run *store.getters.gettedUsers* in a console, then result will be the same as *vm.computedUsers*

**Comment by wostex** [comment]
Getters are designed to be used in `computed` section afaik. Like this for example:

`computed: {
    users () {
      return store.getters.gettedUsers
    }
  }`

**Comment by ktsn** [comment]
You are putting derived state in component initial data and it is duplicated from store state. So the `gettedUsers` in component is no longer updated even if the store state is updated.
You need to refer the getter via computed properties like @wostex said or just use `mapGetters` helper.
