### ISSUE TITLE
当我切换视图的时候， 这个 view下 vuex store 的 state 仍被保留了。

### ISSUE THREAD

**Issue by taoche** [vuejs/vuex#76]
列子：视图 A B 是通过 vue router 来切换的。  视图A 本来有一部分内容是 隐藏的。
```
state : {
 isShowAnything : false
}
```
再通过 action 改变了 sate的状态 isShowAnything = true 的时候， view a 中内容被显示。

这个时候 切换view 到 b，  再切换回 a... 
默认被隐藏的内容仍是显示状态（因为是通过vue router切换的，所以 view 肯定是被销毁了， 我在 vue  devtools里看 view的 props data已经重置）

这里的问题就很像 component 被 keep-alive了。

我不清楚 vuex 设计的时候 就是这样的，还是我使用中理解错了。还请解答一下，谢谢。

PS：因为英文组织能力较差，怕用英文提issues描述的更混乱，所以用中文提问，还请谅解。

**Comment by yyx990803** [comment]
vuex 的 state 和组件的生命周期无关。
