### ISSUE TITLE
Unsubscribing to store mutations in Vue components

### ISSUE THREAD

**Issue by kristijan97** [vuejs/vuex#760]
### What problem does this feature solve?
I'm referring to this article:
https://github.com/vuejs/vuex/issues/219

You doesn't explain to us how to unsubscribe vuex mutation.
store.subscription doesn't return unsubscription function

### What does the proposed API look like?
.

**Comment by posva** [comment]
```js
const unsubscribe = this.$store.subscribe()
unsubscribe()
```
Next time, make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks! 🙂
