### ISSUE TITLE
How to implement multiple reducers/mutations handle one action ?

### ISSUE THREAD

**Issue by as02700** [vuejs/vuex#767]
### What problem does this feature solve?
how to broadcast one action to multiple reducers/mutations .

### What does the proposed API look like?
这是以前在 ng2 的方式，期望 action 能够广播到多个 reducer
--------
``` javascript
combineReducers({
  state1: R.cond([
    [
      typeIn(['some-action-type1', 'some-action-type2', /*...*/ ]),
      (state, action) => action.payload
    ],
    [
      R.allPass( typeIn('some-action-type-n'), payloadIs( Object ) ),
      (state, action) => /* blah blah blah */
    ],
    [
      R.T,
      R.nthArg(0)
    ]
  ]),
  state2: R.cond([
    [
      typeIn(['some-action-type1', 'some-action-type-n']),
      (state, action) => /* blah blah blah */
    ],
    [ R.T, R.nthArg(0) ]
  ])
})
```

**Comment by ktsn** [comment]
Please don't abuse the issue helper. You should post the question to [gitter](https://gitter.im/vuejs/vue) or [forum](https://forum.vuejs.org/), we are happy to help you on there.
