### ISSUE TITLE
Getting warn for props from global mixin

### ISSUE THREAD

**Issue by Asvae** [vuejs/vuex#77]
As the title suggests, `vuex` harshly handles global props.

When doing
```
new Vuex.Store({
    state,
    mutations
})
```

I get the following warning:
```
[Vue warn]: Props will not be compiled if no `el` option is provided at instantiation.
```

And I have a global `mixin` with `props` defined like this:
```
Vue.mixin({
    props: {
        id: {},
    }
})
```

Stacktrace kindly pins the origin of issue:
```
// use a Vue instance to store the state tree
this._vm = new Vue({
  data: state
});
```

Any information on the subject is much appreciated.

**Comment by yyx990803** [comment]
You can safely ignore that warning. However, a global mixin like that seems like a bad idea to me. Global mixins are intended to add **optional** behavior to components - in most cases, you should only use it to handle a custom option.
