### ISSUE TITLE
Module from factory not independant

### ISSUE THREAD

**Issue by CorentinAndre** [vuejs/vuex#778]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/33248/](https://jsfiddle.net/50wL7mdz/33248/)

### Steps to reproduce
In my index.js in store folder
```
import productFactory from './modules/product'
Vue.use(Vuex);

export default new Vuex.Store({
  modules: {
    Milos: productFactory(),
    Evinrude: productFactory()
  }
});
```

My factory is like so: 
```
const state = {...};

const getters = {...};

const actions = {...};

const mutations = {...};

export default function(name) {
  return{
    namespaced: true,
    state,
    getters,
    actions,
    mutations
  }
}
```

### What is expected?
When I commit a mutation like milos/setName with milos, only the first module should have its state.name = milos.

### What is actually happening?
When I commit a mutation like milos/setName with milos, both modules have their state.name set as milos.

---
Seems to be working fine in my fiddle example, however I have the same setup in my project and cannot make it work.

**Comment by ktsn** [comment]
The reproduction looks incorrect. It doesn't commit any mutations.  Please provide real reproduction.

**Comment by LinusBorg** [comment]
You have to move the constants into the function.

**Comment by CorentinAndre** [comment]
Sorry, this needs to be closed. Linus was right.

Thank you guys
