### ISSUE TITLE
semver

### ISSUE THREAD

**Issue by airtonix** [vuejs/vuex#78]
I'll be that guy.

0.5.0 won't work with my code I've written with 0.2.0.

through out my application I'm accessing my store actions like:

```js
// application/store/index.js
import vuex from 'vuex';

import store from './store';
import mutations from './mutations';
import actions from './actions';
import middlewares from './middlewares';

const store = new Vuex.Store({
	state,
	mutations,
	actions,
	middlewares,
});

export default store;
```

`application/states/root.vue`
```vue
<template>
  <input type="text" v-model="foo">
</template>

<script>
import store from 'application/store';

export default {
  computed: {

    foo: {
      get () { store.state.Foo; },
      set (value) { store.actions.updateFoo(value); } ,
    }

  }
};
</script>
```

This throws: 

```
TypeError: Cannot read property 'updateFoo' of undefined
```

I would have only expected this when moving to 1.x.x

**Comment by yyx990803** [comment]
Please read semver carefully. Pre 1.0 can break any time.

**Comment by airtonix** [comment]
Cool.

So does this mean to migrate:

1. Store no longer accepts `actions`, therefore `key: type.MUTATION_TYPE` no longer automatically gets turned into an action.
2. Using `actions` can now only be done if your component has a `... vuex: { actions: importedActions ... } ...`

?

**Comment by yyx990803** [comment]
Yes, or you can just write the actions inline.

**Comment by airtonix** [comment]
So I can't use actions outside of a component now?

**Comment by yyx990803** [comment]
You can, just pass it the store...
