### ISSUE TITLE
Vue resources mutil options root

### ISSUE THREAD

**Issue by qianthinkover** [vuejs/vuex#782]
### What problem does this feature solve?
Hi,All:
as we know, we could use Vue.http.option.root ='http://localhost:60894' to set vue-resource base address, but I have tow api provider ,how can I set this?

### What does the proposed API look like?
vueInstance.$http.post how to set mutil root addresses?

**Comment by ktsn** [comment]
This is not feature request and not related with Vuex. Please use our [forum](https://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or StackOverflow to ask your questions.
Thanks.
