### ISSUE TITLE
Passing the `this` context in the actions and mutations

### ISSUE THREAD

**Issue by JCWolf** [vuejs/vuex#784]
### What problem does this feature solve?
Let's take the actions for example. 
```javascript
actions   : {
			increment : function ( { commit }, payload ) {
				console.log( payload.message );
				commit( 'increment', payload.by );
			}
		}
```

Having the context as the first parameter or using object destructuring gets the action a little bloated. Also, you cannot pass multiple arguments to actions which is a kinda nasty because you have to pass all your arguments through an object as the second parameter. 

It is possible to bind the context of the actions and/or mutations to the current vuex instance so we don't need to add the context or the state in the case of mutations as parameters? 

Also, it is possible to pass the arguments as they were passed in the initial function in the case of actions?

### What does the proposed API look like?
Before:

```javascript
new Vuex.Store( {
		state     : {
			counter : 0
		},
		getters   : {
			increment : state => state.counter
		},
		mutations : {
			increment : function ( state, by ) {
				state.counter  = by;
			}
		},
		actions   : {
			increment : function ( { commit }, payload ) {
				console.log( payload.message );
				commit( 'increment', payload.by );
			}
		}
	} );

// call in a vuejs component if we used the mapActions(['increment']) helper
this.$store.increment( {
	by      : 25,
	message : 'log this message'
} );
```

After
```javascript
new Vuex.Store( {
		state     : {
			counter : 0
		},
		getters   : {
			increment : state => state.counter
		},
		mutations : {
			increment : function ( by ) {
				this.state.counter  = by;
			}
		},
		actions   : {
			increment : function ( by, someMessage ) {
				console.log( someMessage );
				this.commit( 'increment', by );
			}
		}
	} );

// call in a vuejs component if we used the mapActions(['increment']) helper
this.$store.increment( 25, 'log this message' );
```

Of course, this is not a must to do feature, but enables the user in writing an easy to understand code, also, giving him the opportunity to use an object or simple values as parameters in actions. 

I think these details will make a difference in writing cleaner code.

**Comment by posva** [comment]
> Having the context as the first parameter or using object destructuring gets the action a little bloated. Also, you cannot pass multiple arguments to actions which is a kinda nasty because you have to pass all your arguments through an object as the second parameter.

Passing the context as an argument makes it easy to mock and is intentional. Passing multiple arguments as a single object also makes it easier to read

**Comment by LinusBorg** [comment]
I agree with @posva.

I don't see a worthwile benefit in adding this. Actions and mutations are pure functions so they are testable more easily.

**Comment by JCWolf** [comment]
@posva @LinusBorg 
Ok. I understrand. Maybe in vuex 3? I'm more towards simplicity. And I bet there is another way to make testing easier. Anyways, Glad it was sorted out. I'll close this!
