### ISSUE TITLE
JSFidde example in Vuex docs "Getting Started" page doesn't work in Safari on macOS or iOS

### ISSUE THREAD

**Issue by tinymachine** [vuejs/vuex#790]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/n9jmu5v7/341/](https://jsfiddle.net/n9jmu5v7/341/)

### Steps to reproduce
Open JSFiddle link above in Safari on macOS or iOS (I'm running Safari 10.1.1 on macOS and iOS 10.3.1).

### What is expected?
The result quadrant should show a live counter displaying `1` and the increment/decrement buttons should work when you click them.

### What is actually happening?
The result quadrant shows `{{ count }}`, the increment/decrement buttons don't work, and the console displays the error message, `SyntaxError: Can't create duplicate variable that shadows a global property: 'app'.`

---
Changing the JS language setting from 'Babel   JSX' to just 'JavaScript' fixes the error and works in Chrome, Firefox, and Safari.

**Comment by ktsn** [comment]
Hmm, I'm not sure why `app` throws the error, but we could just remove `const app` from the code.

**Comment by ktsn** [comment]
Updated. Thanks for reporting 🙂

**Comment by tinymachine** [comment]
No prob! Unfortunately the new link (https://jsfiddle.net/n9jmu5v7/1269/ I think?) still isn't working in Safari for me. I'm seeing this error in the console: `ReferenceError: Can't find variable: Vuex`.

**Comment by ktsn** [comment]
Hmm, it's weird... 
The link is working in Safari on macOS for me and it actually loads vue and vuex as external resources.

**Comment by tinymachine** [comment]
Sorry, must have been some caching issue! Cleared Safari's cache and it's working properly now. Sorry for the false alarm!

**Comment by tinymachine** [comment]
(And thank you for your work on Vue!)

**Comment by ktsn** [comment]
Glad to hear that :)
