### ISSUE TITLE
How do I share state with multiple browser tabs?

### ISSUE THREAD

**Issue by OXOYO** [vuejs/vuex#804]
### What problem does this feature solve?
How do I share state with multiple browser tabs?

### What does the proposed API look like?
none!

**Comment by ktsn** [comment]
Please carefully read the description of the [issue helper](https://new-issue.vuejs.org/). 
Questions should be posted to the [forum](https://forum.vuejs.org/) or StackOverflow.

**Comment by Naeemo** [comment]
@OXOYO storage events.
