### ISSUE TITLE
Include an example of how to handle "runInNewContext: false" with store modules

### ISSUE THREAD

**Issue by jazoom** [vuejs/vuex#807]
### What problem does this feature solve?
It is not immediately apparent that each store module needs to be a function that returns a fresh module, which needs to be combined with other store modules when the root store is created afresh.

The above sentence is really confusing. See discussion here to understand what I mean:

https://forum.vuejs.org/t/debugging-state-pollution-with-the-new-behaviour-of-vue-2-3-ssr/11724

### What does the proposed API look like?
This is a documentation suggestion.

**Comment by ktsn** [comment]
You need this section? https://vuex.vuejs.org/en/modules.html#module-reuse

**Comment by jazoom** [comment]
Well, I don't need anything at the moment. @LinusBorg helped me to find out this was what I was missing and we thought it might be a good idea to add it to the documentation.

**Comment by ktsn** [comment]
I mean there is a better approach to reuse store modules now (since Vuex v2.3) and it seems to be already documented.

**Comment by jazoom** [comment]
Then maybe there should be a mention there that this is what is required for SSR to function properly when using `runInNewContext: false`? I still don't understand why this is better, though.
