### ISSUE TITLE
how to clear all data from store

### ISSUE THREAD

**Issue by jagasan** [vuejs/vuex#808]
any idea to clear all data from store in logout time

**Comment by trainiac** [comment]
@jagasan This has been kind of a pain in the but for me as well. If your application uses one vuex module it's easy, but if you are using many modules you will have to add a "reset" mutation for every module.

```javascript
// some function that defines the initial state of your store
const state = getInitialState()
...

const mutations = {
   reset (state) {
         const newState = getInitialState()
         for (const key in newState) {
           Vue.set(state, key, obj[key])
        } 
   }
}
```

That's the mechanism for resetting a given module.  When you log a user out, you will have to find a way to commit a reset on all of your vuex modules that require it.  Hope this helps.

**Comment by kulelikule** [comment]
Does the official provide a means to clear all States?
