### ISSUE TITLE
Two-way Computed Property is not working properly

### ISSUE THREAD

**Issue by blogui91** [vuejs/vuex#819]
### Version
2.3.0

### Reproduction link
[https://codepen.io/blogui91/pen/ZyErdg](https://codepen.io/blogui91/pen/ZyErdg)

### Steps to reproduce
Just fill the inputs with random text

### What is expected?
It should be able to update the state, passing through the set function , declared in the computed property 'form' and log an info saying 'Updating form' as well as to commit the change to 'UPDATE_FORM' event.

Based in the vuex docs [Two-way computed property] 
https://vuex.vuejs.org/en/forms.html

### What is actually happening?
The form value declared as computed seems to update its value, however the 'set' function is not commiting the change

---
The version of Vuex is 2.3.1

**Comment by blogui91** [comment]
I could find the reason, and it's because i am trying to update an object, is there a way to avoid to update an object when a property of the object is updated?

or definitively i have to compute one by one :/

**Comment by LinusBorg** [comment]
In These situstions it's generally far easier to use a value binding and a generic update function bound to the input / change event of the inputs of the form.

**Comment by blogui91** [comment]
I got it.

I solved by doing this

https://codepen.io/blogui91/pen/vZYzgM?editors=1011

Thank you!
