### ISSUE TITLE
Where to follow latest changes?

### ISSUE THREAD

**Issue by jbruni** [vuejs/vuex#83]
Suddenly we are already at version `0.6.1` (at least at the moment I'm writing this)...

Is there a place (maybe a forum thread) where the latest changes are announced?

Please, let me know. I want to be using latest version, but I'm not sure if there are significant or breaking changes, or not.

Thank you!

**Comment by jbruni** [comment]
It seems most impacting recent change is the usage of `getters` instead of `state` in a Vue component `vuex` option...

**Comment by azamat-sharapov** [comment]
> Is there a place (maybe a forum thread) where the latest changes are announced?

https://github.com/vuejs/vuex/releases
https://twitter.com/vuejs

> I want to be using latest version, but I'm not sure if there are significant or breaking changes, or not.

http://semver.org/

**Comment by jonagoldman** [comment]
Best to "watch" the repo and get notifications on GitHub.

**Comment by yyx990803** [comment]
In addition to the links azamat provided above, you might also want to learn about npm version range operators, e.g. What ^0.6.0 means: https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by jbruni** [comment]
Thanks.

I was actually learning from the commits themselves... but they have been a lot...

Actually, https://github.com/vuejs/vuex/releases seems to be what I was looking for!
