### ISSUE TITLE
Why the mapAction is Currying but the store.dispatch just accept 2 parameters 

### ISSUE THREAD

**Issue by AsJoy** [vuejs/vuex#838]
### Version
2.3.0

### Reproduction link
[https://github.com/vuejs/vuex/blob/dev/src/helpers.js#L67](https://github.com/vuejs/vuex/blob/dev/src/helpers.js#L67)

### Steps to reproduce
when I Use mapAction like this: 
```js
    methods: {
            ...mapActions([
                loadAuthor,
            ]),
        },
   ....
  this.loadAuthor(type, id);
```

### What is expected?
the `loadAuthor` action will get the two parameters 

### What is actually happening?
the `loadAuthor` action just get  the first parameters 

---
if the `store.dispatch` just receive 2  parameters why the mapAction Currying,  is there some negative effect has been make to the developer？

**Comment by mlarese** [comment]
this.loadAuthor({typeLtype, id:id});

**Comment by ktsn** [comment]
This is expected behavior. `mapActions` is intended to use for adapting some actions and component methods. That means it specifies the action types before dispatching some actions.
https://vuex.vuejs.org/en/actions.html#dispatching-actions-in-components
