### ISSUE TITLE
Use state as router

### ISSUE THREAD

**Issue by jonagoldman** [vuejs/vuex#84]
Thinking about routing with Vuex and the **single state tree**, it crossed my mind to handle the current route inside a Vuex state. I never used Redux before but I found a few projects that add routing capabilities to Redux. This makes total sense to me and a similar solution could fix the "Using Vuex with ``xxx`` router" problem for good.

@yyx990803 I guess it's more complicated that it sounds, but what do you think about this?

**Comment by yyx990803** [comment]
Actually working on that ;)

**Comment by nblackburn** [comment]
Great idea, would love to see this!

**Comment by jonagoldman** [comment]
Great! Really looking forward to it!

**Comment by RiseupDev** [comment]
+1

**Comment by beeplin** [comment]
+1

**Comment by Gomah** [comment]
+1

**Comment by beeplin** [comment]
@yyx990803 would u pls reveal some of ur thoughts on the vuex-and-route combination in advance? will vue-router be wholly replaced by vuex? or there will just be a bridge that connect vuex and vue-router? will vuex's 0.6.1 new API affected by this?

**Comment by azamat-sharapov** [comment]
https://github.com/vuejs/vuex-router-sync

**Comment by beeplin** [comment]
nice!

**Comment by jonagoldman** [comment]
@yyx990803 that was fast! do you even have time to sleep? :)

**Comment by azamat-sharapov** [comment]
He didn't mention it anywhere yet.. so, "use it on your own risk" probably..

**Comment by nblackburn** [comment]
@azamat-sharapov I have been using it since it got released and it seems pretty stable, after all there is very little that can go wrong at 64 LOC.
