### ISSUE TITLE
Computed method not called when shuffling arrays

### ISSUE THREAD

**Issue by radar155** [vuejs/vuex#868]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/wvamte7a/](https://jsfiddle.net/wvamte7a/)

### Steps to reproduce
Just click on the shuffle button and look: nothing changes!

### What is expected?
The list should change from [1,2,3,4] to [4,2,3,4]

### What is actually happening?
Nothing is changing. The computed method is not called even if shuffle mutation is committed and view is not changing. If you'll use a debugger (like vue-devtool extension for chrome) you'll see the store value changing.

---
 If you click on pop button, the last item of the list will disappear, as expected.
Also, if you click shuffle then pop, the last item will be removed and the first will became 4. This is the proof that the store object is changing and the problem is that the computed method is not triggered

**Comment by posva** [comment]
You need to `Vue.set`. Check https://vuejs.org/v2/guide/list.html#Caveats

**Comment by radar155** [comment]
I miss it. Many thanks
