### ISSUE TITLE
Using new vuex syntax in mixin is overidden by components

### ISSUE THREAD

**Issue by frankdugan3** [vuejs/vuex#87]
When using the new vuex syntax in a mixin:
```
vuex: {
  state: {
    reactiveobject1...
  }
}
```
And then adding a different vuex object in a component that imports the mixin:
```
vuex: {
  state: {
    reactiveobject2...
  }
}
```
The entire vuex tree is overridden by the component. I was expecting behavior similar to computed properties were the tree would be combined and only overridden if conflicting. Would that be a good idea, or is the current behavior best?

**Comment by yyx990803** [comment]
This should work in 0.6.1.
