### ISSUE TITLE
mutation first argument can't use destructuring????

### ISSUE THREAD

**Issue by MorisHarA** [vuejs/vuex#871]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/qh8rn35L/](https://jsfiddle.net/qh8rn35L/)

### Steps to reproduce
mutation first argument use destructuring

### What is expected?
why?

### What is actually happening?
mutation first argument can't use destructuring

**Comment by posva** [comment]
Short answer: because Javascript:

```js
var state = { list: [] }
var list = state.list
list === state.list // true
list = []
list === state.list // false
```

**Comment by MorisHarA** [comment]
thanks. 0.0

**Comment by posva** [comment]
Let me add a bit more information:

First we're referencing the same array (same reference) using 2 different variables but as soon as we do `list = []`, we are creating a new one. You can use methods that modify the array though, like `push` and `splice`
