### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by dunkfordyce** [vuejs/vuex#873]
### Version
2.3.0

### Reproduction link
[https://www.npmjs.com/package/vuex](https://www.npmjs.com/package/vuex)

### Steps to reproduce
npm reports the latest version of vuex is 2.3.1. The latest version actually appears to be 2.3.0. The files in the dist/ folder of version 2.3.1 from npm are for version 2.3.0. 

### What is expected?
The correct version to be on npm... or something 

### What is actually happening?
The version is mixed.

**Comment by ktsn** [comment]
The new version had been released 🙂
