### ISSUE TITLE
Dispatching an action, inside another action of a different module

### ISSUE THREAD

**Issue by Juli0GT** [vuejs/vuex#874]
### What problem does this feature solve?
I'm trying to dispatch an action inside another action from a different module.

### What does the proposed API look like?
**store/modules/users/index.js**

```javascript
const actions = {
    getUserObject({ commit }) {
        console.log('USEROBJECT!!!');
        api.get('/user').then((response) => {
            commit('SET_USER_OBJECT', { user: response.data.data });
        }, (err) => {
            console.log(err);
        });
    },
};
```

**store/modules/auth/index.js**

```javascript
const actions = {
    login({ commit }, creds) {
        api.post('/login', creds).then((response) => {
            console.log(response);
            if (response.status === 200) {
                commit('LOGIN_SUCCESS');
                localStorage.setItem('access_token', response.data.access_token);
                localStorage.setItem('refresh_token', response.data.refresh_token);
                **dispatch('getUserObject');**????
            }
        }, (err) => {
            console.log(err);
        });
    },
};
```

**Comment by posva** [comment]
You should be able to do so by using `{ root: true }` https://vuex.vuejs.org/en/api.html

**Comment by Juli0GT** [comment]
If I do 
```javascript
const actions = {
    login({ commit }, creds) {
        api.post('/login', creds).then((response) => {
            console.log(response);
            if (response.status === 200) {
                commit('LOGIN_SUCCESS');
                localStorage.setItem('access_token', response.data.access_token);
                localStorage.setItem('refresh_token', response.data.refresh_token);
                dispatch('getUserObject');
            }
        }, (err) => {
            console.log(err);
        });
    },
};
```

I got dispatch is not defined!

**Comment by Juli0GT** [comment]
BTW, thanks for your help and yopur rapid response @posva

**Comment by ktsn** [comment]
As @posva described, you already can dispatch an action in the other modules by using `root: true` option.
If that is not the case, please open a new issue as a bug report with a reproduction.

**Comment by bigsee** [comment]
If you have your actions, getters and mutations broken out into separate file, the fix for "dispatch is not defined" might be to use context:

`const action = (context) => {
  context.dispatch('openLoadingScreen', null, { root: true });
  api.makeRequest()
      .then((response) => {
          const data = response.data;
          context.commit('ACTION_COMPLETED', data);
          context.dispatch('closeLoadingScreen', null, { root: true });
        })
        .catch(error => error);
};`

**Comment by jaiko86** [comment]
Your current code:
```
const actions = {
    login({ commit }, creds) { ... }
}
```
should be:
```
const actions = {
    login({ commit, dispatch }, creds) { ... }
}
```

**Comment by 90arther** [comment]
> If you have your actions, getters and mutations broken out into separate file, the fix for "dispatch is not defined" might be to use context:
> 
> ```
> const action = (context) => {
>   context.dispatch('openLoadingScreen', null, { root: true });
>   api.makeRequest()
>       .then((response) => {
>           const data = response.data;
>           context.commit('ACTION_COMPLETED', data);
>           context.dispatch('closeLoadingScreen', null, { root: true });
>         })
>         .catch(error => error);
> };
> ```

Thanks, it work
