### ISSUE TITLE
dispatch latest action 

### ISSUE THREAD

**Issue by MorisHarA** [vuejs/vuex#884]
### What problem does this feature solve?
when dispatch one action repeatedly at the same time，dispatch latest action 

### What does the proposed API look like?
。。

**Comment by LinusBorg** [comment]
I think I understand roughly where you are going with this, but can you be a little bit more specific, especially by providing an example use case where this feature is helpful?

I *think* you want some sort of functionality that would kind of *cancel* a currently executing action if it is triggered again before finishing. is that right, and why / what scenario do you need this for exactly??

I feel that for usual scenarios (canceling a request to the server) this should rather be solved in the API layer that is talking to your server than in the dispatch function.

**Comment by MorisHarA** [comment]
did you mean 304？

**Comment by LinusBorg** [comment]
what is `304`?

**Comment by MorisHarA** [comment]
If a page has two tabs. These two tabs share a vuex state, click on these two tabs are issued an action to request data, payload different request data is different, if the switch quickly tab, before a click Of the tab request back than the latter one, then the current tab page data will be the previous tab page data coverage, if you can provide the implementation of the latest action, then the above situation will not happen

**Comment by ktsn** [comment]
This looks like the same proposal as #885. Let's integrate the threads 🙂
