### ISSUE TITLE
“store” vs “data: store” in Vue() constructor, which is best?

### ISSUE THREAD

**Issue by mariusa** [vuejs/vuex#896]
### What problem does this feature solve?
Vue docs mention to use "data" option on constructor, to keep global/shared data: https://vuejs.org/v2/guide/state-management.html

This makes sense.

Vuex docs passes the "store" object, without a property name though: https://github.com/vuejs/vuex/blob/dev/examples/counter/app.js

new Vue({
  el: '#app',
  store,
  render: h => h(Counter)
})

Shouldn't that have been

new Vue({
  el: '#app',
  data: store,
  render: h => h(Counter)
})
?

### What does the proposed API look like?
 data: store

**Comment by ktsn** [comment]
They are completely different. Former is for injecting store instance to all descendant components while latter is just provide the store data into the root instance.

If you just want to bind the store data to a specific instance, you also can the latter approach with Vuex.

```js
const store = new Vuex.Store({
  // ...
})

new Vue({
  el: '#app',
  data: store.state,
  render: h => h(Counter)
})
```
