### ISSUE TITLE
Can I disable auto install in dist mode if I'm loading vuex from a packaged bundle? 

### ISSUE THREAD

**Issue by paulopmx** [vuejs/vuex#900]
### What problem does this feature solve?
I'm creating an embedded js app that needs to be isolated from what ever version or Vue/Vuex tools the webpage owner is using. When I call Vuex, it tries to install itself into the window.Vue when I don't need it to, because I'm already importing Vue

### What does the proposed API look like?
Not really sure. I end up just hacking the vuex.esm.js file
Maybe a separate package for dist and package bundles

**Comment by posva** [comment]
dup of #731

**Comment by paulopmx** [comment]
@posva The solution in the referenced link does not solve my issue. That's why I added my own comment and shared a hack. Please note, that I will be running my app inside another web page that may have included a different version vue js via a script tag.
