### ISSUE TITLE
vuex状态改变后组件未更新

### ISSUE THREAD

**Issue by a417420427** [vuejs/vuex#913]
index.js
``
const state = {
    city: {
        currentCity: {
            cityId: 0,
            cityName: '全部'
        },
        cityList: []
    },
    params: {
      cityId: 0
    }
}
const actions = {
    cityChange({ commit, rootState }, city) { 
        commit(types.CHANGE_SEACH_PARAMS, {cityId: city.cityId})
    }
} 
const getters = {
     getParams(state){
        return state.params
    }
}

const mutations ={
 [types.CHANGE_SEACH_PARAMS](state, payload){
         state.params.cityId = payload.cityId      
    }
}
export default {
    state,
    actions,
    getters,
    mutations,
    modules: {
        data   //data页面modules 
    }
}
``
city.vue
`` 
<template>
      <ul> 
                <li v-for='item in cityList' @click="cityChange(item)">{{item.cityName}}</li>
               
      </ul>
</template>
methods:{
	...mapActions([
	'cityChange',  // 城市列表组件中调用cityChange方法
	'getCityList'
    ]),
} ``

data.vue
``
<template>
      <h1>{{params.cityId}}</h1>    
</template>
<script>
   export default {
       computed:{
            ...mapGetters({
                params: 'getParams',  
            }),
        },
  }
</script>
``

**Comment by jdinartejesus** [comment]
I still have similar issue, there's no way to have updated computed when using the word city!
