### ISSUE TITLE
Documentation: Comparison of Actions to Mutations is misleading 

### ISSUE THREAD

**Issue by davestewart** [vuejs/vuex#915]
### What problem does this feature solve?

I note the introduction text on the Vuex docs for Actions:  

> ### Actions
> Actions are similar to mutations, the differences being that:
>
> - Instead of mutating the state, actions commit mutations.
> - Actions can contain arbitrary asynchronous operations.
>
> Let's register a simple action:

This sets up in the readers mind that Actions are somehow the same as Mutations, when in fact their differences are more pronounced than their similarities: 

- Actions don't update the state, but they may `commit()` mutations, which do (there is no "instead of")
- Mutations must be synchronous, there is no such restriction on Actions
- Mutations generally won't make other calls, Actions probably will
- Mutations must return a new state object, Actions don't need to return anything
- Mutations must not have side effects, whereas Actions could (changing a route, perhaps)

### What does the proposed API look like?

Perhaps something like the following would be more appropriate:

> Actions provide a mechanism to run additional logic or functionality within the context of the current store or store module.
>
> A typical use case would be to collate and submit data to the server, committing mutations only when the remote call completes. 
> 
> Actions are declared as JavaScript callbacks, taking a special `context` object as their first argument, with additional user-supplied parameters passed after. 
>
> The `context` object is the primary way to access to local and root-level state and getters, along with localised commit and dispatch functions, and may be expanded to local variables using ES6 destructuring:
>
> [ action example that demonstrates the above ]

**Comment by posva** [comment]
I like the _A typical use case would be to collate and submit data to the server, committing mutations only when the remote call completes._ but, they're similar in roles and I think it helps for most people. You seem to have a very technical point of view, but that's not the case for everybody. Some people will understand it better with the _similar to_ sentence

**Comment by davestewart** [comment]
> You seem to have a very technical point of view

Does one not need to? Vuex *is* very technical!

> Some people will understand it better with the "similar to" sentence

I have to respect that point of view. However, I still feel that "similar" implies a "1:1" correlation when the relationship of actions to mutations is more like "1 → 2"

Using the initial intro paragraph, and the example you like, perhaps something like this:

> Actions allow you to wrap logic, often synchronous logic, around commits.
>
> A typical use case would be to collate and submit data to the server, committing mutations only when the remote call completes.

You could then show the simple example, which I think still works (albeit somewhat redundant) or perhaps expand the previous `count` example with actual async logic:

```javascript
// store definition
const store = new Vuex.Store({
  state: {
    count: 0
  },
  mutations: {
    update (state, value) {
      state.count = value
    }
  },
  actions: {
    update (context, value) {
      axios
        .post('/update', value)
        .then(res => {
          context.commit('update', res.data.value)
        })
    }
  }
})
```
```javascript
// usage
store.dispatch('update', 10)
```

**Comment by balint42** [comment]
I would like to make a slightly related comment - it concerns the exact same documentation chapter: reading through it I was left with the impression that actions _may_ return Promises, not that they always by definition do. Quote:
> store.dispatch can handle Promise returned by the triggered action handler and it also returns Promise:

This sentence is not exactly wrong but it does imho not make very clear that `store.dispatch` will _always_ return a Promise no matter what the action returns. What about:

"`store.dispatch` will always return a Promise and thus can handle Promises returned by the triggered action handler."

**Comment by davestewart** [comment]
@balint42 - I completely agree with you - the word "may" is such a tripper-upper in documentation!

The Laravel docs use "may" all over the place, I think to sound polite, but it's ambiguous as it's not explicit whether a result will be of yours or the framework's making.

As an end user you just want to know in concrete terms whether something "is" or "isn't".

**Comment by davidpelayo** [comment]
When it comes to how `commit` and `dispatch` works - I think the terms are ambiguous too.
Inspecting the code and how actions are dispatched, they are *by default* synchronous unless the action returns a Promise.

So, given the following action:
```js
updateConfig({ commit }, someConfigObject) {
  commit('CONFIG', someConfigObject);
},
```
That gets executed synchronously, as if you check the code [here](https://github.com/vuejs/vuex/blob/dev/src/store.js#L410), the action doesn't return a Promise, there is no async operation by default.

Could we improve the docs so we make that much clearer? Happy to raise a PR.

**Comment by kiaking** [comment]
Closing due to its age. I think we could enhance the docs about differences of action and mutations, but I think we should gather latest feedbacks from the community of their current understanding and such.
