### ISSUE TITLE
Using Component prop to map State and Actions

### ISSUE THREAD

**Issue by muhammadsaeedparacha** [vuejs/vuex#928]
So I wanted to decouple my code and move all the crud implimentations to a single locations such as Index.vue. Now CustomersIndex.vue, SuppliersIndex.vue just import Index.vue with a prop: 

`props:["model"]`

In Index.vue I need to be able to mapState and mapActions with the prop passed to the component like:
`...mapState({
      this.model
}),`

And similar with mapActions. But seems like this.model is undefined in vuex mappings. Is there a way to accomplish this?

**Comment by ktsn** [comment]
@muhammadsaeedparacha You may want [vuex-connect](https://github.com/ktsn/vuex-connect)
