### ISSUE TITLE
coding with vuex makes the code tedious, any idea to make it easy?

### ISSUE THREAD

**Issue by njleonzhang** [vuejs/vuex#937]
I recently tried to use `react` and `mobx`, `mobx` with `es7 decorator` make store just like a `Class`, which is so elegant and easy.

Here is a Mobx store sample:

```
import { observable, action } from 'mobx'

export class UiStore {
  @observable roomSelectShow = false

  @action showRoomSelect() {
    this.roomSelectShow = true
  }

  @action hideRoomSelect() {
    this.roomSelectShow = false
  }
}

export default new UiStore()
```

Can `vuex` consider to make code in this way(syntactic sugar or something else)? It is really cool.

**Comment by Erlix322** [comment]
Reopen it! He is so right! all that redux and vuex codes are the exact oposite of DRY and KISS...
