### ISSUE TITLE
with vuex makes the code tedious, any idea to make it easy

### ISSUE THREAD

**Issue by njleonzhang** [vuejs/vuex#938]
### What problem does this feature solve?
I recently tried to use `react` and `mobx`, `mobx` with `es7 decorator` make `store` just lik a`Class`, which is so elegant and easy.

Here is a Mobx store sample:

```
import { observable, action } from 'mobx'

export class UiStore {
  @observable roomSelectShow = false

  @action showRoomSelect() {
    this.roomSelectShow = true
  }

  @action hideRoomSelect() {
    this.roomSelectShow = false
  }
}

export default new UiStore()
```

Can `vuex` consider to make code in this way(syntactic sugar or something else)? It is really cool. 

### What does the proposed API look like?
make vuex support class define and `es7 decorator`

**Comment by ktsn** [comment]
What the point do you feel tedious in Vuex? IMO, class and decorator based API is generally longer than object literal based API.
Anyway, I think it should be provided as separated package like [vue-class-component](https://github.com/vuejs/vue-class-component)

**Comment by njleonzhang** [comment]
@ktsn  look at this project, I think its [doc](https://github.com/dwqs/revuejs/wiki/Introduction), describe `What the point do you feel tedious in Vuex? ` very well. 

> Developed in vuex normative mode, we will write a lot of template code. For completing an action, may switch back and forth between multiple files. As applications become more complex and need to manage more and more module state, writing template code and files often switch is "useless", and it will affect the development efficiency, But Revuejs hope to reduce the writing of the template code and the switch back and forth of the file, simplify vuex some normative processes to improve development efficiency. Of course, if you like the development paradigm of mobx, just try to use vue-mobx.


also you can look at this [issue](https://github.com/dwqs/vue-mobx/issues/2), we have a discuss about why `mobx` there.

**Comment by ktsn** [comment]
Well, that description is a bit vague to take some action to improve Vuex.
The docs use the term `a lot of template code` but it is not described concretely in any place in the docs. I think all Vuex concepts are necessary to manage maintainable apps. If some of them can be simpler, we should discuss **which api can be simpler** and **how we can do that**. This is the reason I asked you before.

In addition, the docs argue that reducing the file numbers will improve dev experience, I however disagree about that. In long term development, it would be better to separate each module for maintainability.

Perhaps, you would like to combine the action/mutation in Vuex into one function like `revue` or just want to set/get state like `mobx`. In that case, you should just use them rather than Vuex because the one of purpose of Vuex is **separate responsibility to achieve maintainable code**. This is a trade-off between short term and long term productivity [as stated in Vuex docs](https://vuex.vuejs.org/en/intro.html).

**Comment by njleonzhang** [comment]
@ktsn Tnx for your explanation. I agree with you that Vuex, which is a full Flux implement, can make big/huge projects maintainable in long term. 

But for most project(small or middle), `multi files` and `mutation` definition strings, which is called as ` template code` in the doc, brings inconvenience. so `revue` and `mobx` seems better for these projects. 

Instead of revising Vuex, maybe Vue team can consider to provide another solution, like `revue`/`mobx` to meet this requirement.

This is my personal opinion after using both `Vuex` and `mobx`.

**Comment by grantcarthew** [comment]
Have a look at [puex](https://github.com/egoist/puex). I didn't really understand why he made it, hence the issue on that repo. Maybe it is what you are looking for @njleonzhang.

Or, as has already been said, use mobx.

**Comment by njleonzhang** [comment]
@grantcarthew Tnx any way, but I am not looking for something. Actually, I know some projects which can meet my requirements, such as `vue-mobx` and `revuejs`. I am just suggesting Vue team to consider this. `React` now can work very well with `mobx`, and it is more and more popular.  Although `Vue` don't need the reactive brought by `mobx`,  `mobx` really make things easy for small/middle project as I have mentioned in above comments.

**Comment by ktsn** [comment]
@njleonzhang 
Actually, defining mutations/actions types as constants is totally optional. You can declare actions/mutations types inline if you want. You also do not have to use actions if it just commits a mutation. (Of cause there are some cases that it is better to use them as I mentioned about trade-off before)

So your example can shorten like below:

```js
export default {
  state: {
    show: false,
  },

  mutations: {
    authenticated(state) {
      state.show = true
    }
  }
}
```

About MobX, I think you can just use a plain Vue instance as a store since Vue actually has the same rectivity system with MobX.

```js
const SideBarStore = Vue.extend({
  data() {
    return {
      authenticated: false
    }
  },
  methods: {
    authed() {
      this.authenticated = true
    }
  }
})
```

You can use vue-class-component if you prefer decorator syntax.

```js
import Vue from 'vue'
import Component from 'vue-class-component'

export class SideBarStore {
  authenticated = false

  authed() {
    this.authenticated = true
  }
}
```

**Comment by njleonzhang** [comment]
@ktsn use a plain `Vue` instance as store is OK. In fact, [revuejs](https://github.com/dwqs/revuejs) implement in this way, we need some thing similar to `react-mobx` to inject this store to Vue instance. [revuejs](https://github.com/dwqs/revuejs) implement a rough one.

**Comment by ktsn** [comment]
@njleonzhang Sorry, I still not sure what you want in Vuex.

> need mutation name space and sync action

If you mean we need to add some namespace for mutation name, Vuex already does that automatically with `namespaced: true` option.

```js
// store module
export default {
  namespaced: true,
  mutations: {
    authenticated(state) { /* ... */ } // -> create `moduleName/authenticated` mutation
  }
}
```

```js
// component
export default {
  methods: {
    ...mapMutations('moduleName', [
      'authenticated'
    ]),

    someMethod() {
      this.authenticated() // -> dispatch `moduleName/authenticated`
    }
  }
}
```

I don't understand what "sync action" is. If it is a typo of "async action", that's true. That is the thing we cannot remove from Vuex to separate async process from state update. It is necessary if we want to track state update in devtools.

> But we still need some thing similar to react-mobx to inject this store to Vue instance. revuejs implement a rough one. This is what I suggest Vue team to consider

Could you describe a bit more about this especially with some example code? I briefly look into revue and mobx but I cannot find anything new concept for me.
Revue looks like uses the same approach with Vuex (using mapXXX helpers) and MobX looks just let the users pass the reactive data via component props.

**Comment by njleonzhang** [comment]
@ktsn I summary what I am talking about:
* use plain Vue instance(or mobx) as store. (This can work as you mentioned)
* a bridge to connect the store to Vue component (like [mobx-react](https://github.com/mobxjs/mobx-react))

sample:

store.js:
```
import Vue from 'vue'
import Component from 'vue-class-component'

@Component
export class SideBarStore {
  authenticated = false

  authed() {
      asyncAction().then(_ => {
         this.authenticated = true
      })
  }
}
```

use in Vue component:

```
<template>
  <div>{authenticated}</div>
</template>

<script>
  import Vue from 'vue'
  import Component from 'vue-class-component'

  // @inject('SideBarStore')
  @Component
  export class SideBar {
      // or mapActions(['SideBarStore'])
  }
</script>
```

There are 2 implementations by @dwqs
[revuejs](https://github.com/dwqs/revuejs): use Vue instance as store and provide mapXXX helpers as bridge.
[vue-mobx](https://github.com/dwqs/vue-mobx/): use mobx as store and provide es7 decorator as bridge.

Will Vue team consider to provide a implementation?

**Comment by ktsn** [comment]
Then, we had already implemented them in Vue core/Vuex/vue-class-component as I explained above 😄 
So I'm closing this issue, Thanks!

**Comment by njleonzhang** [comment]
@ktsn Tnx very much, will try to understand how it works.
