### ISSUE TITLE
When passing object to Vuex's state (e.g. initState), copy it instead of changing its reference directly

### ISSUE THREAD

**Issue by xekri** [vuejs/vuex#946]
### What problem does this feature solve?
In server side rendering, if you set separate initial state object outside of Vuex's constructing function, it will be referenced and all changes to it will be shared. It's very confusing when you building custom Vue SSR project using vuex.
It would be better if vuex doesn't use the outside state object's reference directly, instead, copy it to a new state object every time the vuex instance is created.

FYI, my solution is just using object spread syntax like: `state: { ...initState }`.

### What does the proposed API look like?
If there's need to promise backward compatibility, vuex can offer a option like `initWithNewContext`.

**Comment by ktsn** [comment]
What is the use case for this? Why would you want to mutate the object passed into store as initial state out of store? Why not enough to [pass a function to state option](https://vuex.vuejs.org/en/modules.html#module-reuse)?

IMHO, it would be too complecated to deep copy the state. What if the state includes user defined model?

**Comment by xekri** [comment]
@ktsn OK, I got that. My use case is that use the exported object to get IntelliSense for VSCode, also, it can make type check in props of components be simple:
```
  props: _.mapValues(roomInfo, o => ({
    type: o.constructor,
    required: true
  })),
```

**Comment by ktsn** [comment]
@xekri Thanks, I realized API reference of `state` option does not include about passing a function. Already made a PR #951.
