### ISSUE TITLE
Proposal: Export all helper functions

### ISSUE THREAD

**Issue by Phillys** [vuejs/vuex#947]
### What problem does this feature solve?
Export the following functions so we can build our own helpers using these:
* getModuleByNamespace
* normalizeNamespace
* normalizeMap

I recently built my own helpers to reduce boilerplate code and ended up copying these functions.

### What does the proposed API look like?
export const fnName = ...

**Comment by ktsn** [comment]
IMHO, they should not be exposed in user land since it also expose inner module models. I think it would be better to just concat namespace string with types or wrap mapXXX helpers.
