### ISSUE TITLE
The Plugins is not working

### ISSUE THREAD

**Issue by xuchenchenBoy** [vuejs/vuex#952]
### Version
2.4.0

### Reproduction link
[https://jsfiddle.net/gt1rjtqc/](https://jsfiddle.net/gt1rjtqc/)

### Steps to reproduce
    const processMiddleware = (store) => {
      console.log('processMiddleware')
    }

    const store = new Vuex.Store({
      ...
      plugins: [processMiddleware]
    })

    new Vue({
      ...
      store
    })

### What is expected?
Console a processMiddleware When click the msg.

### What is actually happening?
Nothing

**Comment by ktsn** [comment]
This is expected. The plugin function is called once when the store is ready. If you want to subscribe the mutation, you should call `store.subscribe` method in the plugin.
https://vuex.vuejs.org/en/plugins.html

**Comment by xuchenchenBoy** [comment]
@ktsn Thanks.
