### ISSUE TITLE
Access to getters from namespaced modules

### ISSUE THREAD

**Issue by yageek** [vuejs/vuex#957]
### Version
2.4.0

### Reproduction link
[https://github.com/yageek/vuex-reproduce](https://github.com/yageek/vuex-reproduce)

### Steps to reproduce
1. Create a project with vuex with one namespaced module `moduleA` and a router.
2. Add a `isPositive` getter inside the store's module
3. Try to access the getters with `store.moduleA.isPositive` from the router
4. See the console log

### What is expected?
It should be possible to access the getters with `store.moduleA.isPositive`

### What is actually happening?
We get the error `Cannot read property 'isPositive' of undefined`.

Using the debugger pointed out that the `store`instance does not have a property `store.getters.moduleA.isPositive`but a property with `getters.moduleA/isPositive` (not the slash)
<img width="673" alt="capture d ecran 2017-09-17 a 21 10 57" src="https://user-images.githubusercontent.com/170917/30524056-bfdabb6a-9bec-11e7-9de4-f6de53e58d66.png">

**Comment by LinusBorg** [comment]
This is not a bug, you seem to misunderstand the API. You can't acess getters like that, and never could. 

All getters are collected on the root level (this has technical reasons - getters a are computed properties on the vm that vuex uses for managing its reactive state internally).

As you can see in your screenshot, your getter is accessible through 
`store.getters('moduleA/isPositive')`

**Comment by yageek** [comment]
Sorry for the misunderstanding. Effectively, I have missed out the relevant point inside the documentation. Thank you for the quick answer.

**Comment by hspaaij** [comment]
For those trying to get this working. There is a typo in the note from @LinusBorg. store.getters is not a function, so instead of store.getters('moduleA/isPositive'), use store.getters['moduleA/isPositive'].
Source: this post: https://forum.vuejs.org/t/vuex-getters-is-not-a-function/23642/5

**Comment by LinusBorg** [comment]
Oops you are totally right

**Comment by Erutan409** [comment]
@LinusBorg Sorry to revive this, but is there any reason why a getters prop can't be added to the context of the namespace state object that is mapped to the root collection of getters?  This seems a little confusing and inconsistent with how you can/should interact with namespaced states.

**Comment by alphaelf** [comment]
what about [method-style getters](https://vuex.vuejs.org/guide/getters.html#method-style-access)?
how we can call them with namespaced modules?

**Comment by shekhar108** [comment]
For method-style getters, 

`store.getters.getTodoById(2)` can be written as `store.getters['Todo/getTodoById'](2)` where Todo is the namespaced module.

**Comment by bravik** [comment]
This should have been in the docs

**Comment by dodowhat** [comment]
> store.getters('moduleA/isPositive')

it

> This is not a bug, you seem to misunderstand the API. You can't acess getters like that, and never could.
> 
> All getters are collected on the root level (this has technical reasons - getters a are computed properties on the vm that vuex uses for managing its reactive state internally).
> 
> As you can see in your screenshot, your getter is accessible through
> `store.getters('moduleA/isPositive')`
> 
> Also, you seem to think that getters should be / can be called as functions (`store.moduleA.isPositive()`). That's also not the case. they are computed properties, and behave like such.

It should be `store.getters['moduleA/isPositive']`, square brackets not round brackets.

**Comment by roblight** [comment]
cf. https://github.com/vuejs/vuex/issues/1258
