### ISSUE TITLE
How to use component data in getters?

### ISSUE THREAD

**Issue by patrick-hertling** [vuejs/vuex#96]
I have a scenario where I would like to have the getter to return a specific part of the store.
That part depends on a prop given to the component like:
```
    vuex: {
        getters: {
            state: function(store) {
                return store.windows[this.scope];
            }
        },

        actions: WindowActions
    },
```
I can't pass ```this.scope``` into the getter though. 
Any workaround or alternative?

For now I just pass the whole object to each window and simulate the state with a computed property. 
It would make more sense though to be able to pick just the part of the store I need.

**Comment by jonagoldman** [comment]
According to the docs, thats the correct way to do it. Return the store in the getter and use a computed property to filter it.

**Comment by yyx990803** [comment]
See http://vuex.vuejs.org/en/state.html#getters-must-be-pure

You need to define a separate computed property.
