### ISSUE TITLE
When state store container is Set rather than Array，computed prop does not work!

### ISSUE THREAD

**Issue by VancySavoki** [vuejs/vuex#961]
### Version
2.4.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/63141/](https://jsfiddle.net/50wL7mdz/63141/)

### Steps to reproduce
Vue.use(Vuex)
const store = new Vuex.Store({
  state: {
    tasks: new Set(),
    tasks2: []
  },
  getters: {
    taskCounts: state => {
      return state.tasks.size
    },
    taskCounts2: state => {
      return state.tasks2.length
    }
  },
  mutations: {
    commitTasks(state,task) {
      // 变更状态
      state.tasks.add(task)
    },
    commitTasks2(state,task) {
      // 变更状态
      state.tasks2.push(task)
    }
  }
})
new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!'
  },
 	store,
  computed:{
     taskCounts:function(){
        return this.$store.getters.taskCounts
     },
     taskCounts2:function(){
        return this.$store.getters.taskCounts2
     }

  },
  methods:{
    add(){
       let tasks = {}
       this.$store.commit("commitTasks",tasks)
    },
    add2(){
       let tasks = {}
       this.$store.commit("commitTasks2",tasks)
    }
   
  }
})

### What is expected?
When state store container is Set,computed prop is working

### What is actually happening?
When state store container is Set,computed prop is not working

**Comment by sqal** [comment]
This isn't Vuex issue. Vue's reactivity system doesn't work (currently) with Sets.

**Comment by ktsn** [comment]
As @sqal described, this is actually Vue's issue. And this was reported several times (See https://github.com/vuejs/vue/issues/1319, https://github.com/vuejs/vue/issues/2410)

**Comment by VancySavoki** [comment]
Thanks!
