### ISSUE TITLE
Documentation: When navigating, ad in navigation is constantly jumping / up and down (missing height?)

### ISSUE THREAD

**Issue by peterpme** [vuejs/vuex#969]
### Version
2.4.0

### Reproduction link
[https://vuex.vuejs.org/en/plugins.html](https://vuex.vuejs.org/en/plugins.html)

### Steps to reproduce
- Turn off adblocker
- navigate any internal link on the documentation

### What is expected?
A set width and height so that the navigation isn't jumping up and down

### What is actually happening?
The navigation jumps up and down

---
I was looking at the documentation

**Comment by posva** [comment]
I don't have any issues with Chrome, Safari or Firefox on Mac. What are you using. Can you share a gif recording?

**Comment by peterpme** [comment]
Are you using an adblocker? If you're not you will see the issue in Safari, Opera, Chrome, etc.

Safari demo:
![issue](https://user-images.githubusercontent.com/1211905/30871086-521f6682-a2ab-11e7-8806-dac1031c0ce0.gif)

**Comment by posva** [comment]
Ah, I see what you mean. It already has a fixed height but it's dynamically inserted. I'm not sure we can fix it but I cannot find the repository with the theme 😆 
Personally, I think this is a nice to have and that we're open to a fix it. It has never bothered me

**Comment by peterpme** [comment]
It's a little annoying to be honest but I understand! Thanks for taking the time :) 

Maybe if I end up using Vuex I'll fix it myself as a thank you :)

**Comment by Jinjiang** [comment]
It seems here but I am not sure. https://github.com/pearofducks/gitbook-plugin-theme-vuejs

**Comment by posva** [comment]
Yes, that's the one! I couldn't find it with a google search of _github gitbook plugin theme vue_ 😆

**Comment by Jinjiang** [comment]
I get the clue here: https://github.com/vuejs/vuex/blob/f737137a3ea57f1f8bb037a808d847df7a6af576/docs/book.json#L4
And find it through github search 😜

**Comment by kiaking** [comment]
Closing this one since it seems like solved by the answers in this thread.
