### ISSUE TITLE
Q: Vuex and re-usable components

### ISSUE THREAD

**Issue by luis-conor** [vuejs/vuex#97]
Hi,
Hope you can help with the following:

**Problem:**
I am migrating to vuex v0.6.2 and am struggling with the following:
In my existing app I have child components that I use in a few different views: I use props to inject state data which is retrieved with the new Vuex getters for the state property. The child component is not vuex/store aware as I want to use it to manipulate different paths in the state.
 The child  component calls this.$set it's own defined method to change the data and the parent component uses a watch to call store.dispatch.
All was working fine before API changes but now I get error that says the getters are read-only. 
So, I changed the getter to be a computed get/set, but when I change the data inside the child component it runs an infinite loop on these get/set methods.

**Question:**
What is the recommended approach to feed state data into a child-component (eventually a 3rd party component we don't want to change) and listen to changes on the data in order to dispatch actions?

Thank-you!

**Comment by yyx990803** [comment]
Instead of the child mutating shared state (which is bad idea when you are using Vuex), let the child component emit an event to notify the parent.

**Comment by luis-conor** [comment]
Thanks @yyx990803 
While that will work for me as I can change the child components, how would it be for 3rd party components where we don't have control over emitting events?
Could we inject a `watch` the emits the events via the mixin mechanism?
