### ISSUE TITLE
Updating Example present in Vuex repo

### ISSUE THREAD

**Issue by mbj36** [vuejs/vuex#977]
### Version
2.4.1

### Reproduction link
[https://github.com/vuejs/vuex#examples](https://github.com/vuejs/vuex#examples)

### Steps to reproduce
I am looking at the Shopping cart Example on vuex page and they are all outdated 

### What is expected?
Update with newer version

### What is actually happening?
Older version

**Comment by ktsn** [comment]
ref #890

**Comment by mbj36** [comment]
Thanks!
