### ISSUE TITLE
vuex's can't use,do i must write by es6?

### ISSUE THREAD

**Issue by niluanxy** [vuejs/vuex#98]
my project is write by es5,but today i study vuex by http://vuejs.github.io/vuex/en/index.html,always can't use actions,only can call mutations.

Code is here:

```javascirpt
var good = new Vuex.Store({
	state: {
		count: 1
	},
	mutations: {
		ADD: function(state, num) {
			state.count += num || 1;
		}
	},
	actions: {
		plus: "ADD"
	}
})
```

**Comment by jonagoldman** [comment]
You are using an old version of the API. Actions are separated from Store.

**Comment by yyx990803** [comment]
^ There has been quite some breaking changes starting from 0.4.0. Check the [release notes](https://github.com/vuejs/vuex/releases).
