### ISSUE TITLE
mapState does not work with modules

### ISSUE THREAD

**Issue by mallendeo** [vuejs/vuex#983]
### Version
2.4.1

### Reproduction link
[https://codepen.io/mallendeo/pen/PJevYg](https://codepen.io/mallendeo/pen/PJevYg)

### Steps to reproduce
Nothing, the bug is happening in the first Vue instance.

### What is expected?
isRecording should be true in the first instance.

### What is actually happening?
mapState is not mapping the `recording` module state.
Since it's a non-namespaced module, state should be accessible on the global scope, just like actions and getters.

**Comment by ktsn** [comment]
This is expected. Because `mapState` will look up root state if no namespace is provided.

**Comment by mallendeo** [comment]
@ktsn any other way to do it without setting a namespace? Or without doing `(state) => state.module.prop` for each property? Thanks.
