### ISSUE TITLE
Any way to encapsulate a function in mapGetters or others

### ISSUE THREAD

**Issue by Heleninsa** [vuejs/vuex#989]
### What problem does this feature solve?
I'm using mapGetters to locate my moduling store. <br>
However, to transfrom the number in specific store,  I have to create a new variable.<br> 
For example :
```
    computed: {
        ...mapGetters('my_module', ['test']),
        /* data coupling. obviously there is no need to declare it twice 
            if you only want to use test here */
        newTest() {
            ...do some calculations or maps with var test...
        }
    }
```
Also, I don't find a way to reach the module with out using mapGetters.  I think it would be much better if there is a similar way to reach getter under specific module as state (like. store.getters.module.getterName).  

### What does the proposed API look like?
...mapGetters('module', {newName: {pre: preGettersName, trans: function}, ......})

**Comment by ktsn** [comment]
I'm not sure what you are suggesting but it seems you can achieve all things that you are mentioning with current API.

1. If you just want to rename the getter in component -> Just use object in mapGetters
   - https://vuex.vuejs.org/en/getters.html#the-mapgetters-helper
2. If you want to transform getter value to use in component -> You can use mapState with function
   - https://vuex.vuejs.org/en/state.html#the-mapstate-helper
3. To access namespaced getters, you can just add namespace string with getter name.
   - `store.getters['module/getterName']`
