### ISSUE TITLE
Q: General component with actions depending on the scope

### ISSUE THREAD

**Issue by patrick-hertling** [vuejs/vuex#99]
Imagine a general List component wich can be reused to display users and products. When we click on a item we want to fire an action which dispatches a mutation. 

The twist is: The action should depend on the scope of the component. If its the users list the action should be different from the product list. How I could I set up the vuex.actions depending on the content of the component?

Any better solution or application structure?

**Comment by patrick-hertling** [comment]
I just read in another issue about using events in this case. 
I could indeed pass an event to the parent with the scope and the parent should dispatch the mutation. 
But would't that go a bit against the point of using the store pattern in the first place? I use it certainly to get away from the event spaguetti. 

(Sorry for asking so many questions. I think Vue is awesome. Some day I'll be able to give something back :))

**Comment by yyx990803** [comment]
You can pass specific scope variables as arguments into the action being called.

**Comment by patrick-hertling** [comment]
True, but I have like 5 scopes(users, products, clients, vehicles, ...) resolve that in the actions would be "not that nice". I think the event is the easiest solution. Thank you sir. I close the issue with your permission.
