### ISSUE TITLE
functional mapState not working with typescript

### ISSUE THREAD

**Issue by galenyuan** [vuejs/vuex#992]
### Reproduction link
[https://github.com/galenyuan/vuex-repo](https://github.com/galenyuan/vuex-repo)

### Steps to reproduce
open src/App.vue, then you can find it

![image](https://user-images.githubusercontent.com/10335062/31598231-11c40d88-b212-11e7-8c58-2c2ab1a15ac3.png)

![image](https://user-images.githubusercontent.com/10335062/31598203-f6da8e84-b211-11e7-81ff-52d880141b95.png)

### What is expected?
no typing error

### What is actually happening?
Property 'name' does not exist on type '{}'.

but

```javascript
mapState(['name'])
```
works well

**Comment by ktsn** [comment]
Since `mapState` cannot infer your app state, you need to manually annotate state type.

```ts
computed: {
  ...mapState({
    name: (state: YourAppState) => state.name
  })
}
```

**Comment by galenyuan** [comment]
Hi @ktsn , sorry for disturb you again, can you check this screenshot?

![image](https://user-images.githubusercontent.com/10335062/32164799-8fc87cd8-bd2e-11e7-913d-a76b4421e18f.png)
```
vue@2.5.2
vuex@3.0.0
```
it looks like can not use prop in mapState.

```
error TS2339: Property 'type' does not exist on type 'VueConstructor<Vue>'
```
