### ISSUE TITLE
provide errorHandler, warnHandler or re-use handlers from Vue.config

### ISSUE THREAD

**Issue by rodneyrehm** [vuejs/vuex#995]
### What problem does this feature solve?
My unit tests of Vue components (using a stubbed store) frequently show messages like the following

```
ERROR LOG: '[vuex] unknown getter: alpha/bravo'
```

If I had a way to intercept those messages (like `Vue.config.errorHandler()` and `Vue.config.warnHandler()` provide) I could instruct my test runner to fail tests raising such errors and warnings.

Unfortunately strict mode does not help in this case.

### What does the proposed API look like?
It would be great if the messages could be piped to `Vue.config.errorHandler()` and `Vue.config.warnHandler()`, possibly making those functions accept another argument for passing the plugin's name to maintain the `[name]` prefix.

From a Vue perspective I'd likely make [writing a plugin](https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin) hint at the following in order to make other plugin authors pick up on how to allow the user to define custom handlers in case [Vue's global handlers](https://vuejs.org/v2/api/#errorHandler) should not be used:

```js
Vue.use(ThePlugin, {
  errorHandler (…) { console.log(…) },
  warnHandler (…) { console.log(…) },
})
```

**Comment by LinusBorg** [comment]
The first step would be to actually throw an error, which we don't do:

https://github.com/vuejs/vuex/blob/dev/src/store.js#L129-L134

I think it's idea worth considering, to 

1. throw an error here 
2. (maybe make this optional for backwards compatibility) and 
3. have an option to provide an errorHandler like for Vue.

**Comment by ktsn** [comment]
@LinusBorg I vote to add `errorHandler` in Vuex as well.

@rodneyrehm Why do you need to pipe the errors to Vue's errorHandler? I think it would be suffice your need to add same thing in Vuex.

**Comment by rodneyrehm** [comment]
@ktsn because if every plugin were to pipe its warnings/errors to Vue the user (e.g. me) has to interface with only one entity, instead of working things out with every plugin individually.

**Comment by LinusBorg** [comment]
But the function signature would be quite different anyway, because errors from vuex won't have a component as a source, it's an action, or mutation etc.

**Comment by kiaking** [comment]
Closing the issue for now. This has been discussed in several issues and PRs, and to avoid any breaking changes, we can't do this at the moment for Vuex 3 & 4. We should definitely improve this on the next iteration.
