### ISSUE TITLE
Replace mutation type const with frozen object

### ISSUE THREAD

**Issue by grantcarthew** [vuejs/vuex#997]
### What problem does this feature solve?
Not a problem really, more of an improvement.

### What does the proposed API look like?
Original mutation-types.js:

```js
export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
```

Suggested replacement:

```js
export default Object.freeze({
  ADD_TO_CART: 'ADD_TO_CART',
  CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
  CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
  CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS'
})
```

**Comment by grantcarthew** [comment]
This would change the mutation import from:
`import * as types from '...'`
to
`import types from '...'`

**Comment by grantcarthew** [comment]
Oh, and this has nothing to do with this:

![](https://image.tmdb.org/t/p/w500/jIjdFXKUNtdf1bwqMrhearpyjMj.jpg)

**Comment by LinusBorg** [comment]
...I assume you are talking about the shopping cart example in the docs?

**Comment by grantcarthew** [comment]
Yes @LinusBorg. The examples and docs. Close it if you think not.

**Comment by grantcarthew** [comment]
Forget it. Just thinking about it. Makes no difference. Don't want to cause work.
